### PR TITLE
[bugfix][zeta]Using G1 as defaut garbage colletor in zeta

### LINKED ISSUE #4915: [Bug] [zeta] java.lang.OutOfMemoryError: Metaspace
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I will run about 15 batch synchronization tasks per minute. When I add MaxMetaspaceSize = 2g in jvm_options, OOM will appear after about 1.5 hours of running.

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
    job.mode = BATCH
    execution.parallelism = 1
    checkpoint.interval = 86400000
}
source {
    Clickhouse {
        database = xxx
        password = "xxx"
        host = "xxx:xxx"
        table = xxx
        username = xxx
        sql = "select * from xxx where timeCreated > 1684891467083"
    }
}
sink {
    Clickhouse {
        database = xxx
        password = "xxx"
        host = "127.0.0.1:8123"
        table = xxx
        username = xxx
    }
}
```

### Running Command

```shell
nohup ./bin/seatunnel.sh -c ./config/ck_ck.conf &> ./logs/ck_ck.log &
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Metaspace
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapInCompletionException(AbstractInvocationFuture.java:1347)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.cascadeException(AbstractInvocationFuture.java:1340)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.access$200(AbstractInvocationFuture.java:65)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$ApplyNode.execute(AbstractInvocationFuture.java:1478)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockOtherNode(AbstractInvocationFuture.java:797)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockAll(AbstractInvocationFuture.java:759)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1235)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.completeExceptionallyInternal(AbstractInvocationFuture.java:1223)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.completeExceptionally(AbstractInvocationFuture.java:709)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.completeExceptionally(ClientInvocation.java:294)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.notifyExceptionWithOwnedPermission(ClientInvocation.java:321)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:304)
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier.handleResponse(ClientResponseHandlerSupplier.java:164)
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier.process(ClientResponseHandlerSupplier.java:141)
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier.access$300(ClientResponseHandlerSupplier.java:60)
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier$DynamicResponseHandler.accept(ClientResponseHandlerSupplier.java:251)
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier$DynamicResponseHandler.accept(ClientResponseHandlerSupplier.java:243)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnection.handleClientMessage(TcpClientConnection.java:245)
	at com.hazelcast.client.impl.protocol.util.ClientMessageDecoder.handleMessage(ClientMessageDecoder.java:135)
	at com.hazelcast.client.impl.protocol.util.ClientMessageDecoder.onRead(ClientMessageDecoder.java:89)
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:136)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:383)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294)
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.lang.OutOfMemoryError: Metaspace
```

### Flink or Spark Version

none

### Java or Scala Version

1.8

### Screenshots

image

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liugddx**
### Purpose of this pull request

fix #4915 

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

No testing required.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: config/jvm_options [hunk 1]
```diff
@@ -24,4 +24,10 @@
...
 # Metaspace
--XX:MaxMetaspaceSize=2g
\ No newline at end of file
+-XX:MaxMetaspaceSize=2g
+
+# G1GC
+-XX:+UseG1GC
+-XX:MaxGCPauseMillis=200
+-XX:+PrintGCDateStamps
+-XX:+PrintGCDetails
```
Comment (Hisoka-X) [inline config/jvm_options]: Does this necessary?

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 2]
```diff
@@ -442,6 +442,7 @@ public PassiveCompletableFuture<Void> submitJob(long jobId, Data jobImmutableInf
                         runningJobInfoIMap.remove(jobId);
                         runningJobMasterMap.remove(jobId);
                     }
+                    jobMaster.setClassLoader(null);
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: I'm not sure if this method is reasonable, because `JobMaster` will be cleaned up from `runningJobMasterMap` when the job ends, which means that `JobMaster` will not be referenced after that, and his member variable `classloader` will not be referenced, so then It can be recycled normally. Can you tell me the deeper reason for this change?

Comment (liugddx) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: > I'm not sure if this method is reasonable, because `JobMaster` will be cleaned up from `runningJobMasterMap` when the job ends, which means that `JobMaster` will not be referenced after that, and his member variable `classloader` will not be referenced, so then It can be recycled normally. Can you tell me the deeper reason for this change?

Yes, gc does not recycle the classLoader

File: config/jvm_options (hunk 1 above)
Comment (liugddx) [reply config/jvm_options]: > Does this necessary?

Removed.

File: config/jvm_options [hunk 3]
```diff
@@ -24,4 +24,9 @@
...
 
 # Metaspace
--XX:MaxMetaspaceSize=2g
\ No newline at end of file
+-XX:MaxMetaspaceSize=2g
+
+# G1GC
+-XX:+UseG1GC
+-XX:MaxGCPauseMillis=200
+-XX:+PrintGCDateStamps
```
Comment (Hisoka-X) [inline config/jvm_options]: I think these change should not included.
```suggestion
```

**Review by Hisoka-X — APPROVED** [review]

**Review by Carl-Zhou-CN — APPROVED** [review]
+1
