### PR TITLE
[Fix][Flink] Fix NPE when get null row from upstream transform

### LINKED ISSUE #8468: [Bug] [Seatunnel flink starter] null row causes NPE
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I'm running seatunnel 2.3.9 but got NPE. It seems the null row was not filtered before processing by the downstream operator.

### SeaTunnel Version

2.3.9

### SeaTunnel Config

```conf
{
  "env": {
    "jobMode": "batch",
    "parallelism": 1
  },
  "source": [
    {
      "plugin_name": "FakeSource",
      "plugin_output": "fake",
      "row.num": 5,
      "schema": {
        "fields": {
          "name": "string",
          "age": "int",
          "card": "int"
        }
      }
    }
  ],
  "transform": [
    {
      "plugin_name": "FilterRowKind",
      "plugin_input": "fake",
      "plugin_output": "fake1",
      "exclude_kinds": ["INSERT"]
    },
    {
      "plugin_name": "Copy",
      "plugin_input": "fake1",
      "plugin_output": "fake2",
      "fields": {
        "name1": "name",
        "age1": "age",
        "card1": "card"
      }
    }
  ],
  "sink": [
    {
      "plugin_name": "Console",
      "plugin_input": "fake2"
    }
  ]
}
```

### Running Command

```shell
src/main/java/org/apache/seatunnel/example/flink/v2/SeaTunnelApiExample.java
```

### Error Exception

```log
`
Caused by: java.lang.NullPointerException
	at org.apache.seatunnel.api.table.type.SeaTunnelRowAccessor.getField(SeaTunnelRowAccessor.java:41)
	at org.apache.seatunnel.transform.copy.CopyFieldTransform.getOutputFieldValues(CopyFieldTransform.java:122)
	at org.apache.seatunnel.transform.common.MultipleFieldOutputTransform.transformRow(MultipleFieldOutputTransform.java:56)
	at org.apache.seatunnel.transform.common.MultipleFieldOutputTransform.transformRow(MultipleFieldOutputTransform.java:36)
	at org.apache.seatunnel.transform.common.AbstractSeaTunnelTransform.transform(AbstractSeaTunnelTransform.java:80)
	at org.apache.seatunnel.transform.common.AbstractCatalogSupportMapTransform.map(AbstractCatalogSupportMapTransform.java:42)
	at org.apache.seatunnel.transform.common.AbstractCatalogSupportMapTransform.map(AbstractCatalogSupportMapTransform.java:27)
	at org.apache.seatunnel.transform.common.AbstractMultiCatalogMapTransform.map(AbstractMultiCatalogMapTransform.java:40)
	at org.apache.seatunnel.transform.common.AbstractMultiCatalogMapTransform.map(AbstractMultiCatalogMapTransform.java:28)
	at org.apache.seatunnel.core.starter.flink.execution.TransformExecuteProcessor.lambda$flinkTransform$5d1c7633$1(TransformExecuteProcessor.java:159)
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:38)

`
```

### Zeta or Flink or Spark Version

flink 1.18.1

### Java or Scala Version

java 11

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by litiliu**
### Purpose of this pull request

This close #8468 
This PR adds a filter operator to filter the null rows generated by the transform plugins. It's easier than adding the null check in every transform plugin. 

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — APPROVED** [review]
LGTM if ci passes. Thanks @litiliu

File: seatunnel-e2e/seatunnel-engine-e2e/connector-console-seatunnel-e2e/src/test/java/org/apache/seatunnel/engine/e2e/console/FakeSourceToFilterToCopyToConsoleIT.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+import org.junit.jupiter.api.Assertions;
+import org.junit.jupiter.api.Test;
+import org.testcontainers.containers.Container;
+
+import java.io.IOException;
+
+public class FakeSourceToFilterToCopyToConsoleIT extends SeaTunnelEngineContainer {
+
+    @Test
+    public void testFakeSourceToConsoleSink() throws IOException, InterruptedException {
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-engine-e2e/connector-console-seatunnel-e2e/src/test/java/org/apache/seatunnel/engine/e2e/console/FakeSourceToFilterToCopyToConsoleIT.java]: I think the test case can not cover the change. Because it executed on zeta.

**Review by Hisoka-X — CHANGES_REQUESTED** [review]
Please add test case in https://github.com/apache/seatunnel/blob/adb656e29815e36b8bbcc383e7b400bc38f050c9/seatunnel-e2e/seatunnel-transforms-v2-e2e/seatunnel-transforms-v2-e2e-part-1/src/test/java/org/apache/seatunnel/e2e/transform/TestFilterRowKindIT.java#L28

File: seatunnel-e2e/seatunnel-transforms-v2-e2e/seatunnel-transforms-v2-e2e-part-1/src/test/java/org/apache/seatunnel/e2e/transform/TestFilterRowKindIT.java [hunk 2]
```diff
@@ -39,6 +39,9 @@ public void testFilterRowKind(TestContainer container)
         Container.ExecResult execResult3 =
                 container.executeJob("/filter_row_kind_include_insert.conf");
         Assertions.assertEquals(0, execResult3.getExitCode());
+
+        Container.ExecResult execResult4 = container.executeJob("/fake-filter-copy-console.json");
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-transforms-v2-e2e/seatunnel-transforms-v2-e2e-part-1/src/test/java/org/apache/seatunnel/e2e/transform/TestFilterRowKindIT.java]:
```suggestion
        Container.ExecResult execResult4 = container.executeJob("/filter_row_to_next_transform.json");
```

**Review by Hisoka-X — APPROVED** [review]
LGTM if ci passes.

**Review by hailin0 — APPROVED** [review]
