### PR TITLE
[Fix][Zeta] Converge notifyCompleted failure handling in CheckpointCoordinator

### LINKED ISSUE #10655: [Bug] [Zeta] NPE in CheckpointCoordinator.completePendingCheckpoint()
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When `notifyCompleted()` encounters an exception internally, it calls `handleCoordinatorError()` which in turn calls `cleanPendingCheckpoint()`, which clears pendingCheckpoints. The subsequent `pendingCheckpoints.remove(checkpointId)` then returns null, and the original chained call `abortCheckpointTimeoutFutureWhenIsCompleted()` would throw a NullPointerException.

### SeaTunnel Version

2.3.13

### SeaTunnel Config

```conf
None
```

### Running Command

```shell
None
```

### Error Exception

```log
Caused by: java.lang.NullPointerException
	at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.completePendingCheckpoint(CheckpointCoordinator.java:1004)
	at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.completePendingCheckpoint(CheckpointCoordinator.java:950)
	... 66 more
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

_No response_

### Screenshots

Image

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by hyboll**
Fixes: https://github.com/apache/seatunnel/issues/10655

### Purpose of this pull request

Fix avoid NPE in completePendingCheckpoint when notifyCompleted clears pendingCheckpoints

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Test case is added in the CheckpointCoordinatorTest.testCompletePendingCheckpointShouldNotThrowNPEWhenNotifyCompletedClearsPendingMap

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If necessary, please update `incompatible-changes.md` to describe the incompatibility caused by this PR.
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinatorTest.java [hunk 1]
```diff
@@ -371,6 +374,109 @@ void testFilteringClosedTasksAndActions() {
...
+     * handleCoordinatorError} which in turn calls {@code cleanPendingCheckpoint}, which clears
+     * {@code pendingCheckpoints}. The subsequent {@code pendingCheckpoints.remove(checkpointId)}
+     * then returns {@code null}, and the original chained call {@code
+     * .abortCheckpointTimeoutFutureWhenIsCompleted()} would throw a {@link NullPointerException}.
+     *
+     * <p>After the fix, {@code completePendingCheckpoint} performs a null-check before calling
+     * {@code abortCheckpointTimeoutFutureWhenIsCompleted()}, so no NPE is thrown.
+     */
+    @Test
+    @DisabledOnOs(OS.WINDOWS)
```
Comment (chl-wxp) [inline seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinatorTest.java]: Why is it disabled on the Windows system?

**Review by DanielLeens — CHANGES_REQUESTED** [review]
I think this patch fixes the NPE symptom, but it still leaves the failure path in an inconsistent state.

`notifyCompleted()` catches internal failures and calls `handleCoordinatorError()` (`CheckpointCoordinator.java:372-393`), which already:
- updates the coordinator status to `FAILED`
- clears `pendingCheckpoints`
- resets `pendingCounter` to `0`
- shuts the coordinator down via `cleanPendingCheckpoint()` (`CheckpointCoordinator.java:860-893`)

After control returns to `completePendingCheckpoint()`, the method still continues with the normal completion flow (`CheckpointCoordinator.java:1004-1019`). That means:
- `pendingCounter.decrementAndGet()` now runs after the cleanup path has already reset the counter
- for final checkpoints, `isCompleted()` can still become true and overwrite the failure path with `FINISHED` / `SUSPEND`

So the null-check removes one crash, but the coordinator can still report a completed final checkpoint after `notifyCompleted()` has already failed.

I think we need an early exit once `notifyCompleted()` has triggered cleanup, for example by returning immediately when the coordinator is already failed/shutdown, or by making `notifyCompleted()` propagate a failure signal back to `completePendingCheckpoint()`.

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinatorTest.java (hunk 1 above)
Comment (hyboll) [reply seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinatorTest.java]: Under the Windows system, this test method will throw a `FileNotFoundException` because `HADOOP_HOME` is not found. This bug fix only added an `if` condition and has nothing to do with the environment, so I disabled Windows. If necessary, I can add support for the Windows system.

**Comment by hyboll** [comment]
> I think this patch fixes the NPE symptom, but it still leaves the failure path in an inconsistent state.
> 
> `notifyCompleted()` catches internal failures and calls `handleCoordinatorError()` (`CheckpointCoordinator.java:372-393`), which already:
> 
> * updates the coordinator status to `FAILED`
> * clears `pendingCheckpoints`
> * resets `pendingCounter` to `0`
> * shuts the coordinator down via `cleanPendingCheckpoint()` (`CheckpointCoordinator.java:860-893`)
> 
> After control returns to `completePendingCheckpoint()`, the method still continues with the normal completion flow (`CheckpointCoordinator.java:1004-1019`). That means:
> 
> * `pendingCounter.decrementAndGet()` now runs after the cleanup path has already reset the counter
> * for final checkpoints, `isCompleted()` can still become true and overwrite the failure path with `FINISHED` / `SUSPEND`
> 
> So the null-check removes one crash, but the coordinator can still report a completed final checkpoint after `notifyCompleted()` has already failed.
> 
> I think we need an early exit once `notifyCompleted()` has triggered cleanup, for example by returning immediately when the coordinator is already failed/shutdown, or by making `notifyCompleted()` propagate a failure signal back to `completePendingCheckpoint()`.

Thanks for the suggestion. I've looked into the code again and I'm thinking of making notifyCompleted() return a boolean to handle the flow control. One quick question though: since there are three places calling this method, I plan to add the conditional checks to the other two call sites as well. Does that sound feasible to you?

**Comment by DanielLeens** [comment]
@hyboll Thanks for the follow-up. Yes, I think the boolean / early-exit signal should be handled at all three call sites, not only `completePendingCheckpoint()`.

The reason is that `notifyCompleted()` can already call `handleCoordinatorError()` and `cleanPendingCheckpoint()` on failure (`CheckpointCoordinator.java:283-304`, `372-393`, `860-905`). After that, each caller still continues its local flow today:
- `allTaskReady()` still schedules the next checkpoint after `notifyCompleted()` (`CheckpointCoordinator.java:361-368`)
- `restoreCoordinator()` still calls `tryTriggerPendingCheckpoint(CHECKPOINT_TYPE)` (`CheckpointCoordinator.java:491-494`)
- `completePendingCheckpoint()` still removes/decrements pending state and may overwrite the failure with `FINISHED` / `SUSPEND` for a final checkpoint (`CheckpointCoordinator.java:1003-1019`)

So my recommendation is:
1. Let `notifyCompleted()` return a clear failure signal (or rethrow).
2. Exit immediately at all three call sites once that failure signal is observed.
3. Add a regression that covers the final-checkpoint path as well, because the current test only clears the map manually and does not assert the post-failure state transition.

With the current patch, the NPE is avoided, but the failed completion path is still inconsistent, so this is still blocking from my side.

**Comment by DanielLeens** [comment]
Yes, I think all three call sites should honor the same failure signal, but I would avoid duplicating ad-hoc status checks at each site.

From the current code:
- `completePendingCheckpoint()` (`CheckpointCoordinator.java:1003-1019`) is the critical one: after `notifyCompleted()` calls `handleCoordinatorError()`, this method needs to return before `pendingCounter.decrementAndGet()` and the final `FINISHED` / `SUSPEND` transition.
- `allTaskReady()` (`CheckpointCoordinator.java:361-364`) and `restoreCoordinator(true)` (`CheckpointCoordinator.java:491-494`) should also stop before scheduling / triggering the next checkpoint if `notifyCompleted()` has already failed and shut the coordinator down.

So my suggestion would be to give `notifyCompleted()` a real contract (boolean / enum return, or let the failure propagate) and let each caller short-circuit on that result. That keeps the behavior consistent across all three call sites instead of scattering slightly different `isShutdown` / failed-state checks.

**Comment by DanielLeens** [comment]
Thanks for checking this. I re-traced the three `notifyCompleted()` call sites on the current tip (`be4dbe64`), and returning a boolean (or otherwise propagating a failure signal) looks feasible to me.

From my side:
- `completePendingCheckpoint()` is the must-fix caller. That path can still decrement `pendingCounter` and let a final checkpoint reach `isCompleted()` / `FINISHED` / `SUSPEND` after `handleCoordinatorError()` has already marked the coordinator as `FAILED`.
- Adding the same guard to `allTaskReady()` and `restoreCoordinator()` is also reasonable for consistency. Those two paths do not look as dangerous, because cleanup already flips `shutdown=true` and `isAllTaskReady=false`, so the later scheduling/triggering will bail out. But they still continue work after a failed notify, so returning early there would make the control flow clearer and avoid redundant checkpoint attempts.
- Please also add a regression test for a final checkpoint/savepoint failure path, not just the NPE case, so we verify the coordinator no longer reaches the completion branch after `notifyCompleted()` fails.

So yes, the boolean-return approach sounds good to me, and I would recommend updating all three call sites, with `completePendingCheckpoint()` as the blocking one.

**Comment by DanielLeens** [comment]
@hyboll Yes, that direction makes sense to me. The important part is to propagate the failure signal consistently to all three call sites of `notifyCompleted()`, not just `completePendingCheckpoint()`.

Right now the same catch-and-cleanup path can be hit from:
- `completePendingCheckpoint()` (`CheckpointCoordinator.java:1003`)
- `allTaskReady()` (`CheckpointCoordinator.java:361`)
- `restoreCoordinator()` (`CheckpointCoordinator.java:493`)

So if `notifyCompleted()` fails and `handleCoordinatorError()` has already switched the coordinator into the failed / shutdown path, each caller needs to stop its normal follow-up logic immediately.

In particular, `allTaskReady()` and `restoreCoordinator()` should not continue into scheduling / triggering the next checkpoint after a failed notify, and `completePendingCheckpoint()` still needs the early exit before `pendingCounter.decrementAndGet()` and the final `FINISHED` / `SUSPEND` transition.

So a boolean return value is fine, or an explicit exception / status check, as long as the contract is: once `notifyCompleted()` has triggered cleanup, the caller must bail out and not continue the success path.

**Review by DanielLeens — APPROVED** [review]
I re-checked the latest HEAD locally.

The blocker from my previous review looks addressed now:
- `notifyCompleted()` returns a failure signal and `allTaskReady()` / `restoreCoordinator()` / `completePendingCheckpoint()` all bail out on that signal (`CheckpointCoordinator.java:361-367`, `497-500`, `1009-1016`)
- the new regression tests now cover all three caller paths (`CheckpointCoordinatorTest.java:427-575`)

I do not see the earlier inconsistent-success-path issue in the current revision.
Thanks for following through on the full control-flow fix.

**Review by dybyte — APPROVED** [review]
LGTM. Thanks @hyboll

**Review by corgy-w — APPROVED** [review]
