### PR TITLE
[Fix][Zeta] Fix Imap resource leak

### LINKED ISSUE #9637: [Bug] [seatunnel-engine] Memory Leak
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened
当seatunnel集群长期大量提交任务时,手动触发GC后剩余的不可GC内存持续增长,经过排查发现CoordinatorService有3处存在内存泄露,其中前两处是必然出现,第三种在集群压力较大时有不低的概率出现.
1. runningJobStateIMap, 这个imap扔了4种类型的key进去,但是只移除了3种,checkpoint相关数据只存入没有移除,每个任务会遗留一条数据,目前我司每日任务有8000+, 实际监控这个imap的size每天膨胀8000+
2. CoordinatorService 的 pendingJobMasterMap,这个map在固定slot&REJECT配置时, 若资源不足则任务失败但是pendingJobMasterMap 没有清理,导致有任务提交成功资源分配失败时就会增加一条记录,实际监控这个map的size每天膨胀200+
3. metricsImap,这个imap的移除需要先获取锁,若获取锁失败则直接return没有抛出异常,所以不会触发外层的重试,在集群负载比较高时会导致imap数据清理失败,实际监控这个imap中存的map的size每天膨胀40+
相关代码见截图

### SeaTunnel Version

2.3.10

### SeaTunnel Config

```conf
seatunnel:
  engine:
    job-schedule-strategy: REJECT
    classloader-cache-mode: true
    history-job-expire-minutes: 1440
    telemetry:
      logs:
        scheduled-deletion-enable: false
    backup-count: 1
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    queue-type: blockingqueue
    slot-service:
      dynamic-slot: false
      slot-num: 50
      slot-allocation-strategy: SYSTEM_LOAD
    checkpoint:
      interval: 30000
      timeout: 2147483647
      max-concurrent: 5
      tolerable-failure: 2
      storage:
        type: oss
       
    http:
      enable-http: true
      port: 80
      context-path: /seatunnel
```

### Running Command

```shell
sh /alidata1/za-seatunnel/seatunnel-2.3.10/bin/seatunnel-cluster.sh -d -r worker
```

### Error Exception

```log
无
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by dybyte**
Fixes https://github.com/apache/seatunnel/issues/9637
### Purpose of this pull request

Fixes three memory leak issues:

1. `RunningJobStateIMap` – Checkpoint-related entries are stored but never removed, growing ~8,000/day.

2. `pendingJobMasterMap` – Not cleaned when resource allocation fails, growing ~200/day.

3. `metricsImap` – Cleanup skipped if lock acquisition fails, growing ~40/day.

These changes ensure proper cleanup and retry, reducing memory growth in production.
And this PR introduces a background cleanup worker that collects failed metrics removal tasks into a blocking queue and retries them periodically based on a new configuration option (cleanup-retry-interval).

This is my first time working with the engine codebase, so I might have overlooked some details. I’d appreciate any feedback or suggestions.

### Does this PR introduce _any_ user-facing change?

Yes.
A new configuration option is introduced:

`cleanup-retry-interval` – Interval in seconds between attempts to retry metrics cleanup when previous cleanup fails due to lock contention or other issues.
Default: 10 seconds.

This helps ensure metrics cleanup eventually succeeds under heavy load.

### How was this patch tested?

- Added E2E tests using Testcontainers.
- Verified cleanup via server logs (direct map inspection not possible in this environment).

- **For metricsImap cleanup retries, direct verification is challenging** because the test environment (Docker Testcontainers) does not allow internal state inspection and lock contention is non-deterministic.
If reviewers have suggestions for reliably simulating lock contention in integration tests, it would be greatly appreciated.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobMaster.java [hunk 1]
```diff
@@ -623,6 +629,18 @@ private void removeJobIMap() {
                                                 runningJobStateTimestampsIMap.remove(
                                                         task.getTaskGroupLocation());
                                             });
+
+                            String checkpointStateImapKey =
+                                    CheckpointCoordinator.getCheckpointStateImapKey(
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobMaster.java]: we can reuse https://github.com/apache/seatunnel/pull/9696/files#diff-1abd8bd9a8f72a40ac2f8606a67279bdc7d2d638c0bc415639cea42c61b6a4d8R174

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobMaster.java [hunk 2]
```diff
@@ -623,6 +629,18 @@ private void removeJobIMap() {
...
+                                            jobId, pipeline.getPipelineId());
+                            Object removedState =
+                                    runningJobStateIMap.remove(checkpointStateImapKey);
+                            if (removedState != null) {
+                                LOGGER.info(
+                                        String.format(
+                                                "Successfully removed checkpoint coordinator state: %s",
+                                                checkpointStateImapKey));
+                            }
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobMaster.java]: just like other remove call, do not print any log.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 3]
```diff
@@ -287,6 +295,11 @@ private void pendingJobSchedule() throws InterruptedException {
             } else {
                 queueRemove(jobMaster);
                 completeFailJob(jobMaster);
+                pendingJobMasterMap.remove(jobId);
+                logger.info(
+                        String.format(
+                                "PendingJobMasterMap size after cleanup: %d",
+                                pendingJobMasterMap.size()));
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: don't need logs.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 4]
```diff
@@ -1078,4 +1095,69 @@ public ConnectorPackageService getConnectorPackageService() {
         }
         return connectorPackageService;
     }
+
+    private void startMetricsCleanupWorker() {
+        Runnable cleanupTask =
+                () -> {
+                    Thread.currentThread().setName("metrics-cleanup-worker");
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]:
```suggestion
                    Thread.currentThread().setName("metrics-cleanup-runner");
```

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 5]
```diff
@@ -1078,4 +1095,69 @@ public ConnectorPackageService getConnectorPackageService() {
...
+                                        .filter(
+                                                taskLocation ->
+                                                        taskLocation
+                                                                .getTaskGroupLocation()
+                                                                .getPipelineLocation()
+                                                                .equals(pipelineLocation))
+                                        .collect(Collectors.toList());
+                        collect.forEach(centralMap::remove);
+                        return centralMap;
+                    });
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: Redundant code was found, please refactor.

File: docs/en/seatunnel-engine/hybrid-cluster-deployment.md [hunk 6]
```diff
@@ -168,12 +168,18 @@ The corePoolSize of seatunnel coordinator job's executor cached thread pool
 
 The max job count can be executed at same time
 
+**cleanup-retry-interval**
```
Comment (Hisoka-X) [inline docs/en/seatunnel-engine/hybrid-cluster-deployment.md]: Please update `separated-cluster-deployment.md` and zh docs too.

File: seatunnel-engine/seatunnel-engine-common/src/main/java/org/apache/seatunnel/engine/common/config/server/ServerConfigOptions.java [hunk 7]
```diff
@@ -363,6 +363,14 @@ public static class MasterServerConfigOptions {
                         .defaultValue(Integer.MAX_VALUE)
                         .withDescription("The max thread num of coordinator service");
 
+        public static final Option<Integer> CLEANUP_RETRY_INTERVAL =
+                Options.key("cleanup-retry-interval")
+                        .intType()
+                        .defaultValue(10)
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-common/src/main/java/org/apache/seatunnel/engine/common/config/server/ServerConfigOptions.java]: Let's set the default value to 60s.

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/JobClientJobProxyIT.java [hunk 8]
```diff
@@ -183,4 +183,22 @@ public void testJobFailedWillThrowException() throws IOException, InterruptedExc
...
+    }
+
+    @Test
+    public void testCleanupCheckPointCoordinatorStatus() throws IOException, InterruptedException {
+        Container.ExecResult execResult = executeJob(server, "/batch_slot_enough.conf");
+        Assertions.assertEquals(0, execResult.getExitCode());
+        String serverLogs = server.getLogs();
+        Assertions.assertTrue(
+                serverLogs.contains("Successfully removed checkpoint coordinator state:"));
+    }
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/JobClientJobProxyIT.java]: The current test case is very fragile. If we add new map keys later, the current test case will not detect the new memory leak, which will cause regression. We can directly access the IMAP object in the `CoordinatorServiceTest` test to check whether our data is deleted (when the job is cancelled or fininshed).

**Review by Hisoka-X — COMMENTED** [review]
Thanks @dybyte ! I left some suggestions.

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/JobClientJobProxyIT.java (hunk 8 above)
Comment (dybyte) [reply seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/JobClientJobProxyIT.java]: Thank you for the suggestion! I have added test cases in CoordinatorServiceTest accordingly. However, the memory leak issue related to `metricsIMap` is still difficult to test. When I try to pre-lock the imap during tests, the test fails because other logic using the imap runs before the resource cleanup can happen. [TaskExecutionService](https://github.com/apache/seatunnel/blob/085023ad0db1a8729ce724a14855c0077f051dfe/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/TaskExecutionService.java#L609C9-L611C93)
Should we consider skipping this particular test?

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobMaster.java (hunk 1 above)
Comment (dybyte) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobMaster.java]:
```java
String checkpointStateImapKey = checkpointManager.getCheckpointCoordinator(pipeline.getPipelineId()).getCheckpointStateImapKey();
```
Is this the approach you were referring to?
However, since `getCheckpointCoordinator()` method is annotated with `@VisibleForTesting`, I think it's better to avoid using it in production code.
Please let me know if I misunderstood anything. Thanks!

[checkpointManager.getCheckpointCoordinator()](https://github.com/apache/seatunnel/blob/085023ad0db1a8729ce724a14855c0077f051dfe/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointManager.java#L179)

Comment (Hisoka-X) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobMaster.java]: Let's remove `@VisibleForTesting` now.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobMaster.java [hunk 9]
```diff
@@ -892,25 +906,18 @@ public void removeMetricsContext(
...
-                                                        .getTaskGroupLocation()
-                                                        .getPipelineLocation()
-                                                        .equals(pipelineLocation);
-                                            })
-                                    .collect(Collectors.toList());
-                    collect.forEach(centralMap::remove);
-                    metricsImap.put(Constant.IMAP_RUNNING_JOB_METRICS_KEY, centralMap);
-                }
+                MetricsCleanupUtils.removeMetricsEntries(pipelineLocation, centralMap);
+                metricsImap.put(Constant.IMAP_RUNNING_JOB_METRICS_KEY, centralMap);
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobMaster.java]: You missed check of `centralMap != null` before put map into imap.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 10]
```diff
@@ -1078,4 +1092,57 @@ public ConnectorPackageService getConnectorPackageService() {
...
+    private void startMetricsCleanupWorker() {
+        Runnable cleanupTask =
+                () -> {
+                    Thread.currentThread().setName("metrics-cleanup-runner");
+                    while (!Thread.currentThread().isInterrupted()
+                            && !metricsCleanupRetryQueue.isEmpty()) {
+                        try {
+                            PipelineLocation pipelineLocation =
+                                    metricsCleanupRetryQueue.poll(
+                                            cleanUpRetryInterval, TimeUnit.SECONDS);
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: So it doesn't look likes interval, more like waiting time. This will cause the key that cannot be released normally to be put into the queue to be read out and reprocessed immediately because the interval is very short. The success rate of this method is not very high.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 11]
```diff
@@ -1078,4 +1092,57 @@ public ConnectorPackageService getConnectorPackageService() {
...
+
+                            if (pipelineLocation != null) {
+                                JobMaster jobMaster = getJobMaster(pipelineLocation.getJobId());
+                                if (jobMaster != null) {
+                                    jobMaster.removeMetricsContext(
+                                            pipelineLocation,
+                                            (PipelineStatus)
+                                                    runningJobStateIMap.get(pipelineLocation));
+                                } else {
+                                    retryRemoveMetricsContext(pipelineLocation);
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: we should lock again we remove it from imap.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 12]
```diff
@@ -1078,4 +1092,57 @@ public ConnectorPackageService getConnectorPackageService() {
...
+            metricsImap.compute(
+                    Constant.IMAP_RUNNING_JOB_METRICS_KEY,
+                    (key, centralMap) -> {
+                        MetricsCleanupUtils.removeMetricsEntries(pipelineLocation, centralMap);
+                        return centralMap;
+                    });
+            logger.info(
+                    String.format(
+                            "Metrics cleanup via compute for pipeline: %s", pipelineLocation));
+        } catch (Exception e) {
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: if remove failed, I think we should reput it into queue?

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/JobClientJobProxyIT.java (hunk 8 above)
Comment (Hisoka-X) [reply seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/JobClientJobProxyIT.java]: how about add a data and key into queue by ourself? we should make sure `metrics-cleanup-worker` thread work fine.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java (hunk 10 above)
Comment (dybyte) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: We addressed this by using a `ScheduledExecutorService` with a fixed delay and also adding logic to check the last cleanup time before running the task. This ensures that even if a key is added to the queue immediately after the previous cleanup, the retry will not be executed right away but will respect the configured interval.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java (hunk 12 above)
Comment (dybyte) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: Currently, failed cleanup tasks are added back to the retry queue. This might lead to an infinite retry loop in some cases. Do you think we should limit the number of retries? If so, what would be a reasonable limit? @Hisoka-X

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobMaster.java (hunk 9 above)
Comment (dybyte) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobMaster.java]: Done. I integrated `removeMetricsContext()` into the `MetricsCleanupUtil` class

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/JobClientJobProxyIT.java (hunk 8 above)
Comment (dybyte) [reply seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/JobClientJobProxyIT.java]: Thanks for your guidance! It really helped me find a way to test this part.

**Comment by dybyte** [comment]
I noticed this failure after the recent changes.  
Unfortunately, I can’t look into it right now due to other tasks, but I’ll check and fix it as soon as possible.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java (hunk 12 above)
Comment (Hisoka-X) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: When data is put back into the queue, it will be put at the end of the queue, so there is no need to increase the number of retries. Perhaps we should eliminate the data at the head of the queue when the queue is full.

Comment (dybyte) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: I've set both the retry queue capacity and the batch size to 100. This should be sufficient to avoid issues in most cases.
Additionally, these values are exposed as configurable options, so they can be adjusted if different environments require larger or smaller capacities.

File: docs/en/seatunnel-engine/hybrid-cluster-deployment.md [hunk 13]
```diff
@@ -168,12 +168,31 @@ The corePoolSize of seatunnel coordinator job's executor cached thread pool
...
+
 Example
 
 ```yaml
 coordinator-service:
    core-thread-num: 30
    max-thread-num: 1000
+   cleanup-retry-interval: 60
+   cleanup-retry-queue-size: 100
+   cleanup-retry-batch-size: 100
```
Comment (Hisoka-X) [inline docs/en/seatunnel-engine/hybrid-cluster-deployment.md]:
```suggestion
   metrics.cleanup-retry-interval: 60
   metrics.cleanup-retry-queue-size: 1024
```

`cleanup-retry-batch-size` looks like useless.

Comment (dybyte) [reply docs/en/seatunnel-engine/hybrid-cluster-deployment.md]: I've made the changes. Thanks for the suggestion to increase the default retry queue size to 1024. Could you share the reason behind choosing this value?

File: docs/en/seatunnel-engine/hybrid-cluster-deployment.md [hunk 14]
```diff
@@ -168,12 +168,25 @@ The corePoolSize of seatunnel coordinator job's executor cached thread pool
...
+Default value is 1024.
+
 Example
 
 ```yaml
 coordinator-service:
    core-thread-num: 30
    max-thread-num: 1000
+   cleanup-retry-interval: 60
+   cleanup-retry-queue-size: 1024
```
Comment (Hisoka-X) [inline docs/en/seatunnel-engine/hybrid-cluster-deployment.md]: Hi @dybyte . Perhaps we should follow [this comment](https://github.com/apache/seatunnel/pull/9427#pullrequestreview-2920391531) to modify it to remove the distributed lock, which can remove the unnecessary queue and retry thread. Sorry to tell you now, I just remembered it. Thanks.

Comment (dybyte) [reply docs/en/seatunnel-engine/hybrid-cluster-deployment.md]: Thanks for pointing this out! This seems like a larger change. How about creating a follow-up issue for this refactoring so we can track it separately? If that works for you, could you help create the issue and assign it to me? I'd be happy to work on it. @Hisoka-X

Comment (Hisoka-X) [reply docs/en/seatunnel-engine/hybrid-cluster-deployment.md]: Ok, but we should fix it before release next version. So I think we can revert the code of `queue and retry thread` in this pr.

Comment (Hisoka-X) [reply docs/en/seatunnel-engine/hybrid-cluster-deployment.md]: https://github.com/apache/seatunnel/issues/9727

Comment (dybyte) [reply docs/en/seatunnel-engine/hybrid-cluster-deployment.md]: Got it, when is the next release scheduled?

Comment (Hisoka-X) [reply docs/en/seatunnel-engine/hybrid-cluster-deployment.md]: Not sure yet, maybe the end of this month or the beginning of next month

Comment (dybyte) [reply docs/en/seatunnel-engine/hybrid-cluster-deployment.md]: I’ve removed the retry queue and thread changes as discussed. Please take a look when you get a chance. @Hisoka-X

File: seatunnel-engine/seatunnel-engine-server/src/test/resources/batch_slot_not_enough.conf [hunk 15]
```diff
@@ -0,0 +1,48 @@
...
+# limitations under the License.
+#
+######
+###### This config file is a demonstration of streaming processing in seatunnel config
+######
+
+env {
+  # You can set engine configuration here
+  job.mode = "BATCH"
+  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/test/resources/batch_slot_not_enough.conf]:
```suggestion
```

**Review by Hisoka-X — DISMISSED** [review]
LGTM if ci passes. Thanks @dybyte

**Review by hawk9821 — DISMISSED** [review]
LGTM, let's merge!  Thanks @dybyte

**Comment by dybyte** [comment]
Hi @Hisoka-X @hawk9821 
I fixed the merge conflicts caused by a recent PR and pushed the changes. Please take another look when you have a moment. Thanks!

**Comment by Hisoka-X** [comment]
waiting test case passes.

**Comment by dybyte** [comment]
CI checks have passed. Thanks for reviewing

**Review by hawk9821 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]
Thanks @dybyte !

**Comment by injae-kim** [comment]
Nice work @dybyte 👍👍👍
