### PR TITLE
[Fix][Connector-jdbc] Fix postgresql sink trying to update unique key (#9293)

### LINKED ISSUE #9293: [Bug] [Connector-V2] sink trying to update primary key in distribute sink database
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I am trying to running seatunnel with standalone mysql database and cluster postgresql sink database.
And it gives following ERROR:

It seems that it is trying to update id's value with id condition. how to prevent updating primary columns?

### SeaTunnel Version

2.3.10

### SeaTunnel Config

```conf
env {
  job.name = "mysql-cdc-test"
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 5000
}

source {
  MySQL-CDC {
    server-id = 5652
    username = "system"
    password = "xxxxxxxxx"
    table-names = ["seatunnel.role"]
    base-url = "jdbc:mysql://10.xx.xx.xx:3306"
  }
}

transform {
}

sink {
  jdbc {
    url = "jdbc:postgresql://xxxxxxxxx:11345/tmodel"
    driver = "org.postgresql.Driver"
    user = "xxxxx"
    password = "xxxxxxxx"
    generate_sink_sql = true
    data_save_mode = DROP_DATA
    database = "tmodel"
    table = "data.${table_name}"
    primary_keys = ["${primary_key}"]
    enable_upsert = false
    support_upsert_by_query_primary_key_exist = false
  }
}
```

### Running Command

```shell
`seatunnel.sh --config mysql-cdc-test.conf `
```

### Error Exception

```log
Caused by: java.sql.BatchUpdateException: Batch entry 0 UPDATE "tmodel"."data"."role" SET "id" = ('15'::int4), "type" = ('1'::int4), "role_name" = ('NORMAL_ROLE2'), "description" = ('Normal User'), "create_time" = ('2025-03-24 08:45:55.804+08'), "update_time" = ('2025-05-08 13:31:13.768+08') WHERE "id" = ('15'::int4) was aborted: ERROR: Distributed column "id" can't be updated in current version  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:186)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:591)
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:889)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:913)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1739)
        at org.apache.seatunnel.shade.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
        at org.apache.seatunnel.shade.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.FieldNamedPreparedStatement.executeBatch(FieldNamedPreparedStatement.java:540)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.InsertOrUpdateBatchStatementExecutor.executeBatch(InsertOrUpdateBatchStatementExecutor.java:108)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.BufferReducedBatchStatementExecutor.executeBatch(BufferReducedBatchStatementExecutor.java:89)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.attemptFlush(JdbcOutputFormat.java:172)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.flush(JdbcOutputFormat.java:136)
        ... 9 more
Caused by: org.postgresql.util.PSQLException: ERROR: Distributed column "id" can't be updated in current version
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2733)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2420)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:580)
        ... 19 more

        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:220)
        ... 2 more
2025-05-08 13:31:41,309 INFO  [s.c.s.s.c.ClientExecuteCommand] [SeaTunnel-CompletableFuture-Thread-0] - run shutdown hook because get close signal
```

### Zeta or Flink or Spark Version

zeta with seatunnel v2.3.10 

### Java or Scala Version

java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.391-b13, mixed mode)

### Screenshots

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by papadave66**
### Purpose of this pull request

close #9293 

The JDBC connector of postgresql trying to update primary key colums which is not needed. Then I do some research on apache/flink-connector-jdbc#155 . They fix this month ago. So I think fix in here should be a good idea :)
And I use [fix] instead of [bug] because I am not sure if it is a bug or a feature.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit test: `org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.psql.PostgresDialectTest`

### Check list

* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [x] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-connectors-v2/connector-jdbc/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/psql/PostgresDialectTest.java [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+    @Test
+    void testUpsertStatement() {
+        PostgresDialect dialect = new PostgresDialect();
+        final String database = "seatunnel";
+        final String tableName = "role";
+        final String[] fieldNames = {
+                "id", "type", "role_name", "description", "create_time", "update_time"
+        };
+        final String[] doUpdateKeyFields = {"id"};
+        final String[] doNothingKeyFields = {
```
Comment (papadave66) [inline seatunnel-connectors-v2/connector-jdbc/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/psql/PostgresDialectTest.java:34]: changed to camelCase style.

**Comment by Hisoka-X** [comment]
Thanks @papadave66 ! LGTM. Please open ci on your fork repository. https://github.com/apache/seatunnel/pull/9298/checks?check_run_id=41943176159

**Comment by papadave66** [comment]
> Thanks @papadave66 ! LGTM. Please open ci on your fork repository. https://github.com/apache/seatunnel/pull/9298/checks?check_run_id=41943176159

Oh I just enabled the flow. Please tell me if i am doing correctly.

**Comment by Hisoka-X** [comment]
Please resolve the conflicts.

**Comment by Hisoka-X** [comment]
wating ci passes.

**Comment by papadave66** [comment]
Hi,
I noticed that the CI has completed, but there are still some failed jobs. Could you please confirm whether this is the expected result?
If not, could you advise on what I should do next to address this issue?

Thanks in advance!

**Comment by papadave66** [comment]
> Hi, I noticed that the CI has completed, but there are still some failed jobs. Could you please confirm whether this is the expected result? If not, could you advise on what I should do next to address this issue?
> 
> Thanks in advance!

oh it turns ok after few times retry failed jobs.

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]
