### PR TITLE
[Bug] [Connector-V2] Fix hive source connector parallelism not work

### LINKED ISSUE #2812: [Bug] [Connector-V2] Hive Source Connector parallelism not work
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The test data can found in https://github.com/apache/incubator-seatunnel/issues/2793

The test table have 10 files

image

I set `execution.parallelism = 3` and I found 3 tasks run, but only one task read the hive data.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
  # You can set flink configuration here
  execution.parallelism = 3
  job.name="test_hive_source_to_console"
}

source {
  # This is a example input plugin **only for test and demonstrate the feature input plugin**

  Hive {
    table_name = "test_hive.test_hive_source"
    metastore_uri = "thrift://ctyun7:9083"
  }

  # If you would like to get more information about how to configure seatunnel and see full list of input plugins,
  # please go to https://seatunnel.apache.org/docs/flink/configuration/source-plugins/Fake
}

transform {

}

sink {
  # choose stdout output plugin to output data to console
  Console {
  }

  # If you would like to get more information about how to configure seatunnel and see full list of output plugins,
  # please go to https://seatunnel.apache.org/docs/flink/configuration/sink-plugins/Console
}
```

### Running Command

```shell
sh start-seatunnel-spark-connector-v2.sh --config ../config/spark_hive_to_console.conf --deploy-mode client --master yarn
```

### Error Exception

```log
2 tasks run in test9 node.


[root@test9 application_1660830627671_0128]# ls
container_e08_1660830627671_0128_01_000001  container_e08_1660830627671_0128_01_000003
[root@test9 application_1660830627671_0128]# ll -rt ./*
./container_e08_1660830627671_0128_01_000003:
total 8
-rw-r--r-- 1 root root    0 Sep 20 17:54 prelaunch.err
-rw-r--r-- 1 root root   70 Sep 20 17:54 prelaunch.out
-rw-r--r-- 1 root root    0 Sep 20 17:54 stdout
-rw-r--r-- 1 root root 3914 Sep 20 17:54 stderr

./container_e08_1660830627671_0128_01_000001:
total 16
-rw-r--r-- 1 root root    0 Sep 20 17:54 prelaunch.err
-rw-r--r-- 1 root root   70 Sep 20 17:54 prelaunch.out
-rw-r--r-- 1 root root    0 Sep 20 17:54 stdout
-rw-r--r-- 1 root root 9149 Sep 20 17:54 stderr
[root@test9 application_1660830627671_0128]# 
```

1 task run in test7 node

```
[root@test7 application_1660830627671_0128]# ls
container_e08_1660830627671_0128_01_000002
[root@test7 application_1660830627671_0128]# ll -rt ./*
total 24
-rw-r--r-- 1 root root    0 Sep 20 17:54 prelaunch.err
-rw-r--r-- 1 root root   70 Sep 20 17:54 prelaunch.out
-rw-r--r-- 1 root root 9279 Sep 20 17:54 stdout
-rw-r--r-- 1 root root 6410 Sep 20 17:54 stderr
```

Only the container_e08_1660830627671_0128_01_000002  output the data read from hive and it have all the 40 rows data. container_e08_1660830627671_0128_01_000003 and container_e08_1660830627671_0128_01_000001 did not assigned any split.

### Flink or Spark Version

SeaTunnel version: dev
Hadoop version: Hadoop 2.10.2
Flink version: 1.12.7
Spark version: 2.4.3, scala version 2.11.12

### Java or Scala Version

JDK 1.8

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by TyrantLucifer**
## Purpose of this pull request

fix #2812  https://github.com/apache/incubator-seatunnel/issues/2815

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

File: seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/source/split/FileSourceSplitEnumerator.java [hunk 1]
```diff
@@ -56,45 +55,54 @@ public void open() {
...
     }
 
-    private Set<FileSourceSplit> getHiveFileSplit() {
-        Set<FileSourceSplit> hiveSourceSplits = new HashSet<>();
-        filePaths.forEach(k -> hiveSourceSplits.add(new FileSourceSplit(k)));
-        return hiveSourceSplits;
-
+    private Set<FileSourceSplit> getFileSplit() {
+        Set<FileSourceSplit> fileSourceSplits = new HashSet<>();
+        filePaths.forEach(k -> fileSourceSplits.add(new FileSourceSplit(k)));
```
Comment (EricJoy2048) [inline seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/source/split/FileSourceSplitEnumerator.java:63]: Is `filePaths` possible to be null?

File: seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/source/split/FileSourceSplitEnumerator.java [hunk 2]
```diff
@@ -56,45 +55,54 @@ public void open() {
 
     @Override
     public void run() {
-        pendingSplit = getHiveFileSplit();
-        assignSplit(context.registeredReaders());
+        // do nothing
```
Comment (hailin0) [inline seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/source/split/FileSourceSplitEnumerator.java:58]: line#52  `assignedSplit` cannot be re -initialized, it may contain restore state

**Review by EricJoy2048 — APPROVED** [review]
+1

**Review by Hisoka-X — APPROVED** [review]
