### PR TITLE
[Fix][Spark] Fix source parallelism not working with Spark engine

### LINKED ISSUE #9302: [Bug] [Connector-v2] Bug title The Source Common Options parallelism not work
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I set the parallelism to 5 in env and set the parallelism to 1 in Source. However, the result shows that the parallelism has not been changed to 1, but remains at 5. Is this a bug, or am I using it incorrectly?

Image
This is mentioned on the page Source Common Options in the official documentation.

Image

Then I continued to experiment with Doris and Fakesource, but this parameter still had no effect.

I found the relevant parallelism settings in the code, and it seems that this does not read from the Source, but only reads from the Env.

Image

### SeaTunnel Version

the seatunnel version is 2.3.10;

### SeaTunnel Config

```conf
env{
  parallelism = 5
  job.mode = "BATCH"
  spark.master=local
}

source {
  Http {
    parallelism = 1
    plugin_output = "http"
    url = "http://localhost:8083/ttt/testhttp"
    method = "GET"
    format = "json"
    schema = {
      fields {
        msg = string
      }
    }
  }
}
transform{

}
sink{
 Console = {
 plugin_input = "http"
 }

}
```

### Running Command

```shell
I run it in SeaTunnelApiExample.class.
```

### Error Exception

```log
Caused by: java.lang.IllegalArgumentException: A single split source allows only one single reader to be created. Please make sure source parallelism = 1
	at org.apache.seatunnel.shade.com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
	at org.apache.seatunnel.connectors.seatunnel.common.source.AbstractSingleSplitSource.createReader(AbstractSingleSplitSource.java:34)
	at org.apache.seatunnel.connectors.seatunnel.common.source.AbstractSingleSplitSource.createReader(AbstractSingleSplitSource.java:28)
	at org.apache.seatunnel.translation.source.ParallelSource.<init>(ParallelSource.java:106)
	... 30 more
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by joexjx**
close: https://github.com/apache/seatunnel/issues/9302

This bug was caused by EnvCommonOptions overriding SourceCommonOptions when setting the parallelism in the sparkRuntimeEnvironment.

### Check list

* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

File: seatunnel-core/seatunnel-spark-starter/seatunnel-spark-starter-common/src/main/java/org/apache/seatunnel/core/starter/spark/execution/SourceExecuteProcessor.java [hunk 1]
```diff
@@ -92,12 +92,12 @@ public List<DatasetTableInfo> execute(List<DatasetTableInfo> upstreamDataStreams
...
                                         EnvCommonOptions.PARALLELISM.defaultValue());
             }
+            envOption.put(EnvCommonOptions.PARALLELISM.key(), String.valueOf(parallelism));
             Dataset<Row> dataset =
                     sparkRuntimeEnvironment
                             .getSparkSession()
                             .read()
                             .format(SeaTunnelSource.class.getSimpleName())
-                            .option(EnvCommonOptions.PARALLELISM.key(), parallelism)
                             .option(
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-spark-starter/seatunnel-spark-starter-common/src/main/java/org/apache/seatunnel/core/starter/spark/execution/SourceExecuteProcessor.java:101]: Thanks @joexjx . But in seatunnel, we recommend configuring parallelism in env rather than source configuration. This helps improve configuration consistency across different engines. Maybe you can help update the documentation to make the description clearer.

Comment (joexjx) [reply seatunnel-core/seatunnel-spark-starter/seatunnel-spark-starter-common/src/main/java/org/apache/seatunnel/core/starter/spark/execution/SourceExecuteProcessor.java:101]: I understand. However, this code does contain a very simple and obvious error. envOption is a HashMap that already includes EnvCommonOptions.PARALLELISM.key(). The .option(EnvCommonOptions.PARALLELISM.key(), parallelism) call is being overwritten by .options(envOption), which is why the properly configured parallelism (determined earlier based on whether it comes from env or source) isn't taking effect.

Old Code
image

New Code
image

Comment (joexjx) [reply seatunnel-core/seatunnel-spark-starter/seatunnel-spark-starter-common/src/main/java/org/apache/seatunnel/core/starter/spark/execution/SourceExecuteProcessor.java:101]: I removed .option(EnvCommonOptions.PARALLELISM.key(), ...) and updated envOptions with EnvCommonOptions.PARALLELISM in advance. This ensures that the parallelism value (which was already determined earlier based on whether it should be taken from env or source) takes effect correctly.

**Comment by Hisoka-X** [comment]
Seem like the commit history mess. Please rebase on dev.

**Review by Hisoka-X — APPROVED** [review]

**Review by Hisoka-X — CHANGES_REQUESTED** [review]
Please add unit test case.

File: seatunnel-core/seatunnel-spark-starter/seatunnel-spark-3-starter/src/test/java/org/apache/seatunnel/core/starter/spark/singlesplitsource/SingleSplitSourceParallelismTest.java [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+import java.io.FileNotFoundException;
+import java.net.URISyntaxException;
+import java.net.URL;
+import java.nio.file.Paths;
+
+@Slf4j
+@Order(1)
+public class SingleSplitSourceParallelismTest {
+    @Test
+    public void testSourceParallelismIsOneButEnvParallelismIsNotOne()
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-spark-starter/seatunnel-spark-3-starter/src/test/java/org/apache/seatunnel/core/starter/spark/singlesplitsource/SingleSplitSourceParallelismTest.java]: The current test case is a bit overly complex. We just need to ensure that the DataSet returned by the `execute` method of `SourceExecuteProcessor` has the expected parallelism.
```
SourceExecuteProcessor processor = new SourceExecuteProcessor();
... init

Assertions.equals(10, processor.execute(xxx).get(0).getDataset().rdd().getNumPartitions());

```

**Comment by Hisoka-X** [comment]
waiting test case passes.

File: seatunnel-core/seatunnel-spark-starter/seatunnel-spark-3-starter/src/test/java/org/apache/seatunnel/core/starter/spark/singlesplitsource/SingleSplitSourceParallelismTest.java (hunk 2 above)
Comment (joexjx) [reply seatunnel-core/seatunnel-spark-starter/seatunnel-spark-3-starter/src/test/java/org/apache/seatunnel/core/starter/spark/singlesplitsource/SingleSplitSourceParallelismTest.java]: @Hisoka-X Thank you for the guidance, I have added a simpler unit test.

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]
