### PR TITLE
[Hotfix][Connector-V2][SFTP] Add quote to sftp file names with wildcard characters

### LINKED ISSUE #8500: [Bug] [Sftp Reader] If there are wildcard file names in the sftp directory and there happen to be other matching file names, a uniqueness error will occur
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

If there are wildcard file names in the sftp directory and there happen to be other matching file names, a uniqueness error will occur.
For example, there are two files, `a * b.txt` and `abc.txt`, in the `/data` directory. When configuring/data/a * b.txt, a uniqueness error occurs.
Clipboard_Screenshot_1736600413

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  SftpFile {
    host = ""
    port = xxx
    user = xxx
    password = xxx
    path = "/data/a*b.txt"
    file_format_type = "text"
    field_delimiter = ","
    schema = {
      fields {
        c_int = int
        c_string = string
      }
    }
  }
}

transform {
}

sink {
  console {
  }
}
```

### Running Command

```shell
`org.apache.seatunnel.example.engine.SeaTunnelEngineLocalExample`


public static void main(String[] args)
            throws FileNotFoundException, URISyntaxException, CommandException {
        String configurePath = args.length > 0 ? args[0] : "/examples/sftp_to_console.conf";
        String configFile = getTestConfigFile(configurePath);
        ClientCommandArgs clientCommandArgs = new ClientCommandArgs();
        clientCommandArgs.setConfigFile(configFile);
        clientCommandArgs.setCheckConfig(false);
        clientCommandArgs.setJobName(Paths.get(configFile).getFileName().toString());
        // Change Execution Mode to CLUSTER to use client mode, before do this, you should start
        // SeaTunnelEngineClusterServerExample
        clientCommandArgs.setMasterType(MasterType.LOCAL);
        SeaTunnel.run(clientCommandArgs.buildCommand());
    }
```

### Error Exception

```log
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.connectors.seatunnel.file.exception.FileConnectorException: ErrorCode:[FILE-08], ErrorDescription:[File read failed] - Read data from this file [default.default.default_sftp://xxxx/data/aa*bbb.txt] failed
    at org.apache.seatunnel.connectors.seatunnel.file.source.reader.MultipleTableFileSourceReader.pollNext(MultipleTableFileSourceReader.java:85)
    at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:159)
    at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:127)
    at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:169)
    at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:132)
    at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:694)
    at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1019)
    at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:43)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: 4: /data/aa*bbb.txt is not unique: [/data/aa123bbb.txt, /data/aa*bbb.txt]
    at org.apache.seatunnel.connectors.seatunnel.file.sftp.system.SFTPFileSystem.open(SFTPFileSystem.java:495)
    at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:899)
    at org.apache.seatunnel.connectors.seatunnel.file.hadoop.HadoopFileSystemProxy.lambda$getInputStream$11(HadoopFileSystemProxy.java:195)
    at org.apache.seatunnel.connectors.seatunnel.file.hadoop.HadoopFileSystemProxy.execute(HadoopFileSystemProxy.java:327)
    at org.apache.seatunnel.connectors.seatunnel.file.hadoop.HadoopFileSystemProxy.getInputStream(HadoopFileSystemProxy.java:195)
    at org.apache.seatunnel.connectors.seatunnel.file.source.reader.AbstractReadStrategy.resolveArchiveCompressedInputStream(AbstractReadStrategy.java:272)
    at org.apache.seatunnel.connectors.seatunnel.file.source.reader.TextReadStrategy.read(TextReadStrategy.java:71)
    at org.apache.seatunnel.connectors.seatunnel.file.source.reader.MultipleTableFileSourceReader.pollNext(MultipleTableFileSourceReader.java:81)
    ... 12 more
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by e-mhui**
[Hotfix][Connector-V2][SFTP] Add quote to sftp file names with wildcard characters

### Purpose of this pull request

Fix #8500.

### Does this PR introduce _any_ user-facing change?

No.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by corgy-w** [comment]
@e-mhui Thank you for your contribution. Please open ci according to the guidance and add the tests corresponding to the modified parts.

**Comment by e-mhui** [comment]
> @e-mhui Thank you for your contribution. Please open ci according to the guidance and add the tests corresponding to the modified parts.

Ok, I'll add the test later.

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-sftp-e2e/src/test/java/org/apache/seatunnel/e2e/connector/file/fstp/SftpFileIT.java [hunk 1]
```diff
@@ -113,6 +113,15 @@ public void startUp() throws Exception {
                 "/home/seatunnel/tmp/seatunnel/read/xml/name=tyrantlucifer/hobby=coding/e2e.xml",
                 sftpContainer);
 
+        ContainerUtil.copyFileIntoContainers(
+                "/wildcard/e*e.txt",
+                "/home/seatunnel/tmp/seatunnel/read/wildcard/e*e.txt",
```
Comment (corgy-w) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-sftp-e2e/src/test/java/org/apache/seatunnel/e2e/connector/file/fstp/SftpFileIT.java:120]: See ci, there is a problem with this file path

Comment (e-mhui) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-sftp-e2e/src/test/java/org/apache/seatunnel/e2e/connector/file/fstp/SftpFileIT.java:120]: It seems that Windows does not support file names with wildcard characters. Can test cases bypass Windows?

Comment (corgy-w) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-sftp-e2e/src/test/java/org/apache/seatunnel/e2e/connector/file/fstp/SftpFileIT.java:120]: Try to isolate this test by trying '@DisabledOnOs(OS.WINDOWS)'

Comment (e-mhui) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-sftp-e2e/src/test/java/org/apache/seatunnel/e2e/connector/file/fstp/SftpFileIT.java:120]: Thx, I'll try again

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-sftp-e2e/src/test/java/org/apache/seatunnel/e2e/connector/file/fstp/SftpFileIT.java [hunk 2]
```diff
@@ -113,6 +115,17 @@ public void startUp() throws Exception {
...
 
+        // Windows does not support files with wildcard characters. We can rename `e2e.txt` to
+        // `e*e.txt` when copying to a container
+        ContainerUtil.copyFileIntoContainers(
+                "/wildcard/e2e.txt",
+                "/home/seatunnel/tmp/seatunnel/read/wildcard/e*e.txt",
+                sftpContainer);
+
+        ContainerUtil.copyFileIntoContainers(
+                "/wildcard/e2e.txt",
```
Comment (corgy-w) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-sftp-e2e/src/test/java/org/apache/seatunnel/e2e/connector/file/fstp/SftpFileIT.java]: File forgot to submit when pushing

Comment (e-mhui) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-sftp-e2e/src/test/java/org/apache/seatunnel/e2e/connector/file/fstp/SftpFileIT.java]: Thx

**Review by Hisoka-X — COMMENTED** [review]
Hi @e-mhui , does other file system will face same problems?

**Comment by e-mhui** [comment]
> Hi @e-mhui , does other file system will face same problems?

@Hisoka-X Other file systems will not have this problem. This is because the code in jsch uses `get` to retrieve the file stream, which calls the `isUnique` method to check if the file is unique. However, file names with wildcards will match multiple files, causing `is not unique` error. If we already know the file exists, we can add escape characters to avoid this problem.

https://github.com/rtyley/jsch/blob/96b0558b66ec8982e708e46b6e5a254a3650d01b/src/com/jcraft/jsch/ChannelSftp.java#L864

```java
public InputStream get(String src, final SftpProgressMonitor monitor, final long skip) throws SftpException{

    try{
      ((MyPipedInputStream)io_in).updateReadSide();

      src=remoteAbsolutePath(src);
      src=isUnique(src);
     //........
   }
}

  /**
   * This method will check if the given string can be expanded to the
   * unique string.  If it can be expanded to mutiple files, SftpException
   * will be thrown.
   * @return the returned string is unquoted.
   */
  private String isUnique(String path) throws SftpException, Exception{
    Vector v=glob_remote(path);
    if(v.size()!=1){
      throw new SftpException(SSH_FX_FAILURE, path+" is not unique: "+v.toString());
    }
    return (String)(v.elementAt(0));
  }
```

File: seatunnel-connectors-v2/connector-file/connector-file-sftp/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/sftp/system/SFTPFileSystem.java [hunk 3]
```diff
@@ -154,6 +155,29 @@ private boolean exists(ChannelSftp channel, Path file) throws IOException {
...
+        byte[] _path2 = new byte[_path.length + count];
+        for (int i = 0, j = 0; i < _path.length; i++) {
+            byte b = _path[i];
+            if (b == '\\' || b == '?' || b == '*') {
+                _path2[j++] = '\\';
+            }
+            _path2[j++] = b;
+        }
+        return new String(_path2, 0, _path2.length, StandardCharsets.UTF_8);
+    }
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-file/connector-file-sftp/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/sftp/system/SFTPFileSystem.java]: Please add a UT for this method.

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-sftp-e2e/src/test/resources/text/sftp_file_text_wildcard_character_to_assert.conf [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+  }
+}
+
+sink {
+  Assert {
+    plugin_input = "sftp"
+    rules {
+      row_rules = [
+        {
+          rule_type = MAX_ROW
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-sftp-e2e/src/test/resources/text/sftp_file_text_wildcard_character_to_assert.conf]:
```suggestion
          rule_type = MIN_ROW
```

File: seatunnel-connectors-v2/connector-file/connector-file-sftp/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/sftp/system/SFTPFileSystem.java (hunk 3 above)
Comment (e-mhui) [reply seatunnel-connectors-v2/connector-file/connector-file-sftp/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/sftp/system/SFTPFileSystem.java]: Hello, this is my first pr. Where should I add the test case for the individual method，thanks.

Comment (Hisoka-X) [reply seatunnel-connectors-v2/connector-file/connector-file-sftp/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/sftp/system/SFTPFileSystem.java]: put it in https://github.com/apache/seatunnel/tree/dev/seatunnel-connectors-v2/connector-file/connector-file-sftp/src/test/java/org/apache/seatunnel/connectors/seatunnel/file/sftp

Comment (e-mhui) [reply seatunnel-connectors-v2/connector-file/connector-file-sftp/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/sftp/system/SFTPFileSystem.java]: Thx, please review again.

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]
