### PR TITLE
[Fix][Connector-V2] Use upload session for insert

### LINKED ISSUE #10042: [Bug] 2.3.12 maxcompute sink Primary key not found or invalid
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

2.3.12's seatunnel currently only supports creating transactional tables with specified primary keys in MaxCompute sink, and does not support creating standard tables. Additionally, there is an error in the configuration template on the official website documentation. The default save_mode_create_template should be set with 'transactional'='true' and PRIMARY KEY (`specific fields`) to allow the collection job to proceed normally. However, the default collection template on the official website does not enable transactions or specify primary keys, which will cause the job to fail with a prompt indicating that the primary key is missing or does not exist. MaxCompute's standard tables do not support primary key constraints, so the template settings must enable transactional operations.The source has already been confirmed as a primary key MySQL table.

Image

Solution：maxcompute sink template should be：
sink {
  Maxcompute {
    accessId = "******"
    accesskey = "*******"
    endpoint = "*******/api"
    project = "******"
    table_name = "zbx_payment_info"
    schema_save_mode = "RECREATE_SCHEMA"
    data_save_mode = "DROP_DATA"
	save_mode_create_template = "CREATE TABLE IF NOT EXISTS `${table}` (${rowtype_fields}, PRIMARY KEY (`id`))TBLPROPERTIES ('transactional'='true','comment'='${comment}');"
  }

### SeaTunnel Version

2.3.12

### SeaTunnel Config

```conf
env {
  parallelism = 4
  job.mode = "BATCH"
}

source {
  Jdbc {
    url = "jdbc:mysql://******8.mysql.rds.aliyuncs.com:3306/***?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true"
    driver = "com.mysql.cj.jdbc.Driver"
    connection_check_timeout_sec = 100
    username = "*******"
    password = "*******"
    query = "select * from zbx_payment_info limit 16;"
  }
}

transform {
}

sink {
  Maxcompute {
    accessId = "******"
    accesskey = "*******"
    endpoint = "*******/api"
    project = "******"
    table_name = "zbx_payment_info"
    schema_save_mode = "RECREATE_SCHEMA"
    data_save_mode = "DROP_DATA"
	save_mode_create_template = "CREATE TABLE IF NOT EXISTS `${table}` (${rowtype_fields}, PRIMARY KEY (`id`))TBLPROPERTIES ('transactional'='true','comment'='${comment}');"
  }
}
```

### Running Command

```shell
seatunnel.sh --config mysql2mc_test.conf -m local
```

### Error Exception

```log
log：
Caused by: org.apache.seatunnel.common.exception.SeaTunnelRuntimeException: ErrorCode:[COMMON-23], ErrorDescription:[Maxcompute write SeaTunnelRow failed, the SeaTunnelRow value is 'SeaTunnelRow{tableId=shucang_test.zbx_payment_info, kind=+I, fields=[35245, 696587184968912, 47177, 6, 1102, null, 9197.00, Apple iPhone 12 (A2404) 128GB 黑色 支持移动联通电信5G 双卡双待手机等1件商品, 1602, 2022-06-11T09:41:02, 2022-06-11T09:41:02, callback xxxxxxx, 2022-06-11T09:41:02]}'.]
        at org.apache.seatunnel.common.exception.CommonError.writeSeaTunnelRowFailed(CommonError.java:97)
        at org.apache.seatunnel.connectors.seatunnel.maxcompute.sink.MaxcomputeWriter.write(MaxcomputeWriter.java:56)
        at org.apache.seatunnel.connectors.seatunnel.maxcompute.sink.MaxcomputeWriter.write(MaxcomputeWriter.java:35)
        at org.apache.seatunnel.api.sink.multitablesink.MultiTableWriterRunnable.run(MultiTableWriterRunnable.java:67)
        ... 6 more
Caused by: RequestId=20251105190700df8a341a02d2de97, ErrorCode=MethodNotAllowed, ErrorMessage=Primary key not found or invalid
        at com.aliyun.odps.tunnel.impl.SessionBase.httpRequestWithNoRetry(SessionBase.java:65)
        at com.aliyun.odps.tunnel.impl.SessionBase.lambda$httpRequest$0(SessionBase.java:91)
        at com.aliyun.odps.tunnel.io.TunnelRetryHandler.executeWithRetry(TunnelRetryHandler.java:105)
        at com.aliyun.odps.tunnel.io.TunnelRetryHandler.executeWithRetry(TunnelRetryHandler.java:97)
        at com.aliyun.odps.tunnel.impl.SessionBase.httpRequest(SessionBase.java:90)
        at com.aliyun.odps.tunnel.impl.UpsertSessionImpl.initiate(UpsertSessionImpl.java:268)
        at com.aliyun.odps.tunnel.impl.UpsertSessionImpl.<init>(UpsertSessionImpl.java:96)
        at com.aliyun.odps.tunnel.impl.UpsertSessionImpl$Builder.build(UpsertSessionImpl.java:677)
        at com.aliyun.odps.tunnel.impl.UpsertSessionImpl$Builder.build(UpsertSessionImpl.java:535)
        at org.apache.seatunnel.connectors.seatunnel.maxcompute.util.MaxcomputeOutputFormat.initializeUpsertSession(MaxcomputeOutputFormat.java:129)
        at org.apache.seatunnel.connectors.seatunnel.maxcompute.util.MaxcomputeOutputFormat.ensureUpsertSessionAndWriter(MaxcomputeOutputFormat.java:104)
        at org.apache.seatunnel.connectors.seatunnel.maxcompute.util.MaxcomputeOutputFormat.write(MaxcomputeOutputFormat.java:58)
        at org.apache.seatunnel.connectors.seatunnel.maxcompute.sink.MaxcomputeWriter.write(MaxcomputeWriter.java:52)
        ... 8 more

        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:220)
        ... 2 more
```

### Zeta or Flink or Spark Version

zeta:2.3.12

### Java or Scala Version

java1.8

### Screenshots

Image

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by dybyte**
Fixes: https://github.com/apache/seatunnel/issues/10042
### Purpose of this pull request

After #9462, upsert stream is used by default for MaxCompute sink.
However, tables without primary keys or transactional properties fail during upsert stream commit/close.
This breaks insert-only use cases that previously worked with upload sessions.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Although a test was added, it has been disabled since the maxcompute emulator does not support upload sessions.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If necessary, please update `incompatible-changes.md` to describe the incompatibility caused by this PR.
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

File: seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/util/MaxcomputeOutputFormat.java [hunk 1]
```diff
@@ -55,22 +60,15 @@ public MaxcomputeOutputFormat(SeaTunnelRowType rowType, ReadonlyConfig readonlyC
...
-                        seaTunnelRow,
-                        this.tableSchema,
-                        this.rowType,
-                        formatterContext);
-
         switch (seaTunnelRow.getRowKind()) {
             case INSERT:
+                insertRecord(seaTunnelRow);
+                break;
             case UPDATE_AFTER:
```
Comment (yzeng1618) [inline seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/util/MaxcomputeOutputFormat.java:85]: For UPDATE/DELETE operations on tables without a primary key, will an error still be thrown because the UpsertSession requires a primary key? It would be better to either clarify this in the documentation or throw an explicit exception.

File: seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/util/MaxcomputeOutputFormat.java [hunk 2]
```diff
@@ -55,22 +60,15 @@ public MaxcomputeOutputFormat(SeaTunnelRowType rowType, ReadonlyConfig readonlyC
...
-                upsertStream.upsert(newRecord);
+                upsertRecord(seaTunnelRow);
                 break;
             case DELETE:
```
Comment (yzeng1618) [inline seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/util/MaxcomputeOutputFormat.java:88]: ditto

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-maxcompute-e2e/src/test/java/org/apache/seatunnel/e2e/connector/maxcompute/MaxComputeIT.java [hunk 3]
```diff
@@ -216,6 +227,34 @@ public void testMaxCompute(TestContainer container)
     }
 
     @TestTemplate
+    @Disabled(
+            "maxcompute-emulator does not support upload session for now. MaxcomputeWriter uses upload session to insert data.")
```
Comment (yzeng1618) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-maxcompute-e2e/src/test/java/org/apache/seatunnel/e2e/connector/maxcompute/MaxComputeIT.java:229]: The key new capability (UploadSession insertion) is marked with @Disabled in the CI environment. Could we add a unit test to verify that the basic invocation process runs without errors?

File: seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/util/MaxcomputeOutputFormat.java (hunk 1 above)
Comment (dybyte) [reply seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/util/MaxcomputeOutputFormat.java:85]: Yes. I think throwing an explicit exception would be better.

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-maxcompute-e2e/src/test/java/org/apache/seatunnel/e2e/connector/maxcompute/MaxComputeIT.java (hunk 3 above)
Comment (dybyte) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-maxcompute-e2e/src/test/java/org/apache/seatunnel/e2e/connector/maxcompute/MaxComputeIT.java:229]: Given that UploadSession is not supported by the emulator and the core behavior depends on the Maxcompute SDK, mock-based unit tests would have very limited value here.

**Comment by zhangshenghang** [comment]
INSERT → UploadSession (batch insertion into the table during commit)
UPDATE_AFTER / DELETE → UpsertStream (real-time insertion into the table)

Could there be such a problem: When UpsertStream processes an UPDATE, the record written by UploadSession may not yet be visible in the table?

File: seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/util/MaxcomputeOutputFormat.java [hunk 4]
```diff
@@ -129,4 +177,34 @@ private void initializeUpsertSession() throws TunnelException, IOException {
                             .build();
         }
     }
+
+    private void ensureInsertSessionAndWriter() throws TunnelException {
+        if (uploadSession == null) {
+            initializeInsertSession();
+            Objects.requireNonNull(uploadSession, "UploadSession was not initialized properly");
```
Comment (zhangshenghang) [inline seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/util/MaxcomputeOutputFormat.java]: What about throwing an exception with throw new?

**Comment by dybyte** [comment]
> INSERT → UploadSession (batch insertion into the table during commit) UPDATE_AFTER / DELETE → UpsertStream (real-time insertion into the table)
> 
> Could there be such a problem: When UpsertStream processes an UPDATE, the record written by UploadSession may not yet be visible in the table?

I’ve considered this case, and I think it would be better to separate it via a configuration (`insert-mode` and `upsert-mode`). By default, `insert-mode` uses UploadSession for insert operations, while in `upsert-mode`, inserts use UpsertStream.
For `insert-mode`, it would be good to document this behavior. For `upsert-mode`, it should be clearly noted that a primary key is required. What do you think?

File: seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/util/MaxcomputeOutputFormat.java (hunk 4 above)
Comment (dybyte) [reply seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/util/MaxcomputeOutputFormat.java]: After reviewing the code again, it seems that this check is unnecessary, so it can be removed.

Comment (zhangshenghang) [reply seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/util/MaxcomputeOutputFormat.java]: > After reviewing the code again, it seems that this check is unnecessary, so it can be removed.

ok

**Comment by zhangshenghang** [comment]
> > INSERT → UploadSession (batch insertion into the table during commit) UPDATE_AFTER / DELETE → UpsertStream (real-time insertion into the table)
> > Could there be such a problem: When UpsertStream processes an UPDATE, the record written by UploadSession may not yet be visible in the table?
> 
> I’ve considered this case, and I think it would be better to separate it via a configuration (`insert-mode` and `upsert-mode`). By default, `insert-mode` uses UploadSession for insert operations, while in `upsert-mode`, inserts use UpsertStream. For `insert-mode`, it would be good to document this behavior. For `upsert-mode`, it should be clearly noted that a primary key is required. What do you think?

Then let's provide a detailed explanation in the document.

File: seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/util/MaxcomputeOutputFormat.java (hunk 1 above)
Comment (dybyte) [reply seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/util/MaxcomputeOutputFormat.java:85]: After reconsidering, I think documenting this is the better choice.

**Review by zhangshenghang — APPROVED** [review]
+1

**Review by corgy-w — APPROVED** [review]
