### PR TITLE
[Fix][paimon-e2e] e2e test error

### LINKED ISSUE #9466: [Bug] [connector-e2e] test class have error
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

the job read paimon data is empty when engine type in flink or spark

### SeaTunnel Version

1.12

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
noe
```

### Error Exception

```log
none
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by WenDing-Y**
### Purpose of this pull request

fix #9466 

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

**Comment by corgy-w** [comment]
Hi Why do need to change this? This test seems to be able to run in flink spark

**Comment by WenDing-Y** [comment]
The reader read data actually is empty,the assert is error

**Comment by WenDing-Y** [comment]
The write data in task manager,but read split info in jobmanager

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/java/org/apache/seatunnel/e2e/connector/paimon/PaimonIT.java [hunk 1]
```diff
@@ -34,9 +35,21 @@
 import java.nio.file.Path;
 
 @DisabledOnContainer(
-        value = TestContainerId.FLINK_1_13,
-        disabledReason = "Paimon does not support flink 1.13")
-public class PaimonIT extends TestSuiteBase {
+        value = {},
+        type = {EngineType.SPARK, EngineType.FLINK},
+        disabledReason =
+                "Spark and Flink engine can not auto create paimon table on worker node in local file(e.g flink tm) by savemode feature which can lead error")
```
Comment (corgy-w) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/java/org/apache/seatunnel/e2e/connector/paimon/PaimonIT.java]: It seems not necessary here

Comment (WenDing-Y) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/java/org/apache/seatunnel/e2e/connector/paimon/PaimonIT.java]: The fundamental reason is the lack of distributed storage. Why is the retrieved data empty? Because the data was written to the local node. The data write operation happens on the TaskManager node, while the JobManager is responsible for reading the split information. However, the JobManager cannot access the metadata of the data since there is no distributed storage system in place.

Another issue is why the assertion passes even though no data was read. This is because the assert statement was implemented incorrectly, allowing it to pass even when no data was actually retrieved.

Comment (WenDing-Y) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/java/org/apache/seatunnel/e2e/connector/paimon/PaimonIT.java]: @corgy-w

Comment (corgy-w) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/java/org/apache/seatunnel/e2e/connector/paimon/PaimonIT.java]: It might be that there is a error with assert

**Comment by Hisoka-X** [comment]
cc @hawk9821

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/resources/fake_to_dynamic_bucket_paimon_case1.conf [hunk 2]
```diff
@@ -42,10 +42,6 @@ source {
         c_timestamp = timestamp
         c_time = time
       }
-      primaryKey {
-          name = "pk_id"
-          columnNames = [pk_id]
-        }
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/resources/fake_to_dynamic_bucket_paimon_case1.conf:48]: why remove this?

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/java/org/apache/seatunnel/e2e/connector/paimon/PaimonIT.java (hunk 1 above)
Comment (Hisoka-X) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/java/org/apache/seatunnel/e2e/connector/paimon/PaimonIT.java]: Can we make jobmanager and taskmanager mount the same path to solve this problem?

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/resources/fake_to_dynamic_bucket_paimon_case1.conf (hunk 2 above)
Comment (WenDing-Y) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/resources/fake_to_dynamic_bucket_paimon_case1.conf:48]: The pk_id in the generated fake data is randomly created, which may lead to duplicate entries. Due to the primary key constraint, the actual amount of inserted data may be less than the target. The reason it passed the previous assertion is because the assertion was written incorrectly.

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/java/org/apache/seatunnel/e2e/connector/paimon/PaimonIT.java (hunk 1 above)
Comment (WenDing-Y) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/java/org/apache/seatunnel/e2e/connector/paimon/PaimonIT.java]: I attempted to resolve the issue by mounting the same file path, however, the necessary changes would need to be made in the AbstractTestFlinkContainer class — a shared base class. Modifying it could affect multiple tests and introduces too much risk. As an alternative, I looked into how other test classes handle similar cases, and decided that skipping the Spark and Flink engines is the most practical solution.
```
 @Override
    public void startUp() throws Exception {
        final String dockerImage = getDockerImage();
        final String properties = String.join("\n", getFlinkProperties());
        jobManager =
                new GenericContainer<>(dockerImage)
                        .withCommand("jobmanager")
                        .withNetwork(NETWORK)
                        .withNetworkAliases("jobmanager")
                        .withExposedPorts()
                        .withEnv("FLINK_PROPERTIES", properties)
                        .withLogConsumer(
                                new Slf4jLogConsumer(
                                        DockerLoggerFactory.getLogger(dockerImage + ":jobmanager")))
                        .waitingFor(
                                new LogMessageWaitStrategy()
                                        .withRegEx(".*Starting the resource manager.*")
                                        .withStartupTimeout(Duration.ofMinutes(2)));
        copySeaTunnelStarterToContainer(jobManager);
        copySeaTunnelStarterLoggingToContainer(jobManager);

        jobManager.setPortBindings(Lists.newArrayList(String.format("%s:%s", 8081, 8081)));

        taskManager =
                new GenericContainer<>(dockerImage)
                        .withCommand("taskmanager")
                        .withNetwork(NETWORK)
                        .withNetworkAliases("taskmanager")
                        .withEnv("FLINK_PROPERTIES", properties)
                        .dependsOn(jobManager)
                        .withLogConsumer(
                                new Slf4jLogConsumer(
                                        DockerLoggerFactory.getLogger(
                                                dockerImage + ":taskmanager")))
                        .waitingFor(
                                new LogMessageWaitStrategy()
                                        .withRegEx(
                                                ".*Successful registration at resource manager.*")
                                        .withStartupTimeout(Duration.ofMinutes(2)));

        Startables.deepStart(Stream.of(jobManager)).join();
        Startables.deepStart(Stream.of(taskManager)).join();
        // execute extra commands
        executeExtraCommands(jobManager);
    }


```

Comment (Hisoka-X) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/java/org/apache/seatunnel/e2e/connector/paimon/PaimonIT.java]: It should be possible to add a shared path address that other programs will not use. For example, /opt/seatunnel

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/resources/fake_to_dynamic_bucket_paimon_case1.conf (hunk 2 above)
Comment (Hisoka-X) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/resources/fake_to_dynamic_bucket_paimon_case1.conf:48]: make sense to me. cc @hawk9821

Comment (hawk9821) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/resources/fake_to_dynamic_bucket_paimon_case1.conf:48]: data generated by fakesource may indeed be repetitive.    0 - Integer.MAX_VALUE  the probability of repetition is relatively low, so this case can run correctly.  I think to ensure absolute certainty, we can enable fakesource to support the capability of auto-incrementing primary keys.   cc @WenDing-Y  @Hisoka-X

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/java/org/apache/seatunnel/e2e/connector/paimon/PaimonIT.java (hunk 1 above)
Comment (WenDing-Y) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-paimon-e2e/src/test/java/org/apache/seatunnel/e2e/connector/paimon/PaimonIT.java]: done

**Review by Hisoka-X — APPROVED** [review]
LGTM. Thanks @WenDing-Y

**Review by corgy-w — APPROVED** [review]
