### PR TITLE
[Bug] [formats] Fix fail to parse line when content contains the file delimiter

### LINKED ISSUE #6588: [Bug] [Seatunnel-formats] Fail to parse line if content contains the file delimiter
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I'm using the seatunnel Flink engine to ingest S3 Files. But the Seatunnel ends with an Exception:
````
Caused by: java.time.format.DateTimeParseException: Text '"2022-07-14 05:42:24"' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at org.apache.seatunnel.common.utils.DateTimeUtils.parse(DateTimeUtils.java:51)
	at org.apache.seatunnel.format.text.TextDeserializationSchema.convert(TextDeserializationSchema.java:271)
	at org.apache.seatunnel.format.text.TextDeserializationSchema.deserialize(TextDeserializationSchema.java:121)
	at org.apache.seatunnel.format.text.TextDeserializationSchema.deserialize(TextDeserializationSchema.java:45)
	at org.apache.seatunnel.connectors.seatunnel.file.source.reader.TextReadStrategy.lambda$read$0(TextReadStrategy.java:90)
````

The data that trigger above exception looks like this:
````
240002,9506858246848,"tes,t-dfw","2023-05-10 07:12:10","2023-06-05 07:57:59"
````

The root cause is my file contains the file delimiter in the line.  And in the org.apache.seatunnel.format.text.TextDeserializationSchema#splitLineBySeaTunnelRowType This line was wrongly split. 
[data.csv](https://github.com/apache/seatunnel/files/14768243/data.csv)

 

### SeaTunnel Version

2.3.4 with flink engine

### SeaTunnel Config

```conf
# Defining the runtime environment
env {
  # You can set flink configuration here
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
  S3File {
    result_table_name = "s3_source"
    path = "/test/"
    fs.s3a.endpoint="**.amazonaws.com"
    fs.s3a.aws.credentials.provider = "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    access_key = "***"
    secret_key = "***"
    bucket = "s3a://**"
    file_format_type = "csv"
    delimiter = ","
    skip_header_row_number = "1"
    schema {
          fields {
            id = int
            code = string
            name = string
            create_time = TIMESTAMP
            update_time = TIMESTAMP
          }
    }
  }
}

transform {
  Sql {
    source_table_name = "s3_source"
    result_table_name = "after_filter_result"
    query = "select * from s3_source where name like '%dfw%' "
  }
}

sink {
  Console {
    source_table_name = "after_filter_result"
  }
}
```

### Running Command

```shell
run SeaTunnelApiExample in the local IDEA
```

### Error Exception

```log
Caused by: java.time.format.DateTimeParseException: Text '"2022-07-14 05:42:24"' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at org.apache.seatunnel.common.utils.DateTimeUtils.parse(DateTimeUtils.java:51)
	at org.apache.seatunnel.format.text.TextDeserializationSchema.convert(TextDeserializationSchema.java:271)
	at org.apache.seatunnel.format.text.TextDeserializationSchema.deserialize(TextDeserializationSchema.java:121)
	at org.apache.seatunnel.format.text.TextDeserializationSchema.deserialize(TextDeserializationSchema.java:45)
	at org.apache.seatunnel.connectors.seatunnel.file.source.reader.TextReadStrategy.lambda$read$0(TextReadStrategy.java:90)
```

### Zeta or Flink or Spark Version

Flink 1.15.3

### Java or Scala Version

java 1.8

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by litiliu**
### Purpose of this pull request

This close #6588
This PR import the apache-common-csv to parse the line of csv file to ensure the csv file's line will not be split if it contains quotation marks.
if the original content is 
````
a,"b,c",d
````
and the delimiter is "," then it will be split into 
````
a     b,c    d
````
instead of 
````
a "b  c"  d
````

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

unit test has been added for the above case.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by HsbcJone** [comment]
auto failed

**Comment by EricJoy2048** [comment]
Please fix ci error.

File: seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/source/reader/TextReadStrategy.java [hunk 1]
```diff
@@ -232,5 +237,13 @@ private void initFormatter() {
                     pluginConfig.getString(BaseSourceConfigOptions.COMPRESS_CODEC.key());
             compressFormat = CompressFormat.valueOf(compressCodec.toUpperCase());
         }
+        if (FileFormat.CSV.equals(
```
Comment (TyrantLucifer) [inline seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/source/reader/TextReadStrategy.java:241]: if format == csv splitor = csvsplitor else splitor = defaultsplitor

Comment (TyrantLucifer) [reply seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/source/reader/TextReadStrategy.java:241]: add this logic, https://github.com/apache/seatunnel/pull/6589/files#diff-4c0c7afb3f42ad70464170efea9a9ff777151020ddcb837fc182207d1a79df9dR132 can be removed. Maybe it's a good option.

File: seatunnel-formats/seatunnel-format-text/src/main/java/org/apache/seatunnel/format/text/splitor/CsvLineSplitor.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+import java.util.ArrayList;
+import java.util.List;
+import java.util.Objects;
+
+public class CsvLineSplitor implements TextLineSplitor, Serializable {
+    private CSVFormat format;
+
+    @Override
+    public String[] spliteLine(String line, String splitor) {
+        if (Objects.isNull(format)) {
```
Comment (TyrantLucifer) [inline seatunnel-formats/seatunnel-format-text/src/main/java/org/apache/seatunnel/format/text/splitor/CsvLineSplitor.java]: If parsing nested types, the delimiter will change, and when entering the next layer of recursion, the delimiter will still be the previous layer's delimiter. So I think there should create a map to store the formats of delimiters. If format == null and create.

Comment (litiliu) [reply seatunnel-formats/seatunnel-format-text/src/main/java/org/apache/seatunnel/format/text/splitor/CsvLineSplitor.java]: I agree, but usually the CSV format doesn't support nested types I think.  Can we simply extract that field and let user to do the further data processing(like deserializing the JSON or XML) with Other queryEngine or DataEngine?

Comment (TyrantLucifer) [reply seatunnel-formats/seatunnel-format-text/src/main/java/org/apache/seatunnel/format/text/splitor/CsvLineSplitor.java]: In most production cases, if you want to use CSV to save nested types, you will follow the invisible character principle created by hive. The first layer of CSV is a comma, the second layer may be \u0002, and the third layer may be \u0003. In fact, when parsing each layer, only the delimiter needs to be specified because there will be no duplicate delimiters when parsing each layer.

File: seatunnel-formats/seatunnel-format-text/src/main/java/org/apache/seatunnel/format/text/splitor/CsvLineSplitor.java [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+import java.io.IOException;
+import java.io.Serializable;
+import java.util.ArrayList;
+import java.util.HashMap;
+import java.util.List;
+import java.util.Map;
+import java.util.Objects;
+
+public class CsvLineSplitor implements TextLineSplitor, Serializable {
+    private Map<Character, CSVFormat> splitorFormatMap = new HashMap<>(4);
```
Comment (TyrantLucifer) [inline seatunnel-formats/seatunnel-format-text/src/main/java/org/apache/seatunnel/format/text/splitor/CsvLineSplitor.java]: Why set the capacity to 4? There may be more than 4 layers of analysis.

Comment (litiliu) [reply seatunnel-formats/seatunnel-format-text/src/main/java/org/apache/seatunnel/format/text/splitor/CsvLineSplitor.java:33]: It's just the initalCapacity.  HashMap will auto scale, if there are more elements added to it.  Do you want me to change it to 16 or remove it?

Comment (litiliu) [reply seatunnel-formats/seatunnel-format-text/src/main/java/org/apache/seatunnel/format/text/splitor/CsvLineSplitor.java]: removed

File: seatunnel-formats/seatunnel-format-text/src/main/java/org/apache/seatunnel/format/text/splitor/CsvLineSplitor.java [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+            List<String> res = new ArrayList<>();
+            for (CSVRecord record : parser.getRecords()) {
+                for (String value : record) {
+                    res.add(value);
+                }
+            }
+            parser.close();
+            return res.toArray(new String[0]);
+        } catch (Exception e) {
+            e.printStackTrace();
```
Comment (EricJoy2048) [inline seatunnel-formats/seatunnel-format-text/src/main/java/org/apache/seatunnel/format/text/splitor/CsvLineSplitor.java]:
```suggestion
            log.error(ExceptionUtils.getMessage(e));
```

File: seatunnel-formats/seatunnel-format-text/src/main/java/org/apache/seatunnel/format/text/splitor/CsvLineSplitor.java [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+            return new String[0];
+        } finally {
+            if (Objects.nonNull(parser)) {
+                try {
+                    parser.close();
+                } catch (IOException e) {
+                    e.printStackTrace();
```
Comment (EricJoy2048) [inline seatunnel-formats/seatunnel-format-text/src/main/java/org/apache/seatunnel/format/text/splitor/CsvLineSplitor.java]: same as above.

File: seatunnel-formats/seatunnel-format-text/src/main/java/org/apache/seatunnel/format/text/splitor/CsvLineSplitor.java [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+            // Create CSV parser
+            parser = CSVParser.parse(line, format);
+            // Parse the CSV records
+            List<String> res = new ArrayList<>();
+            for (CSVRecord record : parser.getRecords()) {
+                for (String value : record) {
+                    res.add(value);
+                }
+            }
+            parser.close();
```
Comment (EricJoy2048) [inline seatunnel-formats/seatunnel-format-text/src/main/java/org/apache/seatunnel/format/text/splitor/CsvLineSplitor.java]: `parser.close()` called in `finally`, remove from here?

File: seatunnel-formats/seatunnel-format-text/src/test/java/org/apache/seatunnel/format/text/CsvTextFormatSchemaTest.java [hunk 7]
```diff
@@ -0,0 +1,241 @@
...
+
+import java.io.IOException;
+import java.math.BigDecimal;
+import java.time.LocalDate;
+import java.util.Arrays;
+import java.util.Map;
+
+public class CsvTextFormatSchemaTest {
+    public String content =
+            "tyrantlucifer\001"
```
Comment (EricJoy2048) [inline seatunnel-formats/seatunnel-format-text/src/test/java/org/apache/seatunnel/format/text/CsvTextFormatSchemaTest.java]: Add test case for `a,"b,c",d` and can read as `a`, `b,c`, `d` ?

Comment (litiliu) [reply seatunnel-formats/seatunnel-format-text/src/test/java/org/apache/seatunnel/format/text/CsvTextFormatSchemaTest.java:42]: yes, the function named `testDeserilizewithQuote` to test class is used for testing this case.

Comment (litiliu) [reply seatunnel-formats/seatunnel-format-text/src/test/java/org/apache/seatunnel/format/text/CsvTextFormatSchemaTest.java]: updated test case, please review again

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Review by hailin0 — APPROVED** [review]
