### PR TITLE
[Bug][Zeta] SeaTunnelClient can not exit with error

### LINKED ISSUE #9257: [Bug][Zeta] SeaTunnelClient can not exit with error
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When SeaTunnelClient initializes Hazelcast-related classes, a fatal exception, such as OOM. Hazelcast-related threads cannot be released normally, resulting in the client not being able to close normally. We need to add logic to call System.exit(1) when catch fatal exception like this.

Image

Image

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
./bin/seatunnel.sh -c config/v2.xxx.conf
```

### Error Exception

```log
-
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by CosmosNi**
SeaTunnelClient can not exit with error

close #9257

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-core/seatunnel-starter/src/main/java/org/apache/seatunnel/core/starter/seatunnel/command/ClientExecuteCommand.java [hunk 1]
```diff
@@ -281,10 +281,16 @@ private HazelcastInstance createServerInLocal(
...
 
-        return HazelcastInstanceFactory.newHazelcastInstance(
-                seaTunnelConfig.getHazelcastConfig(),
-                Thread.currentThread().getName(),
-                new SeaTunnelNodeContext(seaTunnelConfig));
+        try {
+            return HazelcastInstanceFactory.newHazelcastInstance(
+                    seaTunnelConfig.getHazelcastConfig(),
+                    Thread.currentThread().getName(),
+                    new SeaTunnelNodeContext(seaTunnelConfig));
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-starter/src/main/java/org/apache/seatunnel/core/starter/seatunnel/command/ClientExecuteCommand.java]: create hazelcast instance is one of potential crisis. So we should handle it in https://github.com/apache/seatunnel/blob/0b1122ceda60b4e94a9c2665e33f0d893644b22d/seatunnel-core/seatunnel-core-starter/src/main/java/org/apache/seatunnel/core/starter/SeaTunnel.java#L40 to catch all exist problem.

**Comment by Hisoka-X** [comment]
wating test case passes.

**Comment by Hisoka-X** [comment]
Hi @CosmosNi , please merge from dev to disable dead link check.

File: seatunnel-core/seatunnel-core-starter/src/main/java/org/apache/seatunnel/core/starter/SeaTunnel.java [hunk 2]
```diff
@@ -40,9 +40,11 @@ public static <T extends CommandArgs> void run(Command<T> command) throws Comman
             command.execute();
         } catch (ConfigRuntimeException e) {
             showConfigError(e);
+            System.exit(1);
             throw e;
-        } catch (Exception e) {
+        } catch (Exception | Error e) {
             showFatalError(e);
+            System.exit(1);
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-core-starter/src/main/java/org/apache/seatunnel/core/starter/SeaTunnel.java]: we should print the error statck before exit. Should we should update `showConfigError` and `showFatalError`

File: seatunnel-core/seatunnel-core-starter/src/main/java/org/apache/seatunnel/core/starter/SeaTunnel.java [hunk 3]
```diff
@@ -40,9 +40,11 @@ public static <T extends CommandArgs> void run(Command<T> command) throws Comman
             command.execute();
         } catch (ConfigRuntimeException e) {
             showConfigError(e);
+            System.exit(1);
             throw e;
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-core-starter/src/main/java/org/apache/seatunnel/core/starter/SeaTunnel.java]:
```suggestion
```

File: seatunnel-core/seatunnel-core-starter/src/main/java/org/apache/seatunnel/core/starter/SeaTunnel.java [hunk 4]
```diff
@@ -40,9 +40,11 @@ public static <T extends CommandArgs> void run(Command<T> command) throws Comman
...
-        } catch (Exception e) {
+        } catch (Exception | Error e) {
             showFatalError(e);
+            System.exit(1);
             throw e;
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-core-starter/src/main/java/org/apache/seatunnel/core/starter/SeaTunnel.java]:
```suggestion
```

File: seatunnel-core/seatunnel-flink-starter/seatunnel-flink-15-starter/src/test/java/org/apache/seatunnel/core/starter/flink/FlinkCommandArgsTest.java [hunk 5]
```diff
@@ -42,18 +42,31 @@ public void testExecuteClientCommandArgsWithPluginName()
...
+                                SeaTunnel.run(flinkCommandArgs.buildCommand());
+                            } catch (CommandExecuteException e) {
+                                // Verify the exception message
+                                Assertions.assertEquals(
+                                        String.format(
+                                                "No configuration setting found for key '%s'",
+                                                PLUGIN_NAME.key()),
+                                        e.getCause().getMessage());
+                                // Re-throw to ensure the test fails if System.exit is not called
+                                throw e;
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-flink-starter/seatunnel-flink-15-starter/src/test/java/org/apache/seatunnel/core/starter/flink/FlinkCommandArgsTest.java]: I believe the catch block will never reach. We can delete it.

File: seatunnel-core/seatunnel-starter/src/test/java/org/apache/seatunnel/core/starter/seatunnel/args/ClientCommandArgsTest.java [hunk 6]
```diff
@@ -51,20 +52,31 @@ public void testSetJobId() throws FileNotFoundException, URISyntaxException {
...
+
+        // Catch System.exit call and verify exit code
+        int statusCode =
+                catchSystemExit(
+                        () -> {
+                            try {
+                                SeaTunnel.run(clientCommandArgs.buildCommand());
+                            } catch (CommandExecuteException e) {
+                                // Verify the exception message
+                                Assertions.assertEquals(
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-starter/src/test/java/org/apache/seatunnel/core/starter/seatunnel/args/ClientCommandArgsTest.java]: ditto

File: seatunnel-core/seatunnel-spark-starter/seatunnel-spark-3-starter/src/test/java/org/apache/seatunnel/core/starter/spark/SparkCommandArgsTest.java [hunk 7]
```diff
@@ -43,19 +44,32 @@ public void testExecuteClientCommandArgsWithPluginName()
...
+
+        // Catch System.exit call and verify exit code
+        int statusCode =
+                catchSystemExit(
+                        () -> {
+                            try {
+                                SeaTunnel.run(sparkCommandArgs.buildCommand());
+                            } catch (CommandExecuteException e) {
+                                // Verify the exception message
+                                Assertions.assertEquals(
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-spark-starter/seatunnel-spark-3-starter/src/test/java/org/apache/seatunnel/core/starter/spark/SparkCommandArgsTest.java]: ditto

Comment (CosmosNi) [reply seatunnel-core/seatunnel-spark-starter/seatunnel-spark-3-starter/src/test/java/org/apache/seatunnel/core/starter/spark/SparkCommandArgsTest.java]: GET

**Review by Hisoka-X — DISMISSED** [review]
LGTM if ci passes. Thanks @CosmosNi

**Review by hailin0 — DISMISSED** [review]

**Comment by hailin0** [comment]
Please retry ci

**Review by hailin0 — DISMISSED** [review]

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-clickhouse-e2e/src/test/java/org/apache/seatunnel/connectors/seatunnel/clickhouse/ClickhouseIT.java [hunk 8]
```diff
@@ -147,11 +147,14 @@ public void clickhouseWithErrorWhenSchemaNotExist(TestContainer container) throw
...
-                        .contains(
-                                "ErrorCode:[API-11], ErrorDescription:[The sink table not exist]"));
+        // This assertion is commented out because SeaTunnel calls System.exit(1) when encountering
+        // errors
+        //        Assertions.assertTrue(
+        //                execResult
+        //                        .getStderr()
+        //                        .contains(
+        //                                "ErrorCode:[API-11], ErrorDescription:[The sink table not
+        // exist]"));
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-clickhouse-e2e/src/test/java/org/apache/seatunnel/connectors/seatunnel/clickhouse/ClickhouseIT.java]: In fact we still should get error msg from execResult. Please check where we can get the error msg now?

**Review by Hisoka-X — CHANGES_REQUESTED** [review]

File: seatunnel-core/seatunnel-starter/src/test/java/org/apache/seatunnel/core/starter/seatunnel/SeaTunnelClientOOMTest.java [hunk 9]
```diff
@@ -0,0 +1,118 @@
...
+
+import lombok.extern.slf4j.Slf4j;
+
+import static com.github.stefanbirkner.systemlambda.SystemLambda.catchSystemExit;
+
+@Slf4j
+public class SeaTunnelClientOOMTest {
+
+    @Test
+    public void testHazelcastOOMExitBehavior() throws Exception {
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-starter/src/test/java/org/apache/seatunnel/core/starter/seatunnel/SeaTunnelClientOOMTest.java:37]: I found two test case are same. Any code missed update or we can keep one?

**Review by Hisoka-X — APPROVED** [review]
LGTM if ci passes.

**Review by hailin0 — APPROVED** [review]
