### PR TITLE
[fix][REST API] does not apply ConfigShade decryption for HOCON/SQL format and upload-file submissions

### LINKED ISSUE #10590: [Bug] [REST API] does not apply ConfigShade decryption for HOCON/SQL format and upload-file submissions
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When submitting a job via REST API with `shade.identifier` configured in the `env` section, `ConfigShadeUtils.decryptConfig()` is **only invoked for JSON format** submissions. HOCON format, SQL format, and the upload-file endpoint (`/submit-job/upload`) all skip the decryption step, causing `shade.identifier` and `shade.options` to be silently ignored.
**Root Cause:**
In `JobInfoService.submitJob(Map, byte[])`, the HOCON and SQL branches directly call `ConfigFactory.parseString()` / `SqlConfigBuilder.of()` without calling `ConfigShadeUtils.decryptConfig()`:

```java
switch (configFormat) {
    case HOCON:
        config = ConfigFactory.parseString(new String(requestBody, StandardCharsets.UTF_8));
        // ❌ Missing: ConfigShadeUtils.decryptConfig(config)
        break;
    case SQL:
        config = SqlConfigBuilder.of(new String(requestBody, StandardCharsets.UTF_8));
        // ❌ Missing: ConfigShadeUtils.decryptConfig(config)
        break;
    case JSON:
    default:
        config = RestUtil.buildConfig(requestHandle(requestBody), false);
        // ✅ Decrypt happens inside ConfigBuilder.of(objectMap, false)
        break;
}
```

The JSON branch works because `RestUtil.buildConfig()` → `ConfigBuilder.of(Map, boolean)` internally calls `ConfigShadeUtils.decryptConfig()`.
Similarly, `SubmitJobByUploadFileServlet` never calls decrypt for **any** format, and it uses the `submitJob(Map, Config)` overload which also has no decrypt logic.
**Summary of affected endpoints:**
| Endpoint | Format | Decryption Applied? |
|----------|--------|:---:|
| `POST /submit-job` | JSON (default) | ✅ Yes |
| `POST /submit-job?config_format=hocon` | HOCON | ❌ No |
| `POST /submit-job?config_format=sql` | SQL | ❌ No |
| `POST /submit-job/upload` | ALL formats | ❌ No |
| `POST /submit-jobs` | JSON | ✅ Yes |
| CLI `seatunnel.sh` | ALL formats | ✅ Yes |

### SeaTunnel Version

2.3.12
2.3.13

### SeaTunnel Config

```conf
env {
  job.mode = "BATCH"
  shade.identifier = "base64"
}

source {
  FakeSource {
    row.num = 10
    username = "c2VhdHVubmVs"
    password = "c2VhdHVubmVsX3Bhc3N3b3Jk"
    schema {
      fields {
        name = "string"
      }
    }
  }
}

transform {
}

sink {
  Console {}
}
```

### Running Command

```shell
# Submit with HOCON format — shade decryption is NOT applied (bug)
curl -X POST 'http://localhost:5801/hazelcast/rest/maps/submit-job?config_format=hocon' \
  -H 'Content-Type: text/plain' \
  -d 'env {
  job.mode = "BATCH"
  shade.identifier = "base64"
}
source {
  FakeSource {
    row.num = 10
    username = "c2VhdHVubmVs"
    password = "c2VhdHVubmVsX3Bhc3N3b3Jk"
    schema { fields { name = "string" } }
  }
}
transform {}
sink { Console {} }'

# Submit with JSON format — shade decryption IS applied (works correctly)
curl -X POST 'http://localhost:5801/hazelcast/rest/maps/submit-job' \
  -H 'Content-Type: application/json' \
  -d '{
  "env": {"job.mode":"BATCH","shade.identifier":"base64"},
  "source": [{"plugin_name":"FakeSource","row.num":10,"username":"c2VhdHVubmVs","password":"c2VhdHVubmVsX3Bhc3N3b3Jk","schema":{"fields":{"name":"string"}}}],
  "transform": [],
  "sink": [{"plugin_name":"Console"}]
}'
```

### Error Exception

```log
No exception is thrown. The encrypted values (e.g. `c2VhdHVubmVs`) are passed through to the connector without being decrypted, causing authentication failures or incorrect data at the connector level.
With HOCON format, the `shade.identifier = "base64"` in the env section is completely ignored — `ConfigShadeUtils.decryptConfig()` is never called.
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nzw921rx**
## Purpose of this pull request

Fix [#10590](https://github.com/apache/seatunnel/issues/10590).

When submitting a job via REST API with `shade.identifier` configured in the env section, `ConfigShadeUtils.decryptConfig()` is only invoked for JSON format submissions. HOCON format, SQL format, and the upload-file endpoint (`/submit-job/upload`) all skip the decryption step, causing `shade.identifier` and encrypted values to be silently ignored.

**Root cause:**
- In `JobInfoService.submitJob(Map, byte[])`, the HOCON and SQL branches call `ConfigFactory.parseString()` / `SqlConfigBuilder.of()` without calling `ConfigShadeUtils.decryptConfig()`. The JSON branch works because `RestUtil.buildConfig()` → `ConfigBuilder.of(Map, boolean)` internally calls it.
- In `SubmitJobByUploadFileServlet.doPost()`, no format calls `decryptConfig()` before passing the config to `jobInfoService.submitJob(Map, Config)`.

**Fix:**
- Added `ConfigShadeUtils.decryptConfig(config)` after config parsing in HOCON and SQL branches of `JobInfoService.submitJob()`.
- Added `ConfigShadeUtils.decryptConfig(config)` after the format switch in `SubmitJobByUploadFileServlet.doPost()`.

| Endpoint | Format | Before | After |
|---|---|---|---|
| `POST /submit-job` | JSON (default) | ✅ | ✅ |
| `POST /submit-job?format=hocon` | HOCON | ❌ | ✅ |
| `POST /submit-job?format=sql` | SQL | ❌ | ✅ |
| `POST /submit-job/upload` | ALL | ❌ | ✅ |

## Does this PR introduce _any_ user-facing change?

No new user-facing change. This PR fixes existing behavior so that `shade.identifier` (e.g. `base64`) correctly decrypts sensitive config values (like `password`, `username`) for HOCON, SQL, and upload-file submissions — matching the behavior that JSON format already had.

## How was this patch tested?

Added integration test `RestApiSubmitJobConfigShadeDecryptTest` that starts a real Hazelcast + Jetty REST server and verifies the following scenarios end-to-end:

1. `testSubmitJobWithHoconFormatDecryptsConfig` — POST `/submit-job?format=hocon` with base64-encrypted `username`/`password` and `shade.identifier = "base64"`, asserts HTTP 200 with `jobId`.
2. `testSubmitJobWithSqlFormatDecryptsConfig` — POST `/submit-job?format=sql` with the same encrypted values, asserts HTTP 200 with `jobId`.
3. `testSubmitJobByUploadHoconFileDecryptsConfig` — POST multipart `/submit-job/upload` with `.conf` file, asserts HTTP 200 with `jobId`.

## Check list

* [x] No new Jar binary package added.
* [x] No documentation update needed (bug fix for existing behavior).
* [x] No incompatible change.
* [x] Not a connector code contribution.

### CODE REVIEW

**Comment by DanielCarter-stack** [comment]
### Issue 2: Insufficient Test Coverage

**Location**: `RestApiSubmitJobConfigShadeDecryptTest.java`

**Modified Code**:
Added 364 lines of integration tests

**Related Context**:
- Parent class: None
- Child class/Implementation class: None
- Caller: JUnit 5 test framework

**Problem Description**:

Although integration tests were added, the following test coverage gaps exist:

1. **Insufficient Boundary Condition Testing**:
   - No testing for missing or empty `shade.identifier`
   - No testing for decryption failures (e.g., invalid base64 strings)
   - No testing for configurations missing required fields (e.g., empty source or sink)

2. **Insufficient File Upload Testing**:
   - Only tested HOCON file upload (`.conf`)
   - No testing for SQL file upload (`.sql`)
   - No testing for JSON file upload (`.json`)

3. **Missing Error Scenario Testing**:
   - No testing for configuration format errors (e.g., HOCON syntax errors)
   - No testing for HTTP response codes and error messages when decryption throws exceptions

4. **Missing Concurrency and Performance Testing**:
   - No testing for concurrent submission scenarios
   - No testing for performance with large configuration files

**Potential Risks**:
- **Medium Risk**: Boundary conditions and error scenarios could lead to runtime exceptions, returning 500 errors instead of user-friendly 400 errors
- **Low Risk**: Untested scenarios may have issues in actual use

**Impact Scope**:
- **Direct Impact**: REST API error handling and user experience
- **Indirect Impact**: Production environment stability
- **Affected Area**: REST API module

**Severity**: MINOR

**Improvement Suggestions**:

It is recommended to add the following test cases (can be done in a follow-up PR):

```java
@Test
public void testSubmitJobWithHoconFormatInvalidBase64() throws Exception {
    String invalidBase64Body = buildHoconBody()
            .replace("c2VhdHVubmVs", "invalid_base64!");
    
    String requestUrl = "http://localhost:" + restPort + "/submit-job?format=hocon";
    
    HttpResponse response = post(requestUrl, "text/plain", invalidBase64Body);
    // Should return 400 Bad Request or 500 Internal Server Error
    Assertions.assertTrue(response.code == 400 || response.code == 500);
    Assertions.assertTrue(response.body.contains("error") || response.body.contains("Illegal"));
}

@Test
public void testSubmitJobByUploadSqlFileDecryptsConfig() throws Exception {
    String requestUrl = "http://localhost:" + restPort + "/submit-job/upload";
    
    HttpResponse response = postMultipart(requestUrl, "job.sql", buildSqlBody());
    Assertions.assertEquals(200, response.code);
    Assertions.assertTrue(response.body.contains("jobId"));
}

@Test
public void testSubmitJobWithHoconFormatMissingShadeIdentifier() throws Exception {
    String bodyWithoutShade = "env {\n"
            + "  job.mode = \"BATCH\"\n"
            + "}\n"
            + "source {\n"
            + "  FakeSource {\n"
            + "    row.num = 5\n"
            + "    username = \"plain_text_username\"\n"
            + "    password = \"plain_text_password\"\n"
            + "  }\n"
            + "}\n"
            + "sink { Console {} }";
    
    String requestUrl = "http://localhost:" + restPort + "/submit-job?format=hocon";
    
    HttpResponse response = post(requestUrl, "text/plain", bodyWithoutShade);
    // Should handle normally (without decryption)
    Assertions.assertEquals(200, response.code);
}
```

**Rationale**:
- Although this is not a blocking issue, more comprehensive testing can improve code quality and confidence
- Especially testing of error scenarios can ensure users receive friendly error messages
- This is a best practice and recommended to be supplemented in a follow-up PR

---

### Issue 3: Potential Log Security Issue (Non-blocking)

**Location**: `ConfigShadeUtils.java:173`

**Related Context**:
- In `ConfigShadeUtils.processConfig()` method
- Line 173: `String jsonString = config.root().render(ConfigRenderOptions.concise());`

**Problem Description**:

Inside the `processConfig()` method, the configuration is rendered as a JSON string (including **decrypted passwords**). If an exception occurs at this stage (e.g., `Preconditions.checkArgument` on lines 183-186 throws an exception), the unmasked configuration may be logged in logs or exception stacks.

Checking `ConfigBuilder` line 118, it uses `configDesensitization()` for masking, but this is called only after `decryptConfig()` completes successfully.

**Potential Risks**:
- **Low Risk**: Exposed only when an exception is thrown
- Production environment log levels are typically set to INFO or WARN, making it unlikely to log detailed exception stacks
- This is not an issue introduced by this PR, but a potential risk in the original code

**Impact Scope**:
- **Direct Impact**: Logging system
- **Indirect Impact**: Security (log leakage of sensitive information)
- **Affected Area**: All places using `ConfigShadeUtils.decryptConfig()`

**Severity**: MINOR

**Improvement Suggestions**:

It is recommended to add exception handling in `ConfigShadeUtils.processConfig()` to ensure sensitive information is not logged when exceptions occur:

```java
private static Config processConfig(
        String identifier, Config config, boolean isDecrypted, Map<String, Object> props) {
    try {
        ConfigShade configShade = CONFIG_SHADES.getOrDefault(identifier, DEFAULT_SHADE);
        configShade.open(props);

        Set<String> sensitiveOptions = new HashSet<>(getSensitiveOptions(config));
        sensitiveOptions.addAll(Arrays.asList(configShade.sensitiveOptions()));
        
        // ... existing processing logic ...
        
        return ConfigFactory.parseMap(configMap);
    } catch (Exception e) {
        // Log desensitized error information
        log.error("Failed to {} config with identifier: {}", 
                  isDecrypted ? "decrypt" : "encrypt", 
                  identifier, 
                  e);
        // Rethrow exception without sensitive information
        throw new IllegalArgumentException(
            String.format("Failed to %s config. Please check your configuration.", 
                         isDecrypted ? "decrypt" : "encrypt"), 
            e);
    }
}
```

**Rationale**:
- This is a security enhancement suggestion, not a blocking issue
- Can be handled separately as a security improvement in a follow-up PR
- Not related to the fix target of this PR (this PR ensures decryption is called, rather than improving the decryption logic itself)

---

### Issue 4: Missing Explicit Decryption Call for JSON Path (Inconsistency)

**Location**: `JobInfoService.java:190-193`

**Modified Code**:
```java
case JSON:
default:
    config = RestUtil.buildConfig(requestHandle(requestBody), false);
    break;
```

**Related Context**:
- Line 192 calls `RestUtil.buildConfig(JsonNode, false)`
- `RestUtil.buildConfig()` internally calls `ConfigBuilder.of(Map, boolean)`
- `ConfigBuilder.of()` line 115 decides whether to decrypt based on the second parameter

**Problem Description**:

The JSON path does not explicitly call `ConfigShadeUtils.decryptConfig()`, but instead relies on the decryption logic inside `RestUtil.buildConfig()` → `ConfigBuilder.of()`.

This inconsistency may lead to:
1. Code review requiring tracing multiple layers of calls to confirm that the JSON path is also decrypted
2. If the implementation of `ConfigBuilder.of()` changes (e.g., the meaning of the `isEncrypt` parameter changes), it may lead to bugs

**Potential Risks**:
- **Low Risk**: Current implementation is correct, but not obvious enough
- If someone modifies the implementation of `ConfigBuilder.of()` in the future, it may introduce bugs

**Impact Scope**:
- **Direct Impact**: Code maintainability
- **Indirect Impact**: Possible future bugs
- **Affected Area**: REST API submissions in JSON format

**Severity**: MINOR

**Improvement Suggestions**:

It is recommended to unify the decryption call method for all paths, explicitly calling `ConfigShadeUtils.decryptConfig()`:

```java
// fix issue: https://github.com/apache/seatunnel/issues/10590
switch (configFormat) {
    case HOCON:
        config = ConfigFactory.parseString(new String(requestBody, StandardCharsets.UTF_8));
        break;
    case SQL:
        config = SqlConfigBuilder.of(new String(requestBody, StandardCharsets.UTF_8));
        break;
    case JSON:
    default:
        config = RestUtil.buildConfig(requestHandle(requestBody), false);
        break;
}
// Unified decryption after switch
config = ConfigShadeUtils.decryptConfig(config);
```

**But note**: `RestUtil.buildConfig(requestHandle(requestBody), false)` already calls `ConfigBuilder.of(Map, false)` → `decryptConfig()`, so this modification would result in **duplicate decryption**.

A better approach is to modify `RestUtil.buildConfig()` and `ConfigBuilder.of()`:

1. **Option A** (Recommended): Modify the semantics of `RestUtil.buildConfig(JsonNode, boolean isEncrypt)` to no longer decrypt, and decrypt uniformly in `JobInfoService`:
```java
// RestUtil.java
public static Config buildConfig(JsonNode jsonNode) {
    // Remove isEncrypt parameter, no longer decrypt
    Map<String, Object> objectMap = JsonUtils.toMap(jsonNode);
    return ConfigFactory.parseMap(objectMap)
            .resolve(ConfigResolveOptions.defaults().setAllowUnresolved(true))
            .resolveWith(ConfigFactory.systemProperties(), 
                        ConfigResolveOptions.defaults().setAllowUnresolved(true));
}

// JobInfoService.java
switch (configFormat) {
    case JSON:
    default:
        config = RestUtil.buildConfig(requestHandle(requestBody));
        break;
}
// Unified decryption
config = ConfigShadeUtils.decryptConfig(config);
```

2. **Option B**: Keep the current implementation, but add comments explaining that the JSON path is decrypted internally through `RestUtil.buildConfig()`.

**Rationale**:
- This is a code consistency and maintainability issue
- Although the current implementation is functionally correct, it is not obvious enough
- Recommended as a follow-up improvement for code refactoring, not a blocking issue for this PR

---

**Comment by nzw921rx** [comment]
Thank you for your detailed review and valuable suggestions. I have carefully reviewed all the issues raised, including **insufficient test coverage**, **potential log security risks**, and **inconsistent decryption calls for the JSON path**, and I fully agree with the improvement recommendations.

I will address all the above issues in subsequent pull requests, including but not limited to:
1. Supplement comprehensive test cases covering boundary conditions, multi-format file uploads, error scenarios, and concurrency/performance testing.
2. Add exception handling in `ConfigShadeUtils.processConfig()` to prevent sensitive information from being logged in exception stacks or logs.
3. Unify decryption call approaches to improve code consistency and maintainability.

I will submit the follow-up PRs in a timely manner. Please let me know if you have any additional guidance or requirements.

**Comment by nzw921rx** [comment]
# Pull Request: Unify decryption logic and enhance test coverage
## What changes were proposed in this pull request?
1. **Unify decryption logic for all config formats** (fix Issue 4)
   - Add explicit comment for JSON path decryption logic in `JobInfoService.java` (lines 190-193) to clarify that decryption is handled in `RestUtil.buildConfig()`
   - Keep functional correctness while improving code maintainability (avoid duplicate decryption)
   
2. **Enhance test coverage** (fix Issue 2)
   - Add boundary condition tests: missing/empty `shade.identifier`, invalid base64 strings, missing required fields
   - Add file upload tests for SQL (.sql) and JSON (.json) formats (only HOCON was tested before)
   - Add error scenario tests: HOCON syntax errors, HTTP response code verification for decryption exceptions
   - Note: Concurrency/performance tests are marked as follow-up due to low priority

3. **Security hardening for config logs** (optimize Issue 3)
   - Add exception handling in `ConfigShadeUtils.processConfig()` to avoid sensitive info (e.g., decrypted passwords) leakage in logs
   - Log desensitized error messages and rethrow exceptions with generic hints (no sensitive details)

4. **Keep backward compatibility**
   - No breaking changes to existing decryption logic
   - All fixes are MINOR severity and non-blocking for core functionality

**Comment by dybyte** [comment]
Please enable CI following the [instructions](https://github.com/apache/seatunnel/pull/10595/checks?check_run_id=66909791402).

**Comment by nzw921rx** [comment]
Done, I've enabled GitHub Actions on my fork. Could you please approve the CI workflow run? Thanks!

**Comment by nzw921rx** [comment]
Hi @dybyte @liunaijie,

CI has been triggered and I've already re-run the failed jobs multiple times (5 attempts so far). Some previously failing jobs have passed after re-runs, but the following 3 jobs consistently fail across all attempts and appear to be unrelated to the changes in this PR:

1. **`all-connectors-it-6 (11, ubuntu-latest)`** — `Process completed with exit code 1` in "run connector-v2 integration test (part-6)". This PR only modifies files in `seatunnel-engine-server` (REST API layer), and the failing job runs connector-v2 e2e integration tests with `-DskipUT=true`, which does not execute any of the tests added/modified in this PR.

2. **`all-connectors-it-6 (8, ubuntu-latest)`** — Automatically canceled due to the default `fail-fast: true` matrix strategy after the Java 11 variant above failed.

3. **`Build website`** — `The job has exceeded the maximum execution time of 1h0m0s` during "Run docusaurus build". This is a website build timeout, completely unrelated to the code changes.

These failures seem to be pre-existing flaky tests / infrastructure issues on the `dev` branch. Could you please help review and advise? Thank you!

**Review by davidzollo — DISMISSED** [review]
+1 if CI passes.
LGTM

**Comment by dybyte** [comment]
> Hi @dybyte @liunaijie,
> 
> CI has been triggered and I've already re-run the failed jobs multiple times (5 attempts so far). Some previously failing jobs have passed after re-runs, but the following 3 jobs consistently fail across all attempts and appear to be unrelated to the changes in this PR:
> 
> 1. **`all-connectors-it-6 (11, ubuntu-latest)`** — `Process completed with exit code 1` in "run connector-v2 integration test (part-6)". This PR only modifies files in `seatunnel-engine-server` (REST API layer), and the failing job runs connector-v2 e2e integration tests with `-DskipUT=true`, which does not execute any of the tests added/modified in this PR.
> 2. **`all-connectors-it-6 (8, ubuntu-latest)`** — Automatically canceled due to the default `fail-fast: true` matrix strategy after the Java 11 variant above failed.
> 3. **`Build website`** — `The job has exceeded the maximum execution time of 1h0m0s` during "Run docusaurus build". This is a website build timeout, completely unrelated to the code changes.
> 
> These failures seem to be pre-existing flaky tests / infrastructure issues on the `dev` branch. Could you please help review and advise? Thank you!

Could you try re-running the CI with a clean [cache](https://github.com/nzw921rx/seatunnel/actions/caches)?

**Comment by nzw921rx** [comment]
OK thanks

**Comment by nzw921rx** [comment]
HI @dybyte 
Clearing cache still partially failed. Check the latest PR to see if it is caused by website timeout. Do I need to wait for the PR merge to complete before running the rebase dev branch again?

**Comment by dybyte** [comment]
> HI @dybyte Clearing cache still partially failed. Check the latest PR to see if it is caused by website timeout. Do I need to wait for the PR merge to complete before running the rebase dev branch again?

Yes, please wait for the PR to be merged first and then try rebasing again.

File: seatunnel-core/seatunnel-core-starter/src/main/java/org/apache/seatunnel/core/starter/utils/ConfigBuilder.java [hunk 1]
```diff
@@ -100,20 +100,13 @@ public static Config of(@NonNull Path filePath, List<String> variables) {
     }
 
     public static Config of(@NonNull Map<String, Object> objectMap) {
-        return of(objectMap, false);
-    }
-
-    public static Config of(@NonNull Map<String, Object> objectMap, boolean isEncrypt) {
```
Comment (chl-wxp) [inline seatunnel-core/seatunnel-core-starter/src/main/java/org/apache/seatunnel/core/starter/utils/ConfigBuilder.java:106]: I noticed that the variable `isEncrypt` was removed. Will the decryption logic be executed even when `shade.identifier` is not configured?

Comment (nzw921rx) [reply seatunnel-core/seatunnel-core-starter/src/main/java/org/apache/seatunnel/core/starter/utils/ConfigBuilder.java:106]: Removed the use of 'isEncrypt' to determine whether to decrypt, and called it uniformly through the outer layer. Only the conversion is performed here, and the deleted code is as follows:

```
if (!isEncrypt) {
     config = ConfigShadeUtils.decryptConfig(config);
}
```

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/servlet/SubmitJobByUploadFileServlet.java [hunk 2]
```diff
@@ -74,6 +75,8 @@ public void doPost(HttpServletRequest req, HttpServletResponse resp)
                 config = ConfigFactory.parseString(content);
                 break;
         }
+        // fix issue: https://github.com/apache/seatunnel/issues/10590
```
Comment (chl-wxp) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/servlet/SubmitJobByUploadFileServlet.java]: delete

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/service/JobInfoService.java [hunk 3]
```diff
@@ -180,10 +182,15 @@ public JsonObject submitJob(Map<String, String> requestParams, byte[] requestBod
                 break;
             case JSON:
             default:
-                config = RestUtil.buildConfig(requestHandle(requestBody), false);
+                config = RestUtil.buildConfig(requestHandle(requestBody));
                 break;
         }
+
+        // fix issue: https://github.com/apache/seatunnel/issues/10590
```
Comment (chl-wxp) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/service/JobInfoService.java]: delete

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/servlet/SubmitJobByUploadFileServlet.java (hunk 2 above)
Comment (nzw921rx) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/servlet/SubmitJobByUploadFileServlet.java]: completed

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/service/JobInfoService.java (hunk 3 above)
Comment (nzw921rx) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/service/JobInfoService.java]: completed

**Comment by nzw921rx** [comment]
@dybyte  please  helep me Review and Megre? tanks

**Review by chl-wxp — APPROVED** [review]

**Review by DanielLeens — APPROVED** [review]
I pulled the current HEAD locally and rechecked the REST submit path end to end instead of only reading the diff.

Current runtime chain:
`/submit-job`
-> `JobInfoService.submitJob()` parses HOCON / SQL / JSON (`JobInfoService.java:176-187`)
-> `ConfigShadeUtils.decryptConfig(config)` (`JobInfoService.java:189`)
-> `submitJobInternal(...)`

`/submit-jobs`
-> `RestUtil.buildConfigList(...)`
-> `JobInfoService.submitJobs()`
-> decrypt each tuple before `submitJobInternal(...)` (`JobInfoService.java:205-223`)

`/submit-job/upload`
-> `SubmitJobByUploadFileServlet#doPost()` parses by file format (`SubmitJobByUploadFileServlet.java:61-77`)
-> `ConfigShadeUtils.decryptConfig(config)` (`SubmitJobByUploadFileServlet.java:79`)
-> submit.

The current branch removes the old implicit object-map decryption from `ConfigBuilder.of(Map)` and centralizes decryption explicitly on the REST submit endpoints, which closes the HOCON / SQL / upload gap without breaking the JSON path. The new `RestApiSubmitJobConfigShadeDecryptTest` coverage also exercises these submit flows directly.

Conclusion: mergeable from a code-review perspective.
Blocking items: none from my side.
Suggested follow-up: none required for this PR. The current `Build` check is already green.

**Review by davidzollo — APPROVED** [review]
+1
Good job

**Review by dybyte — APPROVED** [review]
+1
