### PR TITLE
[Fix][Connector-V2] Fix postgres cdc with debezium_json format can not parse number without scale

### LINKED ISSUE #9037: postgrescdc compatible_debezium_json当数据库字段类型有NUMERIC(24)这种报错
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

postgrescdc compatible_debezium_json当数据库字段类型有NUMERIC(24)这种报java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.String

### SeaTunnel Version

2.3.9

### SeaTunnel Config

```conf
{
    "env": {
        "job.mode": "STREAMING",
        "execution.parallelism": 1,
        "checkpoint.interval": 5000,
        "read_limit.bytes_per_second": 7000000,
        "read_limit.rows_per_second": 400
    },
    "source": [
        {
            "plugin_name": "Postgres-CDC",
            "plugin_output": "customers_Postgre_cdc",
            "username": "",
            "password": "",
            "database-names": [
                "postgres"
            ],
            "schema-names": [
                "public"
            ],
            "table-names": [
                "postgres.public.test"
            ],
            "base-url": "",
            "format":"compatible_debezium_json",
            "debezium":{
                "key.converter.schemas.enable":false,
                "value.converter.schemas.enable":false
            }
        }
    ],
    "transform": [],
    "sink": [
        {
            "plugin_name": "Console",
            "plugin_output": "customers_Postgre_cdc",
            "format":"compatible_debezium_json"
        }
    ]
}
```

### Running Command

```shell
rest api submit-job
```

### Error Exception

```log
java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.String
```

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

1.8

### Screenshots

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by FrommyMind**
### Purpose of this pull request

Fix #9037

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Updated E2E test cases.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-api/src/main/java/org/apache/seatunnel/api/table/type/SeaTunnelRow.java [hunk 1]
```diff
@@ -132,6 +133,9 @@ private int getBytesForValue(Object v, SeaTunnelDataType<?> dataType) {
         SqlType sqlType = dataType.getSqlType();
         switch (sqlType) {
             case STRING:
+                if (v instanceof BigDecimal) {
+                    return v.toString().length();
+                }
```
Comment (Hisoka-X) [inline seatunnel-api/src/main/java/org/apache/seatunnel/api/table/type/SeaTunnelRow.java]: If it is declared as string, but the returned type is BigDecimal, this is wrong. We need to solve this wrong behavior instead of condoning it.

**Review by Hisoka-X — COMMENTED** [review]
Could you add a test case with `compatible_debezium_json` format in https://github.com/apache/seatunnel/blob/44e54c7d8d19ce6fbd49d506702a6047f046e962/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-postgres-e2e/src/test/java/org/apache/seatunnel/connectors/seatunnel/cdc/postgres/PostgresCDCIT.java#L81

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-postgres-e2e/src/test/java/org/apache/seatunnel/connectors/seatunnel/cdc/postgres/PostgresCDCIT.java [hunk 2]
```diff
@@ -603,6 +603,53 @@ public void testPostgresCdcCheckDataWithCustomPrimaryKey(TestContainer container
         }
     }
 
+    public void testPostgresCdcWithDebeziumJsonFormat(TestContainer container) throws Exception {
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-postgres-e2e/src/test/java/org/apache/seatunnel/connectors/seatunnel/cdc/postgres/PostgresCDCIT.java]:
```suggestion
    @Test
    public void testPostgresCdcWithDebeziumJsonFormat(TestContainer container) throws Exception {
```

File: seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/IncrementalSourceRecordEmitter.java [hunk 3]
```diff
@@ -98,9 +98,11 @@ public void emitRecord(
...
         while (elementIterator.hasNext()) {
             SourceRecord next = elementIterator.next();
-            reportMetrics(next);
-            processElement(next, collector, splitState);
-            markEnterPureIncrementPhase(next, splitState);
+            if (next.value() != null) {
+                reportMetrics(next);
+                processElement(next, collector, splitState);
+                markEnterPureIncrementPhase(next, splitState);
+            }
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/IncrementalSourceRecordEmitter.java]: Does this change necessary? cc @hailin0

**Review by Hisoka-X — COMMENTED** [review]
Thanks @FrommyMind for update and added test case!

File: seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/IncrementalSourceRecordEmitter.java (hunk 3 above)
Comment (FrommyMind) [reply seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/IncrementalSourceRecordEmitter.java]: I found that, the `next` is not null ,but `next.value()` maybe null when write data to kafka, so I change this.

Comment (Hisoka-X) [reply seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/IncrementalSourceRecordEmitter.java]: Please revert it and create another PR to do this.

Comment (FrommyMind) [reply seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/IncrementalSourceRecordEmitter.java]: Ok

**Review by hailin0 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]
