### PR TITLE
[Fix][JDBC] Fix starrocks jdbc dialect catalog conflict with starrocks connector

### LINKED ISSUE #7551: [Bug] [StarRocks] StarRocks JDBC Dialect confilect with StarRocks Connector
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

this pr https://github.com/apache/seatunnel/pull/7294 added StarRocks JDBC dialect. 

It will has some issue when both JDBC connector and StarRocks connector exist.

image

jdbc catalog will use `dialect.dialectName()` as factoryIdentifier to load Catalog. `StarRocks` catalog in created in `StarRocks` connector, so if `StarRocks` connector exist, it will read an error Catalog get `ClassCastException` exception

If not exist, it will use loading tables from jdbc directly, the e2e test case is work because of this.
image

```
Caused by: java.lang.ClassCastException: org.apache.seatunnel.connectors.seatunnel.starrocks.catalog.StarRocksCatalog cannot be cast to org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog

	at org.apache.seatunnel.connectors.seatunnel.jdbc.utils.JdbcCatalogUtils.getTables(JdbcCatalogUtils.java:75) ~[?:?]

```

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
jdbc {
compatible_mode = "starrocks"
}
```

### Running Command

```shell
rest api to submit job
```

### Error Exception

```log
Caused by: java.lang.ClassCastException: org.apache.seatunnel.connectors.seatunnel.starrocks.catalog.StarRocksCatalog cannot be cast to org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog

	at org.apache.seatunnel.connectors.seatunnel.jdbc.utils.JdbcCatalogUtils.getTables(JdbcCatalogUtils.java:75) ~[?:?]

```
```


### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liunaijie**
### Purpose of this pull request

close https://github.com/apache/seatunnel/issues/7551

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — COMMENTED** [review]
Could you add a test case for this?

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcStarRocksdbIT.java [hunk 1]
```diff
@@ -111,7 +115,19 @@ JdbcCase getJdbcCase() {
     }
 
     @Override
-    void compareResult(String executeKey) {}
+    @DisabledOnContainer(
+            value = {},
+            type = {EngineType.FLINK, EngineType.SPARK},
+            disabledReason = "only Zeta Engine can get this log")
+    void checkResult(String executeKey, TestContainer container, Container.ExecResult execResult) {
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcStarRocksdbIT.java:118]: please revert

Comment (liunaijie) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcStarRocksdbIT.java:118]: Done.

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-common/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/AbstractJdbcIT.java [hunk 2]
```diff
@@ -112,7 +112,7 @@ public abstract class AbstractJdbcIT extends TestSuiteBase implements TestResour
 
     abstract JdbcCase getJdbcCase();
 
-    abstract void compareResult(String executeKey) throws SQLException, IOException;
+    void checkResult(String executeKey, TestContainer container, Container.ExecResult execResult) {}
```
Comment (liunaijie) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-common/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/AbstractJdbcIT.java:115]: add more parameter to help check log. 
and delete the abstract keyword, the implement class only need implement it when necessary.

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcStarRocksdbIT.java [hunk 3]
```diff
@@ -111,7 +115,12 @@ JdbcCase getJdbcCase() {
     }
 
     @Override
-    void compareResult(String executeKey) {}
+    void checkResult(String executeKey, TestContainer container, Container.ExecResult execResult) {
+        if (container.identifier().equals(TestContainerId.SEATUNNEL)) {
+            Assertions.assertTrue(
+                    execResult.getStdout().contains("Loading catalog tables for catalog"));
+        }
```
Comment (liunaijie) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcStarRocksdbIT.java:122]: i run some test, find the stdout and container log is different on different engine and version.
so here only check seatunnel engine's log.

Comment (liunaijie) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcStarRocksdbIT.java:122]: when has this log `Loading catalog tables for catalog` means it was load table from MySQLCatalog. rather than 
use jdbc. 

related log location: 
https://github.com/apache/seatunnel/blob/dev/seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/utils/JdbcCatalogUtils.java#L77


https://github.com/apache/seatunnel/blob/dev/seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/utils/JdbcCatalogUtils.java#L127

**Review by Hisoka-X — APPROVED** [review]
LGTM.

**Review by hailin0 — APPROVED** [review]
