### PR TITLE
[Fix][Connector-V2][OceanBase] oceanbase vector support simple vector index

### LINKED ISSUE #9056: [Fix][Connector-V2][OceanBase] oceanbase vector support  simple vector index
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

ConstraintType class add VECTOR_INDEX_KEY enum，The error is reported in the buildConstrainKeySql method of OceanBaseMysqlCreateTableSqlBuilder. Currently, the vector index supported by oceanbase is very limited. It is not a good solution to not add an index under a large amount of data. Here is an appendix to a default index implementation.

### SeaTunnel Version

all version

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "BATCH"
  checkpoint.interval = 5000
}

source {
  Milvus {
    url = "http://ip:port"
    token = "root:Milvus"
    database = "default"
    collection="test"
  }
}

transform {
}
sink {
    jdbc {
        url = "jdbc:oceanbase://ip:port/db"
        driver = "com.oceanbase.jdbc.Driver"
        user = "user"
        password = "password"
        compatible_mode = "mysql"
        generate_sink_sql = true
        database = db
        table = test
    }
}
```

### Running Command

```shell
bin/seatunnel.sh --config conf/jdbc_milvus_to_oceanbase.conf -e local
```

### Error Exception

```log
Caused by: java.lang.UnsupportedOperationException: Unsupported constraint type: VECTOR_INDEX_KEY
	at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.oceanbase.OceanBaseMysqlCreateTableSqlBuilder.buildConstraintKeySql(OceanBaseMysqlCreateTableSqlBuilder.java:269)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.oceanbase.OceanBaseMysqlCreateTableSqlBuilder.buildColumnsIdentifySql(OceanBaseMysqlCreateTableSqlBuilder.java:173)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.oceanbase.OceanBaseMysqlCreateTableSqlBuilder.build(OceanBaseMysqlCreateTableSqlBuilder.java:143)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.oceanbase.OceanBaseMySqlCatalog.getCreateTableSql(OceanBaseMySqlCatalog.java:186)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getCreateTableSqls(AbstractJdbcCatalog.java:442)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.createTableInternal(AbstractJdbcCatalog.java:450)
	... 28 more

	at org.apache.seatunnel.engine.server.CoordinatorService.lambda$submitJob$6(CoordinatorService.java:656)
	at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:43)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

### Zeta or Flink or Spark Version

无

### Java or Scala Version

_No response_

### Screenshots

Image

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xxsc0529**
### Purpose of this pull request

ConstraintType class add VECTOR_INDEX_KEY enum，The error is reported in the buildConstrainKeySql method of OceanBaseMysqlCreateTableSqlBuilder. Currently, the vector index supported by oceanbase is very limited. It is not a good solution to not add an index under a large amount of data. Here is an appendix to a default index implementation. 
close #9056
### Does this PR introduce _any_ user-facing change?

none

### How was this patch tested?

seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcOceanBaseMilvusIT.java

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — COMMENTED** [review]
Hi @xxsc0529 , thanks for the pr. Could you explain why test case execute normally before this patch. Does the change not be covered by test case?

**Comment by xxsc0529** [comment]
> Hi @xxsc0529 , thanks for the pr. Could you explain why test case execute normally before this patch. Does the change not be covered by test case?

add test case:testMilvusToOceanBaseNotTable
The oceanbase table can be automatically created. This test passes the test, which means that the upstream has an index, and the downstream can be aware and created an oceanabse table when processing it downstream, without an error.

**Comment by Hisoka-X** [comment]
> > Hi @xxsc0529 , thanks for the pr. Could you explain why test case execute normally before this patch. Does the change not be covered by test case?
> 
> add test case:testMilvusToOceanBaseNotTable The oceanbase table can be automatically created. This test passes the test, which means that the upstream has an index, and the downstream can be aware and created an oceanabse table when processing it downstream, without an error.

image
I cannot found the create table log... Maybe something wrong in test case.

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcOceanBaseMilvusIT.java [hunk 1]
```diff
@@ -275,6 +275,18 @@ public void testMilvusToOceanBase(TestContainer container) throws Exception {
         }
     }
 
+    @TestTemplate
+    public void testMilvusToOceanBaseNotTable(TestContainer container) throws Exception {
+        try {
+            dropOceanBaseTable();
+            Container.ExecResult execResult =
+                    container.executeJob("/jdbc_milvus_source_and_oceanbase_sink.conf");
+            Assertions.assertEquals(0, execResult.getExitCode(), execResult.getStderr());
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcOceanBaseMilvusIT.java]: Let's set [schema_save_mode](https://github.com/apache/seatunnel/blob/dev/docs/en/connector-v2/sink/Jdbc.md#schema_save_mode-enum) to `RECREATE_SCHEMA` to force create table.

Comment (xxsc0529) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcOceanBaseMilvusIT.java]: Do you think it is feasible to check whether the table creation statement is working as expected after the synchronization is completed?

Comment (Hisoka-X) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcOceanBaseMilvusIT.java]: Sure, but we also should check the table indeed not exist before job start.

Comment (xxsc0529) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcOceanBaseMilvusIT.java]: @Hisoka-X I added the check to remove the automatic setting added based on the environment information when OceanBase created the table, but I can confirm that the vector index is created successfully

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcOceanBaseMilvusIT.java [hunk 2]
```diff
@@ -493,6 +517,65 @@ public String buildTableInfoWithSchema(String schema, String table) {
         }
     }
 
+    private void dropOceanBaseTable() {
+        String sql =
+                String.format("drop table IF EXISTS %s.%s", OCEANBASE_DATABASE, OCEANBASE_SINK);
+        executeSql(sql);
+    }
+
+    private void checkTableExist() {
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcOceanBaseMilvusIT.java]:
```suggestion
    private void checkTableNotExist() {
```

**Review by Hisoka-X — COMMENTED** [review]
Thanks @xxsc0529 ! LGTM except one minior problem.

**Comment by xxsc0529** [comment]
> Thanks @xxsc0529 ! LGTM except one minior problem.

It has been modified

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcOceanBaseMilvusIT.java [hunk 3]
```diff
@@ -275,6 +276,20 @@ public void testMilvusToOceanBase(TestContainer container) throws Exception {
         }
     }
 
+    @TestTemplate
+    public void testMilvusToOceanBaseNotTable(TestContainer container) throws Exception {
+        try {
+            dropOceanBaseTable();
+            checkTableExist();
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-2/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcOceanBaseMilvusIT.java]:
```suggestion
            checkTableNotExist();
```

**Review by Hisoka-X — DISMISSED** [review]

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]
