### PR TITLE
[Fix][Zeta] Avoid redundant checkpoint reads when disabled checkpoint

### LINKED ISSUE #9542: [Bug] [Zeta] 'checkpoint.interval' configuration of env is missing, checkpoint  be disabled, but still create storage.
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Remove the 'checkpoint.interval' from the task configuration environment variable. Also, checkpointEnable=false is still triggering the creation of checkpoint storage. 

### SeaTunnel Version

2.3.11

### SeaTunnel Config

```conf
env {
  # You can set SeaTunnel environment configuration here
  parallelism = 2
  job.mode = "BATCH"
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
  FakeSource {
    parallelism = 2
    plugin_output = "fake"
    row.num = 16
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
  }

  # If you would like to get more information about how to configure SeaTunnel and see full list of source plugins,
  # please go to https://seatunnel.apache.org/docs/connector-v2/source
}

sink {
  Console {
  }

  # If you would like to get more information about how to configure SeaTunnel and see full list of sink plugins,
  # please go to https://seatunnel.apache.org/docs/connector-v2/sink
}
```

### Running Command

```shell
--config ./config/v2.batch.config.template -m local
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:228)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:40)
Caused by: java.util.concurrent.CompletionException: org.apache.seatunnel.engine.common.exception.JobException: java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.common.HdfsFileStorageInstance.getOrCreateStorage(HdfsFileStorageInstance.java:53)
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorageFactory.create(HdfsStorageFactory.java:74)
	at org.apache.seatunnel.engine.server.checkpoint.CheckpointManager.<init>(CheckpointManager.java:107)
	at org.apache.seatunnel.engine.server.master.JobMaster.initCheckPointManager(JobMaster.java:329)
	at org.apache.seatunnel.engine.server.master.JobMaster.init(JobMaster.java:312)
	at org.apache.seatunnel.engine.server.CoordinatorService.lambda$submitJob$6(CoordinatorService.java:656)
	at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:43)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
```

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by chestnut-c**
### Purpose of this pull request

If the batch task configuration property checkpoint.interval is missing or checkpointEnable=false, the checkpoint storage policy configured in seatunnel.yaml will not be triggered, and the default loaclfile will be used to avoid not enabling checkpoint but actually using the checkpoint storage configured in seatunnel.yaml. https://github.com/apache/seatunnel/issues/9542

Just like the PR I closed last time https://github.com/apache/seatunnel/pull/9543 , this time I resubmitted the PR after modification.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

yes,When running batch tasks locally, remove the task configuration checkpoint.interval, but the checkpoint storage configured in seatunnel.yaml is still hdfs. After the modification, the task runs normally.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Hi @chestnut-c . Could you help to check the root reason of ClassNotFound before we consider how to fix it? https://github.com/apache/seatunnel/issues/9542#issuecomment-3050917474

**Comment by chestnut-c** [comment]
> Hi @chestnut-c . Could you help to check the root reason of ClassNotFound before we consider how to fix it? [#9542 (comment)](https://github.com/apache/seatunnel/issues/9542#issuecomment-3050917474)

hi @Hisoka-X  The purpose of this PR is to ask why checkpoint will be disabled, and the system will still create checkpoint Storage later. Maybe I didn't express it clearly. hahha

**Comment by Hisoka-X** [comment]
> why checkpoint will be disabled, and the system will still create checkpoint Storage later. 

When we disabled checkpoints, it is indeed unnecessary to create extra checkpoint storage. But re-examining this code,
we have actually created the checkpoint storage when the server starts.
https://github.com/apache/seatunnel/blob/3836c97a62079f1e8d7ca7a9f32c02175030bb3a/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/SeaTunnelServer.java#L167

Perhaps we should modify it like this:
1. Remove the checkpoint storage creation every time the CheckpointManager is created, and reuse the created checkpoint storage.
https://github.com/apache/seatunnel/blob/3836c97a62079f1e8d7ca7a9f32c02175030bb3a/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointManager.java#L102
2. When a job does not have checkpoints enabled, skip reading data from the checkpoint storage, which can reduce unnecessary overhead.
https://github.com/apache/seatunnel/blob/3836c97a62079f1e8d7ca7a9f32c02175030bb3a/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointManager.java#L121
and
https://github.com/apache/seatunnel/blob/3836c97a62079f1e8d7ca7a9f32c02175030bb3a/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointManager.java#L245

Regarding the logic of skipping checkpoint storage reading, for the sake of subsequent maintainability, we can inject a storage named empty into the checkpoint manager when the checkpoint is disabled, and all read and write operations will have no additional effect.

**Comment by chestnut-c** [comment]
> > why checkpoint will be disabled, and the system will still create checkpoint Storage later.
> 
> When we disabled checkpoints, it is indeed unnecessary to create extra checkpoint storage. But re-examining this code, we have actually created the checkpoint storage when the server starts.
> 
> https://github.com/apache/seatunnel/blob/3836c97a62079f1e8d7ca7a9f32c02175030bb3a/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/SeaTunnelServer.java#L167
> 
> Perhaps we should modify it like this:
> 
> 1. Remove the checkpoint storage creation every time the CheckpointManager is created, and reuse the created checkpoint storage.
>    https://github.com/apache/seatunnel/blob/3836c97a62079f1e8d7ca7a9f32c02175030bb3a/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointManager.java#L102
> 2. When a job does not have checkpoints enabled, skip reading data from the checkpoint storage, which can reduce unnecessary overhead.
>    https://github.com/apache/seatunnel/blob/3836c97a62079f1e8d7ca7a9f32c02175030bb3a/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointManager.java#L121
>    
>    and
>    https://github.com/apache/seatunnel/blob/3836c97a62079f1e8d7ca7a9f32c02175030bb3a/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointManager.java#L245
> 
> Regarding the logic of skipping checkpoint storage reading, for the sake of subsequent maintainability, we can inject a storage named empty into the checkpoint manager when the checkpoint is disabled, and all read and write operations will have no additional effect.

@Hisoka-X  OK, maybe I misunderstood. I think if it is not enabled, there is no need to trigger the relevant logic. Since this is the framework design, we can skip this issue. thx bro

**Comment by Hisoka-X** [comment]
> 1. Remove the checkpoint storage creation every time the CheckpointManager is created, and reuse the created checkpoint storage.
>    https://github.com/apache/seatunnel/blob/3836c97a62079f1e8d7ca7a9f32c02175030bb3a/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointManager.java#L102
> 2. When a job does not have checkpoints enabled, skip reading data from the checkpoint storage, which can reduce unnecessary overhead.
>    https://github.com/apache/seatunnel/blob/3836c97a62079f1e8d7ca7a9f32c02175030bb3a/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointManager.java#L121
>    
>    and
>    https://github.com/apache/seatunnel/blob/3836c97a62079f1e8d7ca7a9f32c02175030bb3a/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointManager.java#L245
> 
> Regarding the logic of skipping checkpoint storage reading, for the sake of subsequent maintainability, we can inject a storage named empty into the checkpoint manager when the checkpoint is disabled, and all read and write operations will have no additional effect.

@chestnut-c , Could you help to perform an optimization in this way?

**Comment by chestnut-c** [comment]
> When we disabled checkpoints, it is indeed unnecessary to create extra checkpoint storage. But re-examining this code,
> we have actually created the checkpoint storage when the server starts.

ok , @Hisoka-X  pls help me to review this again

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointStorageTest.java [hunk 1]
```diff
@@ -177,4 +179,30 @@ public void testStreamJobWithCancel() throws CheckpointStorageException, Interru
...
+
+        startJob(jobId, BATCH_CONF_WITHOUT_CHECKPOINT_INTERVAL_PATH, false);
+        await().atMost(120000, TimeUnit.MILLISECONDS)
+                .untilAsserted(
+                        () ->
+                                Assertions.assertEquals(
+                                        server.getCoordinatorService().getJobStatus(jobId),
+                                        JobStatus.FINISHED));
+        List<PipelineState> allCheckpoints =
+                checkpointStorage.getAllCheckpoints(String.valueOf(jobId));
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointStorageTest.java]: Before this PR, this test case should also be able to run normally, so our test case also needs to verify that the checkpoint storage has not been accessed. Perhaps we can create a checkpoint storage class only for testing and record the number of times it is called to verify this modification.

**Review by Hisoka-X — COMMENTED** [review]
Thanks @chestnut-c for update. I left a problem that needs improve.

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointStorageTest.java (hunk 1 above)
Comment (chestnut-c) [reply seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointStorageTest.java]: ok thanks @Hisoka-X , i will fix this one

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointStorageTest.java [hunk 2]
```diff
@@ -177,4 +183,104 @@ public void testStreamJobWithCancel() throws CheckpointStorageException, Interru
...
+                .untilAsserted(
+                        () ->
+                                Assertions.assertEquals(
+                                        server.getCoordinatorService().getJobStatus(jobId),
+                                        JobStatus.FINISHED));
+
+        List<PipelineState> allCheckpoints =
+                checkpointStorage.getAllCheckpoints(String.valueOf(jobId));
+        Assertions.assertEquals(0, allCheckpoints.size());
+        Assertions.assertEquals(1, accessCnt.get());
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointStorageTest.java]:
```suggestion
                checkpointStorage.getAllCheckpoints(String.valueOf(jobId));
        Assertions.assertEquals(1, accessCnt.get());
```

The assert useless.

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointStorageTest.java [hunk 3]
```diff
@@ -177,4 +183,104 @@ public void testStreamJobWithCancel() throws CheckpointStorageException, Interru
...
+                        accessCnt.incrementAndGet();
+                    }
+                };
+
+        // replace the checkpoint storage reused by the system
+        CheckpointService checkpointService = server.getCheckpointService();
+        Field checkpointStorageField =
+                checkpointService.getClass().getDeclaredField("checkpointStorage");
+        checkpointStorageField.setAccessible(true);
+        checkpointStorageField.set(checkpointService, checkpointStorage);
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointStorageTest.java]: Please reuse `org.apache.seatunnel.common.utils.ReflectionUtils`

Comment (chestnut-c) [reply seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointStorageTest.java]: ok thx @Hisoka-X

**Review by Hisoka-X — DISMISSED** [review]
LGTM if ci passes. Thanks @chestnut-c

**Comment by chestnut-c** [comment]
I found that sometimes some unit test cases in the CI pipeline would time out, sometimes fail, and sometimes succeed, which was very strange. @Hisoka-X

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointStorageTest.java [hunk 4]
```diff
@@ -177,4 +159,97 @@ public void testStreamJobWithCancel() throws CheckpointStorageException, Interru
...
+
+        startJob(jobId, BATCH_CONF_WITHOUT_CHECKPOINT_INTERVAL_PATH, false);
+        await().atMost(120000, TimeUnit.MILLISECONDS)
+                .untilAsserted(
+                        () ->
+                                Assertions.assertEquals(
+                                        server.getCoordinatorService().getJobStatus(jobId),
+                                        JobStatus.FINISHED));
+
+        checkpointStorage.getAllCheckpoints(String.valueOf(jobId));
```
[the remark this answers is not in the document]
Comment (chestnut-c) [reply seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointStorageTest.java:252]: The method is currently called to count the number of times checkpointStorage is accessed. It has nothing to do with the returned result, but it still needs to be called.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointManager.java [hunk 5]
```diff
@@ -81,9 +78,9 @@ public class CheckpointManager {
 
     private final CheckpointStorage checkpointStorage;
 
-    private final JobMaster jobMaster;
+    private final CheckpointConfig checkpointConfig;
```
[the remark this answers is not in the document]
Comment (chestnut-c) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointManager.java:82]: I don't think it has any impact

**Comment by chestnut-c** [comment]
@Hisoka-X  thanks , the unit case tests all is ok hahahha

**Review by Hisoka-X — APPROVED** [review]
Thanks @chestnut-c

**Comment by chestnut-c** [comment]
@corgy-w please help review.

**Review by corgy-w — APPROVED** [review]
