### PR TITLE
[Fix][Connector-v2] Fix the sql statement error of create table for doris and starrocks

### LINKED ISSUE #6646: [Bug] [Doris] sync from mysql to doris create table error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

there's 1500+ tables in my  source database，doris create some table error，perhaps my source table does not contains primary key？ 有一千五百多张表在我的源数据库里，在Doris 创建表的时候就报错了，可能是我的源表没有主键，生成Doris建表语句的时候没考虑到这点，导致出现错误

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
sink {
Doris {
     base-url = "jdbc:mysql://localhost:9030"                        
     username = "root"                        
     password = "****"                        
     database = "***"                        
     enable_upsert_delete = true                        
     batch_max_rows = 8192                        
     batch_max_bytes = 10485760                        
     fenodes = "127.0.0.1:8030"                        
     sink.enable-2pc = "true"                        
     sink.enable-delete = "true"                        
     doris.config {                                
         format = "json"                                
         read_json_by_line = "true"                        
     }        
}
}
```

### Running Command

```shell
sh bin/seatunnel.sh --config job/mysql.streaming.config -m local
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:199)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.common.exception.SeaTunnelRuntimeException: ErrorCode:[API-09], ErrorDescription:[Handle save mode failed]
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.handleSaveMode(MultipleTableJobConfigParser.java:669)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.createSinkAction(MultipleTableJobConfigParser.java:655)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSink(MultipleTableJobConfigParser.java:567)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:193)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:161)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:146)
        ... 2 more
Caused by: org.apache.seatunnel.api.table.catalog.exception.CatalogException: ErrorCode:[API-03], ErrorDescription:[Catalog initialize failed] - create table statement execute failed
        at org.apache.seatunnel.connectors.doris.catalog.DorisCatalog.createTable(DorisCatalog.java:286)
        at org.apache.seatunnel.api.sink.DefaultSaveModeHandler.createTable(DefaultSaveModeHandler.java:142)
        at org.apache.seatunnel.api.sink.DefaultSaveModeHandler.createSchemaWhenNotExist(DefaultSaveModeHandler.java:101)
        at org.apache.seatunnel.api.sink.DefaultSaveModeHandler.handleSchemaSaveMode(DefaultSaveModeHandler.java:62)
        at org.apache.seatunnel.api.sink.SaveModeHandler.handleSaveMode(SaveModeHandler.java:27)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.handleSaveMode(MultipleTableJobConfigParser.java:667)
        ... 8 more
Caused by: java.sql.SQLException: errCode = 2, detailMessage = Syntax error in line 21:
 UNIQUE KEY ()
             ^
Encountered: )
Expected: IDENTIFIER

        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
        at org.apache.seatunnel.connectors.doris.catalog.DorisCatalog.createTable(DorisCatalog.java:284)
        ... 13 more
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by dailai**
### Purpose of this pull request

Fix the sql statement error caused by the source table having no primary key or unique key for doris and startrocks. Link #6646

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/util/DorisCatalogUtil.java [hunk 1]
```diff
@@ -110,21 +111,27 @@ public static String getCreateTableStatement(
         String template = createTableTemplate;
         TableSchema tableSchema = catalogTable.getTableSchema();
 
-        String primaryKey = "";
+        String primaryKey = StringUtils.EMPTY;
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/util/DorisCatalogUtil.java]: I think the old code style more clear.
```suggestion
        String primaryKey = "";
```

File: seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/util/DorisCatalogUtil.java [hunk 2]
```diff
@@ -110,21 +111,27 @@ public static String getCreateTableStatement(
...
         if (tableSchema.getPrimaryKey() != null) {
             primaryKey =
                     tableSchema.getPrimaryKey().getColumnNames().stream()
                             .map(r -> "`" + r + "`")
                             .collect(Collectors.joining(","));
         }
-        String uniqueKey = "";
+        String uniqueKey = StringUtils.EMPTY;
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/util/DorisCatalogUtil.java]: ditto

File: seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/util/DorisCatalogUtil.java [hunk 3]
```diff
@@ -110,21 +111,27 @@ public static String getCreateTableStatement(
...
             uniqueKey =
                     tableSchema.getConstraintKeys().stream()
                             .flatMap(c -> c.getColumnNames().stream())
                             .map(r -> "`" + r.getColumnName() + "`")
                             .collect(Collectors.joining(","));
         }
+        if (checkPrimaryKeyAndUniqueKey(template, primaryKey, uniqueKey)) {
+            throw new RuntimeException(
+                    String.format(
+                            "The table of %s has no primaryKey or uniqueKey, please use the option named save_mode_create_template to specify sql template",
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/util/DorisCatalogUtil.java]:
```suggestion
                            "The table of %s has no primaryKey or uniqueKey, please use the option named " + SAVE_MODE_CREATE_TEMPLATE.key() + " to specify sql template",
```

File: seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/util/DorisCatalogUtil.java [hunk 4]
```diff
@@ -153,6 +160,17 @@ public static String getCreateTableStatement(
                         rowTypeFields);
     }
 
+    private static boolean checkPrimaryKeyAndUniqueKey(
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/util/DorisCatalogUtil.java]:
```suggestion
    private static boolean canHandledByDefaultTemplate(
```

File: seatunnel-connectors-v2/connector-doris/src/test/java/org/apache/seatunnel/connectors/doris/catalog/DorisCreateTableTest.java [hunk 5]
```diff
@@ -130,6 +133,26 @@ public void test() {
...
+                        Collections.emptyMap(),
+                        Collections.emptyList(),
+                        "");
+        Assertions.assertThrows(
+                RuntimeException.class,
+                () ->
+                        DorisCatalogUtil.getCreateTableStatement(
+                                DorisOptions.SAVE_MODE_CREATE_TEMPLATE.defaultValue(),
+                                TablePath.of("test1.test2"),
+                                catalogTable));
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-doris/src/test/java/org/apache/seatunnel/connectors/doris/catalog/DorisCreateTableTest.java]: Please assert the `RuntimeException`'s message.

File: seatunnel-connectors-v2/connector-doris/src/test/java/org/apache/seatunnel/connectors/doris/catalog/PreviewActionTest.java [hunk 6]
```diff
@@ -110,10 +110,20 @@ private void assertPreviewResult(
...
+            Assertions.assertEquals(expectedSql, ((SQLPreviewResult) previewResult).getSql());
+        } else {
+            Assertions.assertThrows(
+                    RuntimeException.class,
+                    () ->
+                            catalog.previewAction(
+                                    actionType,
+                                    TablePath.of("testddatabase.testtable"),
+                                    catalogTable));
+        }
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-doris/src/test/java/org/apache/seatunnel/connectors/doris/catalog/PreviewActionTest.java]: The file main to test preview create table action. So I think we should modify test to make sure the test case of preview create table action passed, not throw exception. I think we can add primary keys in `CATALOG_TABLE`.

**Review by Hisoka-X — COMMENTED** [review]
Thanks @dailai !

**Comment by Hisoka-X** [comment]
Could you check the starrocks connector too? Thanks

**Comment by dailai** [comment]
> Could you check the starrocks connector too? Thanks

OK

File: seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/util/DorisCatalogUtil.java [hunk 7]
```diff
@@ -153,6 +162,17 @@ public static String getCreateTableStatement(
                         rowTypeFields);
     }
 
+    private static boolean canHandledByDefaultTemplate(
+            String createTemplate, String primaryKey, String uniqueKey) {
+        return (StringUtils.equals(
+                                createTemplate,
+                                DorisOptions.SAVE_MODE_CREATE_TEMPLATE.defaultValue())
+                        && StringUtils.isBlank(primaryKey)
+                        && StringUtils.isBlank(uniqueKey))
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/util/DorisCatalogUtil.java]: The default template seem like doesn't care uniqueKey value.
```suggestion
                        && StringUtils.isBlank(primaryKey))
```

File: seatunnel-connectors-v2/connector-starrocks/src/main/java/org/apache/seatunnel/connectors/seatunnel/starrocks/sink/StarRocksSaveModeUtil.java [hunk 8]
```diff
@@ -80,6 +89,17 @@ public static String getCreateTableSql(
                         rowTypeFields);
     }
 
+    private static boolean canHandledByDefaultTemplate(
+            String createTemplate, String primaryKey, String uniqueKey) {
+        return (StringUtils.equals(
+                                createTemplate,
+                                StarRocksSinkOptions.SAVE_MODE_CREATE_TEMPLATE.defaultValue())
+                        && StringUtils.isBlank(primaryKey)
+                        && StringUtils.isBlank(uniqueKey))
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-starrocks/src/main/java/org/apache/seatunnel/connectors/seatunnel/starrocks/sink/StarRocksSaveModeUtil.java]: ditto

Comment (dailai) [reply seatunnel-connectors-v2/connector-starrocks/src/main/java/org/apache/seatunnel/connectors/seatunnel/starrocks/sink/StarRocksSaveModeUtil.java]: done

File: seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/util/DorisCatalogUtil.java [hunk 9]
```diff
@@ -153,6 +162,12 @@ public static String getCreateTableStatement(
                         rowTypeFields);
     }
 
+    private static boolean canHandledByDefaultTemplate(String createTemplate, String primaryKey) {
+        return StringUtils.equals(
+                        createTemplate, DorisOptions.SAVE_MODE_CREATE_TEMPLATE.defaultValue())
+                && StringUtils.isBlank(primaryKey);
+    }
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/util/DorisCatalogUtil.java]: I thought about it again, whether this kind of check is too rigid, and its useful scenarios are very limited. We can predict whether the spliced SQL will be abnormal by checking whether the placeholders and corresponding values used in the template exist. For example, by default template, we know that the primarykeys information needs to be used by scanning the template, but the primarykeys information is not found, then we can throw an exception.
```java
    private static boolean canHandledByDefaultTemplate(String createTemplate, String primaryKey) {
        if (createTemplate.contains(String.format("\\$\\{%s\\}", SaveModeConstants.ROWTYPE_PRIMARY_KEY)) && StringUtils.isEmpty(primaryKey)) {
            throw exception;
        }
        .... same for uniqueKeys
    }
```

Comment (dailai) [reply seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/util/DorisCatalogUtil.java:169]: Good idea.

Comment (dailai) [reply seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/util/DorisCatalogUtil.java]: My intention is to do so, because the relationship of time I made the simplest. I'm going to take some time to do that.

File: seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java [hunk 10]
```diff
@@ -17,13 +17,24 @@
 
 package org.apache.seatunnel.api.sink;
 
-public class SaveModeConstants {
+public enum SaveModePlaceHolderEnum {
+    ROWTYPE_PRIMARY_KEY("primaryKeys"),
+    ROWTYPE_UNIQUE_KEY("uniqueKeys"),
+    ROWTYPE_FIELDS("fields"),
+    TABLE_NAME("tableName"),
+    DATABASE("database");
```
Comment (Hisoka-X) [inline seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java]: Please do not change the key value. We need to ensure backward compatibility

File: seatunnel-api/src/main/java/org/apache/seatunnel/api/table/sql/template/SqlTemplate.java [hunk 11]
```diff
@@ -0,0 +1,46 @@
...
+    public static final String EXCEPTION_TEMPLATE =
+            "The table of %s has no %s, but the template \n %s \n which has the place holder named %s. Please use the option named %s to specify sql template";
+
+    public static void canHandledByTemplateWithPlaceholder(
+            String createTemplate,
+            String keyPlaceholder,
+            String actualKey,
+            String tableName,
+            String optionsKey) {
+        if (createTemplate.contains(keyPlaceholder) && StringUtils.isBlank(actualKey)) {
```
Comment (Hisoka-X) [inline seatunnel-api/src/main/java/org/apache/seatunnel/api/table/sql/template/SqlTemplate.java]: `keyPlaceholder` just string like `database`, it is easily confused with other normal fields. We should check `${database}`.

File: seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java (hunk 10 above)
Comment (dailai) [reply seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java]: > Please do not change the key value. We need to ensure backward compatibility

There are already methods in the class to get the placeholder, the enumeration names are the same as before, and the keyValue here is used for other purposes.

File: seatunnel-api/src/main/java/org/apache/seatunnel/api/table/sql/template/SqlTemplate.java (hunk 11 above)
Comment (dailai) [reply seatunnel-api/src/main/java/org/apache/seatunnel/api/table/sql/template/SqlTemplate.java]: Oh, my God, that's true. Let me fix it

File: seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java [hunk 12]
```diff
@@ -0,0 +1,66 @@
+/*
```
Comment (Hisoka-X) [inline seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java]: Please this file and `SqlTemplate` into `connector-common` module. I think that is a better place.

File: seatunnel-connectors-v2/connector-doris/src/test/java/org/apache/seatunnel/connectors/doris/catalog/DorisCreateTableTest.java [hunk 13]
```diff
@@ -111,25 +116,37 @@ public void test() {
...
-                        + "PARTITION BY RANGE (`create_time`)(  \n"
-                        + "   PARTITION p20230329 VALUES LESS THAN (\"2023-03-29\")                                                                                                                                                           \n"
-                        + ")                                      \n"
-                        + "DISTRIBUTED BY HASH (`id`,`age`)  \n"
-                        + "PROPERTIES (\n"
-                        + "\"replication_allocation\" = \"tag.location.default: 1\",\n"
-                        + "\"in_memory\" = \"false\",\n"
-                        + "\"storage_format\" = \"V2\",\n"
-                        + "\"disable_auto_compaction\" = \"false\"\n"
-                        + ")");
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-doris/src/test/java/org/apache/seatunnel/connectors/doris/catalog/DorisCreateTableTest.java]: Where is this part?

File: seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java [hunk 14]
```diff
@@ -0,0 +1,66 @@
...
+
+public enum SaveModePlaceHolderEnum {
+    ROWTYPE_PRIMARY_KEY("rowtype_primary_key", "primaryKeys"),
+    ROWTYPE_UNIQUE_KEY("rowtype_unique_key", "uniqueKeys"),
+    ROWTYPE_FIELDS("rowtype_fields", "fields"),
+    TABLE_NAME("table_name", "tableName"),
+    DATABASE("database", "database");
+
+    private String keyValue;
+    private String actualValue;
```
Comment (Hisoka-X) [inline seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java]:
```suggestion
    private String display;
```

File: seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java [hunk 15]
```diff
@@ -0,0 +1,66 @@
...
+package org.apache.seatunnel.api.sink;
+
+import java.util.Arrays;
+import java.util.Optional;
+
+public enum SaveModePlaceHolderEnum {
+    ROWTYPE_PRIMARY_KEY("rowtype_primary_key", "primaryKeys"),
+    ROWTYPE_UNIQUE_KEY("rowtype_unique_key", "uniqueKeys"),
+    ROWTYPE_FIELDS("rowtype_fields", "fields"),
+    TABLE_NAME("table_name", "tableName"),
```
Comment (Hisoka-X) [inline seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java]:
```suggestion
    ROWTYPE_PRIMARY_KEY("rowtype_primary_key", "primary keys"),
    ROWTYPE_UNIQUE_KEY("rowtype_unique_key", "unique keys"),
    ROWTYPE_FIELDS("rowtype_fields", "fields"),
    TABLE_NAME("table_name", "table name"),
```

File: seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java [hunk 16]
```diff
@@ -0,0 +1,66 @@
...
+
+    private static final String REPLACE_PLACE_HOLDER = "\\$\\{%s\\}";
+    private static final String PLACE_HOLDER = "${%s}";
+
+    SaveModePlaceHolderEnum(String keyValue, String actualValue) {
+        this.keyValue = keyValue;
+        this.actualValue = actualValue;
+    }
+
+    public static String getActualValueByPlaceHolder(String placeholder) {
```
Comment (Hisoka-X) [inline seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java]:
```suggestion
    public static String getDisplay(String placeholder) {
```

File: seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java [hunk 17]
```diff
@@ -0,0 +1,66 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.apache.seatunnel.api.sink;
+
+import java.util.Arrays;
+import java.util.Optional;
+
+public enum SaveModePlaceHolderEnum {
```
Comment (Hisoka-X) [inline seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java]:
```suggestion
public enum SaveModePlaceholder {
```

File: seatunnel-api/src/main/java/org/apache/seatunnel/api/table/sql/template/SqlTemplate.java [hunk 18]
```diff
@@ -0,0 +1,46 @@
...
+            "The table of %s has no %s, but the template \n %s \n which has the place holder named %s. Please use the option named %s to specify sql template";
+
+    public static void canHandledByTemplateWithPlaceholder(
+            String createTemplate,
+            String placeholder,
+            String actualPlaceHolderValue,
+            String tableName,
+            String optionsKey) {
+        if (createTemplate.contains(placeholder) && StringUtils.isBlank(actualPlaceHolderValue)) {
+            throw new RuntimeException(
```
Comment (Hisoka-X) [inline seatunnel-api/src/main/java/org/apache/seatunnel/api/table/sql/template/SqlTemplate.java]: Please add common error in https://github.com/apache/seatunnel/blob/790150a54b559148657a599fa16bf00539a5ab74/seatunnel-common/src/main/java/org/apache/seatunnel/common/exception/CommonError.java. Not throw RuntimeException.

File: seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java [hunk 19]
```diff
@@ -0,0 +1,66 @@
...
+        return this.keyValue;
+    }
+
+    public String getPlaceHolder() {
+        return String.format(PLACE_HOLDER, getPlaceHolderKeyValue());
+    }
+
+    public String getReplacePlaceHolder() {
+        return String.format(REPLACE_PLACE_HOLDER, getPlaceHolderKeyValue());
+    }
```
Comment (Hisoka-X) [inline seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java]:
```suggestion
    public String getPlaceholderKey() {
        return this.keyValue;
    }

    public String getPlaceholder() {
        return String.format(PLACE_HOLDER, getPlaceholderKey());
    }

    public String getReplacePlaceholder() {
        return String.format(REPLACE_PLACE_HOLDER, getPlaceholderKey());
    }
```

File: seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java (hunk 12 above)
Comment (dailai) [reply seatunnel-api/src/main/java/org/apache/seatunnel/api/sink/SaveModePlaceHolderEnum.java]: done

File: seatunnel-common/src/main/java/org/apache/seatunnel/common/exception/CommonErrorCode.java [hunk 20]
```diff
@@ -48,7 +48,8 @@ public enum CommonErrorCode implements SeaTunnelErrorCode {
             "<identifier> <operation> file '<fileName>' failed, because it not existed."),
     WRITE_SEATUNNEL_ROW_ERROR(
             "COMMON-23",
-            "<connector> write SeaTunnelRow failed, the SeaTunnelRow value is '<seaTunnelRow>'.");
+            "<connector> write SeaTunnelRow failed, the SeaTunnelRow value is '<seaTunnelRow>'."),
+    SQL_TEMPLATE_HANDLED_ERROR("COMMON-24", "Handle the template with placeholder failed.");
```
Comment (Hisoka-X) [inline seatunnel-common/src/main/java/org/apache/seatunnel/common/exception/CommonErrorCode.java]:
```suggestion
    SQL_TEMPLATE_HANDLED_ERROR("COMMON-24", "The table of <tableName> has no <keyName>, but the template \n <template> \n which has the place holder named <placeholder>. Please use the option named <optionName> to specify sql template");
```

File: seatunnel-common/src/main/java/org/apache/seatunnel/common/exception/CommonError.java [hunk 21]
```diff
@@ -183,4 +184,12 @@ public static SeaTunnelRuntimeException jsonOperationError(
             return new SeaTunnelRuntimeException(code, params);
         }
     }
+
+    public static SeaTunnelRuntimeException sqlTemplateHandledError(
+            String identifier, String operation, Throwable cause) {
+        Map<String, String> params = new HashMap<>();
+        params.put("identifier", identifier);
+        params.put("operation", operation);
```
Comment (Hisoka-X) [inline seatunnel-common/src/main/java/org/apache/seatunnel/common/exception/CommonError.java]:
```suggestion
        params.put("tableName", tableName);
        params.put("keyName", keyName);
        params.put("template", template);
        params.put("placeholder", placeholder);
        params.put("optionName", optionName);
```

File: seatunnel-connectors-v2/connector-common/src/main/java/org/apache/seatunnel/connectors/seatunnel/common/sql/template/SqlTemplate.java [hunk 22]
```diff
@@ -0,0 +1,50 @@
...
+                    "canHandledByTemplateWithPlaceholder",
+                    new RuntimeException(
+                            String.format(
+                                    EXCEPTION_TEMPLATE,
+                                    tableName,
+                                    SaveModePlaceHolder.getDisplay(placeholder),
+                                    createTemplate,
+                                    placeholder,
+                                    optionsKey)));
+        }
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-common/src/main/java/org/apache/seatunnel/connectors/seatunnel/common/sql/template/SqlTemplate.java]:
```suggestion
            throw CommonError.sqlTemplateHandledError(
                                    tableName,
                                    SaveModePlaceHolder.getDisplay(placeholder),
                                    createTemplate,
                                    placeholder,
                                    optionsKey));
        }
```

**Review by Hisoka-X — COMMENTED** [review]
We can just use common error to throw key message.

**Comment by dailai** [comment]
> We can just use common error to throw key message.

I see it. It's done

**Review by Hisoka-X — DISMISSED** [review]
LGTM if ci passed. Thanks @dailai !

**Comment by EricJoy2048** [comment]
Just a record: https://github.com/apache/seatunnel/pull/6354  I add `rowtype_dup_key` for Doris duplicate table Source sync to Doris duplicate table Sink. After this pr merge, I will change code.

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]
