### PR TITLE
[Fix] [Clickhouse] Parallelism makes data duplicate

### LINKED ISSUE #8803: [Bug] [Clickhouse to localfile] export Data rows error，need 1000,000 but actual 2000,000
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Image

Image

Image

Image

I want to export 100 or 1000,000 datas,but actual export 200 or 2000,000，it will  happens every 10-20 times

### SeaTunnel Version

2.3.9

### SeaTunnel Config

```conf
env {
  parallelism = 4
  job.mode = "BATCH"
  checkpoint.interval = 100000
}

source {
  Clickhouse {
    host = "192.168.0.22:8123"
    database = "default"
    sql = "select * from argus.test limit 100"
    username = "default"
    password = "xxx"
    clickhouse.config = {
      "socket_timeout": "300000"
    }
  }
}

sink {

  LocalFile {
    path = "/home/zhaohy/seatunnel/output/"
    file_format_type = "csv"
    field_delimiter = ","
    row_delimiter = "\n"
  }

}
```

### Running Command

```shell
./bin/seatunnel.sh --config config/argus_clickhouse_2_csv_100.conf -m local
```

### Error Exception

```log
no error
```

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

1.8

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by FrommyMind**
### Purpose of this pull request
close #8803

### Does this PR introduce _any_ user-facing change?

When use Clickhouse, use must set parallelism to 1.

### Check list

* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [x] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Maybe fixing ClickHouse connector's sharding logic is a better option.

**Comment by FrommyMind** [comment]
> Maybe fixing ClickHouse connector's sharding logic is a better option.

Could you please provide more details?


Currently the source using SQL to query data, if we try to implement parallelism, we must split the SQL.

For example:
```
select * from table1;
select * from table1 limit 10;
select a ,count(1) as b from table1 group by a ;
select a, count(1) as b from table1 group by a limit 10;
select a ,count(1) as b from table1 group by a  having count(1) > 10;
select a ,count(1) as b from table1 group by a  having count(1) > 10 limit 10;
```
That would be more complex.

File: seatunnel-connectors-v2/connector-clickhouse/src/main/java/org/apache/seatunnel/connectors/seatunnel/clickhouse/source/ClickhouseSourceReader.java [hunk 1]
```diff
@@ -80,31 +75,27 @@ public void close() throws IOException {
...
+                                    }
+                                    output.collect(new SeaTunnelRow(values));
+                                });
             }
-            if (noMoreSplit
-                    && splits.isEmpty()
-                    && Boundedness.BOUNDED.equals(readerContext.getBoundedness())) {
+            signalNoMoreElement();
+            if (Boundedness.BOUNDED.equals(readerContext.getBoundedness())) {
                 signalNoMoreElement();
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-clickhouse/src/main/java/org/apache/seatunnel/connectors/seatunnel/clickhouse/source/ClickhouseSourceReader.java]:
```suggestion
            signalNoMoreElement();
```

**Comment by Hisoka-X** [comment]
> > Maybe fixing ClickHouse connector's sharding logic is a better option.
> 
> Could you please provide more details?
> 
> Currently the source using SQL to query data, if we try to implement parallelism, we must split the SQL.
> 
> For example:
> 
> ```
> select * from table1;
> select * from table1 limit 10;
> select a ,count(1) as b from table1 group by a ;
> select a, count(1) as b from table1 group by a limit 10;
> select a ,count(1) as b from table1 group by a  having count(1) > 10;
> select a ,count(1) as b from table1 group by a  having count(1) > 10 limit 10;
> ```
> 
> That would be more complex.

Oh I get it. Maybe we can implement query table without sql in the future.

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]
