### PR TITLE
[Hotfix][Zeta] Fix the problem of unstable job status

### LINKED ISSUE #5342: [Bug] [CI][E2E] connector-seatunnel-e2e-base failed randomly
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

During the execution of CI, `connector-seatunnel-e2e-base` will fail randomly.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
no
```

### Running Command

```shell
no
```

### Error Exception

```log
2023-08-21T02:16:53.0373169Z 2023-08-21 02:16:53,036 WARN  com.hazelcast.internal.cluster.impl.MembershipManager - [localhost]:5802 [runner_ClusterFaultToleranceTwoPipelineIT_testTwoPipelineStreamJobRunOkIn2Node] [5.1] Member [localhost]:5801 - 5f743673-55a3-48ea-b818-24621eb949f0 is suspected to be dead for reason: No connection
2023-08-21T02:16:53.0375353Z 2023-08-21 02:16:53,037 WARN  org.apache.seatunnel.engine.server.SeaTunnelServer - This is master node, waiting the coordinator service init finished
2023-08-21T02:16:54.0387664Z 2023-08-21 02:16:54,037 ERROR org.apache.seatunnel.engine.server.SeaTunnelServer - Error when handle member removed event
2023-08-21T02:16:54.0389152Z org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: cluster have no master node
2023-08-21T02:16:54.0390933Z 	at org.apache.seatunnel.engine.server.SeaTunnelServer.isMasterNode(SeaTunnelServer.java:243) ~[seatunnel-engine-server-2.3.3-SNAPSHOT-2.11.12.jar:2.3.3-SNAPSHOT]
2023-08-21T02:16:54.0392376Z 	at org.apache.seatunnel.engine.server.SeaTunnelServer.getCoordinatorService(SeaTunnelServer.java:183) ~[seatunnel-engine-server-2.3.3-SNAPSHOT-2.11.12.jar:2.3.3-SNAPSHOT]
2023-08-21T02:16:54.0394174Z 	at org.apache.seatunnel.engine.server.SeaTunnelServer.memberRemoved(SeaTunnelServer.java:141) ~[seatunnel-engine-server-2.3.3-SNAPSHOT-2.11.12.jar:2.3.3-SNAPSHOT]
2023-08-21T02:16:54.0396045Z 	at com.hazelcast.internal.cluster.impl.MembershipManager.lambda$sendMembershipEventNotifications$2(MembershipManager.java:835) ~[hazelcast-5.1.jar:5.1]
2023-08-21T02:16:54.0397178Z 	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [hazelcast-5.1.jar:5.1]
2023-08-21T02:16:54.0397840Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_382]
2023-08-21T02:16:54.0399902Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_382]
2023-08-21T02:16:54.0400367Z 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_382]
2023-08-21T02:16:54.0401428Z 	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-5.1.jar:5.1]
2023-08-21T02:16:54.0402764Z 	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-5.1.jar:5.1]
2023-08-21T02:16:54.0405330Z Caused by: java.lang.NullPointerException
2023-08-21T02:16:54.0406171Z 	at org.apache.seatunnel.engine.server.SeaTunnelServer.lambda$isMasterNode$0(SeaTunnelServer.java:233) ~[seatunnel-engine-server-2.3.3-SNAPSHOT-2.11.12.jar:2.3.3-SNAPSHOT]
2023-08-21T02:16:54.0407258Z 	at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:48) ~[seatunnel-common-2.3.3-SNAPSHOT-2.11.12.jar:2.3.3-SNAPSHOT]
2023-08-21T02:16:54.0408701Z 	at org.apache.seatunnel.engine.server.SeaTunnelServer.isMasterNode(SeaTunnelServer.java:232) ~[seatunnel-engine-server-2.3.3-SNAPSHOT-2.11.12.jar:2.3.3-SNAPSHOT]
2023-08-21T02:16:54.0409291Z 	... 9 more
2023-08-21T02:16:54.0415058Z ##[error]Exception in thread "hz.zen_poitras.cached.thread-5" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@955e3e8 rejected from com.hazelcast.internal.util.executor.LoggingScheduledExecutor@1f8677e3[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 522]
2023-08-21T02:16:54.0420308Z 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
2023-08-21T02:16:54.0421092Z 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
2023-08-21T02:16:54.0421722Z 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
2023-08-21T02:16:54.0422425Z 	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
2023-08-21T02:16:54.0423453Z 	at com.hazelcast.spi.impl.executionservice.impl.DelegatingTaskScheduler.schedule(DelegatingTaskScheduler.java:49)
2023-08-21T02:16:54.0424310Z 	at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl.schedule(ExecutionServiceImpl.java:270)
2023-08-21T02:16:54.0425134Z 	at com.hazelcast.internal.crdt.CRDTReplicationMigrationService.scheduleMigrationTask(CRDTReplicationMigrationService.java:256)
2023-08-21T02:16:54.0425996Z 	at com.hazelcast.internal.crdt.CRDTReplicationMigrationService.memberRemoved(CRDTReplicationMigrationService.java:245)
2023-08-21T02:16:54.0426769Z 	at com.hazelcast.internal.cluster.impl.MembershipManager.lambda$sendMembershipEventNotifications$2(MembershipManager.java:835)
2023-08-21T02:16:54.0427526Z 	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
2023-08-21T02:16:54.0428186Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2023-08-21T02:16:54.0428729Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2023-08-21T02:16:54.0429141Z 	at java.lang.Thread.run(Thread.java:750)
2023-08-21T02:16:54.0429671Z 	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
2023-08-21T02:16:54.0430740Z 	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
2023-08-21T02:16:54.1007603Z [ERROR] Tests run: 7, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 223.538 s <<< FAILURE! - in org.apache.seatunnel.engine.e2e.ClusterFaultToleranceTwoPipelineIT
2023-08-21T02:16:54.1015282Z Aug 21, 2023 2:16:54 AM com.hazelcast.internal.config.AbstractConfigLocator
2023-08-21T02:16:54.1015888Z [ERROR] testTwoPipelineStreamJobRestoreIn2NodeMasterDown  Time elapsed: 76.027 s  <<< ERROR!
2023-08-21T02:16:54.1018047Z INFO: Loading 'seatunnel.yaml' from the classpath.
2023-08-21T02:16:54.1018738Z java.lang.NullPointerException
2023-08-21T02:16:54.1019732Z 	at org.apache.seatunnel.engine.e2e.ClusterFaultToleranceTwoPipelineIT.lambda$testTwoPipelineStreamJobRestoreIn2NodeMasterDown$18(ClusterFaultToleranceTwoPipelineIT.java:736)
2023-08-21T02:16:54.1020420Z 
2023-08-21T02:16:54.1020701Z [INFO] Running org.apache.seatunnel.engine.e2e.ClusterIT
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EricJoy2048**
### Purpose of this pull request

Fix https://github.com/apache/seatunnel/issues/5342

Reconstructed the scheduling process for Jobs, Pipelines, and Tasks. Change to state driven.

Modified the status types of Job, Pipeline, and Task.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
e2e already exists

### Check list

* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/resources/log4j2-test.properties [hunk 1]
```diff
@@ -22,7 +22,7 @@ rootLogger.appenderRef.consoleStdout.ref = consoleStdoutAppender
 rootLogger.appenderRef.consoleStderr.ref = consoleStderrAppender
 
 logger.zeta.name=org.apache.seatunnel.engine
-logger.zeta.level=WARN
+logger.zeta.level=INFO
```
Comment (EricJoy2048) [inline seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/resources/log4j2-test.properties]:
```suggestion
logger.zeta.level=WARN
```

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalPlan.java [hunk 2]
```diff
@@ -81,6 +78,8 @@ public class PhysicalPlan {
     /** Whether we make the job end when pipeline turn to end state. */
     private boolean makeJobEndWhenPipelineEnded = true;
```
Comment (ic4y) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalPlan.java:79]: delete it

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalPlan.java [hunk 3]
```diff
@@ -141,124 +140,57 @@ public void addPipelineEndCallback(SubPlan subPlan) {
...
-                                        String.format(
-                                                "cancel job %s because makeJobEndWhenPipelineEnded is true",
-                                                jobFullName));
-                                cancelJob();
-                            }
                         } else if (PipelineStatus.FAILED.equals(
                                 pipelineState.getPipelineStatus())) {
                             failedPipelineNum.incrementAndGet();
                             errorBySubPlan.compareAndSet(null, pipelineState.getThrowableMsg());
                             if (makeJobEndWhenPipelineEnded) {
```
Comment (ic4y) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalPlan.java:151]: remove this if

**Review by ic4y — COMMENTED** [review]
And turn on CheckpointTimeOutTest#testJobLevelCheckpointTimeOut

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalPlan.java (hunk 2 above)
Comment (EricJoy2048) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalPlan.java:79]: This is useful. In the future, we may allow `makeJobEndWhenPipelineEnded` to be false, so that failed pipelines will not affect running pipelines.

File: seatunnel-engine/seatunnel-engine-core/src/main/java/org/apache/seatunnel/engine/core/job/JobStatus.java [hunk 4]
```diff
@@ -29,10 +29,10 @@ public enum JobStatus {
     /** Job is newly created, no task has started to run. */
     CREATED(EndState.NOT_END),
 
-    /** Job is begin schedule but some task not deploy complete. */
+    /** Job will scheduler every pipeline */
     SCHEDULED(EndState.NOT_END),
 
-    /** Some tasks are scheduled or running, some may be pending, some may be finished. */
+    /** Job is running and begine to scheduler pipeline running. */
```
Comment (EricJoy2048) [inline seatunnel-engine/seatunnel-engine-core/src/main/java/org/apache/seatunnel/engine/core/job/JobStatus.java]:
```suggestion
    /** The job is already running, and each pipeline is already running. */
```

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 5]
```diff
@@ -759,9 +703,6 @@ public void printJobDetailInfo() {
                                         case CREATED:
                                             createdJobCount.addAndGet(1);
                                             break;
-                                        case SCHEDULED:
```
Comment (EricJoy2048) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: `SCHEDULED` job need to keep it because the status of the job can be SCHEDULED.

**Comment by ruanwenjun** [comment]
CI failed, please make sure your dev branch has rebased the upstream dev.

**Comment by EricJoy2048** [comment]
> CI failed, please make sure your dev branch has rebased the upstream dev.

Please waiting for https://github.com/apache/seatunnel/pull/5515

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterFaultToleranceIT.java [hunk 6]
```diff
@@ -840,15 +840,15 @@ public void testStreamJobRestoreInAllNodeDown()
             node1.shutdown();
             node2.shutdown();
 
-            log.info(
```
Comment (hailin0) [inline seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterFaultToleranceIT.java:843]: Why change

**Review by ic4y — DISMISSED** [review]

File: pom.xml [hunk 7]
```diff
@@ -730,6 +730,8 @@
                     <encoding>UTF-8</encoding>
                 </configuration>
             </plugin>
+            <!-- disable spotless check during release -->
```
Comment (Hisoka-X) [inline pom.xml]: But the plugin you disabled not spotless. Is there have some special reason?

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterFaultToleranceIT.java [hunk 8]
```diff
@@ -840,15 +840,15 @@ public void testStreamJobRestoreInAllNodeDown()
...
+            System.out.println(
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterFaultToleranceIT.java]: Any reason for change this?

File: seatunnel-engine/seatunnel-engine-core/src/main/java/org/apache/seatunnel/engine/core/job/JobStatus.java [hunk 9]
```diff
@@ -29,10 +29,10 @@ public enum JobStatus {
     /** Job is newly created, no task has started to run. */
     CREATED(EndState.NOT_END),
 
-    /** Job is begin schedule but some task not deploy complete. */
+    /** Job will scheduler every pipeline */
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-core/src/main/java/org/apache/seatunnel/engine/core/job/JobStatus.java]: I think new comment not clearly than old one.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinator.java [hunk 10]
```diff
@@ -425,7 +425,7 @@ protected void tryTriggerPendingCheckpoint(CheckpointType checkpointType) {
             startTriggerPendingCheckpoint(pendingCheckpoint);
             pendingCounter.incrementAndGet();
             // if checkpoint type are final type, we don't need to trigger next checkpoint
-            if (checkpointType.notFinalCheckpoint() && checkpointType.notSchemaChangeCheckpoint()) {
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinator.java]: PTAL @hailin0

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalPlan.java [hunk 11]
```diff
@@ -315,4 +262,63 @@ public JobStatus getJobStatus() {
...
+                                    }
+                                });
+                updateJobState(JobStatus.RUNNING);
+                break;
+            case RUNNING:
+                try {
+                    Thread.sleep(200);
+                } catch (InterruptedException e) {
+                    makeJobFailing(e);
+                }
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalPlan.java]: `sleep` seem like not unnecessary. Because this method will return with void, not foreach with `while(true)`.

**Comment by Hisoka-X** [comment]
By the way, has this PR passed the stability test of a large number of jobs? Because our CI does not provide such a test, so maybe additional stability testing is required.

File: pom.xml (hunk 7 above)
Comment (EricJoy2048) [reply pom.xml]: done

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterFaultToleranceIT.java (hunk 8 above)
Comment (EricJoy2048) [reply seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterFaultToleranceIT.java]: > Any reason for change this?

`sysout` is easier to read than log. And the log level is warn default. This information is very important and can better help us locate the problem when CI reports an error.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalPlan.java (hunk 11 above)
Comment (EricJoy2048) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalPlan.java]: done

**Comment by EricJoy2048** [comment]
> By the way, has this PR passed the stability test of a large number of jobs? Because our CI does not provide such a test, so maybe additional stability testing is required.

I test this pr in `seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e`. I tested each case loop about 100 times and found no errors. Of course, this is not a real stress test, I do not have the environment for stress testing.

File: config/log4j2.properties [hunk 12]
```diff
@@ -42,7 +42,7 @@ appender.consoleStdout.name = consoleStdoutAppender
 appender.consoleStdout.type = CONSOLE
 appender.consoleStdout.target = SYSTEM_OUT
 appender.consoleStdout.layout.type = PatternLayout
-appender.consoleStdout.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %c - %m%n
+appender.consoleStdout.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%-30.30c{1.}] [%t] - %m%n
```
Comment (hailin0) [inline config/log4j2.properties:45]: sync update to `log4j2_client.properties`?

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterFaultToleranceIT.java (hunk 8 above)
Comment (hailin0) [reply seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterFaultToleranceIT.java]: why not use `log.warn`?

**Review by ic4y — DISMISSED** [review]

**Comment by Hisoka-X** [comment]
> > By the way, has this PR passed the stability test of a large number of jobs? Because our CI does not provide such a test, so maybe additional stability testing is required.
> 
> I test this pr in `seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e`. I tested each case loop about 100 times and found no errors. Of course, this is not a real stress test, I do not have the environment for stress testing.

Got it. Let us do it before next version release.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinator.java (hunk 10 above)
Comment (hailin0) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinator.java]: why delete it？ @EricJoy2048

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterFaultToleranceIT.java (hunk 8 above)
Comment (EricJoy2048) [reply seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterFaultToleranceIT.java]: > why not use `log.warn`?

done

File: seatunnel-engine/seatunnel-engine-core/src/main/java/org/apache/seatunnel/engine/core/job/JobStatus.java (hunk 9 above)
Comment (EricJoy2048) [reply seatunnel-engine/seatunnel-engine-core/src/main/java/org/apache/seatunnel/engine/core/job/JobStatus.java]: done

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinator.java (hunk 10 above)
Comment (EricJoy2048) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinator.java]: > why delete it？ @EricJoy2048

revert already.

File: config/log4j2.properties (hunk 12 above)
Comment (EricJoy2048) [reply config/log4j2.properties:45]: done

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterFaultToleranceIT.java [hunk 13]
```diff
@@ -458,9 +458,9 @@ public void testStreamJobRestoreIn2NodeWorkerDown()
                             () -> {
                                 // Wait job write all rows in file
                                 Thread.sleep(2000);
-                                System.out.println(
-                                        FileUtils.getFileLineNumberFromDir(
-                                                testResources.getLeft()));
+                                log.warn(
+                                        FileUtils.getFileLineNumberFromDir(testResources.getLeft())
+                                                + "");
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterFaultToleranceIT.java]:
```suggestion
                                        FileUtils.getFileLineNumberFromDir(testResources.getLeft()));
```

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/RestApiIT.java [hunk 14]
```diff
@@ -144,9 +144,6 @@ public void testSubmitJob() {
                                 .getNodeExtension()
                                 .createExtensionServices()
                                 .get(Constant.SEATUNNEL_SERVICE_NAME);
-        JobStatus jobStatus =
-                seaTunnelServer.getCoordinatorService().getJobStatus(Long.parseLong(jobId));
-        Assertions.assertEquals(JobStatus.RUNNING, jobStatus);
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/RestApiIT.java:149]: Why remove this?

**Review by Hisoka-X — DISMISSED** [review]
LGTM if test passed.

**Comment by hailin0** [comment]
> LGTM if test passed.

+1

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]
