### PR TITLE
[Fix][Rest-API] Submit or stop job from an inactive master node 

### LINKED ISSUE #6208: [Bug] [Zeta RestApi ] Submit or Stop job from an inactive master node
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

error when submit or stop job with error message " Please don't get coordinator service from an inactive master node" 

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
nothiong related
```

### Running Command

```shell
rest api to submit job
```

### Error Exception

```log
2024-01-15 16:55:32,395 INFO  [Log4j2HttpPostCommandProcessor] [hz.main.cached.thread-1] - [172.20.216.3]:5801 [seatunnel] [5.1] cluster master is :[172.20.216.1]:5801
2024-01-15 16:55:32,395 INFO  [Log4j2HttpPostCommandProcessor] [hz.main.cached.thread-1] - [172.20.216.3]:5801 [seatunnel] [5.1] [172.20.216.3]:5801 is :false
2024-01-15 16:55:32,396 INFO  [Log4j2HttpPostCommandProcessor] [hz.main.cached.thread-1] - [172.20.216.3]:5801 [seatunnel] [5.1] [172.20.216.3]:5801 is :false
2024-01-15 16:55:32,396 WARN  [Log4j2HttpPostCommandProcessor] [hz.main.cached.thread-1] - [172.20.216.3]:5801 [seatunnel] [5.1] An error occurred while handling request HttpCommand [HTTP_POST]{uri='/hazelcast/rest/maps/submit-job'}AbstractTextCommand[HTTP_POST]{requestId=2}
org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: Please don't get coordinator service from an inactive master node
        at org.apache.seatunnel.engine.server.SeaTunnelServer.getCoordinatorService(SeaTunnelServer.java:211) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.submitJob(RestHttpPostCommandProcessor.java:383) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handleSubmitJob(RestHttpPostCommandProcessor.java:180) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:91) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:70) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.ascii.TextCommandServiceImpl$CommandExecutor.run(TextCommandServiceImpl.java:402) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
2024-01-15 16:55:51,128 INFO  [o.a.s.e.s.CoordinatorService  ] [pool-5-thread-1] - [172.20.216.3]:5801 [seatunnel] [5.1]
```

### Zeta or Flink or Spark Version

nothing

### Java or Scala Version

java 1.8 191

### Screenshots

i try to add some debug logs!
5b30e229611c13b27608d80be3ea1f2

Hazelcast.getAllHazelcastInstances() has only one instance(the current node)
5638414a27860a19f4bc5422abc4019

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liugddx**
### Purpose of this pull request

close #6208 

### Does this PR introduce _any_ user-facing change?

No
### How was this patch tested?

test case

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — COMMENTED** [review]
Please add test case

**Comment by VincentSleepless** [comment]
good job ~~

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/RestApiIT.java [hunk 1]
```diff
@@ -153,248 +143,6 @@ public void testSystemMonitoringInformation() {
                         });
     }
 
-    @Test
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/RestApiIT.java:158]: why remove this?

Comment (liugddx) [reply seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/RestApiIT.java:158]: > why remove this?

Migrated to ClusterSeaTunnelContainer.java

Comment (liugddx) [reply seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/RestApiIT.java:158]: > > why remove this?
> 
> Migrated to ClusterSeaTunnelContainer.java

Use two jvm processes to simulate real scenarios.

Comment (Hisoka-X) [reply seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/RestApiIT.java:158]: oh I see.

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterSeaTunnelContainer.java [hunk 2]
```diff
@@ -0,0 +1,498 @@
...
+    private static final String confFile = "/fakesource_to_console.conf";
+
+    @Override
+    @BeforeEach
+    public void startUp() throws Exception {
+        Path binPath = Paths.get(SEATUNNEL_HOME, "bin", SERVER_SHELL);
+        Path config = Paths.get(SEATUNNEL_HOME, "config");
+        Path hadoopJar = Paths.get(SEATUNNEL_HOME, "lib/seatunnel-hadoop3-3.1.4-uber.jar");
+
+        server =
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterSeaTunnelContainer.java]: Seem like just same code copy twice. Could you do some refactor to extract a method?

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterSeaTunnelContainer.java [hunk 3]
```diff
@@ -0,0 +1,498 @@
...
+                            Assertions.assertEquals(
+                                    2, response.jsonPath().getList("members").size());
+                        });
+    }
+
+    @Override
+    @AfterEach
+    public void tearDown() throws Exception {
+        super.tearDown();
+        if (secondServer != null) {
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterSeaTunnelContainer.java:100]: why only close `secondServer`?

Comment (liugddx) [reply seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterSeaTunnelContainer.java:100]: > why only close `secondServer`?

server closed in `super.tearDown();`

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterSeaTunnelContainer.java (hunk 2 above)
Comment (liugddx) [reply seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterSeaTunnelContainer.java]: > Seem like just same code copy twice. Could you do some refactor to extract a method?

Done.

**Review by Hisoka-X — DISMISSED** [review]
LGTM if CI passed.

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]
