### PR TITLE
[CI] Fix FixSlotResourceTest testNotEnoughResource test error

### LINKED ISSUE #6819: [Bug] [CI] Fix FixSlotResourceTest Unstable issues
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When reapplying for resources, it is possible that the resources have not been released, which can cause CI instability

image

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
*
```

### Running Command

```shell
*
```

### Error Exception

```log
*
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EricJoy2048**
### Purpose of this pull request

close https://github.com/apache/seatunnel/issues/6819

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/resourcemanager/ResourceManager.java [hunk 1]
```diff
@@ -58,4 +58,11 @@ CompletableFuture<List<SlotProfile>> applyResources(
     void memberRemoved(MembershipServiceEvent event);
 
     void close();
+
+    /**
+     * Get all can use slots
+     *
+     * @return
+     */
+    List<SlotProfile> getAllCanUseSlots();
```
Comment (hailin0) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/resourcemanager/ResourceManager.java]:
```suggestion
    List<SlotProfile> getUnassignedSlots();
```

Comment (EricJoy2048) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/resourcemanager/ResourceManager.java]: done

**Review by hailin0 — DISMISSED** [review]

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/resourcemanager/ResourceManager.java [hunk 2]
```diff
@@ -58,4 +58,11 @@ CompletableFuture<List<SlotProfile>> applyResources(
     void memberRemoved(MembershipServiceEvent event);
 
     void close();
+
+    /**
+     * Get all can use slots
+     *
+     * @return
+     */
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/resourcemanager/ResourceManager.java]:
```suggestion
```

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]
