### PR TITLE
[Zeta][Feature] Optimize SeaTunnel Zeta engine Jar package upload logic

### LINKED ISSUE #5012: [ST-Engine][Design] Optimize SeaTunnel Zeta engine Jar package upload logic
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

## Introduction
From #2333 we know, this approach has two significant limitations:

1. The server needs to have all connectors and their dependent JAR packages.
2. The installation path of the client must be exactly the same as the server, and the installation path of Seatunnel Zeta in all nodes must also be the same. This leads to the engine side of SeaTunnel Zeta being relatively heavy, and the container volume becoming very large when performing Docker or Kubernetes (K8S) submission tasks.

To address these limitations, we need to optimize the logic of the Zeta engine to execute the job. The server should only have the core jar package of the engine, and all the connector packages are on the Client side. When the job is submitted, the Client side should upload the required jar package to the server side, instead of just keeping the path of the jar package. When the server executes the job, it downloads the jar package required for the job and then loads it. After the job runs, the jar package is deleted.

### ConnectorPackageServer: 

- Capable of responding to third-party JAR package file upload and download requests for connectors and their dependencies. 

- The local file system can read and write connector JAR package files.
- The local file system reads and writes the third-party JAR package files that the connector depends on.
- Supports HA-distributed file system read and write.
- Responsible for cleaning up the local file system and distributed file system.
- Download requests prioritize using files from the local file system for HA recovery, downloading files from the distributed system to the local file system. 

### ConnectorPackageClient: 
- Caches local files in the ConnectorPackageServer for reading and writing.
- Prioritizes using files from the local file system, then attempts to obtain them from the ConnectorPackageServert running on the JobMaster side, and finally attempts to download them from the HA distributed file system.
- Responsible for cleaning the local file system.

### ConnectorPackageHAStorage: 
ConnectorPackageServer only temporarily saves files without specialized persistence operations. To ensure successful recovery from checkpoints after exceptions occur during task execution, it is necessary to persist JAR Package to the local file system or other distributed storage services, such as HDFS, S3, etc. 

### ConnectorJarsLoader:
ConnectorJarsLoader is a bridge between the JAR package of the connector obtained through component download, the JAR package that the connector depends on, and ClassLoader. These JAR package files are loaded into the path using the corresponding ClassLoader through ConnectorJarsLoader.

### Uploads the JAR package files
During the process of creating a job execution environment, the seatunnel client searches for third-party JAR packages that the connector depends on in the SEATUNNEL_HOME/plugins directory. After parsing the job configuration file according to the plugin type, the unique identifier of each connector plugin needs to be passed to PluginDiscovery. PluginDiscovery will obtain the JAR package name prefix for the corresponding connector from the relevant configuration file (mapping.properties) based on the plugin's unique identifier. Finally, PluginDiscovery searches for the connector JAR package in the storage directory where the corresponding connector JAR package is saved, and uploads it to the Hazelcast main node before the job submission process.

The file is first uploaded to JobMaster for local storage and then transferred to HA storage. Only after both are successfully written can the upload be confirmed (if HA is configured).

### JAR package file integrity verification
By performing file verification during the file upload process, it is possible to increase the verification of the integrity of the uploaded file. This helps to ensure that the uploaded files are not tampered with or damaged during transmission and storage.

### Obtain JAR package files
JobMaster will create a job scheduler to schedule and deploy physical node tasks in the job. The first step in deploying tasks through task execution services is to obtain the JAR package URL required for the current task execution from the job information. The second step is to determine whether the JAR package associated with the task exists locally. If there is no connector JAR package or third-party JAR package that the connector depends on in the local storage of the current executing node, then we need to obtain the corresponding connector JAR package for the current task and the third-party JAR package file that the connector depends on from JobMaster. Therefore, this step is the process of obtaining the JAR package on the execution end. Similarly, it is necessary to perform file integrity verification on the JAR package file obtained by the execution end. As long as the file integrity verification is successful, the next class loading process can proceed. After the class is loaded, the execution service executes the task.

### JobMaster Reliability Assurance (HA)
When the main node crashes, Hazelcast will automatically select another node as the master node. The re-selected master node will undergo the JobMaster reinitialization process again. In order to ensure the normal execution of previous jobs, we need to restore the locally stored job connector JAR package and the third-party JAR package that the connector relies on. We obtain the JAR files required for the job from the distributed file system and load them.

### Clear the JAR package files
The cleaning work is carried out not only on the local file system of the Hazelcast master node running on JobMaster but also on the connector JAR packages associated with the job and the third-party JAR packages that the connector depends on in the distributed file system.

### Connector JAR file type
Through the ConnectorPackageClient, you can download the JAR package of the connector, the JAR package that the connector depends on, and the user's JAR files from the service executed by JobMaster and store their JAR file content on a local disk. All JAR package files can be roughly divided into two types:
- COMMON_PLUGIN_JAR
- CONNECTOR_PLUGIN_JAR

## Abstract Interface

This class implements a server that supports storing JAR package files for connectors, JAR files that connectors depend on. The server is responsible for listening to incoming requests and generating threads to process them. In addition, it is also responsible for creating directory structures that temporarily or permanently store JAR package files for connectors, as well as third-party JAR files that the connector depends on.

The ConnectorPackageClient can communicate with the ConnectorPackageServer, sending requests to upload files and download files to the ConnectorPackageServer.

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lianghuan-xatu**
### Purpose of this pull request

https://github.com/apache/seatunnel/issues/5012

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by liugddx** [comment]
Nice job. Please maintain the documentation and add test cases.

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java [hunk 1]
```diff
@@ -64,6 +83,82 @@ protected MultipleTableJobConfigParser getJobConfigParser() {
...
+        // packages
+        // and dependent third-party Jar packages to the server before job execution.
+        // Enabling this configuration does not require the server to hold all connector Jar
+        // packages.
+        boolean enableUploadConnectorJarPackage =
+                seaTunnelConfig.getEngineConfig().getConnectorJarStorageConfig().getEnable();
+        if (enableUploadConnectorJarPackage == true) {
+            Set<ConnectorJarIdentifier> commonJarIdentifiers =
+                    connectorPackageClient.uploadCommonPluginJars(
+                            Long.parseLong(jobConfig.getJobContext().getJobId()), commonPluginJars);
```
Comment (ruanwenjun) [inline seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java]: Do we need to check if the jar already exist in Master?

**Review by hailin0 — COMMENTED** [review]
Please add e2e testcase

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java (hunk 1 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java:100]: If we send a request from the client to the server to determine whether the connector Jar package exists, then if the Jar package exists, a separate request API is required under the shared storage strategy to increase the Jar package reference count of the connector JarRefCounters in the shared storage mode. Do I need to change to this method?

Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java]: If we send a  request from the client to the server to check for the existence of the connector Jar package, and if the Jar package does exist, we need a separate API request to increment the reference count for the connector Jar package in shared connector jar storage mode. Should we switch to this approach?

**Comment by lianghuan-xatu** [comment]
> Please add e2e testcase



> Please add e2e testcase

I have added the e2e test case, PTAL!

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java (hunk 1 above)
Comment (ruanwenjun) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java]: You can add todo here, this is not needed, but this can help to reduce the request size, since most of the Job may have the same connector jars.

Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java]: Thank you very much for your suggestion. I have added todo, PTAL!

**Comment by Hisoka-X** [comment]
Could you try `rebase on dev`? I tried reading all the modified code locally, but it was difficult to `undo commit` due to too many commits. Thanks a lot.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/job/JobImmutableInformationEnv.java [hunk 2]
```diff
@@ -62,6 +71,20 @@ public Long getJobId() {
...
+        actions.addAll(immutablePair.getLeft());
+        jarUrls.addAll(commonPluginJars);
+        jarUrls.addAll(immutablePair.getRight());
+        actions.forEach(
+                action -> {
+                    addCommonPluginJarsToAction(
+                            action, new HashSet<>(commonPluginJars), Collections.emptySet());
+                });
+        return getLogicalDagGenerator().generate();
+    }
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/job/JobImmutableInformationEnv.java]: Compare with https://github.com/apache/seatunnel/pull/5542/files#diff-466c4277b9a67418eb669f75714d0b035ef17ad838977c5556dc58b3aa38e030L108-L113, seem like you add commPluginJars for all actions and jarUrls. Why do this change? Is there any problem before this PR?

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java [hunk 3]
```diff
@@ -64,6 +83,92 @@ protected MultipleTableJobConfigParser getJobConfigParser() {
...
+        ImmutablePair<List<Action>, Set<URL>> immutablePair = getJobConfigParser().parse();
+        actions.addAll(immutablePair.getLeft());
+        // Enable upload connector jar package to engine server, automatically upload connector Jar
+        // packages
+        // and dependent third-party Jar packages to the server before job execution.
+        // Enabling this configuration does not require the server to hold all connector Jar
+        // packages.
+        boolean enableUploadConnectorJarPackage =
+                seaTunnelConfig.getEngineConfig().getConnectorJarStorageConfig().getEnable();
+        if (enableUploadConnectorJarPackage == true) {
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java]:
```suggestion
        if (enableUploadConnectorJarPackage) {
```

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ConnectorPackageClient.java [hunk 4]
```diff
@@ -0,0 +1,149 @@
...
+        // Upload commonPluginJar
+        for (URL commonPluginJar : commonPluginJars) {
+            // handle the local file path
+            // origin path : /${SEATUNNEL_HOME}/plugins/Jdbc/lib/mysql-connector-java-5.1.32.jar ->
+            // handled path : ${SEATUNNEL_HOME}/plugins/Jdbc/lib/mysql-connector-java-5.1.32.jar
+            Path path = Paths.get(commonPluginJar.getPath().substring(1));
+            // Obtain the directory name of the relative location of the file path.
+            // for example, The path is
+            // ${SEATUNNEL_HOME}/plugins/Jdbc/lib/mysql-connector-java-5.1.32.jar, so the name
+            // obtained here is the connector plugin name : JDBC
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ConnectorPackageClient.java]: The logic not right. In fact, we don't must use plugin name like `Jdbc` to create directory. It could be any name, like `today`, `mysql` etc. Directory name doesn't have any relation with plugin name. The jar in `plugin/` should used for all connector. (PS: in Zeta engine, we mark `plugin` directory as deprecated. Refer: https://github.com/apache/seatunnel/blob/dev/plugins/README.md, user should put jar into `lib` on all node. I think in this situation, you should not care common jar). But we supported define common jar in job env. Refer https://seatunnel.apache.org/docs/2.3.3/concept/JobEnvConfig#jars

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java (hunk 1 above)
Comment (Hisoka-X) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java]: This feature can be done on server side. When client upload jar to server, server can do check for jar already existed or not. If existed, just skip save jar into server, finally return successed to client. So you don't need to send another check request, all be done in one request.

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java [hunk 5]
```diff
@@ -64,6 +83,92 @@ protected MultipleTableJobConfigParser getJobConfigParser() {
...
+                                action.getConfig();
+                    });
+        } else {
+            jarUrls.addAll(commonPluginJars);
+            jarUrls.addAll(immutablePair.getRight());
+            actions.forEach(
+                    action -> {
+                        addCommonPluginJarsToAction(
+                                action, new HashSet<>(commonPluginJars), Collections.emptySet());
+                    });
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java]: ditto

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java [hunk 6]
```diff
@@ -64,6 +83,92 @@ protected MultipleTableJobConfigParser getJobConfigParser() {
...
+                    ConnectorJarIdentifier connectorJarIdentifier =
+                            connectorPackageClient.uploadConnectorPluginJar(
+                                    Long.parseLong(jobConfig.getJobContext().getJobId()),
+                                    pluginJarUrl);
+                    pluginJarIdentifiers.add(connectorJarIdentifier);
+                });
+        return pluginJarIdentifiers;
+    }
+
+    private void transformActionPluginJarUrls(
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java]:
```suggestion
    private void uploadActionPluginJar(
```

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java [hunk 7]
```diff
@@ -64,6 +83,92 @@ protected MultipleTableJobConfigParser getJobConfigParser() {
...
+            actions.forEach(
+                    action -> {
+                        addCommonPluginJarsToAction(
+                                action, new HashSet<>(commonPluginJars), Collections.emptySet());
+                    });
+        }
+        return getLogicalDagGenerator().generate();
+    }
+
+    protected Set<ConnectorJarIdentifier> uploadPluginJarUrls(Set<URL> pluginJarUrls) {
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java]: You are doing upload jar, not upload jar url
```suggestion
    protected Set<ConnectorJarIdentifier> uploadPluginJar(Set<URL> pluginJarUrls) {
```

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/job/JobImmutableInformationEnv.java (hunk 2 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/job/JobImmutableInformationEnv.java]: In the previous parsing logic, we need to pass the local CommonPluginJar through method parameters to the MultiTableJobParser, in order to set the URLs of all current CommonPluginJars in the construction Action. But what we need to set is the path to the server that will be returned after uploading to the server. If the URLs of commonPlugin are set to Action in advance, it will cause the CommonPluginJarUrl in the Action to be indistinguishable from the JarUrl of the connector. we must upload CommonPluginJar and ConnectorPluginJar separately. Because the MultiTableJobParser is in the Core module, the upload process cannot be done simultaneously when building Actions. Instead, the logical relationship diagrams of all Actions can be constructed and the CommonPluginJar and ConnectorPluginJar can be uploaded recursively. So we need to first recurse each Action and upload the ConnectorPlugin, then set the storage path of the ConnectorPluginJar in the server to the Action. After all the ConnectorPluginJar paths in all upstream and downstream Action chains are replaced, add the path of CommonPluginJar on the server to each Action.

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ConnectorPackageClient.java (hunk 4 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ConnectorPackageClient.java]: May I ask if we can keep the function of uploading common jars to the Zeta engine？ When common jars do not exist in Zeta's `lib`, it can upload the local common jars of the client to the lib directory of all engine nodes. This way, even if the user does not place a jar on all nodes in Zeta's lib, the task can still be executed normally.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/job/JobImmutableInformationEnv.java (hunk 2 above)
Comment (Hisoka-X) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/job/JobImmutableInformationEnv.java]: I get your point.

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ConnectorPackageClient.java (hunk 4 above)
Comment (Hisoka-X) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ConnectorPackageClient.java]: > May I ask if we can keep the function of uploading common jars to the Zeta engine？

Yes, keep it. But marked as not recommend.

> When common jars do not exist in Zeta's lib, it can upload the local common jars of the client to the lib directory of all engine nodes.

Do not touch `lib` directory. This may cause exceptions after the server restarts. If user put jar in `plugin/`, just upload to `plugin/` in server.

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java (hunk 7 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java]: I have made the changes, PTAL!

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java (hunk 6 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java]: I have made the changes, PTAL!

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java (hunk 1 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java]: I understand your point and have implemented the the check of Jar package on the server side. PTAL!

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java (hunk 5 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/JobExecutionEnvironment.java]: I understand your point and have implemented the the check of Jar package on the server side. PTAL!

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ConnectorPackageServiceIT.java [hunk 8]
```diff
@@ -0,0 +1,148 @@
+/*
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ConnectorPackageServiceIT.java:1]: I find all test case running on same JVM instance. It can't prove the upload logic work fine. Please add some e2e test case with 1 client and 2 server, all runnning on different docker containers. You can refer `org.apache.seatunnel.e2e.common.container.seatunnel.SeaTunnelContainer`

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 9]
```diff
@@ -259,6 +259,20 @@ private void restoreJobFromMasterActiveSwitch(@NonNull Long jobId, @NonNull JobI
...
+        //        List<ConnectorJarIdentifier> pluginJarIdentifiers =
+        //                jobImmutableInformation.getPluginJarIdentifiers();
+        //        pluginJarIdentifiers.forEach(
+        //                pluginJarIdentifier -> {
+        //                    String storagePath = pluginJarIdentifier.getStoragePath();
+        //                    if (!new File(storagePath).exists()) {
+        //                        connectorPackageHAStorage.downloadConnectorJar(jobId,
+        // pluginJarIdentifier);
+        //                    }
+        //                });
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: Any reason？

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/SeaTunnelServer.java [hunk 10]
```diff
@@ -253,4 +257,63 @@ private void printExecutionInfo() {
...
+
+    public ConnectorPackageService getConnectorPackageService() {
+        int retryCount = 0;
+        if (isMasterNode()) {
+            // The hazelcast operator request invocation will retry, We must wait enough time to
+            // wait the invocation return.
+            String hazelcastInvocationMaxRetry =
+                    seaTunnelConfig
+                            .getHazelcastConfig()
+                            .getProperty("hazelcast.invocation.max.retry.count");
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/SeaTunnelServer.java]: Please use reference not hard code config. You can refer https://github.com/apache/seatunnel/pull/5618

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/SeaTunnelServer.java [hunk 11]
```diff
@@ -253,4 +257,63 @@ private void printExecutionInfo() {
...
+            int maxRetry =
+                    hazelcastInvocationMaxRetry == null
+                            ? 250 * 2
+                            : Integer.parseInt(hazelcastInvocationMaxRetry) * 2;
+
+            String hazelcastRetryPause =
+                    seaTunnelConfig
+                            .getHazelcastConfig()
+                            .getProperty("hazelcast.invocation.retry.pause.millis");
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/SeaTunnelServer.java]: ditto

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/SeaTunnelServer.java [hunk 12]
```diff
@@ -253,4 +257,63 @@ private void printExecutionInfo() {
...
+
+    public SeaTunnelConfig getSeaTunnelConfig() {
+        return seaTunnelConfig;
+    }
+
+    public NodeEngineImpl getNodeEngine() {
+        return nodeEngine;
+    }
+
+    public ConnectorPackageService getConnectorPackageService() {
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/SeaTunnelServer.java:266]: Why not put it into `CoordinatorService` since connectorPackageService only work on master node.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/TaskExecutionService.java [hunk 13]
```diff
@@ -252,9 +259,25 @@ public TaskDeployState deployTask(@NonNull TaskGroupImmutableInformation taskImm
...
         try {
+            Set<ConnectorJarIdentifier> connectorJarIdentifiers =
+                    taskImmutableInfo.getConnectorJarIdentifiers();
             Set<URL> jars = taskImmutableInfo.getJars();
             ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
-            if (!CollectionUtils.isEmpty(jars)) {
+            if (!CollectionUtils.isEmpty(connectorJarIdentifiers)) {
+                // Prioritize obtaining the jar package file required for the current task execution
+                // from the local,
+                // if it does not exist locally, it will be downloaded from the master node.
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/TaskExecutionService.java]:
```suggestion
                // Prioritize obtaining the jar package file required for the current task execution
                // from the local, if it does not exist locally, it will be downloaded from the master node.
```

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/task/TaskGroupImmutableInformation.java [hunk 14]
```diff
@@ -40,6 +41,8 @@ public class TaskGroupImmutableInformation implements IdentifiedDataSerializable
 
     private Set<URL> jars;
 
+    private Set<ConnectorJarIdentifier> connectorJarIdentifiers;
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/task/TaskGroupImmutableInformation.java]: Why we need maintain two different jars collection? It looks bad.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalVertex.java [hunk 15]
```diff
@@ -113,6 +116,7 @@ public PhysicalVertex(
             int pipelineId,
             int totalPipelineNum,
             Set<URL> pluginJarsUrls,
+            Set<ConnectorJarIdentifier> connectorJarIdentifiers,
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalVertex.java:133]: ditto

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ConnectorPackageClient.java (hunk 4 above)
Comment (Hisoka-X) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ConnectorPackageClient.java]: So. You still don't fix this problem.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/AbstractConnectorJarStorageStrategy.java [hunk 16]
```diff
@@ -0,0 +1,182 @@
...
+        return file;
+    }
+
+    @Override
+    public ConnectorJarIdentifier getConnectorJarIdentifier(long jobId, ConnectorJar connectorJar) {
+        return ConnectorJarIdentifier.of(connectorJar, getStorageLocationPath(jobId, connectorJar));
+    }
+
+    @Override
+    public Path storageConnectorJarFileInternal(ConnectorJar connectorJar, File storageFile) {
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/AbstractConnectorJarStorageStrategy.java]: Please use `Optional<Path>` as return cause you may return null.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/RestHttpPostCommandProcessor.java [hunk 17]
```diff
@@ -96,6 +96,7 @@ private void handleSubmitJob(HttpPostCommand httpPostCommand, String uri)
         Config config = RestUtil.buildConfig(requestHandle(httpPostCommand));
         JobConfig jobConfig = new JobConfig();
         jobConfig.setName(requestParams.get(RestConstant.JOB_NAME));
+        CoordinatorService coordinatorService = getSeaTunnelServer().getCoordinatorService();
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/RestHttpPostCommandProcessor.java]: Any reason for move this?

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/ConnectorPackageServiceTest.java [hunk 18]
```diff
@@ -0,0 +1,406 @@
...
+
+        SeaTunnelServer server1 =
+                instance1.node.getNodeEngine().getService(SeaTunnelServer.SERVICE_NAME);
+        SeaTunnelServer server2 =
+                instance2.node.getNodeEngine().getService(SeaTunnelServer.SERVICE_NAME);
+
+        Assertions.assertTrue(server1.isMasterNode());
+        ConnectorPackageService connectorPackageService1 = server1.getConnectorPackageService();
+        Assertions.assertTrue(connectorPackageService1.isConnectorPackageServiceActive());
+
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/ConnectorPackageServiceTest.java]: So, even disable upload jar feature, the connectorPackageService instance will be created? I think we create it only when this feature enabled.

**Comment by Hisoka-X** [comment]
@TyrantLucifer I think you should take a look too.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/task/TaskGroupImmutableInformation.java (hunk 14 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/task/TaskGroupImmutableInformation.java]: ConnectorJarIdentifiers represent the unique identifier of a Jar package file, which contains more information about the Jar package file, including the name of the connector plugin using the current Jar, the type of the current Jar package, and so on. If we use the Identifier to obtain Jar packages or distributed file systems (functions that have not yet been implemented) from the master node, it will be much more convenient because the root directory of Jar packages stored on the distributed file system can be configured by the user. We can generate a storage path on the distributed file system based on user user-configured root directory, Jar package names, Jar package types, and other information, achieving more flexible storage. If we want the Jar package storage path on the distributed file system to be completely consistent with the local path, then I can remove it.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/SeaTunnelServer.java (hunk 12 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/SeaTunnelServer.java:266]: Because in the previous incorrect design, during the initialization of the ConnectorPackageService, the CoordinaterService would be obtained first, and at this time, the CoordinaterService has not yet completed the initialization process. My design here is incorrect. Thank you very much for your reminder. I will put the ConnectorPackageService into the CoordinatorService.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/RestHttpPostCommandProcessor.java (hunk 17 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/RestHttpPostCommandProcessor.java]: Sorry, there is no need to move, there is no problem here.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java (hunk 9 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: I will remove this useless annotation.

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ConnectorPackageClient.java (hunk 4 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ConnectorPackageClient.java]: I'm very sorry, I don't quite understand your previous description. I have made modifications to this part of the code. Could you please help me see if this logic is right? If not, I will make the necessary modifications.

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ConnectorPackageServiceIT.java (hunk 8 above)
Comment (lianghuan-xatu) [reply seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ConnectorPackageServiceIT.java:1]: I have added an e2e test created a Seatunnel Zeta Cluster through three Docker instances, and conducted relevant testing.PTAL， thx！

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/ConnectorPackageServiceTest.java (hunk 18 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/ConnectorPackageServiceTest.java]: Thank you very much for raising this problem. The master node will only create the connector package service when the configuration of the connector package service is enabled. I have fixed the related issue.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/task/TaskGroupImmutableInformation.java (hunk 14 above)
Comment (Hisoka-X) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/task/TaskGroupImmutableInformation.java]: cc @hailin0 @EricJoy2048 WDYT?

File: docs/en/seatunnel-engine/optimize-job-submission.md [hunk 19]
```diff
@@ -0,0 +1,101 @@
+---
```
Comment (Hisoka-X) [inline docs/en/seatunnel-engine/optimize-job-submission.md]: This doc more like design, not face to user. Please move it to the issue related to this PR.

File: seatunnel-e2e/seatunnel-e2e-common/src/test/java/org/apache/seatunnel/e2e/common/container/seatunnel/ConnectorPackageServiceContainer.java [hunk 20]
```diff
@@ -0,0 +1,216 @@
...
+/**
+ * This class is the base class of SeatunnelEnvironment test for connector package service. The
+ * before method will create a Seatunnel Zeta cluster with connector package service enabled, and
+ * after method will close the Seatunnel Zeta cluster. You can use {@link
+ * ConnectorPackageServiceContainer#executeJob} to submit a seatunnel config and run a seatunnel
+ * job.
+ */
+@NoArgsConstructor
+@Slf4j
+public class ConnectorPackageServiceContainer extends AbstractTestContainer {
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-e2e-common/src/test/java/org/apache/seatunnel/e2e/common/container/seatunnel/ConnectorPackageServiceContainer.java:54]: Let us add `TestContainer` SPI to enable test on all exist test case.
```suggestion
@AutoService(TestContainer.class)
public class ConnectorPackageServiceContainer extends AbstractTestContainer {
```

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/task/TaskGroupImmutableInformation.java (hunk 14 above)
Comment (Hisoka-X) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/task/TaskGroupImmutableInformation.java]: I think we should add some comment in code to tell other developers whats difference between two jars collection. And what's reason why we should use two jars collection. PS: I think we should just use `ConnectorJarIdentifier` for all jars collection would be better.

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ClientJobExecutionEnvironment.java [hunk 21]
```diff
@@ -64,6 +83,81 @@ protected MultipleTableJobConfigParser getJobConfigParser() {
...
+            actions.forEach(
+                    action -> {
+                        addCommonPluginJarsToAction(
+                                action, commonPluginJarUrls, commonJarIdentifiers);
+                    });
+            actions.forEach(
+                    action -> {
+                        org.apache.seatunnel.engine.core.dag.actions.Config config =
+                                action.getConfig();
+                    });
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ClientJobExecutionEnvironment.java]: Is this part right?

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ClientJobExecutionEnvironment.java [hunk 22]
```diff
@@ -64,6 +83,81 @@ protected MultipleTableJobConfigParser getJobConfigParser() {
...
 
+    @Override
+    protected LogicalDag getLogicalDag() {
+        ImmutablePair<List<Action>, Set<URL>> immutablePair = getJobConfigParser().parse();
+        actions.addAll(immutablePair.getLeft());
+        // Enable upload connector jar package to engine server, automatically upload connector Jar
+        // packages
+        // and dependent third-party Jar packages to the server before job execution.
+        // Enabling this configuration does not require the server to hold all connector Jar
+        // packages.
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ClientJobExecutionEnvironment.java]:
```suggestion
        // Enable upload connector jar package to engine server, automatically upload connector Jar
        // packages and dependent third-party Jar packages to the server before job execution.
        // Enabling this configuration does not require the server to hold all connector Jar packages.
```

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ClientJobExecutionEnvironment.java (hunk 21 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ClientJobExecutionEnvironment.java]: This is useless code left over from previous versions of seatunnel and can be removed.

File: docs/en/seatunnel-engine/optimize-job-submission.md (hunk 19 above)
Comment (lianghuan-xatu) [reply docs/en/seatunnel-engine/optimize-job-submission.md]: Done, PTAL!

File: seatunnel-e2e/seatunnel-e2e-common/src/test/java/org/apache/seatunnel/e2e/common/container/seatunnel/ConnectorPackageServiceContainer.java (hunk 20 above)
Comment (lianghuan-xatu) [reply seatunnel-e2e/seatunnel-e2e-common/src/test/java/org/apache/seatunnel/e2e/common/container/seatunnel/ConnectorPackageServiceContainer.java:54]: Done, PTAL!

File: seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ClientJobExecutionEnvironment.java (hunk 22 above)
Comment (lianghuan-xatu) [reply seatunnel-engine/seatunnel-engine-client/src/main/java/org/apache/seatunnel/engine/client/job/ClientJobExecutionEnvironment.java]: I have fixed it, PTAL!

**Review by Hisoka-X — APPROVED** [review]

**Review by TyrantLucifer — APPROVED** [review]
