### PR TITLE
[Bugfix][TDengine] Fix the degree of multiple parallelism affects driver loading

### LINKED ISSUE #6019: [Bug] [TDengine] The degree of multiple parallelism affects driver loading, and thus the connection can't be obtained correctly
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I run the e2e test of TDengine. I found that when the parallelism degree is greater than 1, the `TDengineSinkWriter` cannot get the connection correctly during initialization. I analyzed the problem and came to the following conclusion:

First of all, only this one task is running in Server. DriverManager will be loaded by the Jvm when it is used for the first time, and then the `loadInitialDrivers` method in the static code block will be executed to load the driver. However, at this time, our task is multi-parallel.  When the first thread attempts to load the driver, the other threads will directly fetch the connection, but if the first thread has not yet loaded, the other threads will directly throw an exception.

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  parallelism = 2
  job.mode = "BATCH"
}

source {
  TDengine {
    url: "jdbc:TAOS-RS://flink_e2e_tdengine_src:6041/"
    username: "root"
    password: "taosdata"
    database: "power"
    stable: "meters"
    lower_bound: "2018-10-03 14:38:05.000"
    upper_bound: "2018-10-03 14:38:16.801"
    result_table_name = "tdengine_result"
  }
}

transform {
}

sink {
  TDengine {
    url: "jdbc:TAOS-RS://flink_e2e_tdengine_sink:6041/"
    username: "root"
    password: "taosdata"
    database: "power2"
    stable: "meters2"
    timezone: "UTC"
  }
}
```

### Running Command

```shell
no command, this is runs in e2e case.
```

### Error Exception

```log
Caused by: org.apache.seatunnel.common.utils.SeaTunnelException: java.sql.SQLException: No suitable driver found for jdbc:TAOS-RS://flink_e2e_tdengine_sink:6041/power2?user=root&***
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by happyboy1024**
### Purpose of this pull request

Fix the degree of multiple parallelism affects driver loading, and thus the connection can't be obtained correctly. close #6019

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-connectors-v2/connector-tdengine/src/main/java/org/apache/seatunnel/connectors/seatunnel/tdengine/utils/TDengineUtil.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+import lombok.extern.slf4j.Slf4j;
+
+import java.sql.Driver;
+import java.sql.DriverManager;
+import java.sql.SQLException;
+
+@Slf4j
+public class TDengineUtil {
+
+    public static void checkDriverExist(String jdbcUrl) {
```
Comment (hailin0) [inline seatunnel-connectors-v2/connector-tdengine/src/main/java/org/apache/seatunnel/connectors/seatunnel/tdengine/utils/TDengineUtil.java]:
```suggestion
    public synchronized static void registerJdbcDriver(String jdbcUrl) {
```

Comment (happyboy1024) [reply seatunnel-connectors-v2/connector-tdengine/src/main/java/org/apache/seatunnel/connectors/seatunnel/tdengine/utils/TDengineUtil.java]: > 

have been modified

**Review by hailin0 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]
