### PR TITLE
[Fix][Zeta] Fix NPE when querying pending job info

### LINKED ISSUE #10455: [Bug] [Seatunnel] GetJobInfoOperation gives null pointer exception
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

For the pending jobs, when i click the job link and  it shows "java.util.concurrent.ExecutionException: 

Image

`    public JobDAGInfo getJobInfo(long jobId) {
        JobDAGInfo jobInfo = jobHistoryService.getJobDAGInfo(jobId);
        if (jobInfo != null) {
            return jobInfo;
        }
        return runningJobMasterMap.get(jobId).getJobDAGInfo();
    }
`
### SeaTunnel Version

2.3.9

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
none
```

### Error Exception

```log
7:06,689 ERROR [.a.s.e.s.o.GetJobInfoOperation] [hz.main.client.thread-2] - [localhost]:5801 [seatunnel] [5.1] java.util.concurrent.ExecutionException: java.lang.NullPointerException
org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.apache.seatunnel.engine.server.operation.GetJobInfoOperation.run(GetJobInfoOperation.java:63) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:601) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:580) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.task.AbstractInvocationMessageTask.processInternal(AbstractInvocationMessageTask.java:38) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.task.AbstractAsyncMessageTask.processMessage(AbstractAsyncMessageTask.java:71) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_192-ea]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_192-ea]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192-ea]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_192-ea]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_192-ea]
	at org.apache.seatunnel.engine.common.utils.concurrent.CompletableFuture.get(CompletableFuture.java:147) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at org.apache.seatunnel.engine.server.operation.GetJobInfoOperation.run(GetJobInfoOperation.java:61) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	... 20 more
Caused by: java.lang.NullPointerException
	at org.apache.seatunnel.engine.server.CoordinatorService.getJobInfo(CoordinatorService.java:914) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at org.apache.seatunnel.engine.server.operation.GetJobInfoOperation.lambda$run$0(GetJobInfoOperation.java:55) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_192-ea]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[seatunnel-starter.jar:2.3.10-SNAPSHOT]
	... 5 more
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

java.lang.NullPointerException"
Image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by dybyte**
Fixes: https://github.com/apache/seatunnel/issues/10455
### Purpose of this pull request

This PR fixes an issue where `pending` state job information could not be retrieved correctly.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Added `CoordinatorServiceTest.testGetPendingJobInfo()`.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If necessary, please update `incompatible-changes.md` to describe the incompatibility caused by this PR.
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

**Comment by DanielCarter-stack** [comment]
#### Issue 1: Missing edge case tests

**Location**: `CoordinatorServiceTest.java:341-358`

**Problem Description**:
The newly added test `testGetPendingJobInfo()` only covers the scenario where "the job is in the pending queue". It lacks tests for "throwing JobNotFoundException when the job does not exist". Although this is an enhancement to existing code, the new exception behavior should be verified.

**Potential Risks**:
- Future code refactoring may accidentally break the exception logic
- Unable to verify through tests whether the error message for `JobNotFoundException` is correct

**Impact Scope**:
- Direct impact: `CoordinatorServiceTest` test suite
- Indirect impact: Confidence during code refactoring
- Affected area: Core engine service layer

**Severity**: MINOR

**Improvement Suggestion**:
```java
@Test
void testGetJobInfoNotFound() {
    CoordinatorService coordinatorService = getCoordinatorService();
    long nonExistentJobId = 999999L;
    
    JobNotFoundException exception = Assertions.assertThrows(
        JobNotFoundException.class,
        () -> coordinatorService.getJobInfo(nonExistentJobId)
    );
    
    Assertions.assertTrue(exception.getMessage().contains("999999"));
}
```

**Rationale**: 
- Complete test coverage should include all branches
- Testing exception messages helps ensure error message debuggability
- Low cost, only requires adding a simple test method

---

#### Issue 2: Missing method documentation comments

**Location**: `CoordinatorService.java:867`

**Problem Description**:
The `getJobInfo()` method lacks JavaDoc comments, making it unclear what order this method queries job information and what exceptions it might throw.

**Potential Risks**:
- New developers may not understand why three places need to be queried
- May be unclear under what circumstances `JobNotFoundException` is thrown
- IDE cannot provide accurate parameter and return value descriptions

**Impact Scope**:
- Direct impact: Maintainability of `CoordinatorService`
- Indirect impact: Callers' understanding of the method
- Affected area: Core engine service layer

**Severity**: MINOR

**Improvement Suggestion**:
```java
/**
 * Get job information by job ID.
 * 
 * <p>This method searches for job information in the following order:
 * <ol>
 *   <li>Job history service (for finished jobs)</li>
 *   <li>Running job master map (for currently running jobs)</li>
 *   <li>Pending job queue (for jobs waiting for resources)</li>
 * </ol>
 *
 * @param jobId the job ID to query
 * @return the job DAG information
 * @throws JobNotFoundException if the job is not found in any of the three locations
 */
public JobDAGInfo getJobInfo(long jobId) {
    // ... implementation
}
```

**Rationale**:
- Clear documentation helps team collaboration
- Explains the query order for better logic understanding
- Clarifies exception behavior, consistent with Java best practices

---

#### Issue 3: Missing debug logs

**Location**: `CoordinatorService.java:883`

**Problem Description**:
When a job does not exist, an exception is thrown directly without logging. In production environments, if this error occurs frequently, the cause cannot be traced.

**Potential Risks**:
- Unable to track the frequency of "job not found" events
- Lack of contextual information when debugging user issues
- Unable to monitor exception occurrence rates

**Impact Scope**:
- Direct impact: Production environment observability
- Indirect impact: Problem diagnosis efficiency
- Affected area: Production operations

**Severity**: MINOR

**Improvement Suggestion**:
```java
PendingJobInfo pendingJobInfo = pendingJobQueue.getById(jobId);
if (pendingJobInfo != null) {
    return pendingJobInfo.getJobMaster().getJobDAGInfo();
}

logger.debug(String.format("Job %s not found in history, running, or pending queue", jobId));
throw new JobNotFoundException(String.format("Job %s not found", jobId));
```

**Rationale**:
- Debug level logging does not affect performance
- Facilitates problem tracking in production environments
- Consistent with logging style elsewhere in the project

---

#### Issue 4: Query order inconsistency with getJobMaster()

**Location**: 
- `CoordinatorService.java:392-398` (getJobMaster)
- `CoordinatorService.java:867-884` (getJobInfo)

**Problem Description**:
`getJobMaster()` queries `pendingJobQueue` first, then `runningJobMasterMap`; whereas `getJobInfo()` queries `runningJobMasterMap` first, then `pendingJobQueue`. Although this difference is reasonable under their respective semantics, it may cause confusion.

**Potential Risks**:
- Developers may mistakenly assume the query logic of both methods is consistent
- Future refactoring may inappropriately unify the logic, breaking existing behavior

**Impact Scope**:
- Direct impact: Code maintainability
- Indirect impact: Safety of future refactoring
- Affected area: Core engine service layer

**Severity**: MINOR

**Improvement Suggestion**:
In the comments for `getJobMaster()` and `getJobInfo()`, explicitly explain the different reasons for query order:

```java
/**
 * Get the JobMaster for a job.
 * 
 * <p>This method searches in the following order:
 * <ol>
 *   <li>Pending job queue (for jobs waiting for resources)</li>
 *   <li>Running job master map (for currently running jobs)</li>
 * </ol>
 * 
 * <p>Note: The search order prioritizes pending jobs because this method is typically
 * used to obtain a JobMaster for job control operations, where pending jobs should
 * be handled first.
 */
public JobMaster getJobMaster(Long jobId) {
    // ...
}

/**
 * Get job information by job ID.
 * 
 * <p>This method searches in the following order:
 * <ol>
 *   <li>Job history service (for finished jobs)</li>
 *   <li>Running job master map (for currently running jobs)</li>
 *   <li>Pending job queue (for jobs waiting for resources)</li>
 * </ol>
 * 
 * <p>Note: The search order follows the job lifecycle (finished → running → pending)
 * to prioritize the most recent state for information queries.
 */
public JobDAGInfo getJobInfo(long jobId) {
    // ...
}
```

**Rationale**:
- Explicitly explain design decisions to avoid future misunderstanding
- Explains why the query order differs between the two methods
- Improves code maintainability

---

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/CoordinatorServiceTest.java [hunk 1]
```diff
@@ -336,6 +337,26 @@ void testCleanupPendingJobMasterMapWhenJobSubmitFutureIsExceptionally() {
...
+        JobInformation jobInformation =
+                submitJob(
+                        "CoordinatorServiceTest_testGetPendingJobInfo",
+                        "batch_fake_to_console.conf",
+                        "test_get_pending_job_info");
+
+        CoordinatorService coordinatorService = jobInformation.coordinatorService;
+        Long jobId = jobInformation.jobId;
+
+        Assertions.assertTrue(coordinatorService.getPendingJobQueue().contains(jobId));
```
Comment (xiaochen-zhou) [inline seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/CoordinatorServiceTest.java:351]: We should simulate a task being pending by setting a fixed slot mode. You can refer to the implementation of the `CoordinatorServiceTest#testCleanupPendingJobMasterMapAfterJobFailed()`

**Review by zhangshenghang — APPROVED** [review]
LGTM

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/CoordinatorServiceTest.java (hunk 1 above)
Comment (corgy-w) [reply seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/CoordinatorServiceTest.java:351]: It seems that this test can now verify this fix.

**Review by corgy-w — APPROVED** [review]

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/CoordinatorServiceTest.java (hunk 1 above)
Comment (dybyte) [reply seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/CoordinatorServiceTest.java:351]: > It seems that this test can now verify this fix.

Yes. I think this test can also simulate the pending state and verify the fix properly.
