### PR TITLE
[Bug][Connector-V2][File] Fix IndexOutOfBoundsException when reading empty directories

### LINKED ISSUE #10369: [Bug] [Connecotor-File] TextReadStrategy got IndexOutOfBoundsException when file list is empty
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

https://github.com/apache/seatunnel/blob/dev/seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/source/reader/TextReadStrategy.java#L273

When fileNames is empty, call fileNames.get(0) will got exception

# What's I expect

when read empty director, the job can run normal with zero reocrd.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
n/a
```

### Running Command

```shell
n/a
```

### Error Exception

```log
IndexOutOfBoundsException
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yzeng1618**
### Purpose of this pull request
Fix #10369. When the source path resolves to an empty file list (empty directory or all files filtered out), some ReadStrategy implementations call fileNames.get(0) during schema/partition inference and throw IndexOutOfBoundsException. This PR makes partition inference resilient by avoiding direct access to fileNames.get(0) and falling back to a safe inference path, so jobs can run normally with zero records.

### Does this PR introduce _any_ user-facing change?
Yes. Previously, reading an empty directory (or a directory whose files were all filtered out) could fail at initialization with IndexOutOfBoundsException. After this change, the job starts successfully and produces zero records (schema remains valid; partition columns are appended only when a partition path is available).

### How was this patch tested?

1. Added unit test to cover empty fileNames + schema initialization path: EmptyFileListReadStrategyTest.java (line 39)
2. Added an E2E case to cover the real trigger path 

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If necessary, please update `incompatible-changes.md` to describe the incompatibility caused by this PR.
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  4. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  5. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  6. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

**Review by dybyte — APPROVED** [review]

File: seatunnel-connectors-v2/connector-file/connector-file-base/src/test/java/org/apache/seatunnel/connectors/seatunnel/file/source/reader/EmptyFileListReadStrategyTest.java [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+import org.apache.seatunnel.connectors.seatunnel.file.config.FileBaseSourceOptions;
+
+import org.junit.jupiter.api.Assertions;
+import org.junit.jupiter.api.Test;
+
+import java.util.HashMap;
+import java.util.Map;
+
+public class EmptyFileListReadStrategyTest {
+
```
Comment (corgy-w) [inline seatunnel-connectors-v2/connector-file/connector-file-base/src/test/java/org/apache/seatunnel/connectors/seatunnel/file/source/reader/EmptyFileListReadStrategyTest.java]: `EmptyFileListReadStrategyTest` testing recommendations on here `AbstractReadStrategyTest`

Comment (yzeng1618) [reply seatunnel-connectors-v2/connector-file/connector-file-base/src/test/java/org/apache/seatunnel/connectors/seatunnel/file/source/reader/EmptyFileListReadStrategyTest.java]: OK, I will add the relevant unit tests to AbstractReadStrategyTest.

**Review by corgy-w — APPROVED** [review]
LGTM

**Review by Carl-Zhou-CN — APPROVED** [review]
LGTM
