### PR TITLE
[Hotfix][Zeta] Fix taskgroup failed log lost

### LINKED ISSUE #7239: [Bug] [Zeta] TaskGroup Failed MSG lost when job restore time more than one
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

If the Pipeline fails and the restore is successful, the next time the task fails, the fault cause of the task is the same as that of the first failed task, and the latest failure cause is lost.

### SeaTunnel Version

2.3.5
dev

### SeaTunnel Config

```conf
*
```

### Running Command

```shell
*
```

### Error Exception

```log
2024-07-17 10:27:43,088 ERROR [o.a.s.e.s.d.p.PhysicalVertex  ] [hz.main.generic-operation.thread-2] - Job 实时.ods_hzy_pos_cxj (841136001937047570), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-MySQL-CDC]-SourceTask (1/2)] end with state FAILED and Exception: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.seatunnel.connectors.doris.exception.DorisConnectorException: ErrorCode:[Doris-01], ErrorDescription:[stream load error] - stream load error: [INTERNAL_ERROR]cancelled: [INTERNAL_ERROR]cancelled: Process has no memory available, cancel top memory used load: load memory tracker <Load#Id=e341448d2b6ec8b9-a059d67d96356bb8> consumption 31.19 MB, backend 10.3.215.114 process memory used 228.96 GB exceed limit 222.98 GB or sys available memory 15.46 GB less than low water mark 1.60 GB. Execute again after enough memory, details see be.INFO.
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EricJoy2048**
### Purpose of this pull request

1. closes https://github.com/apache/seatunnel/issues/7239

2. make failed when taskgroup state is `deploying` at master node switch restore.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalVertex.java [hunk 1]
```diff
@@ -214,7 +214,7 @@ public PassiveCompletableFuture<TaskExecutionState> initStateFuture() {
             }
         } else if (ExecutionState.DEPLOYING.equals(currExecutionState)) {
             if (!checkTaskGroupIsExecuting(taskGroupLocation)) {
-                updateTaskState(ExecutionState.RUNNING);
+                updateTaskState(ExecutionState.FAILING);
```
Comment (hailin0) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalVertex.java:217]: cc @Hisoka-X

**Comment by Hisoka-X** [comment]
shall we add test case?

**Comment by EricJoy2048** [comment]
> shall we add test case?

Test cases are not easy to simulate

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalVertex.java [hunk 2]
```diff
@@ -485,6 +485,8 @@ private void resetExecutionState() {
                         () -> {
                             updateStateTimestamps(ExecutionState.CREATED);
                             runningJobStateIMap.set(taskGroupLocation, ExecutionState.CREATED);
+                            // reset the errorByPhysicalVertex
+                            errorByPhysicalVertex = new AtomicReference<>();
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalVertex.java:489]: https://github.com/apache/seatunnel/blob/4b3af9bef4e1753838a7750e86bde71bae8562ae/seatunnel-e2e/seatunnel-e2e-common/src/test/java/org/apache/seatunnel/e2e/sink/inmemory/InMemorySinkWriter.java#L80 `InMemorySinkWriter` is a good choice because it can construct different error messages each time, so you can check the error messages to see if the changes are effective.

Comment (Hisoka-X) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalVertex.java:489]: Use static variables to record the current number of retries

Comment (EricJoy2048) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalVertex.java:489]: Ok, I will try it.

Comment (EricJoy2048) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalVertex.java:489]: done

**Review by hailin0 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]
