### PR TITLE
[Hotfix][CDC] Fix split schema change stream

### LINKED ISSUE #7000: [Bug] [CDC] Loss  last batch data in splitSchemaChangeStream
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When a Schema change occurs, the last batch of data after the last Schema change is lost。I use this pr test #6929 

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
mysqlcdc_to_mysql_with_schema_change.conf
```

### Running Command

```shell
org.apache.seatunnel.connectors.seatunnel.cdc.mysql.MysqlCDCWithSchemaChangeIT#testMysqlCdcWithSchemaEvolutionCase
```

### Error Exception

```log
loss data
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by hailin0**
### Purpose of this pull request

close https://github.com/apache/seatunnel/issues/7000
[CDC] Fix split schema change stream

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
added

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by hailin0** [comment]
link https://github.com/apache/seatunnel/pull/6929

File: seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/external/IncrementalSourceStreamFetcher.java [hunk 1]
```diff
@@ -349,4 +287,99 @@ private void configureFilter() {
         this.maxSplitHighWatermarkMap = tableIdBinlogPositionMap;
         this.pureBinlogPhaseTables.clear();
     }
+
+    class SchemaChangeStreamSplitter {
+        private List<SourceRecords> blockSet;
+        private List<SourceRecord> currentBlock;
+        private SourceRecord previousRecord;
+
+        void reset() {
```
Comment (dailai) [inline seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/external/IncrementalSourceStreamFetcher.java]: Here use the method of reset is a bit odd, because every time is newed a new SchemaChangeStreamSplitter instance of a batch of data processing.

A choice between two suggestions:

Suggested 1: Keep reset method, don't need new  a SchemaChangeStreamSplitter instance every time, sharing the same class instance.

Suggested 2: Change the reset method to a constructor.

File: seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/external/IncrementalSourceStreamFetcher.java [hunk 2]
```diff
@@ -349,4 +287,99 @@ private void configureFilter() {
...
+            }
+
+            return blockSet.iterator();
+        }
+
+        void flipBlock() {
+            if (currentBlock != null && !currentBlock.isEmpty()) {
+                blockSet.add(new SourceRecords(currentBlock));
+            }
+            currentBlock = new ArrayList<>();
```
Comment (dailai) [inline seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/external/IncrementalSourceStreamFetcher.java]: Here, a new ArrayList is created each time whether currentBlock is empty or not, so if currentBlock is empty, don't you need to create a new one.

**Review by dailai — APPROVED** [review]
LGTM

File: seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/external/IncrementalSourceStreamFetcher.java (hunk 1 above)
Comment (hailin0) [reply seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/external/IncrementalSourceStreamFetcher.java]: fixed

File: seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/external/IncrementalSourceStreamFetcher.java (hunk 2 above)
Comment (hailin0) [reply seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/external/IncrementalSourceStreamFetcher.java]: fixed

**Review by Hisoka-X — APPROVED** [review]

**Review by wuchunfu — APPROVED** [review]
