### PR TITLE
[Fix][Zeta] Prevent terminal-state zombie jobs from being restored after master switch

### LINKED ISSUE #10675: [Bug][Zeta] Job appears RUNNING in UI with no checkpointing — next master switch restores from stale checkpoint
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened
                      
A CDC job was running normally with checkpoints completing at regular intervals. At some point during a rolling restart, checkpoint completion logs stopped entirely. From that point onward, the coordinator logs only showed `MessageDelayedEvent` entries — records being streamed from the source — but no `pending checkpoint notify finished` or `start notify checkpoint completed` entries appeared at all.
                                                                                                                                                                        
Despite this, the job showed as **RUNNING** in both the REST API (`/running-jobs`) and the UI. Data was continuing to flow to the sink. There was no error, no indication anything was wrong.      

This continued for several days across multiple coordinator restarts. Each time a new master came up, the job appeared in the running jobs list with RUNNING status.No checkpoint was ever written to S3 after the initial failure point.

  During the next rolling restart:
  - The new master called `restoreAllRunningJobFromMasterNodeSwitch()`
  - Found the jobId in `runningJobInfoIMap`
  - Read the last checkpoint from S3 — which pointed to a binlog file from the original failure, now purged from MySQL
  - Job failed immediately with:

  IllegalStateException: The connector is trying to read binlog starting at
  file=mysql-bin-changelog.XXXXXX, pos=XXXXXXX
  but this is no longer available on the server.
  Reconfigure the connector to use a snapshot when needed.

### Anticipated root cause

When a job fails and the coordinator starts `cleanJob()`, the sequence is:

  1. Coordinator writes terminal state (`FAILED`) to `runningJobStateIMap`
  2. `cleanJob()` is triggered → eventually calls `removeJobIMap()` which removes the jobId from `runningJobInfoIMap`

  If the coordinator pod is killed (OOM, rolling restart, eviction) **between step 1 and step 2**, the jobId remains as a zombie in `runningJobInfoIMap` with `FAILED`
  state in `runningJobStateIMap`.

On the next master switch, `restoreJobFromMasterActiveSwitch()` does:

  ```java
  Object jobState = runningJobStateIMap.get(jobId);
  if (jobState == null) {
      runningJobInfoIMap.remove(jobId);
      return;
  }
  // proceeds to restore — no terminal state check

Since FAILED != null, it proceeds to restore the job. A new JobMaster is created, the job appears as RUNNING in the API and UI, but the underlying checkpoint coordinator may immediately fail again (same root cause), leaving the job in a state where:
  - Worker tasks run without an active checkpoint coordinator
  - No checkpoint barriers are injected
  - No checkpoints are written to S3
  - The job shows RUNNING in the UI indefinitely

The last written checkpoint on S3 remains frozen at the pre-failure position. On any subsequent master switch or rollout, this stale checkpoint is used for restoration, leading to the binlog-purged error above.

  ```
Fix : 

```
In CoordinatorService.restoreJobFromMasterActiveSwitch(), add a terminal state check after the existing null check:

  if (jobState == null) {
      runningJobInfoIMap.remove(jobId);
      return;                                                                                                                                                           
  }
                                                                                                                                                                        
  // NEW: do not restore jobs already in terminal state                                                                                                               
  // coordinator was killed before cleanJob() could remove them from IMap
  if (jobState instanceof JobStatus && ((JobStatus) jobState).isEndState()) {
      logger.warning(String.format(
          "Job %s is in terminal state %s, skipping restore and cleaning up IMap",
          jobId, jobState));
      runningJobInfoIMap.remove(jobId);
      return;
  }


```

This covers FAILED, CANCELED, FINISHED, SAVEPOINT_DONE, UNKNOWABLE.

Additional observation — missing UI visibility

There is currently no way in the SeaTunnel UI or REST API to see when the last checkpoint completed for a running job (e.g. "last checkpointed 30s ago"). This makes it impossible to detect the silent no-checkpoint scenario described above — the job appears healthy with RUNNING status while checkpointing has completely stopped.

A lastCheckpointTime or secondsSinceLastCheckpoint field exposed via /running-jobs or the UI would allow operators to immediately isolate jobs where checkpointing has silently stopped, rather than discovering the problem only at the next rollout when the stale checkpoint causes a restoration failure.

### SeaTunnel Version

**SeaTunnel version:** 2.3.12 (Zeta engine)
**Environment:** Kubernetes, S3 checkpoint `storage`

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ricky2129**
Fixes: https://github.com/apache/seatunnel/issues/10675

During coordinator failover, if the coordinator pod was killed after writing a terminal state (FAILED/CANCELED/FINISHED) to runningJobStateIMap but before removeJobIMap() executed, the job's entry remains in runningJobInfoIMap with a terminal state. On the next master switch, restoreJobFromMasterActiveSwitch() only checked for null jobState and unconditionally restored all other entries, causing zombie jobs to be incorrectly re-restored as RUNNING.

Fix: after fetching jobState, check if it is a terminal JobStatus (isEndState()). If so, remove the zombie entry from runningJobInfoIMap and skip restore.

Adds CoordinatorServiceTest.testZombieJobRemovedFromImapOnMasterSwitchRestore which injects a FAILED-state zombie via IMap, triggers a master switch, and asserts the zombie is removed after restore completes.

#10675 addressed via this PR.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If necessary, please update `incompatible-changes.md` to describe the incompatibility caused by this PR.
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 1]
```diff
@@ -721,6 +721,16 @@ private void restoreJobFromMasterActiveSwitch(@NonNull Long jobId, @NonNull JobI
...
 
+        if (jobState instanceof JobStatus && ((JobStatus) jobState).isEndState()) {
+            logger.warning(
+                    String.format(
+                            "Job %s is in terminal state %s in runningJobInfoIMap, "
+                                    + "removing zombie entry to prevent incorrect restore",
+                            jobId, jobState));
+            runningJobInfoIMap.remove(jobId);
+            return;
+        }
```
Comment (dybyte) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: Instead of directly removing the jobId from `runningJobInfoIMap`,
would it make sense to create the JobMaster and call
`jobMaster.neverNeedRestore()` to ensure proper cleanup in the terminal state?

This might help avoid leaving any incomplete cleanup behind. What do you think?
cc @zhangshenghang

Comment (ricky2129) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: @dybyte Thanks — you're right, our fix leaves orphan entries in runningJobStateIMap and
  runningJobStateTimestampsIMap (all pipeline/task keys that removeJobIMap() normally handles).

  neverNeedRestore() on its own is just this.needRestore = false — a flag setter used
  only by SubPlan.canRestorePipeline(). It doesn't trigger cleanup.

  Following the normal restore path (pending queue + updateJobState(PENDING)) would
  eventually reach cleanJob() but introduces a small risk: PENDING is not a terminal
  state, so if the coordinator crashes in that window, the zombie re-enters the restore
  loop with needRestore=true on a fresh instance — exactly the original bug, now with
  a stale checkpoint.

  Cleaner approach: call jobMaster.init() to build the PhysicalPlan structure, then
  call jobMaster.cleanJob() directly (it's public) — bypassing the pending queue
  entirely. No updateJobState(PENDING), no re-execution risk. Wrap in try-catch so if
  init() fails (e.g. S3 unavailable), we fall back to direct runningJobInfoIMap.remove().

Happy to update the PR.

Comment (dybyte) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: +1, this approach looks good to me.

**Review by DanielLeens — CHANGES_REQUESTED** [review]
Superseded by my later review https://github.com/apache/seatunnel/pull/10692#pullrequestreview-4060298056, which consolidates the current blocking findings for this PR. I am shortening this older review to avoid duplicate guidance.

**Review by DanielLeens — CHANGES_REQUESTED** [review]
Superseded by my later review https://github.com/apache/seatunnel/pull/10692#pullrequestreview-4060298056 and the remaining inline comment on the test path. I am shortening this older review to avoid repeating the same guidance in multiple places.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 2]
```diff
@@ -652,6 +653,27 @@ private void restoreAllRunningJobFromMasterNodeSwitch() {
...
+        // Pre-filter: clean up terminal-state zombie jobs immediately before waiting for workers.
+        // Zombies do not need a worker — they only need IMap cleanup. Processing them here avoids
+        // blocking zombie cleanup behind the worker-wait loop.
+        Iterator<Map.Entry<Long, JobInfo>> zombieIterator =
+                needRestoreFromMasterNodeSwitchJobs.iterator();
+        while (zombieIterator.hasNext()) {
+            Map.Entry<Long, JobInfo> entry = zombieIterator.next();
+            Object jobState;
+            try {
+                jobState = runningJobStateIMap.get(entry.getKey());
```
Comment (DanielLeens) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: Can we use the same retry wrapper here as in the surrounding failover reads? This code runs in the exact master-switch window where retryable Hazelcast read errors are expected. If `get()` fails once here, we silently keep the zombie in `needRestoreFromMasterNodeSwitchJobs`, then still enter the `workerCount == 0` wait loop and lose the main benefit of this change.

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/CoordinatorServiceTest.java [hunk 3]
```diff
@@ -505,6 +505,71 @@ private JobInformation submitJob(String testClassName, String jobConfigFile, Str
...
+        // (simulates coordinator dying mid-cleanup before removeJobIMap executed)
+        long zombieJobId =
+                instance1.getFlakeIdGenerator(Constant.SEATUNNEL_ID_GENERATOR_NAME).newId();
+        IMap<Long, org.apache.seatunnel.engine.core.job.JobInfo> runningJobInfoIMap =
+                instance1.getMap(Constant.IMAP_RUNNING_JOB_INFO);
+        IMap<Long, JobStatus> runningJobStateIMap =
+                instance1.getMap(Constant.IMAP_RUNNING_JOB_STATE);
+        runningJobInfoIMap.put(
+                zombieJobId,
+                new org.apache.seatunnel.engine.core.job.JobInfo(System.currentTimeMillis(), null));
```
Comment (DanielLeens) [inline seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/CoordinatorServiceTest.java]: This test injects `new JobInfo(..., null)`, but the production submit path stores a non-null `jobImmutableInformation`. With `null` here, `cleanupZombieJob()` cannot complete `JobMaster.init()` and falls back to only `runningJobInfoIMap.remove(jobId)`, so the test never exercises the new `JobMaster.cleanJob()` branch. Can we build the zombie from real immutable job info (or submit a real job first) and assert that the extra stale state keys are removed too?

**Review by DanielLeens — CHANGES_REQUESTED** [review]
The direction is right: this PR correctly targets the zombie-restore bug on master failover, and moving terminal-state cleanup ahead of the worker-wait loop is the right place to fix it. I am still requesting changes for one blocker in the failover path: the new prefilter does a raw `runningJobStateIMap.get()` with no retry and silently skips failures, so in the same master-switch window where the surrounding code already uses `RetryUtils`, a transient Hazelcast read failure can leave the zombie in the restore list and still drop back into the old worker-wait behavior. I also left one test-coverage comment because the new regression test currently only exercises the fallback direct-remove branch, not the `JobMaster.cleanJob()` path the PR is trying to validate.

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/CoordinatorServiceTest.java (hunk 3 above)
Comment (ricky2129) [reply seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/CoordinatorServiceTest.java]: @DanielLeens added the changes.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java (hunk 2 above)
Comment (ricky2129) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: @DanielLeens added the changes.

**Review by DanielLeens — APPROVED** [review]
I re-checked the latest HEAD locally.

The blockers from my previous review look addressed now:
- the zombie pre-filter read is now wrapped in `RetryUtils`, so it no longer drops back to the old worker-wait behavior on a transient Hazelcast read failure (`CoordinatorService.java:663-679`)
- the regression test now uses real `JobImmutableInformation` and asserts that both `runningJobInfoIMap` and `runningJobStateIMap` are removed, which exercises the intended `JobMaster.cleanJob()` path instead of only the fallback direct-remove path (`CoordinatorServiceTest.java:527-593`)

I do not see the earlier failover-path blocker in the current revision.
Thanks for tightening both the retry behavior and the test path.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 4]
```diff
@@ -748,6 +792,47 @@ private void restoreJobFromMasterActiveSwitch(@NonNull Long jobId, @NonNull JobI
...
+                    String.format(
+                            "Zombie job %s cleaned up successfully via JobMaster.cleanJob()",
+                            jobId));
+        } catch (Exception e) {
+            logger.warning(
+                    String.format(
+                            "Failed to init JobMaster for zombie job %s, "
+                                    + "falling back to direct IMap remove: %s",
+                            jobId, e.getMessage()));
+            runningJobInfoIMap.remove(jobId);
```
Comment (dybyte) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]:
```suggestion
```
I think this approach could potentially cause a memory leak. Would it make sense to wait for the next restore process instead?

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 5]
```diff
@@ -748,6 +792,47 @@ private void restoreJobFromMasterActiveSwitch(@NonNull Long jobId, @NonNull JobI
...
+                        engineConfig,
+                        seaTunnelServer);
+        try {
+            jobMaster.init(jobInfo.getInitializationTimestamp(), true);
+            jobMaster.neverNeedRestore();
+            jobMaster.cleanJob();
+            logger.info(
+                    String.format(
+                            "Zombie job %s cleaned up successfully via JobMaster.cleanJob()",
+                            jobId));
```
Comment (dybyte) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]:
```suggestion
        JobResult jobResult = new JobResult(jobState, null);
        jobMaster.getPhysicalPlan().completeJobEndFuture(jobResult);
        getEventProcessor()
                      .process(
                              new JobStateEvent(
                                      jobImmutableInformation.getJobId(),
                                      jobImmutableInformation.getJobConfig().getName(),
                                      jobState));
        // wait job complete
        jobMaster.getJobMasterCompleteFuture().join();
```
I think this approach might be better. What do you think?

**Comment by davidzollo** [comment]
image

**Comment by ricky2129** [comment]
Thanks @dybyte for the detailed review!                                                                                                                             
You're right — calling cleanJob() directly bypassed the jobEndFuture handler chain wired in initStateFuture(), which means jobMasterCompleteFuture was never completed (potential memory leak and missed event processing).                                                                                                        
                                                                                                                                                                        
Updated the approach in the latest commit:                                                                                                                          
                                                                                                                                                                        
- cleanupZombieJob now calls completeJobEndFuture(jobResult) with the already-known terminal JobStatus, which triggers the wired whenComplete handler in JobMaster.initStateFuture() — this calls cleanJob() and completes jobMasterCompleteFuture through the same path as every normally-finishing job.                      
- Also fires JobStateEvent via getEventProcessor() so event listeners see the correct final state.
- jobMasterCompleteFuture.join() ensures cleanup finishes before the method returns.                                                                                
- Removed the fallback runningJobInfoIMap.remove(jobId) — if init() fails (e.g. checkpoint storage unreachable), we 

now log a warning and leave the zombie for the next restore cycle to retry, rather than doing a partial cleanup.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 6]
```diff
@@ -792,6 +837,57 @@ private void restoreJobFromMasterActiveSwitch(@NonNull Long jobId, @NonNull JobI
...
+                        getJobHistoryService(),
+                        runningJobStateIMap,
+                        runningJobStateTimestampsIMap,
+                        ownedSlotProfilesIMap,
+                        runningJobInfoIMap,
+                        engineConfig,
+                        seaTunnelServer);
+        try {
+            jobMaster.init(jobInfo.getInitializationTimestamp(), true);
+            jobMaster.neverNeedRestore();
```
Comment (dybyte) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]:
```suggestion
```
I think this code might be unnecessary for now.

**Review by dybyte — APPROVED** [review]
LGTM if CI passes, thanks @ricky2129 !

**Review by dybyte — CHANGES_REQUESTED** [review]
-1
I took another look, and I still think there is a real issue here.

That said, the new test also seems to pass on the original code, so I’m not sure the current regression test is strong enough yet.
Could you please update the test so that it fails on the original code and only passes with this fix?

**Review by DanielLeens — COMMENTED** [review]
Pulled the latest branch locally and rechecked the master-switch restore flow. The updated path now pre-filters terminal-state zombies before the worker wait loop and routes cleanup through `cleanupZombieJob(...)`, and the regression test asserts both `runningJobInfoIMap` and `runningJobStateIMap` are removed after the switch. I don't see a new blocker from my side in the current code path. The remaining blockers are the red `Build` check and the unresolved reviewer thread.

**Comment by ricky2129** [comment]
@dybyte can you chck once for any gaps?

**Review by DanielLeens — CHANGES_REQUESTED** [review]
I re-pulled the latest branch locally and rechecked the new `restart=false` change in the zombie-cleanup path.

Current cleanup chain on this revision:
`master switch restore` -> `cleanupZombieJob(...)` (`CoordinatorService.java:851-873`) -> `jobMaster.init(..., false)` -> `JobMaster.init()` (`JobMaster.java:255-274`) -> `handleSaveMode(...)` (`JobMaster.java:566-575`) -> `completeJobEndFuture(...)`

I think this introduces a new blocker.

Because `EnvCommonOptions.SAVEMODE_EXECUTE_LOCATION` defaults to `CLUSTER` (`EnvCommonOptions.java:96-99`), changing `cleanupZombieJob()` from `jobMaster.init(..., true)` to `jobMaster.init(..., false)` means the zombie-cleanup path can now execute normal startup save-mode handling while we are only trying to remove stale IMap entries.

That is not a harmless internal difference:
- `JobMaster.init(..., false)` now enters the `!restart` branch at `JobMaster.java:255-274`
- `handleSaveMode(...)` can open the sink save-mode handler and execute its side effects (`JobMaster.java:566-575`)
- so a master-switch zombie cleanup can re-run sink-side save-mode behavior on a terminal job

For sinks that implement `SupportSaveMode`, this can become an unexpected overwrite / truncate / other startup-side effect during failover cleanup, which is worse than the checkpoint-restore failure you were trying to avoid.

So I still see this as a merge blocker. The cleanup path needs a mode that skips both checkpoint restore and normal startup save-mode handling, instead of reusing the normal `restart=false` initialization path.

The new `Build` is also still pending.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java [hunk 7]
```diff
@@ -792,6 +837,61 @@ private void restoreJobFromMasterActiveSwitch(@NonNull Long jobId, @NonNull JobI
...
+                        runningJobInfoIMap,
+                        engineConfig,
+                        seaTunnelServer);
+        try {
+            // restart=false: we are not restarting this job, just cleaning up its IMap
+            // entries. Using restart=true would trigger CheckpointManager restore which
+            // can fail for zombies that were never checkpointed (e.g. freshly injected
+            // or crashed before first checkpoint), causing init() to throw and leaving
+            // the zombie uncleaned.
+            jobMaster.init(jobInfo.getInitializationTimestamp(), false);
```
Comment (dybyte) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]:
```suggestion
            jobMaster.init(jobInfo.getInitializationTimestamp(), true);
```

https://github.com/apache/seatunnel/blob/4a8298df8b2fa9ada9ba723ae1efcb47eac01d25/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointManager.java#L114-L130 

Are you referring to this code snippet?
Since this path is already null-safe, I think passing true here should be fine.

File: seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/CoordinatorServiceTest.java [hunk 8]
```diff
@@ -505,6 +505,99 @@ private JobInformation submitJob(String testClassName, String jobConfigFile, Str
         return new JobInformation(coordinatorServiceTest, coordinatorService, jobId);
     }
 
+    @Test
+    void testZombieJobRemovedFromImapOnMasterSwitchRestore() {
```
Comment (dybyte) [inline seatunnel-engine/seatunnel-engine-server/src/test/java/org/apache/seatunnel/engine/server/CoordinatorServiceTest.java]: Could you refer to this code snippet?

```java
@Test
void testZombieCleanupCanLeaveOrphanWorkerTaskAfterMasterSwitch() {
    String clusterName =
            TestUtils.getClusterName(
                    "CoordinatorServiceTest_testZombieCleanupCanLeaveOrphanWorkerTaskAfterMasterSwitch");

    // instance1: initial master
    HazelcastInstanceImpl instance1 =
            createHazelcastInstanceWithJoinPortTryCount(clusterName, 100);
    SeaTunnelServer server1 =
            instance1.node.getNodeEngine().getService(SeaTunnelServer.SERVICE_NAME);

    await().atMost(10, TimeUnit.SECONDS)
            .untilAsserted(
                    () -> {
                        Assertions.assertTrue(server1.isMasterNode());
                        Assertions.assertTrue(
                                server1.getCoordinatorService().isCoordinatorActive());
                    });

    // instance2: worker that should survive the master switch
    HazelcastInstanceImpl instance2 =
            createHazelcastInstanceWithJoinPortTryCount(clusterName, 100);
    SeaTunnelServer server2 =
            instance2.node.getNodeEngine().getService(SeaTunnelServer.SERVICE_NAME);

    await().atMost(10, TimeUnit.SECONDS)
            .untilAsserted(
                    () -> Assertions.assertEquals(
                            2, instance1.getCluster().getMembers().size()));

    long zombieJobId =
            instance1.getFlakeIdGenerator(Constant.SEATUNNEL_ID_GENERATOR_NAME).newId();

    LogicalDag logicalDag =
            TestUtils.createTestLogicalPlan(
                    "stream_fake_to_console.conf",
                    "zombie-orphan-running-task-test",
                    zombieJobId);

    JobImmutableInformation jobImmutableInfo =
            new JobImmutableInformation(
                    zombieJobId,
                    "Test",
                    instance1.getSerializationService(),
                    logicalDag,
                    Collections.emptyList(),
                    Collections.emptyList());

    Data jobData = instance1.getSerializationService().toData(jobImmutableInfo);

    CoordinatorService coordinatorService = server1.getCoordinatorService();
    coordinatorService
            .submitJob(zombieJobId, jobData, jobImmutableInfo.isStartWithSavePoint())
            .join();

    await().atMost(20, TimeUnit.SECONDS)
            .untilAsserted(
                    () ->
                            Assertions.assertEquals(
                                    JobStatus.RUNNING,
                                    coordinatorService.getJobStatus(zombieJobId)));

    JobMaster jobMaster = coordinatorService.getJobMaster(zombieJobId);
    Assertions.assertNotNull(jobMaster);

    List<PipelineLocation> pipelineLocations = new ArrayList<>();
    List<TaskGroupLocation> allTaskGroupLocations = new ArrayList<>();
    for (SubPlan subPlan : jobMaster.getPhysicalPlan().getPipelineList()) {
        pipelineLocations.add(subPlan.getPipelineLocation());
        subPlan.getCoordinatorVertexList()
                .forEach(v -> allTaskGroupLocations.add(v.getTaskGroupLocation()));
        subPlan.getPhysicalVertexList()
                .forEach(v -> allTaskGroupLocations.add(v.getTaskGroupLocation()));
    }

    AtomicReference<TaskGroupLocation> survivingWorkerTaskGroup = new AtomicReference<>();
    await().atMost(20, TimeUnit.SECONDS)
            .untilAsserted(
                    () -> {
                        TaskGroupLocation found =
                                allTaskGroupLocations.stream()
                                        .filter(loc -> hasActiveExecutionContext(server2, loc))
                                        .findFirst()
                                        .orElse(null);
                        Assertions.assertNotNull(
                                found,
                                "Need at least one task group actively running on instance2 "
                                        + "before killing the master");
                        survivingWorkerTaskGroup.set(found);
                    });

    TaskGroupLocation orphanLocation = survivingWorkerTaskGroup.get();
    Assertions.assertTrue(
            hasActiveExecutionContext(server2, orphanLocation),
            "Sanity check failed: chosen task group is not running on instance2");

    // Poison the distributed metadata to simulate a zombie terminal job while the worker task
    // is still actively executing on instance2.
    IMap<Long, org.apache.seatunnel.engine.core.job.JobInfo> runningJobInfoIMap =
            instance1.getMap(Constant.IMAP_RUNNING_JOB_INFO);
    IMap<Object, Object> runningJobStateIMap =
            instance1.getMap(Constant.IMAP_RUNNING_JOB_STATE);

    Assertions.assertTrue(runningJobInfoIMap.containsKey(zombieJobId));
    runningJobStateIMap.put(zombieJobId, JobStatus.FAILED);

    // Optional but makes the terminal zombie metadata more explicit/consistent.
    for (PipelineLocation pipelineLocation : pipelineLocations) {
        runningJobStateIMap.put(pipelineLocation, PipelineStatus.FAILED);
    }
    for (TaskGroupLocation taskGroupLocation : allTaskGroupLocations) {
        runningJobStateIMap.put(taskGroupLocation, ExecutionState.FAILED);
    }

    // Trigger master switch: instance2 survives and becomes the new master.
    instance1.shutdown();

    await().atMost(20, TimeUnit.SECONDS)
            .untilAsserted(
                    () -> {
                        Assertions.assertTrue(server2.isMasterNode());
                        Assertions.assertTrue(
                                server2.getCoordinatorService().isCoordinatorActive());
                    });

    IMap<Long, org.apache.seatunnel.engine.core.job.JobInfo> runningJobInfoOnInstance2 =
            instance2.getMap(Constant.IMAP_RUNNING_JOB_INFO);
    IMap<Object, Object> runningJobStateOnInstance2 =
            instance2.getMap(Constant.IMAP_RUNNING_JOB_STATE);

    await().atMost(20, TimeUnit.SECONDS)
            .untilAsserted(
                    () -> {
                        Assertions.assertFalse(
                                runningJobInfoOnInstance2.containsKey(zombieJobId),
                                "Zombie job must be removed from runningJobInfoIMap");
                        Assertions.assertFalse(
                                runningJobStateOnInstance2.containsKey(zombieJobId),
                                "Zombie job must be removed from runningJobStateIMap");
                    });

    // This is the bug we want to expose:
    // metadata says the zombie is cleaned up, but the surviving worker task is still executing.
    Assertions.assertTrue(
            hasActiveExecutionContext(server2, orphanLocation),
            "Expected orphan task group to still be running on surviving worker "
                    + "after zombie metadata cleanup");

    instance2.shutdown();
}

private boolean hasActiveExecutionContext(SeaTunnelServer server, TaskGroupLocation location) {
    try {
        return server.getTaskExecutionService().getActiveExecutionContext(location) != null;
    } catch (Exception e) {
        return false;
    }
}
```

**Review by DanielLeens — CHANGES_REQUESTED** [review]
I re-pulled the latest branch locally and traced the current master-switch cleanup path.

Current runtime chain:
```text
restoreAllRunningJobFromMasterNodeSwitch()
  -> pre-filter terminal jobs [CoordinatorService.java:690-718]
  -> restoreJobFromMasterActiveSwitch(jobId, jobInfo) [783-810]
      -> cleanupZombieJob(jobId, jobInfo, terminalStatus) [851-892]
          -> temporary JobMaster.init(..., true)
          -> completeJobEndFuture(jobResult)
          -> join JobMasterCompleteFuture
          -> clean coordinator-side IMap metadata
```

The previous `restart=false` / save-mode side effect is gone, which is good. But I still see one blocking lifecycle gap in the current revision:

- cleanup is still coordinator-side only
- it removes the zombie job from `runningJobInfoIMap` / `runningJobStateIMap`
- it still does not cancel a task group that is already executing on a surviving worker node

The new regression test explicitly documents that gap instead of fixing it:
- `CoordinatorServiceTest.testZombieCleanupCanLeaveOrphanWorkerTaskAfterMasterSwitch()` poisons the metadata to terminal state while a worker task is still active
- after master switch and zombie metadata cleanup, the test *expects* `hasActiveExecutionContext(server2, orphanLocation)` to remain true

That means the current implementation can declare the zombie cleaned up in metadata while the worker task keeps running and may still produce side effects. I still consider that a blocker for merge.

The remaining `Build` check is also still pending.

**Comment by dybyte** [comment]
@ricky2129 I pushed a small follow-up change to refine the test a bit.
The previous version was a little rough, so I made it a bit clearer and more stable.

**Review by DanielLeens — CHANGES_REQUESTED** [review]
I pulled the latest branch locally and rechecked the zombie-cleanup path.

Current runtime chain:
```text
master switch restore
  -> CoordinatorService.cleanupZombieJob()
      -> jobMaster.init(..., true)
      -> physicalPlan.completeJobEndFuture(jobResult)
          -> only completes jobEndFuture
      -> JobMaster initStateFuture callback
          -> cleanJob()
          -> remove IMap metadata
```

The previous `restart=false` / save-mode blocker is fixed in the current revision.

However, I still see one blocker before merge:
this path cleans the metadata layer, but I still cannot find any new logic that reconciles or cancels a surviving worker task group if the master switch happens while execution is still alive on another node. `completeJobEndFuture()` only completes the future, and `cleanJob()` only clears checkpoint/history/IMap state. The current regression test also avoids this window by canceling the real job completely before injecting stale terminal metadata.

So I think this still needs one more round:
- either add explicit surviving-task reconciliation / cancel semantics in the zombie cleanup path
- or at minimum keep a regression test that clearly documents this remaining limitation, so the PR is not interpreted as a full fix for the master-switch scenario

The pending `Build` check is the other remaining item.

**Comment by dybyte** [comment]
Could you please sync your branch with the latest changes from the upstream dev branch? @ricky2129

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java
Comment (dybyte) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]:
```suggestion
if (pendingSourceState == PendingSourceState.RESTORE && !jobStatus.isEndState()) {
     finalJobMaster
                    .getPhysicalPlan()
                    .getPipelineList()
                    .forEach(SubPlan::restorePipelineState);
}
```
I think this part may be the root cause of the issue.

To me, it seems simpler and safer to fix the root cause here, rather than adding more logic for edge cases around it.
So I wonder whether we could just update this condition and remove the extra handling below.

That said, the current approach still looks reasonable to me overall, so this is not a blocker.

Comment (ricky2129) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]: @dybyte Thanks for the suggestion! Adding !jobStatus.isEndState() would guard restorePipelineState(), but the zombie would still be enqueued and run() called on a  terminal-state job, and the stale pipeline/task IMap entries would remain. The cleanupZombieJob() path handles all of this before the job reaches the consumer loop. Happy to add the condition as an extra guard if you'd like — just let me know.

Comment (dybyte) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/CoordinatorService.java]:
```java
//PhysicalPlan.java
    public synchronized void startJob() {
        isRunning = true;
        log.info("{} state process is start", getJobFullName());
        updateJobState(JobStatus.SCHEDULED);
        stateProcess();
    }

```
In this code path, the job status is not actually updated to `SCHEDULED`.

There is already internal logic that filters out end states, so if the job is already in a terminal state, it proceeds directly to `stateProcess()` without transitioning to `SCHEDULED`, and then goes through the cleanup path that removes the IMap entries.

Please feel free to let me know if I’m missing something.

**Comment by ricky2129** [comment]
@dybyte added changes.

**Review by DanielLeens — CHANGES_REQUESTED** [review]
I pulled the latest branch locally and rechecked the updated master-switch restore path.

Current runtime chain on this revision:

test path
  -> cancel the real job first
  -> wait until all task groups are inactive on both nodes
  -> inject stale terminal metadata
  -> master switch
  -> assert no task is restarted

runtime path
  -> restoreAllRunningJobFromMasterNodeSwitch()
      -> pre-filter terminal zombie jobs
      -> restoreJobFromMasterActiveSwitch(...)
      -> pending restore path
      -> skip restorePipelineState() when jobStatus is already end state

This definitely improves the PR: the old restart/save-mode blocker is gone, and the new guard now prevents terminal metadata from re-triggering restorePipelineState().

However, I still see one blocker before merge:
this revision still does not cover the master-switch window where terminal metadata already exists but a surviving worker task is still running on another node. The new regression test explicitly cancels the real job and waits for all task groups to become inactive before injecting stale metadata, so it proves "no restart" but it does not prove "surviving worker execution is reconciled". I still cannot find any new surviving-task reconcile/cancel logic in the cleanup path itself.

So I think this still needs one more round:
- either add explicit surviving-worker reconciliation/cancel semantics for the terminal-zombie cleanup path
- or clearly keep that limitation in the tests / PR scope, so this PR is not interpreted as a full master-switch zombie fix

The  check is also still queued, but the surviving-worker gap is the real merge blocker from my side.

**Review by DanielLeens — CHANGES_REQUESTED** [review]
I pulled the latest branch locally and rechecked the updated master-switch restore path.

Current runtime chain on this revision:

```text
test path
  -> cancel the real job first
  -> wait until all task groups are inactive on both nodes
  -> inject stale terminal metadata
  -> master switch
  -> assert no task is restarted

runtime path
  -> restoreAllRunningJobFromMasterNodeSwitch()
      -> pre-filter terminal zombie jobs
      -> restoreJobFromMasterActiveSwitch(...)
      -> pending restore path
      -> skip restorePipelineState() when jobStatus is already end state
```

This definitely improves the PR: the old restart/save-mode blocker is gone, and the new guard now prevents terminal metadata from re-triggering restorePipelineState().

However, I still see one blocker before merge:
this revision still does not cover the master-switch window where terminal metadata already exists but a surviving worker task is still running on another node. The new regression test explicitly cancels the real job and waits for all task groups to become inactive before injecting stale metadata, so it proves "no restart" but it does not prove "surviving worker execution is reconciled". I still cannot find any new surviving-task reconcile/cancel logic in the cleanup path itself.

So I think this still needs one more round:
- either add explicit surviving-worker reconciliation/cancel semantics for the terminal-zombie cleanup path
- or clearly keep that limitation in the tests / PR scope, so this PR is not interpreted as a full master-switch zombie fix

The `Build` check is also still queued, but the surviving-worker gap is the real merge blocker from my side.

**Comment by dybyte** [comment]
> I pulled the latest branch locally and rechecked the updated master-switch restore path.
> 
> Current runtime chain on this revision:
> 
> ```
> test path
>   -> cancel the real job first
>   -> wait until all task groups are inactive on both nodes
>   -> inject stale terminal metadata
>   -> master switch
>   -> assert no task is restarted
> 
> runtime path
>   -> restoreAllRunningJobFromMasterNodeSwitch()
>       -> pre-filter terminal zombie jobs
>       -> restoreJobFromMasterActiveSwitch(...)
>       -> pending restore path
>       -> skip restorePipelineState() when jobStatus is already end state
> ```
> 
> This definitely improves the PR: the old restart/save-mode blocker is gone, and the new guard now prevents terminal metadata from re-triggering restorePipelineState().
> 
> However, I still see one blocker before merge: this revision still does not cover the master-switch window where terminal metadata already exists but a surviving worker task is still running on another node. The new regression test explicitly cancels the real job and waits for all task groups to become inactive before injecting stale metadata, so it proves "no restart" but it does not prove "surviving worker execution is reconciled". I still cannot find any new surviving-task reconcile/cancel logic in the cleanup path itself.
> 
> So I think this still needs one more round:
> 
> * either add explicit surviving-worker reconciliation/cancel semantics for the terminal-zombie cleanup path
> * or clearly keep that limitation in the tests / PR scope, so this PR is not interpreted as a full master-switch zombie fix
> 
> The `Build` check is also still queued, but the surviving-worker gap is the real merge blocker from my side.

@DanielLeens I think the main point of this test is not zombie-task cleanup itself.

What it tries to verify is whether zombie tasks can be re-created during master switch from stale terminal metadata.
If `restorePipelineState()` is skipped for a job that is already in a terminal state, then that re-trigger does not happen.

**Review by dybyte — APPROVED** [review]
LGTM. Thanks for the update!

**Review by corgy-w — APPROVED** [review]
