### PR TITLE
[Fix][Zeta] Fix premature closure of the checkpoint thread pool causes abnormal task status

### LINKED ISSUE #9061: 任务时间运行一段时间就会有java.lang.RuntimeException: TaskGroupLocation: TaskGroupLocation{jobId=XXX, pipelineId=1, taskGroupId=1}already exists 这样的问题
从使用情况来看，无论是 http 还是 cdc，时间稍微长点就会有这个分片的问题。麻烦帮忙看看。

使用版本是 2.3.9  
zeta 引擎 
分离集群模式

http 中增加了请求间隔就会出现错误。

我的 http 同步到 pg 的 job 配置：
```
{
  "sink": [
    {
      "primary_keys": [
        "BSM"
      ],
      "batch_size": 1000,
      "max_retries": 0,
      "plugin_output": "sink_5c80a053e7d9478f861d505052a30e49",
      "schema_save_mode": "RECREATE_SCHEMA",
      "max_commit_attempts": 3,
      "auto_commit": true,
      "plugin_name": "jdbc",
      "url": "jdbc:postgresql://192.168.11.151:5432/querypro?currentSchema=schema&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&stringtype=unspecified",
      "is_exactly_once": false,
      "password": "YWRtaW4xMjM0QA==",
      "database": "querypro",
      "plugin_input": "source_30ffbda2fe5344c8a3cf10167afd27dd",
      "enable_upsert": true,
      "driver": "org.postgresql.Driver",
      "transaction_timeout_sec": -1,
      "data_save_mode": "APPEND_DATA",
      "connection_check_timeout_sec": 30,
      "generate_sink_sql": true,
      "user": "postgres",
      "table": "zscs.Testcreate"
    }
  ],
  "source": [
    {
      "schema": {
        "columns": [
          {
            "columnLength": 255,
            "nullable": true,
            "name": "XZQJB",
            "type": "string"
          },
          {
            "columnLength": 255,
            "nullable": true,
            "name": "XZQMC",
            "type": "string"
          },
          {
            "columnLength": 255,
            "nullable": true,
            "name": "PARENT",
            "type": "string"
          },
          {
            "columnLength": 255,
            "nullable": true,
            "name": "XZQBM",
            "type": "string"
          },
          {
            "columnLength": 255,
            "nullable": true,
            "name": "FWQBM",
            "type": "string"
          },
          {
            "columnLength": 255,
            "nullable": true,
            "name": "GXSJ",
            "type": "string"
          },
          {
            "columnLength": 255,
            "nullable": false,
            "name": "BSM",
            "type": "string"
          }
        ],
        "primaryKey": {
          "columnNames": [
            "BSM"
          ],
          "name": "BSM"
        }
      },
      "method": "GET",
      "plugin_output": "source_30ffbda2fe5344c8a3cf10167afd27dd",
      "parallelism": 1,
      "format": "json",
      "content_field": "$.data.data.*",
      "retry_backoff_multiplier_ms": 100,
      "plugin_name": "Http",
      "params": {
        "serviceId": "13c4e79ea4a912a5c68093d1afb47fe0",
        "projectId": "650388bd3dda0a558d4c41ff8624045e"
      },
      "url": "http://192.168.11.150:6102/queryPro/api/serviceAPI/publicGetData?serviceId=13c4e79ea4a912a5c68093d1afb47fe0?projectId=650388bd3dda0a558d4c41ff8624045e",
      "poll_interval_millis": 30000,
      "connect_timeout_ms": 12000,
      "enable_multi_lines": false,
      "socket_timeout_ms": 60000,
      "retry_backoff_max_ms": 10000
    }
  ],
  "env": {
    "job.retry.interval.seconds": 3,
    "job.mode": "STREAMING",
    "shade.identifier": "base64",
    "checkpoint.timeout": 300000,
    "job.retry.times": 3,
    "job.name": "PlacetoPG",
    "checkpoint.interval": 30000
  }
}
``` 

报错信息：

> [!IMPORTANT]
org.apache.seatunnel.engine.common.exception.TaskGroupDeployException: java.lang.RuntimeException: TaskGroupLocation: TaskGroupLocation{jobId=957213081283330050, pipelineId=1, taskGroupId=1} already exists at org.apache.seatunnel.engine.server.TaskExecutionService.deployTask(TaskExecutionService.java:338) at org.apache.seatunnel.engine.server.TaskExecutionService.deployTask(TaskExecutionService.java:269) at org.apache.seatunnel.engine.server.task.operation.DeployTaskOperation.runInternal(DeployTaskOperation.java:55) at org.apache.seatunnel.engine.server.task.operation.TracingOperation.run(TracingOperation.java:42) at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:471) at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.stateProcess(PhysicalVertex.java:574) at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.updateTaskState(PhysicalVertex.java:403) at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.makeTaskGroupDeploy(PhysicalVertex.java:317) at org.apache.seatunnel.engine.server.dag.physical.SubPlan.lambda$stateProcess$19(SubPlan.java:643) at java.util.ArrayList.forEach(ArrayList.java:1259) at org.apache.seatunnel.engine.server.dag.physical.SubPlan.stateProcess(SubPlan.java:639) at org.apache.seatunnel.engine.server.dag.physical.SubPlan.updatePipelineState(SubPlan.java:383) at org.apache.seatunnel.engine.server.dag.physical.SubPlan.stateProcess(SubPlan.java:633) at org.apache.seatunnel.engine.server.dag.physical.SubPlan.updatePipelineState(SubPlan.java:383) at org.apache.seatunnel.engine.server.dag.physical.SubPlan.stateProcess(SubPlan.java:624) at org.apache.seatunnel.engine.server.dag.physical.SubPlan.startSubPlanStateProcess(SubPlan.java:608) at org.apache.seatunnel.engine.server.dag.physical.SubPlan.restorePipeline(SubPlan.java:496) at org.apache.seatunnel.engine.server.dag.physical.SubPlan.stateProcess(SubPlan.java:677) at org.apache.seatunnel.engine.server.dag.physical.SubPlan.updatePipelineState(SubPlan.java:383) at org.apache.seatunnel.engine.server.dag.physical.SubPlan.lambda$addPhysicalVertexCallBack$4(SubPlan.java:228) at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:43) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750)
>

### PR DESCRIPTION
**Pull request by Hisoka-X**
### Purpose of this pull request
Fix premature closure of the checkpoint thread pool causes abnormal task status. Closes #9061
Before this change, if the checkpoint fails (for example, the checkpoint times out), the cancel task operation initiated by the checkpoint runs in the thread pool inside the checkpoint. Due to the early closure of the thread pool, it is impossible to check the status of `executionContexts` through `CheckTaskGroupIsExecutingOperation` and clean up the corresponding context by `CancelTaskOperation`. 
image
https://github.com/apache/seatunnel/blob/dev/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/dag/physical/PhysicalVertex.java#L230-L245
This will cause the check of executionContexts to fail when the task is retried.
image

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
add new test.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinator.java [hunk 1]
```diff
@@ -285,12 +285,15 @@ private void handleCoordinatorError(CheckpointCloseReason reason, Throwable e) {
...
             return;
         }
-        cleanPendingCheckpoint(reason);
         updateStatus(CheckpointCoordinatorStatus.FAILED);
         checkpointCoordinatorFuture.complete(
                 new CheckpointCoordinatorState(
                         CheckpointCoordinatorStatus.FAILED, errorByPhysicalVertex.get()));
         checkpointManager.handleCheckpointError(pipelineId, false);
+        // we should wait the checkpoint manager handle the error to cancel other task by use
+        // checkpoint coordinator thread pool. So we killed the thread pool at the end of this
```
Comment (hailin0) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinator.java:294]: Can you explain in detail the logical relationship of the calls?

Comment (Hisoka-X) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinator.java:294]: updated

**Review by hailin0 — APPROVED** [review]

**Review by wuchunfu — APPROVED** [review]
