### PR TITLE
[Fix][Connector-V2] ArrowToSeatunnelRowReader convertSeatunnelRowValue add handle Second TIMESTAMP type

### LINKED ISSUE #8352: [Bug] [Doris] 从Doris表中同步数据时datetime类型读取错误
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

batch模式从doris中同步数据到console中，读取datetime类型数据错误。

doris表结构：
```
CREATE TABLE `test_sync` (
  `id` int NULL,
  `dt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=OLAP
UNIQUE KEY(`id`)
DISTRIBUTED BY HASH(`id`) BUCKETS 2
PROPERTIES (
"storage_format" = "V2",
"inverted_index_storage_format" = "V1",
"enable_unique_key_merge_on_write" = "true"
);
```
数据如下：

| id | dt                  |
|----|---------------------|
|1   | 2024-12-03 10:20:32 |

seatunnel任务打印结果是：
```
2024-12-20 19:39:16,193 INFO  [.a.s.c.s.c.s.ConsoleSinkWriter] [st-multi-table-sink-writer-1] - subtaskIndex=0  rowIndex=1:  SeaTunnelRow#tableId= SeaTunnelRow#kind=INSERT : 1, 1970-01-01T00:28:53.192432
```
seatunnel将`2024-12-03 10:20:32`读成了`1970-01-01T00:28:53.192432`

doris 版本： 2.1.7

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
env {
  job.name = "doris-mysql"
  job.mode = "BATCH"
}

source {
Doris {
    fenodes = "${doris_fe}"
    username = "***"
    password = "***"
    database = "test"
    table = "test_sync"
}
}

transform {
}

sink {
Console {}
}
```

### Running Command

```shell
./bin/seatunnel.sh -c job/doris-mysql.config -m local
```

### Error Exception

```log
no exception
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by dyp12**
### Purpose of this pull request

close https://github.com/apache/seatunnel/issues/8352
### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

**Comment by Hisoka-X** [comment]
cc @liugddx

File: seatunnel-connectors-v2/connector-common/src/main/java/org/apache/seatunnel/connectors/seatunnel/common/source/arrow/reader/ArrowToSeatunnelRowReader.java [hunk 1]
```diff
@@ -204,9 +204,16 @@ private Object convertSeatunnelRowValue(
                 }
             case TIMESTAMP:
                 if (fieldValue instanceof Long) {
-                    return Instant.ofEpochMilli((Long) fieldValue)
-                            .atZone(ZoneId.systemDefault())
-                            .toLocalDateTime();
+                    // this TIMESTAMP value may be  SECOND not  milliseconds
+                    if (((Long) fieldValue).toString().length() == 10) {
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-common/src/main/java/org/apache/seatunnel/connectors/seatunnel/common/source/arrow/reader/ArrowToSeatunnelRowReader.java]: We should get the precision from the type rather than judging directly by the size of the value, which may be wrong.

**Comment by Hisoka-X** [comment]
Please add test case

File: seatunnel-connectors-v2/connector-common/src/main/java/org/apache/seatunnel/connectors/seatunnel/common/source/arrow/reader/ArrowToSeatunnelRowReader.java (hunk 1 above)
Comment (dyp12) [reply seatunnel-connectors-v2/connector-common/src/main/java/org/apache/seatunnel/connectors/seatunnel/common/source/arrow/reader/ArrowToSeatunnelRowReader.java]: > We should get the precision from the type rather than judging directly by the size of the value, which may be wrong.

sorry, i fix it, using Types.MinorType to know

**Review by corgy-w — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]

**Comment by dyp12** [comment]
> Please add test case

thank you for your help
