### PR TITLE
[Connector-V2] [File] Fix bug data file name will duplicate when use SeaTunnel Engine

### LINKED ISSUE #3611: [Bug] [File Connector V2] Data file name will duplicate when use SeaTunnel Engine
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

image

image

### SeaTunnel Version

ALL 

### SeaTunnel Config

```conf
CI: https://github.com/apache/incubator-seatunnel/pull/3456#pullrequestreview-1198820624
```

### Running Command

```shell
CI: https://github.com/apache/incubator-seatunnel/pull/3456#pullrequestreview-1198820624
```

### Error Exception

```log
CI: https://github.com/apache/incubator-seatunnel/pull/3456#pullrequestreview-1198820624
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request
Close #3611 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

### CODE REVIEW

File: seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/sink/writer/AbstractWriteStrategy.java [hunk 1]
```diff
@@ -289,22 +276,27 @@ public List<String> getTransactionIdFromStates(List<FileSinkState> fileStates) {
...
 
     /**
      * using transaction id generate transaction directory
+     *
      * @param transactionId transaction id
      * @return transaction directory
      */
     private String getTransactionDir(@NonNull String transactionId) {
-        String[] strings = new String[]{textFileSinkConfig.getTmpPath(), BaseSinkConfig.SEATUNNEL, jobId, transactionId};
+        return getTransactionDirPrefix(textFileSinkConfig.getTmpPath(), jobId, uuidPrefix) + File.separator + transactionId;
```
Comment (TyrantLucifer) [inline seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/sink/writer/AbstractWriteStrategy.java]:
```suggestion
        String transactionDirectoryPrefix = getTransactionDirPrefix(textFileSinkConfig.getTmpPath(), jobId, uuidPrefix);
        return String.join(File.separator, new String[]{transactionDirectoryPrefix, transactionId})
```

**Review by TyrantLucifer — DISMISSED** [review]

File: seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/sink/writer/AbstractWriteStrategy.java (hunk 1 above)
Comment (Hisoka-X) [reply seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/sink/writer/AbstractWriteStrategy.java]: Done

**Review by TyrantLucifer — APPROVED** [review]

**Review by EricJoy2048 — APPROVED** [review]
