### PR TITLE
[Bug][seatunnel-core-spark] spark on yarn cluster mode can not get --config/-c file

### LINKED ISSUE #1743: [Bug] [seatunnel-core-spark] spark on yarn cluster mode  can not get --config/-c  file
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when  use spark-submit   yarn  cluster  deploy-mode ，spark can not  get  config  file on yarn

### SeaTunnel Version

2.1.1-prepare

### SeaTunnel Config

```conf
env {
        spark.master = yarn
        spark.app.name = "20220315"
        spark.executor.instances = 1
        spark.executor.cores = 1
        spark.executor.memory = "4g"
        spark.driver.memory = "4g"
        spark.yarn.keytab = "xxxx.keytab"
        spark.yarn.principal = "xxxxxx"
        spark.yarn.queue = "xxxxxx"
}
source{
 jdbc {
        driver = "com.mysql.jdbc.Driver"
        url = "xxxxxxxxxx"
        table = "xxxxxxxxxxx"
        result_table_name = "xxxxxxxxxxx"
        user = "root"
        password = "xxxxxxxxxxx"
}

}

transform{
 sql {
        sql = "select   * from xxxxxx"
        result_table_name = "xxxxx"
}
}
sink{
jdbc {
        driver = "com.mysql.jdbc.Driver"
        source_table_name = "xxxxx"
        saveMode = "append"
        url = "xxxxx"
        user = "root"
        password = "xxxxx"
        dbTable = "xxxxx"
        }
}
```

### Running Command

```shell
bin/start-seatunnel-spark.sh --master yarn --deploy-mode cluster -c config/application.conf
```

### Error Exception

```log
22/04/24 14:27:19 WARN conf.HiveConf: HiveConf of name hive.strict.checks.cartesian.product does not exist
22/04/24 14:27:20 INFO security.AMCredentialRenewer: Scheduling login from keytab in 18.0 h.
22/04/24 14:27:20 INFO yarn.ApplicationMaster: Preparing Local resources
22/04/24 14:27:20 INFO yarn.ApplicationMaster: ApplicationAttemptId: appattempt_1647333129725_263600_000001
22/04/24 14:27:20 INFO yarn.ApplicationMaster: Starting the user application in a separate Thread
22/04/24 14:27:20 INFO yarn.ApplicationMaster: Waiting for spark context initialization...
22/04/24 14:27:20 INFO config.ConfigBuilder: Loading config file: ./config/application.conf
22/04/24 14:27:21 INFO config.ConfigBuilder: parsed config file: {}

22/04/24 14:27:21 ERROR seatunnel.Seatunnel: 

===============================================================================


22/04/24 14:27:21 ERROR seatunnel.Seatunnel: Fatal Error, 

22/04/24 14:27:21 ERROR seatunnel.Seatunnel: Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

22/04/24 14:27:21 ERROR seatunnel.Seatunnel: Reason:No configuration setting found for key 'env' 

22/04/24 14:27:21 ERROR seatunnel.Seatunnel: Exception StackTrace:org.apache.seatunnel.shade.com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'env'
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:268)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:274)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:41)
	at org.apache.seatunnel.config.EnvironmentFactory.getEnvironment(EnvironmentFactory.java:47)
	at org.apache.seatunnel.config.ExecutionContext.<init>(ExecutionContext.java:49)
	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:44)
	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:36)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:48)
	at org.apache.seatunnel.SeatunnelSpark.main(SeatunnelSpark.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:685)
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

image
it can not get file so ERROR seatunnel.Seatunnel: Reason:No configuration setting found for key 'env' 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by whb-bigdata**
## Purpose of this pull request

close #1743 

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Hi, You can add `This close #1743` with `Purpose of this pull request`. So we will know which issue this PR fixed.

File: seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java [hunk 1]
```diff
@@ -230,6 +232,18 @@ protected List<String> buildFinal() {
         appendFiles(commands, this.files);
         appendSparkConf(commands, this.sparkConf);
         appendAppJar(commands);
+        if (this.commandArgs.getDeployMode().getName() == "cluster") {
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: Create a method to cover the logic maybe better?

**Comment by whb-bigdata** [comment]
In cluster mode, when files are uploaded to the cluster, the program only needs the file name to read the files, and does not need multi-level directories.By recognizing the cluster mode, extract the file name after - C / - config to splice Arg again.This close #1743 with Purpose of this pull request.[BenJFan](https://github.com/BenJFan)thank you to help me

File: seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java (hunk 1 above)
Comment (whb-bigdata) [reply seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: Thank you for your advice. I'll change it

**Comment by whb-bigdata** [comment]
[https://github.com/apache/incubator-seatunnel/issues/1743](url)

**Review by whb-bigdata — COMMENTED** [review]
Create a method to cover the logic

File: seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java (hunk 1 above)
Comment (whb-bigdata) [reply seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: can you help me review the code and if ok approve that

File: seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java [hunk 2]
```diff
@@ -293,6 +296,24 @@ protected void appendAppJar(List<String> commands) {
         commands.add(Common.appLibDir().resolve("seatunnel-core-spark.jar").toString());
     }
 
+    /**
+     * change file location to get config file on yarn cluster mode
+     */
+    protected void changeFileLocation() {
+        if ( "cluster".equals(this.commandArgs.getDeployMode().getName())) {
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: Please use `org.apache.seatunnel.common.config.DeployMode`  replace `cluster` string.

Comment (whb-bigdata) [reply seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: Thank you for your suggestion. I have revised and retested the submission

Comment (Hisoka-X) [reply seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: Ok, wait workflows run success. @ruanwenjun Hi wenjun, Can you run workflows?

**Review by ruanwenjun — CHANGES_REQUESTED** [review]
Please add UT and solve the checkstyle error.

**Comment by whb-bigdata** [comment]
solved the checkstyle error

**Comment by whb-bigdata** [comment]
@ruanwenjun i have solved the checkstyle error .can you help me review the code and if ok approve that

**Comment by ruanwenjun** [comment]
> @ruanwenjun i have solved the checkstyle error .can you help me review the code and if ok approve that

Please add Unit test.

File: seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java [hunk 3]
```diff
@@ -293,6 +296,24 @@ protected void appendAppJar(List<String> commands) {
...
+     */
+    protected void changeFileLocation() {
+        if (DeployMode.CLUSTER.getName().equals(this.commandArgs.getDeployMode().getName())) {
+            String regEx = ".+/(.+)$";
+            Pattern p = Pattern.compile(regEx);
+            for (int i = 1; i < args.length; i++) {
+                if ("-c".equals(args[i - 1]) || "--config".equals(args[i - 1])) {
+                    Matcher m = p.matcher(args[i]);
+                    if (m.find()) {
+                        args[i] = m.group(1);
```
Comment (yx91490) [inline seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: this patch seems not graceful enough:(

Comment (yx91490) [reply seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: @ruanwenjun Hi wenjun, in original code: [Waterdrop.java#L71](https://github.com/apache/incubator-seatunnel/blob/b1c722e3632327df3a1d65e391e5b36328c3a1a3/waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/Waterdrop.java#L71), when job is spark cluster mode, path will be replaced with fileName only. in the recently code, Seatunnel.java was refactored and I can't found corresponding code, can you explain the evolution process?

Comment (whb-bigdata) [reply seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: Thank you for your reply .The new version adds the parameters to the back but does not get the file name. Based on this, it can be modified by changing the parameters. Do you have any better suggestions?

**Comment by whb-bigdata** [comment]
@ruanwenjun ,Hi wenjun ,I have addded Unit test.Help  me check the code,Thanks

File: seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java (hunk 3 above)
Comment (ruanwenjun) [reply seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: @yx91490 I will take a look, the spark refractor work is not finished by me.

Comment (ruanwenjun) [reply seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: I find the bug may be caused by line 384, we can use `commandArgs.getConfigFile()` to replace `Paths.get(commandArgs.getConfigFile())`.
https://github.com/apache/incubator-seatunnel/blob/eb6aaad51f95298379b17faac465160bf57b61e2/seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java#L370-L386

Comment (whb-bigdata) [reply seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: Thank you for your suggestion. Is it to extract the path and splice args again?

Comment (ruanwenjun) [reply seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: I didn't test it, but I think you can use `commandArgs.getConfigFile()` to replace `Paths.get(commandArgs.getConfigFile())`, and don't need to do other change.

Comment (whb-bigdata) [reply seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: @yx91490 Thank you for your reply .   https://github.com/apache/incubator-seatunnel/blob/eb6aaad51f95298379b17faac465160bf57b61e2/seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java#L233 .but In the new version, all parameters are added to the later for parsing,So i need get "-c"/"--config" and change the next value(config path).

Comment (whb-bigdata) [reply seatunnel-core/seatunnel-core-spark/src/main/java/org/apache/seatunnel/SparkStarter.java]: @ruanwenjun Thank you for your help.i I want  to use commandArgs.getConfigFile().getFileName.but the function also need to create .so i add commits to explain  what i do .can you help me review the code and if ok approve that

**Comment by ruanwenjun** [comment]
@whb-bigdata Hi, I have modified your patch. I think it's better to not change the user's args, I will get the path to the config based on the mode. Please take a look and help to test.

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Review by ruanwenjun — APPROVED** [review]
