### PR TITLE
[Fix][Flink-starter]Hotfix flink checkpoint default value

### LINKED ISSUE #6986: [Bug] [seatunnel-flink-starter] If checkpoint is not set, data will be lost
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Described in the documentation：
image

I submit the Flink task to Yarn for execution through the following command
```
bin/start-seatunnel-flink-13-connector-v2.sh --config ./config/test.config --master yarn-per-job
```
test.config
```
env {
  parallelism = 2
  job.mode = "STREAMING"
#   flink.execution.checkpointing.interval=5000
}
source {
  Kafka {
    schema = {
      fields {
        comment_num = string
        insert_time = string
        user_info = {
            username = string,
            age = string
        }
      }
    }
    topic = "test-topic"
    consumer.group	= "test-group"
    bootstrap.servers = "xxxx"
    kafka.config = {
      client.id = client_1
      max.poll.records = 500
      auto.offset.reset = "earliest"
      enable.auto.commit = "false"
    }
    result_table_name = "kafka_table"
  }
}



sink {
    Elasticsearch {
        source_table_name = "kafka_table"
        hosts = ["xxxx"]
        index = "test-588"
    }
}
```
I did not set the `flink.execution.checkpointing.interval` parameter in the configuration file, 
The `checkpoint.intercal` parameter is not set in the Flink configuration file.
At this time, writing to ElasticSearch will lose data.

Because ElasticSearch Sink uses the parameter maxBatchSize to submit in batches, it will process uncommitted data through prepareCommit
```
    @Override
    public Optional<ElasticsearchCommitInfo> prepareCommit() {
        bulkEsWithRetry(this.esRestClient, this.requestEsList);
        return Optional.empty();
    }

    @Override
    public void write(SeaTunnelRow element) {
        if (RowKind.UPDATE_BEFORE.equals(element.getRowKind())) {
            return;
        }

        String indexRequestRow = seaTunnelRowSerializer.serializeRow(element);
        requestEsList.add(indexRequestRow);
        if (requestEsList.size() >= maxBatchSize) {
            bulkEsWithRetry(this.esRestClient, this.requestEsList);
        }
    }
```

This may be because the default value of checkpoint.interval is not set in Flink STREAMING mode in the code.
image

If this is a problem, please assign me. 

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
seatunnel.yaml

seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
```
```


### Running Command

```shell
bin/start-seatunnel-flink-13-connector-v2.sh --config ./config/test.config --master yarn-per-job
```

### Error Exception

```log
When the data does not meet the maxBatchSize, the writer will not write the data. This will cause the data to not be flushed.
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhangshenghang**
fix #6986 

- Set Flink default Checkpoint time
- In Flink BATCH mode, there is no need to set Checkpoint because it is useless.

### Check list

* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)

### CODE REVIEW

File: seatunnel-api/src/main/java/org/apache/seatunnel/api/env/EnvCommonOptions.java [hunk 1]
```diff
@@ -54,7 +54,7 @@ public interface EnvCommonOptions {
     Option<Long> CHECKPOINT_INTERVAL =
             Options.key("checkpoint.interval")
                     .longType()
-                    .noDefaultValue()
+                    .defaultValue(10000L)
```
Comment (Hisoka-X) [inline seatunnel-api/src/main/java/org/apache/seatunnel/api/env/EnvCommonOptions.java]: Hi, we should not change the default value. Because no `checkpoint.interval` value and have default value is different. The behavior of the two is different.

File: seatunnel-core/seatunnel-flink-starter/seatunnel-flink-13-starter/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java [hunk 2]
```diff
@@ -247,87 +247,84 @@ private void setCheckpoint() {
...
-                        checkpointConfig.setCheckpointingMode(CheckpointingMode.AT_LEAST_ONCE);
-                        break;
-                    default:
-                        log.warn(
-                                "set checkpoint.mode failed, unknown checkpoint.mode [{}],only support exactly-once,at-least-once",
-                                mode);
-                        break;
-                }
-            }
+        CheckpointConfig checkpointConfig = environment.getCheckpointConfig();
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-flink-starter/seatunnel-flink-13-starter/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java]: How about doing some refactoring? Currently there are two copies of the same processing logic.

**Comment by Hisoka-X** [comment]
cc @TyrantLucifer

File: seatunnel-core/seatunnel-flink-starter/seatunnel-flink-13-starter/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java (hunk 2 above)
Comment (zhangshenghang) [reply seatunnel-core/seatunnel-flink-starter/seatunnel-flink-13-starter/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java]: @Hisoka-X Are you saying that these two modules have duplicate code ?
image

Comment (Hisoka-X) [reply seatunnel-core/seatunnel-flink-starter/seatunnel-flink-13-starter/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java]: yes

Comment (zhangshenghang) [reply seatunnel-core/seatunnel-flink-starter/seatunnel-flink-13-starter/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java]: okey， I will optimize it

Comment (zhangshenghang) [reply seatunnel-core/seatunnel-flink-starter/seatunnel-flink-13-starter/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java]: @Hisoka-X The modification is completed, please check it ， thk

File: seatunnel-core/seatunnel-flink-starter/seatunnel-flink-13-starter/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java [hunk 3]
```diff
@@ -185,157 +82,15 @@ private void createStreamTableEnvironment() {
...
-
-    public void registerResultTable(Config config, DataStream<Row> dataStream, String name) {
-        StreamTableEnvironment tableEnvironment = this.getStreamTableEnvironment();
-        if (!TableUtil.tableExists(tableEnvironment, name)) {
-            tableEnvironment.createTemporaryView(
-                    name, tableEnvironment.fromChangelogStream(dataStream));
+    protected void setCheckpoint() {
+        super.setCheckpoint();
+        CheckpointConfig checkpointConfig = environment.getCheckpointConfig();
+        if (config.hasPath(EnvCommonOptions.CHECKPOINT_TIMEOUT.key())) {
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-flink-starter/seatunnel-flink-13-starter/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java]: why not move set checkpoint timeout to abstract environment？

File: seatunnel-core/seatunnel-flink-starter/seatunnel-flink-starter-common/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java [hunk 4]
```diff
@@ -186,158 +82,15 @@ private void createStreamTableEnvironment() {
...
-
-    public void registerResultTable(Config config, DataStream<Row> dataStream, String name) {
-        StreamTableEnvironment tableEnvironment = this.getStreamTableEnvironment();
-        if (!TableUtil.tableExists(tableEnvironment, name)) {
-            tableEnvironment.createTemporaryView(
-                    name, tableEnvironment.fromChangelogStream(dataStream));
+    protected void setCheckpoint() {
+        super.setCheckpoint();
+        CheckpointConfig checkpointConfig = environment.getCheckpointConfig();
+        if (EnvironmentUtil.hasPathAndWaring(config, EnvCommonOptions.CHECKPOINT_TIMEOUT.key())) {
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-flink-starter/seatunnel-flink-starter-common/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java]: it should be same with another runtime environment. I believe it was a mistake.

**Review by Hisoka-X — COMMENTED** [review]
Thanks for update!

File: seatunnel-core/seatunnel-flink-starter/seatunnel-flink-13-starter/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java (hunk 3 above)
Comment (zhangshenghang) [reply seatunnel-core/seatunnel-flink-starter/seatunnel-flink-13-starter/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java]: @Hisoka-X  `flink13-starter` use `config.hasPath(EnvCommonOptions.CHECKPOINT_TIMEOUT.key())`
`flink-starter-common` use `EnvironmentUtil.hasPathAndWaring(config, EnvCommonOptions.CHECKPOINT_TIMEOUT.key())`

The method used in the previous code was different. In the `flink-starter-common` model, a log prompt 
```
log.warn(
                    "the parameter '{}' will be deprecated, please use the 'flink.' prefix with the flink official configuration item to set it",
                    configKey);
```
The developers may have designed it this way, so I didn't make any changes.
If they need to be unified, I can modify it

File: seatunnel-core/seatunnel-flink-starter/seatunnel-flink-starter-common/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java (hunk 4 above)
Comment (zhangshenghang) [reply seatunnel-core/seatunnel-flink-starter/seatunnel-flink-starter-common/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java]: > it should be same with another runtime environment. I believe it was a mistake.

[https://github.com/apache/seatunnel/pull/7040#discussion_r1669436408](https://github.com/apache/seatunnel/pull/7040#discussion_r1669436408)
Can you help me confirm this? If there is any problem, I will modify them to be the same.

Comment (Hisoka-X) [reply seatunnel-core/seatunnel-flink-starter/seatunnel-flink-starter-common/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java]: Yes. Please use `if (config.hasPath(EnvCommonOptions.CHECKPOINT_TIMEOUT.key())) {`.

Comment (zhangshenghang) [reply seatunnel-core/seatunnel-flink-starter/seatunnel-flink-starter-common/src/main/java/org/apache/seatunnel/core/starter/flink/execution/FlinkRuntimeEnvironment.java]: > Yes. Please use `if (config.hasPath(EnvCommonOptions.CHECKPOINT_TIMEOUT.key())) {`.

@Hisoka-X modify completed

**Review by Hisoka-X — APPROVED** [review]

**Review by EricJoy2048 — APPROVED** [review]
