### PR TITLE
[Fix][Connecotr-kafka] Fix kafka IllegalArgumentException when offset is -1

### LINKED ISSUE #9375: [Bug] [connecotr-kafka] kafka report IllegalArgumentException
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

where start_mode is timestamp ,some kafka topic partition offset is -1,
then job error,the message is 
`
java.lang.IllegalArgumentException: seek offset must not be a negative number
at org.apache.kafka.clients.consumer.KafkaConsumer.seek(KafkaConsumer.java:1924)
`

### SeaTunnel Version

2.3.10

### SeaTunnel Config

```conf
# Defining the runtime environment
env {
  parallelism = 2
  job.mode = "BATCH"
}
source {
  Kafka {
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
    start_mode =timestamp
    topic = "topic_1"
    bootstrap.servers = "localhost:9092"
    
  }  
}
sink {
  Console {}
}
```

### Running Command

```shell
none
```

### Error Exception

```log
java.lang.IllegalArgumentException: seek offset must not be a negative number
at org.apache.kafka.clients.consumer.KafkaConsumer.seek(KafkaConsumer.java:1924)
```

### Zeta or Flink or Spark Version

flink 

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by WenDing-Y**
### Purpose of this pull request

fix #9375 

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java [hunk 1]
```diff
@@ -160,9 +161,16 @@ public void startUp() throws Exception {
                     new NewTopic("test_topic_source_timestamp", 1, (short) 1);
             testTopicSourceWithTimestamp.configs(Collections.singletonMap("retention.ms", "-1"));
 
+            NewTopic testTopicSourceSkipPartition =
+                    new NewTopic("test_topic_source_skip_partition", 2, (short) 1);
+            testTopicSourceWithTimestamp.configs(Collections.singletonMap("retention.ms", "-1"));
```
[the remark this answers is not in the document]
Comment (WenDing-Y) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java]: done

File: seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/serialize/DefaultSeaTunnelRowSerializer.java [hunk 2]
```diff
@@ -100,7 +100,7 @@ public static DefaultSeaTunnelRowSerializer create(
             ReadonlyConfig pluginConfig) {
         return new DefaultSeaTunnelRowSerializer(
                 topicExtractor(topic, rowType, format),
-                partitionExtractor(null),
+                partitionNativeExtractor(rowType),
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/serialize/DefaultSeaTunnelRowSerializer.java:103]: I find this method only used by test case. Could you move it into `KafkaIT`?

Comment (WenDing-Y) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/serialize/DefaultSeaTunnelRowSerializer.java:103]: the all method  in DefaultSeaTunnelRowSerializer,only remove new DefaultSeaTunnelRowSerializer () not work

```java
topicExtractor(topic, rowType, format),
                partitionNativeExtractor(rowType),
                timestampExtractor(rowType),
                keyExtractor(null, rowType, format, null, null),
                valueExtractor(rowType, format, delimiter, pluginConfig),
                headersExtractor()
```

Comment (Hisoka-X) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/serialize/DefaultSeaTunnelRowSerializer.java:103]: Ok, let's change the method name `create` to `createWithPartitionAndTimestampFields`

Comment (WenDing-Y) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/serialize/DefaultSeaTunnelRowSerializer.java:103]: done

**Comment by Hisoka-X** [comment]
cc @Carl-Zhou-CN as well.

**Review by Hisoka-X — APPROVED** [review]
LGTM if ci passes. Thanks @WenDing-Y

File: seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceSplitEnumerator.java [hunk 3]
```diff
@@ -204,6 +204,10 @@ private void setPartitionStartOffset() throws ExecutionException, InterruptedExc
                     if (pendingSplit.containsKey(key)) {
                         pendingSplit.get(key).setStartOffset(value);
                     }
+                    if (!isStreamingMode && value < 0) {
```
Comment (Carl-Zhou-CN) [inline seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceSplitEnumerator.java:207]: Will it only happen in batch jobs

Comment (WenDing-Y) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceSplitEnumerator.java:207]: Yes, this logic only applies to batch processing scenarios. In the case of stream processing, since tasks run continuously and the source data may also change over time, skipping certain partitions carelessly could lead to unexpected or strange issues.

Comment (Carl-Zhou-CN) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceSplitEnumerator.java:207]: Could you help add a corresponding E2E IT for the streaming task as well

Comment (WenDing-Y) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceSplitEnumerator.java:207]: What should be the focus of the test? When the offset is -1, can all partitions be consumed normally without any partition being skipped?

Comment (Carl-Zhou-CN) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceSplitEnumerator.java:207]: Sorry, I see that the existing tests have already covered this scenario,Thanks @WenDing-Y

**Review by Carl-Zhou-CN — APPROVED** [review]
LGTM
