### PR TITLE
[Fix] [Kafka Source] kafka source use topic as table name instead of fullName

### LINKED ISSUE #8396: [Bug] [Kafka Source] Failed when the consume topic name like a.b.c.d
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When consume topic name has more than 2 `.`, will got exception.

the code is: 
https://github.com/apache/seatunnel/blob/dev/seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceConfig.java#L208

https://github.com/apache/seatunnel/blob/dev/seatunnel-api/src/main/java/org/apache/seatunnel/api/table/catalog/TablePath.java#L53

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
read kafka, topic name is `a.b.c.d`
```

### Running Command

```shell
na
```

### Error Exception

```log
Cannot get split '%s' to get databaseName and tableName
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Cheun99**
### Purpose of this pull request

resolve https://github.com/apache/seatunnel/issues/8396

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — DISMISSED** [review]
LGTM if ci passes.

File: seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceConfig.java [hunk 1]
```diff
@@ -205,7 +205,8 @@ private ConsumerMetadata createConsumerMetadata(ReadonlyConfig readonlyConfig) {
     private CatalogTable createCatalogTable(ReadonlyConfig readonlyConfig) {
         Optional<Map<String, Object>> schemaOptions =
                 readonlyConfig.getOptional(TableSchemaOptions.SCHEMA);
-        TablePath tablePath = TablePath.of(readonlyConfig.get(TOPIC));
+        String topic = readonlyConfig.get(TOPIC).replace(".", "_");
+        TablePath tablePath = TablePath.of("kafka", topic);
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceConfig.java]: Hi why not use `TablePath.of("kafka", readonlyConfig.get(TOPIC))`?

Comment (Cheun99) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceConfig.java]: https://github.com/apache/seatunnel/blob/dev/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/task/flow/SinkFlowLifeCycle.java#L132

If the kafka topic name contains more than 3 points, when this line of code is executed, it will still be separated by points. If the element is greater than 3, IllegalArgumentException will still be thrown

Comment (Hisoka-X) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceConfig.java]: I think we should fix it. We can save the TablePath directly instead of the corresponding string in `SinkFlowLifeCycle`.

Comment (Cheun99) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceConfig.java]: I tried to save the TablePath  before, but it involved other files and many of them were modified

Comment (Hisoka-X) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceConfig.java]: Never mind. Please commit it then we can review it together.

Comment (Cheun99) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceConfig.java]: @Hisoka-X Hi，pls have a review

File: seatunnel-engine/seatunnel-engine-core/src/main/java/org/apache/seatunnel/engine/core/parse/MultipleTableJobConfigParser.java [hunk 2]
```diff
@@ -657,16 +658,18 @@ private static <T> T findLast(LinkedHashMap<?, T> map) {
...
                 sinkActions.stream()
                         .flatMap(a -> a.getJarUrls().stream())
                         .collect(Collectors.toSet());
         sinkActions.forEach(
                 action -> {
                     SeaTunnelSink sink = action.getSink();
-                    String tableId = action.getConfig().getMultipleRowTableId();
-                    sinks.put(tableId, sink);
+                    //                    String tableId =
+                    // action.getConfig().getMultipleRowTableId();
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-core/src/main/java/org/apache/seatunnel/engine/core/parse/MultipleTableJobConfigParser.java]:
```suggestion
```

File: seatunnel-engine/seatunnel-engine-core/src/main/java/org/apache/seatunnel/engine/core/dag/actions/SinkConfig.java [hunk 3]
```diff
@@ -25,5 +27,6 @@
 @NoArgsConstructor
 @AllArgsConstructor
 public class SinkConfig implements Config {
-    private String multipleRowTableId;
+    //    private String multipleRowTableId;
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-core/src/main/java/org/apache/seatunnel/engine/core/dag/actions/SinkConfig.java]:
```suggestion
```

**Comment by Hisoka-X** [comment]
Overall LGTM. Let's waiting to check the ci result.

**Review by Hisoka-X — COMMENTED** [review]
But you lost the change of kafka and test case.

**Comment by Cheun99** [comment]
> But you lost the change of kafka and test case.

ok, I will delete the comment  code you just mentioned and add  kafka test case

**Comment by Cheun99** [comment]
> But you lost the change of kafka and test case.
@Hisoka-X Hi，I see that all the test cases have been executed successfully, but only one has failed. I have tried multiple times but have not seen any detailed error logs. However, it has failed. What should I do next。
https://github.com/Cheun99/seatunnel/actions/runs/12721493790/job/35505507161

**Comment by Cheun99** [comment]
When I run test cases, it always times out. This method took too much time, so I reduced the data volume of the mock and the size of the test cases from 100 to 10

image

https://github.com/apache/seatunnel/blob/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java#L282

**Review by liunaijie — APPROVED** [review]
LGTM

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java [hunk 4]
```diff
@@ -295,7 +315,7 @@ public void testSourceKafkaJsonFormatErrorHandleWaySkipToConsole(TestContainer c
                         DEFAULT_FORMAT,
                         DEFAULT_FIELD_DELIMITER,
                         null);
-        generateTestData(serializer::serializeRow, 0, 100);
+        generateTestData(serializer::serializeRow, 0, 10);
```
Comment (Cheun99) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java:318]: When I run test cases, it always times out. This method took too much time, so I reduced  the size of the mock data from 100 to 10

image

**Review by Hisoka-X — APPROVED** [review]
