### PR TITLE
[Bug] [seatunnel-connector-flink-fake] Type is not supported: BigInteger

### LINKED ISSUE #2114: [Bug] [seatunnel-connector-flink-fake] Type is not supported: BigInteger
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

TableException throws when run seatunnel config below.
if i remove result_table_name parameter , the job is running well 

### SeaTunnel Version

2.1.2

### SeaTunnel Config

```conf
{
  "env": {
    "job.name": "dev_sample"
  },
  "source": [
    {
      "mock_data_schema": [
        {
          "name": "col_3",
          "type": "bigint"
        }
      ],
      "mock_data_size": "3000",
      "plugin_name": "FakeSource",
      "result_table_name": "table_54"
    }
  ],
  "transform": [],
  "sink": [
    {
      "limit": "10000",
      "plugin_name": "ConsoleSink",
      "source_table_name": "table_54"
    }
  ]
}
```

### Running Command

```shell
LocalFlinkExample
```

### Error Exception

```log
ERROR Seatunnel: Exception StackTrace:java.lang.RuntimeException: Execute Flink task error
	at org.apache.seatunnel.core.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:84)
	at org.apache.seatunnel.core.base.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.example.flink.LocalFlinkExample.main(LocalFlinkExample.java:40)
Caused by: org.apache.flink.table.api.TableException: Type is not supported: BigInteger
	at org.apache.flink.table.calcite.FlinkTypeFactory$.org$apache$flink$table$calcite$FlinkTypeFactory$$typeInfoToSqlTypeName(FlinkTypeFactory.scala:389)
	at org.apache.flink.table.calcite.FlinkTypeFactory.createTypeFromTypeInfo(FlinkTypeFactory.scala:67)
	at org.apache.flink.table.calcite.FlinkTypeFactory$$anonfun$buildLogicalRowType$1.apply(FlinkTypeFactory.scala:212)
	at org.apache.flink.table.calcite.FlinkTypeFactory$$anonfun$buildLogicalRowType$1.apply(FlinkTypeFactory.scala:202)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.apache.flink.table.calcite.FlinkTypeFactory.buildLogicalRowType(FlinkTypeFactory.scala:202)
	at org.apache.flink.table.calcite.FlinkTypeFactory.buildLogicalRowType(FlinkTypeFactory.scala:185)
	at org.apache.flink.table.catalog.QueryOperationCatalogViewTable.lambda$createCalciteTable$3(QueryOperationCatalogViewTable.java:69)
	at org.apache.flink.table.catalog.QueryOperationCatalogViewTable.getRowType(QueryOperationCatalogViewTable.java:114)
	at org.apache.calcite.prepare.CalciteCatalogReader.getTable(CalciteCatalogReader.java:130)
	at org.apache.calcite.prepare.CalciteCatalogReader.getTableForMember(CalciteCatalogReader.java:229)
	at org.apache.calcite.prepare.CalciteCatalogReader.getTableForMember(CalciteCatalogReader.java:83)
	at org.apache.calcite.tools.RelBuilder.scan(RelBuilder.java:1094)
	at org.apache.calcite.tools.RelBuilder.scan(RelBuilder.java:1123)
	at org.apache.flink.table.plan.QueryOperationConverter$SingleRelVisitor.visit(QueryOperationConverter.java:284)
	at org.apache.flink.table.plan.QueryOperationConverter$SingleRelVisitor.visit(QueryOperationConverter.java:140)
	at org.apache.flink.table.operations.CatalogQueryOperation.accept(CatalogQueryOperation.java:68)
	at org.apache.flink.table.plan.QueryOperationConverter.defaultMethod(QueryOperationConverter.java:137)
	at org.apache.flink.table.plan.QueryOperationConverter.defaultMethod(QueryOperationConverter.java:118)
	at org.apache.flink.table.operations.utils.QueryOperationDefaultVisitor.visit(QueryOperationDefaultVisitor.java:92)
	at org.apache.flink.table.operations.CatalogQueryOperation.accept(CatalogQueryOperation.java:68)
	at org.apache.flink.table.calcite.FlinkRelBuilder.tableOperation(FlinkRelBuilder.scala:121)
	at org.apache.flink.table.api.internal.BatchTableEnvImpl.translate(BatchTableEnvImpl.scala:568)
	at org.apache.flink.table.api.internal.BatchTableEnvImpl.translate(BatchTableEnvImpl.scala:552)
	at org.apache.flink.table.api.bridge.java.internal.BatchTableEnvironmentImpl.toDataSet(BatchTableEnvironmentImpl.scala:106)
	at org.apache.seatunnel.flink.util.TableUtil.tableToDataSet(TableUtil.java:50)
	at org.apache.seatunnel.flink.batch.FlinkBatchExecution.fromSourceTable(FlinkBatchExecution.java:105)
	at org.apache.seatunnel.flink.batch.FlinkBatchExecution.start(FlinkBatchExecution.java:70)
	at org.apache.seatunnel.core.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:81)
	... 2 more
```

### Flink or Spark Version

flink ：1.13

### Java or Scala Version

1.8

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gleiyu**
## Purpose of this pull request

fix : https://github.com/apache/incubator-seatunnel/issues/2114

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

File: seatunnel-connectors/seatunnel-connectors-flink/seatunnel-connector-flink-fake/src/main/java/org/apache/seatunnel/flink/fake/source/MockSchema.java [hunk 1]
```diff
@@ -132,6 +132,7 @@ public TypeInformation<?> typeInformation() {
                 dataType = BasicTypeInfo.SHORT_TYPE_INFO;
                 break;
             case "long":
+            case "bigint":
```
Comment (ruanwenjun) [inline seatunnel-connectors/seatunnel-connectors-flink/seatunnel-connector-flink-fake/src/main/java/org/apache/seatunnel/flink/fake/source/MockSchema.java:134]: I don't think we need to add `bigint`, since we already has `BigInteger`, and I see the [Jmock doc](https://github.com/jsonzou/jmockdata#java对象), they did support `bigint`.

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: seatunnel-connectors/seatunnel-connectors-flink/seatunnel-connector-flink-fake/src/main/java/org/apache/seatunnel/flink/fake/source/MockSchema.java (hunk 1 above)
Comment (gleiyu) [reply seatunnel-connectors/seatunnel-connectors-flink/seatunnel-connector-flink-fake/src/main/java/org/apache/seatunnel/flink/fake/source/MockSchema.java:134]: i have try to using biginteger and  produces the same error. 
as a data developer, i usually used bigint in data warehouse , and it's as same as long in java .

Comment (gleiyu) [reply seatunnel-connectors/seatunnel-connectors-flink/seatunnel-connector-flink-fake/src/main/java/org/apache/seatunnel/flink/fake/source/MockSchema.java:134]: I think that most users of seatunnel are data developers , they are more familiar with the data types in the database and may not know java at all .

Comment (ruanwenjun) [reply seatunnel-connectors/seatunnel-connectors-flink/seatunnel-connector-flink-fake/src/main/java/org/apache/seatunnel/flink/fake/source/MockSchema.java:134]: Yes, use bigint is better, and I check the [seatunnel doc](https://seatunnel.apache.org/docs/2.1.2/connector/source/Fake#mock_data_schema-option--listcolumn_config), there are already support bigint.

You get the error is due to ST will generate BigInteger but flink doesn't support BitInteger, so you need to change the line 239.
```java
mockData = JMockData.mock(Long.class, mockConfig);
```

Comment (gleiyu) [reply seatunnel-connectors/seatunnel-connectors-flink/seatunnel-connector-flink-fake/src/main/java/org/apache/seatunnel/flink/fake/source/MockSchema.java:134]: it's still not work until change TypeInformation defined in line 154  `dataType = BasicTypeInfo.LONG_TYPE_INFO;`
so can we remove biginteger and set bigint as same as long ?

Comment (ruanwenjun) [reply seatunnel-connectors/seatunnel-connectors-flink/seatunnel-connector-flink-fake/src/main/java/org/apache/seatunnel/flink/fake/source/MockSchema.java:134]: I think we can, the BigInteger cannot work may due to the version of table api.

**Review by ruanwenjun — APPROVED** [review]
LGTM
