### PR TITLE
[bigfix][S3 File]:Change the [SCHEMA] attribute of the [S3CONF class] to be non-static to avoid being reassigned after deserialization

### LINKED ISSUE #6678: [Bug] [S3File] [zeta-local] Error writing to S3File in version 2.3.4:: Java lang. An IllegalStateException: Connection pool shut down
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When jdbc- > s3File is executed using the local mode, it occurs sporadically, good and bad in most cases, but there is no problem with using the cluster mode: 
image

I probably searched for this error about using aws-sdk: Connection pool shut down, the related issues is https://github.com/awslabs/amazon-sqs-java-messaging-lib/issues/96. 
It mentions the problem of multithreaded connection pooling, so I initially guess whether it is possible that there is a [aggregate commit] operation after [S3file] executes the [sink] operation, but the [sink] operation executes the close method, which causes the [rename] of [commit] to report an error, indicating that the connection pool is closed, but why the lcoal mode is good and bad, the cluster mode is not a problem. 
And I've tried the 2.3.3 local mode, and that's not the case.
[error.txt](https://github.com/apache/seatunnel/files/14928339/error.txt)

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
	Jdbc {
		result_table_name = "TEST_100W"
		query = "select * from SYSDBA.TEST_100W limit 10"
		fetch_size = 5000
		table_path = "SYSDBA.TEST_100W"
		driver = "com.mysql.cj.jdbc.Driver"
		url = "jdbc:mysql://10.28.23.xxx:3306/test"
		user = "test"
		password ="xxx"
	} 
}
sink {
  S3File {
    source_table_name = "aa"
    path = "/xugurtp/seatunnel/tmp/6af80b38f3434aceb573cc65b9cd12216a/3918"
    bucket = "s3a://xugurtp"
    fs.s3a.endpoint = "http://10.28.23.xxx:9010"
    fs.s3a.aws.credentials.provider = "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    access_key = "xxxx"
    secret_key = "xxxxxxx"
    custom_filename = true
    file_name_expression = "output_params"
    file_format_type = "json"
    is_enable_transaction = false
    ##sink_columns = ["ID"]
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh  -e local --config job/s3_sink.conf
```

### Error Exception

```log
2024-04-10 14:02:28,387 ERROR [.c.FileSinkAggregatedCommitter] [hz.main.generic-operation.thread-43] - commit aggregatedCommitInfo error, aggregatedCommitInfo = FileAggregatedCommitInfo(transactionMap={/tmp/seatunnel/seatunnel/830321799827816449/3eff006528/T_830321799827816449_3eff006528_0_1={/tmp/seatunnel/seatunnel/830321799827816449/3eff006528/T_830321799827816449_3eff006528_0_1/NON_PARTITION/output_params_0.json=/xugurtp/seatunnel/tmp/6af80b38f3434aceb573cc65b9cd12216a/3918/output_params_0.json}}, partitionDirAndValuesMap={}) 
java.lang.IllegalStateException: Connection pool shut down
        at com.amazonaws.thirdparty.apache.http.util.Asserts.check(Asserts.java:34) ~[aws-java-sdk-bundle-1.11.271.jar:?]
        at com.amazonaws.thirdparty.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:184) ~[aws-java-sdk-bundle-1.11.271.jar:?]
        at com.amazonaws.thirdparty.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:251) ~[aws-java-sdk-bundle-1.11.271.jar:?]
```

### Zeta or Flink or Spark Version

local模式

### Java or Scala Version

1.8

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by LeonYoah**
### Purpose of this pull request

fix bug : #6678 
The [S3Conf] class in the S3 connector has a statically modified variable [SCHEMA], which causes it to be reassigned after deserialization. I will remove the static modification: 
image
image
close #6678 
### Does this PR introduce _any_ user-facing change?

No

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-connectors-v2/connector-file/connector-file-s3/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/s3/config/S3Conf.java [hunk 1]
```diff
@@ -73,13 +77,13 @@ public static HadoopConf buildWithConfig(Config config) {
 
     public static HadoopConf buildWithReadOnlyConfig(ReadonlyConfig readonlyConfig) {
         Config config = readonlyConfig.toConfig();
-        HadoopConf hadoopConf = new S3Conf(readonlyConfig.get(S3ConfigOptions.S3_BUCKET));
-        String bucketName = readonlyConfig.get(S3ConfigOptions.S3_BUCKET);
+        String bucketName = config.getString(S3ConfigOptions.S3_BUCKET.key());
```
Comment (EricJoy2048) [inline seatunnel-connectors-v2/connector-file/connector-file-s3/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/s3/config/S3Conf.java]: Can reuse the code above:

```
return buildWithReadOnlyConfig(readonlyConfig.toConfig);

```

**Review by EricJoy2048 — APPROVED** [review]
LGTM, waiting for CI complete.

**Review by hailin0 — APPROVED** [review]
