### PR TITLE
[Bug][e2e] the e2e exec error in win10, fix path separator

### LINKED ISSUE #2631: [Bug] [connector-v2] #!/bin/sh need modify to #!/bin/bash
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Such as in file start-seatunnel-flink-new-connector.sh
#!/bin/sh need modify to #!/bin/bash
Because in some Linux  Distributions,sh linked to dash.

### SeaTunnel Version

2.1.3-SNAPSHOT

### SeaTunnel Config

```conf
no
```

### Running Command

```shell
Run FakeSourceToConsoleIT.java
```

### Error Exception

```log
22/09/03 18:28:04 ERROR FlinkContainer: /tmp/flink/seatunnel/bin/start-seatunnel-flink-new-connector.sh: 46: [: 2: unexpected operator
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by laglangyue**
## Purpose of this pull request

when run the e2e in win10 os,and docker in virtual-linux，it will error.
because the separate in win10 is // for paths.
besides the line feed of the start.sh must be \n in linux.

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by laglangyue** [comment]
the lind feed is only in my os, I only need to fix in local

**Comment by laglangyue** [comment]
> the lind feed is only in my os, I only need to fix in local

image

**Comment by liugddx** [comment]
LGTM

**Comment by laglangyue** [comment]
close #2631

File: seatunnel-e2e/seatunnel-spark-connector-v2-e2e/src/test/java/org/apache/seatunnel/e2e/spark/SparkContainer.java [hunk 1]
```diff
@@ -97,7 +97,8 @@ public Container.ExecResult executeSeaTunnelSparkJob(String confFile) throws IOE
         // Running IT use cases under Windows requires replacing \ with /
         String conf = targetConfInContainer.replaceAll("\\\\", "/");
         final List<String> command = new ArrayList<>();
-        command.add(Paths.get(SEATUNNEL_HOME, "bin", SEATUNNEL_SPARK_BIN).toString());
+        String sparkSh = Paths.get(SEATUNNEL_HOME, "bin", SEATUNNEL_SPARK_BIN).toString();
```
Comment (TyrantLucifer) [inline seatunnel-e2e/seatunnel-spark-connector-v2-e2e/src/test/java/org/apache/seatunnel/e2e/spark/SparkContainer.java]: How about change these codes to 
```java
        String sparkBinPath = Paths.get(SEATUNNEL_HOME, "bin", SEATUNNEL_SPARK_BIN).toString()
                        .replaceAll("\\\\", "/");
        command.add(sparkBinPath);
```

Comment (laglangyue) [reply seatunnel-e2e/seatunnel-spark-connector-v2-e2e/src/test/java/org/apache/seatunnel/e2e/spark/SparkContainer.java]: done

File: seatunnel-e2e/seatunnel-spark-connector-v2-e2e/src/test/java/org/apache/seatunnel/e2e/spark/SparkContainer.java [hunk 2]
```diff
@@ -97,7 +97,8 @@ public Container.ExecResult executeSeaTunnelSparkJob(String confFile) throws IOE
         // Running IT use cases under Windows requires replacing \ with /
         String conf = targetConfInContainer.replaceAll("\\\\", "/");
         final List<String> command = new ArrayList<>();
-        command.add(Paths.get(SEATUNNEL_HOME, "bin", SEATUNNEL_SPARK_BIN).toString());
+        String sparkBinPath = Paths.get(SEATUNNEL_HOME, "bin", SEATUNNEL_SPARK_BIN).toString();
+        command.add(sparkBinPath.replaceAll("\\\\", "/"));
```
Comment (TyrantLucifer) [inline seatunnel-e2e/seatunnel-spark-connector-v2-e2e/src/test/java/org/apache/seatunnel/e2e/spark/SparkContainer.java]: Could you please move `replaceAll` method out of `command.add()`? This will make the process clearer.

File: seatunnel-e2e/seatunnel-spark-connector-v2-e2e/connector-spark-e2e-base/src/test/java/org/apache/seatunnel/e2e/spark/SparkContainer.java [hunk 3]
```diff
@@ -98,12 +97,12 @@ public Container.ExecResult executeSeaTunnelSparkJob(String confFile) throws IOE
         String conf = targetConfInContainer.replaceAll("\\\\", "/");
```
Comment (TyrantLucifer) [inline seatunnel-e2e/seatunnel-spark-connector-v2-e2e/connector-spark-e2e-base/src/test/java/org/apache/seatunnel/e2e/spark/SparkContainer.java]: This line should be removed.

**Review by TyrantLucifer — CHANGES_REQUESTED** [review]

File: seatunnel-e2e/seatunnel-spark-connector-v2-e2e/connector-spark-e2e-base/src/test/java/org/apache/seatunnel/e2e/spark/SparkContainer.java (hunk 3 above)
Comment (laglangyue) [reply seatunnel-e2e/seatunnel-spark-connector-v2-e2e/connector-spark-e2e-base/src/test/java/org/apache/seatunnel/e2e/spark/SparkContainer.java]: done

**Review by TyrantLucifer — APPROVED** [review]
LGTM.
