### PR TITLE
[Fix][Connector-V2] Fix iceberg throw java: package sun.security.krb5 does not exist when use jdk 11

### LINKED ISSUE #7731: [Bug] [Iceberg] java: package sun.security.krb5 does not exist
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

An exception occurred while using JDK 11.
image

Don't refrence directly
image

### SeaTunnel Version

jdk 11

### SeaTunnel Config

```conf
org/apache/seatunnel/e2e/connector/iceberg/IcebergSinkCDCIT.java
```

### Running Command

```shell
org/apache/seatunnel/e2e/connector/iceberg/IcebergSinkCDCIT.java
```

### Error Exception

```log
java: package sun.security.krb5 does not exist
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by sunxiaojian**
### Purpose of this pull request

closed https://github.com/apache/seatunnel/issues/7731

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/IcebergCatalogLoader.java [hunk 1]
```diff
@@ -170,11 +169,10 @@ public static void doKerberosAuthentication(
                         "Start Kerberos authentication using principal {} and keytab {}",
                         principal,
                         keytabPath);
-                sun.security.krb5.Config.refresh();
```
Comment (hailin0) [inline seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/IcebergCatalogLoader.java:173]: Is this logic invalid?

Comment (sunxiaojian) [reply seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/IcebergCatalogLoader.java:173]: > Is this logic invalid?

@hailin0   when using loginUserFromKeytabAndReturnUGI, refreshKrb5Config=true will be added by default. So I think there is no need to call refresh

Comment (dailai) [reply seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/IcebergCatalogLoader.java:173]: If your application is running and you modify the krb5.conf file at the same time. LoginUserFromKeytabAndReturnUGI will not reload the changes. It will only read and load the current Kerberos configuration when the application starts.

I think the correct way to modify it is to find out why this error is reported instead of directly removing it

Comment (sunxiaojian) [reply seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/IcebergCatalogLoader.java:173]: > If your application is running and you modify the krb5.conf file at the same time. LoginUserFromKeytabAndReturnUGI will not reload the changes. It will only read and load the current Kerberos configuration when the application starts.
> 
> I think the correct way to modify it is to find out why this error is reported instead of directly removing it

@dailai Please explain the impact of removing it

Comment (sunxiaojian) [reply seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/IcebergCatalogLoader.java:173]: > If your application is running and you modify the krb5.conf file at the same time. LoginUserFromKeytabAndReturnUGI will not reload the changes. It will only read and load the current Kerberos configuration when the application starts.
> 
> I think the correct way to modify it is to find out why this error is reported instead of directly removing it

@dailai https://github.com/apache/incubator-uniffle/issues/625 ,https://stackoverflow.com/questions/1437281/reload-kerberos-config-in-java-without-restarting-jvm It would be best to explain the necessity of the existence of this code

Comment (dailai) [reply seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/IcebergCatalogLoader.java:173]: > > If your application is running and you modify the krb5.conf file at the same time. LoginUserFromKeytabAndReturnUGI will not reload the changes. It will only read and load the current Kerberos configuration when the application starts.
> > I think the correct way to modify it is to find out why this error is reported instead of directly removing it
> 
> @dailai [apache/incubator-uniffle#625](https://github.com/apache/incubator-uniffle/issues/625) , It would be best to explain the necessity of the existence of this code

It's wight. You can refer this way https://github.com/apache/incubator-uniffle/pull/932

Comment (sunxiaojian) [reply seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/IcebergCatalogLoader.java:173]: > > > If your application is running and you modify the krb5.conf file at the same time. LoginUserFromKeytabAndReturnUGI will not reload the changes. It will only read and load the current Kerberos configuration when the application starts.
> > > I think the correct way to modify it is to find out why this error is reported instead of directly removing it
> > 
> > 
> > @dailai [apache/incubator-uniffle#625](https://github.com/apache/incubator-uniffle/issues/625) , It would be best to explain the necessity of the existence of this code
> 
> It's wight. You can refer this way [apache/incubator-uniffle#932](https://github.com/apache/incubator-uniffle/pull/932)

@dailai  Why not call Config.refresh() JDK>8?   So isn't this necessary?   

Have 2 ways to solve the issue.

- Remove sun.security.krb5.Config.refresh(); code.
- Add --add-exports java.security.jgss/sun.security.krb5=ALL-UNNAMED in the pom.xml of the project.

Firstly, explain the necessity of calling refresh clearly

Comment (dailai) [reply seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/IcebergCatalogLoader.java:173]: My doubt is the method called by loginUserFromKeytabAndReturnUGI which can automatically refresh krb5 conf. If you can prove that it is, I think you directly remove this line of code that is no problem.

Comment (dailai) [reply seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/IcebergCatalogLoader.java:173]: I mean that. @hailin0 It's right. The calling procedure is that:
org.apache.seatunnel.connectors.seatunnel.iceberg.IcebergCatalogLoader#doKerberosAuthentication 
org.apache.hadoop.security.UserGroupInformation#loginUserFromKeytab
org.apache.hadoop.security.UserGroupInformation#loginUserFromKeytabAndReturnUGI
org.apache.hadoop.security.UserGroupInformation#doSubjectLogin
org.apache.hadoop.security.UserGroupInformation#newLoginContext
javax.security.auth.login.LoginContext#LoginContext(java.lang.String, javax.security.auth.Subject, javax.security.auth.callback.CallbackHandler, javax.security.auth.login.Configuration)
javax.security.auth.login.LoginContext#init
org.apache.hadoop.security.UserGroupInformation.HadoopConfiguration#getAppConfigurationEntry
org.apache.hadoop.security.UserGroupInformation.HadoopConfiguration#getKerberosEntry
which made refreshKrb5Config is true

Finally,  org.apache.hadoop.security.UserGroupInformation.HadoopLoginContext#login
call the method named com.sun.security.auth.module.Krb5LoginModule#login
image

**Review by dailai — APPROVED** [review]
LGTM

**Review by hailin0 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]
