### PR TITLE
[Bug] [Seatunnel-Engine] Fix NEP when scheduling sub plan fails.

### LINKED ISSUE #3908: [Bug] [Seatunnel-Engine] when sub plan scheduling  fails，a NPE will happen.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

2023-01-10 06:56:28,409 ERROR org.apache.seatunnel.engine.server.dag.physical.SubPlan - Restore pipeline Job testBatchJobRestoreIn3NodeMasterDown (665086496562216963), Pipeline: [(1/2)] error with exception: java.lang.NullPointerException
	at org.apache.seatunnel.engine.common.utils.PassiveCompletableFuture.<init>(PassiveCompletableFuture.java:30)
	at org.apache.seatunnel.engine.server.master.JobMaster.reSchedulerPipeline(JobMaster.java:260)
	at org.apache.seatunnel.engine.server.dag.physical.SubPlan.restorePipeline(SubPlan.java:347)
	at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlan.lambda$addPipelineEndCallback$1(PhysicalPlan.java:154)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at java.lang.Thread.run(Thread.java:750)

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
2023-01-10 06:56:28,409 ERROR org.apache.seatunnel.engine.server.dag.physical.SubPlan - Restore pipeline Job testBatchJobRestoreIn3NodeMasterDown (665086496562216963), Pipeline: [(1/2)] error with exception: java.lang.NullPointerException
	at org.apache.seatunnel.engine.common.utils.PassiveCompletableFuture.<init>(PassiveCompletableFuture.java:30)
	at org.apache.seatunnel.engine.server.master.JobMaster.reSchedulerPipeline(JobMaster.java:260)
	at org.apache.seatunnel.engine.server.dag.physical.SubPlan.restorePipeline(SubPlan.java:347)
	at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlan.lambda$addPipelineEndCallback$1(PhysicalPlan.java:154)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at java.lang.Thread.run(Thread.java:750)
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liugddx**
close #3908 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by hailin0** [comment]
please fix ci error

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/scheduler/PipelineBaseScheduler.java [hunk 1]
```diff
@@ -99,6 +101,8 @@ private CompletableFuture<Void> schedulerPipeline(SubPlan pipeline) {
                 deployPipeline(pipeline, slotProfiles);
             }, jobMaster.getExecutorService());
         } catch (Exception e) {
+            log.error(String.format("scheduler pipeline [%s] error and cancel pipeline. The error is %s",
```
Comment (EricJoy2048) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/scheduler/PipelineBaseScheduler.java]:
```
log.error(String.format("scheduler %s error and cancel pipeline. The error is %s"), pipeline.getPipelineFullName(), ExceptionUtils.getMessage(e)) 
```

**Comment by liugddx** [comment]
@hailin0 @EricJoy2048 PTAL thanks.

**Comment by hailin0** [comment]
Title: Fix NEP when scheduling sub plan fails

**Review by hailin0 — APPROVED** [review]

**Comment by liugddx** [comment]
> Title: Fix NEP when scheduling sub plan fails

Done.

**Review by ashulin — APPROVED** [review]
LGTM
