### PR TITLE
[Bug][seatunnel-format-json] Fix jackson package conflict with spark

### LINKED ISSUE #2929: [Bug] [Format][JSON]  json-format conflicts with the Jackson version of Spark-2.4.3
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

`json-format` conflicts with the Jackson version of Spark-2.4.3

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
    execution.parallelism = 1
    job.mode = "BATCH"

    #spark config
    spark.app.name = "SeaTunnel"
    spark.executor.instances = 2
    spark.executor.cores = 1
    spark.executor.memory = "1g"
    spark.master = local
}

source {
    Redis {
        host = "redis-e2e"
        port = 6379
        auth = "SeaTunnel"
        keys = "key_test*"
        data_type = key
    }
}

transform {
}

sink {
    Redis {
        host = "redis-e2e"
        port = 6379
        auth = "SeaTunnel"
        key = "key_list"
        data_type = list
    }
}
```

### Running Command

```shell
-
```

### Error Exception

```log
Error: Exception in thread "main" java.lang.NoSuchFieldError: ALLOW_LEADING_DECIMAL_POINT_FOR_NUMBERS
	at com.fasterxml.jackson.core.json.JsonReadFeature.<clinit>(JsonReadFeature.java:121)
	at org.apache.seatunnel.format.json.JsonDeserializationSchema.<init>(JsonDeserializationSchema.java:84)
	at org.apache.seatunnel.connectors.seatunnel.redis.source.RedisSource.prepare(RedisSource.java:74)
	at org.apache.seatunnel.core.starter.spark.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:78)
	at org.apache.seatunnel.core.starter.spark.execution.AbstractPluginExecuteProcessor.<init>(AbstractPluginExecuteProcessor.java:49)
	at org.apache.seatunnel.core.starter.spark.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:49)
	at org.apache.seatunnel.core.starter.spark.execution.SparkExecution.<init>(SparkExecution.java:48)
	at org.apache.seatunnel.core.starter.spark.command.SparkApiTaskExecuteCommand.execute(SparkApiTaskExecuteCommand.java:53)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:40)
	at org.apache.seatunnel.core.starter.spark.SeatunnelSpark.main(SeatunnelSpark.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

### Flink or Spark Version

Spark 2.4.3

### Java or Scala Version

Java 8/11

### Screenshots

image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by hailin0**
## Purpose of this pull request

close #2929

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by hailin0** [comment]
@ashulin PTAL

**Review by ashulin — DISMISSED** [review]
link: https://stackoverflow.com/questions/28946655/invalid-lambda-deserialization-when-lambda-used-for-interface-implementation

**Review by ashulin — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

File: seatunnel-formats/seatunnel-format-json/src/main/java/org/apache/seatunnel/format/json/JsonToRowConverters.java [hunk 1]
```diff
@@ -83,33 +86,103 @@ private JsonToRowConverter createNotNullConverter(SeaTunnelDataType<?> type) {
             case ROW:
                 return createRowConverter((SeaTunnelRowType) type);
             case NULL:
-                return jsonNode -> null;
+                return new JsonToRowConverter() {
```
Comment (Hisoka-X) [inline seatunnel-formats/seatunnel-format-json/src/main/java/org/apache/seatunnel/format/json/JsonToRowConverters.java:89]: Add comment about why not use lambda.

Comment (ashulin) [reply seatunnel-formats/seatunnel-format-json/src/main/java/org/apache/seatunnel/format/json/JsonToRowConverters.java:89]: https://stackoverflow.com/questions/28946655/invalid-lambda-deserialization-when-lambda-used-for-interface-implementation @Hisoka-X

Comment (Hisoka-X) [reply seatunnel-formats/seatunnel-format-json/src/main/java/org/apache/seatunnel/format/json/JsonToRowConverters.java:89]: It is for developers which want change the code.
