### PR TITLE
[Hotfix][Core][Shell] Fix bug that shell script about downloading plugins does not work

### LINKED ISSUE #3461: [Bug][Core][Shell] Fix the bug that plugin download shell dost not work
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The shell of download plugins does not work

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
none
```

### Error Exception

```log
none
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by TyrantLucifer**
## Purpose of this pull request

fix #3461 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

### CODE REVIEW

File: bin/install-plugin.sh [hunk 1]
```diff
@@ -20,38 +20,50 @@
 #All are downloaded by default. You can also choose what you need. 
 #You only need to configure the plug-in name in config/plugin_config.
 
+# get seatunnel home
+SEATUNNEL_HOME=$(cd $(dirname $0);cd ../;pwd)
+
 # connector default version is 2.2.0, you can also choose a custom version. eg: 2.1.2:  sh install-plugin.sh 2.1.2
```
Comment (CalvinKirs) [inline bin/install-plugin.sh:26]: Perhaps the easiest way to determine whether the current `bin` directory or the `root` directory, if it's the `bin` directory, then `cd..` Since we use maven to download the jar, the`maven-wrapper` file must correspond to the directory.

File: bin/install-plugin.sh [hunk 2]
```diff
@@ -20,64 +20,80 @@
...
 	  if [ "$line" = "--connectors-v2--" ]
-	    then 
+	    then
 	  	 path=seatunnel
-	  fi	 
+	  fi
+    if  [ ${line:0:1} != "-" ] && [ ${line:0:1} != "#" ]
+      	then
+      		echo "install connector : " $line
+      		${SEATUNNEL_HOME}/mvnw dependency:get -DgroupId=org.apache.seatunnel -DartifactId=${line} -Dversion=${version} -Ddest=connectors/${path}
```
Comment (CalvinKirs) [inline bin/install-plugin.sh]:
```suggestion
      		${SEATUNNEL_HOME}/mvnw dependency:get -DgroupId=org.apache.seatunnel -DartifactId=${line} -Dversion=${version} -Ddest=${SEATUNNEL_HOME}/connectors/${path}
```
We also need to do this, otherwise the connector installation will still be the current directory

Comment (TyrantLucifer) [reply bin/install-plugin.sh]: Done. Thank you for your review.

**Review by CalvinKirs — APPROVED** [review]

**Review by wuchunfu — APPROVED** [review]
