### PR TITLE
[Fix][Zeta] Fix release slot resource twice

### LINKED ISSUE #7210: [Bug] [Zeta ] Repeatedly releasing
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Repeatedly releasing solt Zeta will call releaseTaskGroupResource after the normal task is completed
Release PipeResource This will result in duplicate release of solt
image

releaseTaskGroupResource   Should it be for optimizing the release of resources during idle tasks in CDC, and should it only be used for CDC tasks
https://github.com/apache/seatunnel/pull/6526

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
no
```

### Running Command

```shell
no
```

### Error Exception

```log
2024-07-16 10:43:20,411 WARN  org.apache.seatunnel.engine.server.resourcemanager.opeartion.ReleaseSlotOperation - wrong target release operation with job 865423301965512705 and slot profile SlotProfile{worker=[localhost]:5801, slotID=2, ownerJobID=865423301965512705, assigned=true, resourceProfile=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=0}}, sequence='45b4e9f2-bbe0-4776-8f72-ea4ded8cf9a1'}, exception: org.apache.seatunnel.engine.server.service.slot.WrongTargetSlotException: Not exist this slot in slot service, slot profile: SlotProfile{worker=[localhost]:5801, slotID=2, ownerJobID=865423301965512705, assigned=true, resourceProfile=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=0}}, sequence='45b4e9f2-bbe0-4776-8f72-ea4ded8cf9a1'}
	at org.apache.seatunnel.engine.server.service.slot.DefaultSlotService.releaseSlot(DefaultSlotService.java:166)
	at org.apache.seatunnel.engine.server.resourcemanager.opeartion.ReleaseSlotOperation.run(ReleaseSlotOperation.java:53)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hisoka-X**
### Purpose of this pull request
This PR fix release slot resource twice. It cause by #6526 

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
add new test.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/task/operation/CheckTaskGroupIsExecutingOperation.java [hunk 1]
```diff
@@ -46,7 +46,8 @@ public void run() {
         SeaTunnelServer server = getService();
         try {
             response =
-                    server.getTaskExecutionService().getExecutionContext(taskGroupLocation) != null;
+                    server.getTaskExecutionService().getActiveExecutionContext(taskGroupLocation)
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/task/operation/CheckTaskGroupIsExecutingOperation.java:49]: Also fixed the incorrect logic of getting the task executing status.

**Review by hailin0 — APPROVED** [review]

**Review by EricJoy2048 — APPROVED** [review]
