### PR TITLE
[HotFix][zeta]: Fix loss job (#6759)

### LINKED ISSUE #6759: [Bug] [seatunnel-engine-server] #5191 bugfix bring loss job
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

image
1. "Set<Long> runningJonIds...." execute complete
2. "job A" just finished
3. "Stream.concat(runningJobMasterMap.values().stream()..." execute complete lost "job A"

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
default config
```

### Running Command

```shell
seatunnel.sh -l
```

### Error Exception

```log
lose job
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by drgonroot**
### Purpose of this pull request
fix loss job #6759

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
test case

### Check list

* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [x] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Thanks @drgonroot for fix this, could you follow the guide to open ci on your fork repository? https://github.com/apache/seatunnel/pull/6807/checks?check_run_id=24679528654

**Review by Hisoka-X — DISMISSED** [review]
LGTM if ci passed.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobHistoryService.java [hunk 1]
```diff
@@ -104,16 +104,17 @@ public JobHistoryService(
         this.finishedJobExpireTime = finishedJobExpireTime;
     }
 
-    // Gets the status of a running and completed job
+    // Gets the status of a running and completed job. (fix loss job 6759)
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobHistoryService.java]:
```suggestion
    // Gets the status of a running and completed job.
```

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]
