### PR TITLE
[Bug][connector-http] Fix paging request running infinitely

### LINKED ISSUE #9442: [Bug] [seatunnel-connector-http-base] PlaceholderReplace Pageing does not replace subsequent placeholder in the loop
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

## Description
I was using `PlaceholderReplacement` pageing to fetch HTTP  API data ,
```text
    pageing={
       page_type="PageNumber"
       use_placeholder_replacement = true 
       page_field = "pageNo"
       batch_size = 100
    }

    body: """ {
      "pageNo": "${pageNo}",
      "pageSize": "100"
    } """
```

However, seatunnel task ran infinitely and always requested for one page. Specifically , seatunnel  sent  request body
```text
body: """ {
      "pageNo": "1",
      "pageSize": "100"
}
```
Here's the log
```text
paging: pageNo=1 pageSize=100
INFO:     127.0.0.1:47260 - "POST /api/items_page HTTP/1.1" 200 OK
paging: pageNo=1 pageSize=100
INFO:     127.0.0.1:47260 - "POST /api/items_page HTTP/1.1" 200 OK
paging: pageNo=1 pageSize=100
INFO:     127.0.0.1:47260 - "POST /api/items_page HTTP/1.1" 200 OK
paging: pageNo=1 pageSize=100
INFO:     127.0.0.1:47260 - "POST /api/items_page HTTP/1.1" 200 OK
paging: pageNo=1 pageSize=100
INFO:     127.0.0.1:47260 - "POST /api/items_page HTTP/1.1" 200 OK
paging: pageNo=1 pageSize=100
INFO:     127.0.0.1:47260 - "POST /api/items_page HTTP/1.1" 200 OK
paging: pageNo=1 pageSize=100
INFO:     127.0.0.1:47260 - "POST /api/items_page HTTP/1.1" 200 OK
paging: pageNo=1 pageSize=100
INFO:     127.0.0.1:47260 - "POST /api/items_page HTTP/1.1" 200 OK
paging: pageNo=1 pageSize=100
INFO:     127.0.0.1:47260 - "POST /api/items_page HTTP/1.1" 200 OK
paging: pageNo=1 pageSize=100
INFO:     127.0.0.1:47260 - "POST /api/items_page HTTP/1.1" 200 OK
```
it failed to increase the `pageNo`. I have to manually kill the task.

## Expected result
Seatunnel would fetch all pages and finish successfully.

## Root cause analysis
The root cause lies in `HttpSourceReader`, method `updateRequestParam` and `processBody`
In  the while loop,  the placeholder in request body is substitued to pageValue in the first iteration, however, in the subsequent replacement, the subsituion failed because placeholder is missing, processBodyString changes request body. 

中文
每次循环时， processBodyString 直接修改 http request body, 造成 placeholder 只能被替换一次，后续的替换失败。因而在分页查询时，pageNo 不递增，陷入死循环。

```java
            Long pageIndex = info.getPageIndex();
            while (!noMoreElementFlag) {
                // increment page
                info.setPageIndex(pageIndex);
                // set request param
                updateRequestParam(info, info.isUsePlaceholderReplacement());
                pollAndCollectData(output);
                pageIndex += 1;
                Thread.sleep(10);
            }

            String processedBody =
                    processBodyString(
                            this.httpParameter.getBody(),
                            pageField,
                            pageValue,
                            usePlaceholderReplacement);

private String processBodyString(
            String bodyString,
            String pageField,
            Object pageValue,
            boolean usePlaceholderReplacement) {
        if (pageField == null || pageValue == null || Strings.isNullOrEmpty(bodyString)) {
            return bodyString;
        }
        if (usePlaceholderReplacement) {
            String unquotedPlaceholder = "${" + pageField + "}";
            if (bodyString.contains(unquotedPlaceholder)) {
                bodyString = bodyString.replace(unquotedPlaceholder, pageValue.toString());
            }

            return bodyString;
        } else {
            // Key-based replacement
            Map<String, Object> bodyMap =
                    JsonUtils.parseObject(bodyString, new TypeReference<Map<String, Object>>() {});
            if (bodyMap != null) {
                processBodyMapRecursively(bodyMap, pageField, pageValue);
                return JsonUtils.toJsonString(bodyMap);
            }
            return bodyString;
        }
    }
```

## Reference
The python HTTP API
from fastapi import FastAPI, HTTPException, Depends, Header, Body
from pydantic import BaseModel, Field

```python
class PagingRequest(BaseModel):
    pageNo: int = Field(..., description="当前页码")
    pageSize: int = Field(..., description="每页记录数")

@app.post("/api/items_page", response_model=ItemResponse)
async def get_items(paging: PagingRequest = Body(..., description="分页请求")):
    """
    获取示例数据列表（分页）
    """
    try:
        # 示例数据
        items = [
            {"id": i, "name": f"用户{i}"} for i in range(1, 1001)
        ]
        print(f"paging: {paging}")
        # 计算分页信息
        total = len(items)
        total_pages = (total + paging.pageSize - 1) // paging.pageSize
        
        # 验证页码
        if paging.pageNo > total_pages:
            return {
            "code": "200",
            "msg": "OK",
            "data": [],
            "total": total,
            "pageNo": paging.pageNo,
            "pageSize": 0,
            "totalPages": total_pages
        }

        # 计算当前页的数据
        start_idx = (paging.pageNo - 1) * paging.pageSize
        end_idx = start_idx + paging.pageSize
        
        return {
            "code": "200",
            "msg": "OK",
            "data": items[start_idx:end_idx],
            "total": total,
            "pageNo": paging.pageNo,
            "pageSize": paging.pageSize,
            "totalPages": total_pages
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
```

### SeaTunnel Version

Seatunnel 2.3.11

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  Http {    
    url = "http://localhost:8000/api/items_page"
    method = "POST"
    format = "json"
    headers {
      "Content-Type" = "application/json"
    }
    body: """ {
      "pageNo": "${pageNo}",
      "pageSize": "100"
    } """
    json_field {
      id = "$.data[*].id"
      name = "$.data[*].name"
    }
    schema {
      fields {
        id = "string"
        name = "string"
      }
    }
    pageing={
       page_type="PageNumber"
       use_placeholder_replacement = true 
       page_field = "pageNo"
       batch_size = 100
    }
  }
}


sink {
  Doris {
    fenodes = "192.168.1.236:8030"
    username = hello
    password = "password"
    database = "test"
    table = "test_http"
    sink.label-prefix = "test-doris"
    sink.enable-delete = "false"
    doris.config {
      format = "json"
      read_json_by_line = "true"
    }
    plugin_input = "fake_table"
  }
}
```

### Running Command

```shell
Assuming config file is `http_paging.config`

${SEATUNNEL_HOME}/bin/seatunnel.sh --deploy-mode local -c http_paging.config
```

### Error Exception

```log
The job runs infiniely.
```

### Zeta or Flink or Spark Version

Zeta engine, runns locally. However, the issue should effect spark/flink engine as well.

### Java or Scala Version

openJDK 17
```
openjdk version "17.0.14" 2025-01-21
OpenJDK Runtime Environment OpenLogic-OpenJDK (build 17.0.14+7-adhoc.root.jdk17u)
OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (build 17.0.14+7-adhoc.root.jdk17u, mixed mode, sharing)
```

### Screenshots

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by chncaesar**
### Purpose of this pull request
This PR close #9442

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
The code change is covered by unit-test testInternalPollNextWithBodyPlaceholderBatchSize in HttpSourceReaderUpdateRequestParamTest.
mvn clean package install -am  -Pci
image

### Check list

* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

**Review by corgy-w — DISMISSED** [review]
Thank you for your contribution

File: seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java [hunk 1]
```diff
@@ -337,14 +334,16 @@ public void internalPollNext(Collector<SeaTunnelRow> output) throws Exception {
             if (pageInfoOptional.isPresent()) {
                 noMoreElementFlag = false;
                 PageInfo info = pageInfoOptional.get();
+                if (!Strings.isNullOrEmpty(this.httpParameter.getBody())) {
+                    this.rawBody = this.httpParameter.getBody();
+                }
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java]: Could move the behavior of set `rawBody` value into constructer?

Comment (chncaesar) [reply seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java]: Code is updated, please take a look.

Comment (chncaesar) [reply seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java]: @Hisoka-X Please take a look at your earliest convenience

**Review by Hisoka-X — COMMENTED** [review]
Thanks @chncaesar for update. Could you add a unit test to simulate a loop to dynamically update the requestbody? There seems to be no unit test that can prove that the requestbody will be dynamically updated after executing the request multiple times.

**Comment by chncaesar** [comment]
> Thanks @chncaesar for update. Could you add a unit test to simulate a loop to dynamically update the requestbody? There seems to be no unit test that can prove that the requestbody will be dynamically updated after executing the request multiple times.

Hi @Hisoka-X , that's is really good idea, i've added a new unit test case in `HttpSourceReaderInternalPollNextTest` . Thank you for your precious time to review this PR. Please take another look.

**Comment by corgy-w** [comment]
Hi @chncaesar resolve the conflict

File: seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java [hunk 2]
```diff
@@ -337,14 +336,16 @@ public void internalPollNext(Collector<SeaTunnelRow> output) throws Exception {
...
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java]: Why we still need set `rawBody` in here but we already set it in constructer?

Comment (chncaesar) [reply seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java]: My bad, something went wrong during the code merge.

**Review by Hisoka-X — APPROVED** [review]
Thanks @chncaesar

**Review by corgy-w — APPROVED** [review]
