### PR TITLE
[Fix][Connector-Jdbc]Fixed Vertica data source cannot upsert data.

### LINKED ISSUE #9534: [Bug] [Module Name] vertica sink 使用generate_sink_sql无法通过主键进行更新
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

sink config中：
generate_sink_sql = true
primary_keys = ["id"]
vertica jdbc使用8.x、12.x、24.x，都会在实际插入数据时，不管主键是否存在重复值，都会报错：
Caused by: com.vertica.util.ClientSyntaxErrorException: [Vertica][VJDBC](2848) ERROR: Could not determine data type of parameter $1
上述报错是在将表中字段全部改成string之后的，若是表中存在int类型或date类型字段，报错稍有不同：
Caused by: java.sql.SQLException: [Vertica][VJDBC](https://github.com/apache/seatunnel/3376) ERROR: Failed to find conversion function from unknown to date
或
Caused by: com.vertica.support.exceptions.ErrorException: [Vertica][VJDBC](https://github.com/apache/seatunnel/3376) ERROR: Failed to find conversion function from unknown to int

### SeaTunnel Version

2.3.9

### SeaTunnel Config

```conf
env {
    parallelism = 1
    checkpoint.interval = 120000
    job.name= "kafka-seatunnel-vertia"
    job.mode= "STREAMING"
}

source {
    kafka {
        plugin_output = "kafka_out"
        bootstrap.servers = "127.0.0.1:9092,127.0.0.2:9092,127.0.0.3:9092"
        topic = "input-test"
        consumer.group = "test-group"
        format = json
        partition-discovery.interval-millis = 60000
        commit_on_checkpoint = true
        start_mode = group_offsets
        kafka.config = {
            client.id = test-group
            max.poll.records = 10
            auto.offset.reset = "latest"
            enable.auto.commit = "false"
        }
        schema = {
            fields {
                id = "string"
                gtoken = "string"
                gname = "string"
                device_score = "string"
                device_level = "string"
                detecttime = "string"
            }
        }
    }
}


sink {
    jdbc {
        plugin_input = "kafka_out"
        url = "jdbc:vertica://127.0.0.1:5433/dev"
        driver = "com.vertica.jdbc.Driver"
        user = "xxxxxxxx"
        password = "xxxxxxxxx"
        generate_sink_sql = true
        primary_keys = ["id"]
        database = "tmp"
        table = "test_table"
        batch_size = 1
        batch_interval_ms = 30000
    }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/kafka.template -m local
```

### Error Exception

```log
org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-08], ErrorDescription:[Sql operation failed, such as (execute,addBatch,close) etc...] - unable to open JDBC writer
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.createAndOpenStatementExecutor(JdbcOutputFormat.java:107) ~[connector-jdbc-2.3.9-2.12.15-em.jar:2.3.9]
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.open(JdbcOutputFormat.java:79) ~[connector-jdbc-2.3.9-2.12.15-em.jar:2.3.9]
        at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSinkWriter.tryOpen(JdbcSinkWriter.java:122) ~[connector-jdbc-2.3.9-2.12.15-em.jar:2.3.9]
        at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSinkWriter.write(JdbcSinkWriter.java:133) ~[connector-jdbc-2.3.9-2.12.15-em.jar:2.3.9]
        at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSinkWriter.write(JdbcSinkWriter.java:43) ~[connector-jdbc-2.3.9-2.12.15-em.jar:2.3.9]
        at org.apache.seatunnel.api.sink.multitablesink.MultiTableWriterRunnable.run(MultiTableWriterRunnable.java:67) [seatunnel-starter.jar:2.3.9]
        at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:43) [seatunnel-starter.jar:2.3.9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.sql.SQLSyntaxErrorException: [Vertica][VJDBC](2848) ERROR: Could not determine data type of parameter $1
        at com.vertica.util.ServerErrorData.buildException(Unknown Source) ~[vertica-jdbc-24.2.0-1.jar:?]
        at com.vertica.io.ProtocolStream.readExpectedMessage(Unknown Source) ~[vertica-jdbc-24.2.0-1.jar:?]
        at com.vertica.dataengine.VDataEngine.prepareImpl(Unknown Source) ~[vertica-jdbc-24.2.0-1.jar:?]
        at com.vertica.dataengine.VDataEngine.prepare(Unknown Source) ~[vertica-jdbc-24.2.0-1.jar:?]
        at com.vertica.dataengine.VDataEngine.prepare(Unknown Source) ~[vertica-jdbc-24.2.0-1.jar:?]
        at com.vertica.jdbc.common.SPreparedStatement.<init>(SPreparedStatement.java:310) ~[vertica-jdbc-24.2.0-1.jar:?]
        at com.vertica.jdbc.jdbc41.S41PreparedStatement.<init>(S41PreparedStatement.java:91) ~[vertica-jdbc-24.2.0-1.jar:?]
        at com.vertica.jdbc.jdbc42.S42PreparedStatement.<init>(S42PreparedStatement.java:77) ~[vertica-jdbc-24.2.0-1.jar:?]
        at com.vertica.jdbc.VerticaJdbc42PreparedStatementImpl.<init>(Unknown Source) ~[vertica-jdbc-24.2.0-1.jar:?]
        at com.vertica.jdbc.VJDBCObjectFactory.createPreparedStatement(Unknown Source) ~[vertica-jdbc-24.2.0-1.jar:?]
        at com.vertica.jdbc.common.SConnection.prepareStatement(SConnection.java:1309) ~[vertica-jdbc-24.2.0-1.jar:?]
        at com.vertica.jdbc.common.SConnection.prepareStatement(SConnection.java:1263) ~[vertica-jdbc-24.2.0-1.jar:?]
        at org.apache.seatunnel.shade.com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337) ~[connector-jdbc-2.3.9-2.12.15-em.jar:2.3.9]
        at org.apache.seatunnel.shade.com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[connector-jdbc-2.3.9-2.12.15-em.jar:2.3.9]
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.FieldNamedPreparedStatement.prepareStatement(FieldNamedPreparedStatement.java:673) ~[connector-jdbc-2.3.9-2.12.15-em.jar:2.3.9]
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormatBuilder.lambda$createSimpleExecutor$6(JdbcOutputFormatBuilder.java:348) ~[connector-jdbc-2.3.9-2.12.15-em.jar:2.3.9]
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.SimpleBatchStatementExecutor.prepareStatements(SimpleBatchStatementExecutor.java:43) ~[connector-jdbc-2.3.9-2.12.15-em.jar:2.3.9]
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.BufferReducedBatchStatementExecutor.prepareStatements(BufferReducedBatchStatementExecutor.java:50) ~[connector-jdbc-2.3.9-2.12.15-em.jar:2.3.9]
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.createAndOpenStatementExecutor(JdbcOutputFormat.java:105) ~[connector-jdbc-2.3.9-2.12.15-em.jar:2.3.9]
        ... 11 more
```

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by chestnut-c**
### Purpose of this pull request

1. Optimize and extend each jdbc data source to rewrite `getUpsertStatementByTableSchema` to obtain specific field information of the table schema when generating upsert statements.
2. Fix the problem that the vertica data source does not support the DUAL pseudo table like Oracle when rewriting,
3. Fix the problem that the Vertica jdbc reports the `[Vertica]VJDBC ERROR: Failed to find conversion function from unknown to int` type inference exception by specifying the specific field type when writing with the `MERGE INTO` syntax.

close https://github.com/apache/seatunnel/issues/9534
Refer to `Vertica` official documentation: `https://docs.vertica.com/23.4.x/en/sql-reference/statements/merge/`

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Abnormal before modification：
Clipboard_Screenshot_1753156454

Normal operation after modification：

Clipboard_Screenshot_1753164488
Clipboard_Screenshot_1753164506
Clipboard_Screenshot_1753164581

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  4. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  5. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  6. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

File: seatunnel-connectors-v2/connector-jdbc/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialectTest.java [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+                dialect.getUpsertStatementByTableSchema(
+                                dataBaseName, tableName, tableSchema, doNothingKeyFields)
+                        .orElseThrow(
+                                () ->
+                                        new AssertionError(
+                                                "Expected doNothingSql String to be present"));
+        Assertions.assertEquals(
+                doNothingSql,
+                " MERGE INTO test_database.\"test_table\" TARGET USING (SELECT CAST(:id AS BIGINT) AS \"id\", CAST(:name AS VARCHAR) AS \"name\", CAST(:age AS INT) AS \"age\", CAST(:createTime AS TIME) AS \"createTime\" ) SOURCE ON (TARGET.\"id\"=SOURCE.\"id\" AND TARGET.\"name\"=SOURCE.\"name\" AND TARGET.\"age\"=SOURCE.\"age\")  WHEN MATCHED THEN UPDATE SET \"createTime\"=SOURCE.\"createTime\" WHEN NOT MATCHED THEN INSERT (\"id\", \"name\", \"age\", \"createTime\") VALUES (SOURCE.\"id\", SOURCE.\"name\", SOURCE.\"age\", SOURCE.\"createTime\")");
+    }
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-jdbc/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialectTest.java]: The result sql not do nothing. It updated the createTime when matched.

File: seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialect.java [hunk 2]
```diff
@@ -53,16 +54,35 @@ public String quoteIdentifier(String identifier) {
...
+                                    String fieldName = column.getName();
+                                    String sourceType = column.getSourceType();
+                                    return "CAST("
+                                            + ":"
+                                            + fieldName
+                                            + " AS "
+                                            + sourceType
+                                            + ")"
+                                            + " AS "
+                                            + quoteIdentifier(fieldName);
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialect.java:82]: why we must add cast as statement? Is it the only way to fix `[Vertica]VJDBC ERROR: Failed to find conversion function from unknown to in` error?

File: seatunnel-connectors-v2/connector-jdbc/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialectTest.java (hunk 1 above)
Comment (chestnut-c) [reply seatunnel-connectors-v2/connector-jdbc/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialectTest.java]: yes, That's how it is now
Clipboard_Screenshot_1753189764

Comment (Hisoka-X) [reply seatunnel-connectors-v2/connector-jdbc/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialectTest.java]: So I think we should not call it as `doNothingSql`.

File: seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialect.java (hunk 2 above)
Comment (chestnut-c) [reply seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialect.java:82]: > why we must add cast as statement? Is it the only way to fix `[Vertica]VJDBC ERROR: Failed to find conversion function from unknown to in` error?

@Hisoka-X Yes, after testing, vertica jdbc currently needs to display the specified type to execute, and the same error occurs when upgrading to a higher version. The test found that the inferred type is not supported and needs to be explicitly specified to succeed

File: seatunnel-connectors-v2/connector-jdbc/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialectTest.java (hunk 1 above)
Comment (chestnut-c) [reply seatunnel-connectors-v2/connector-jdbc/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialectTest.java]: > doNothingSql

`doNothingSql` literally means not updating these columns, which seems to be fine. Hahaha, do you have any better suggestions? haha maybe i will fix this name to `upsertCreateTimeSQL`

File: seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialect.java (hunk 2 above)
Comment (Hisoka-X) [reply seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialect.java:82]: I got it. Please add some comment on code for this.

File: seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialect.java [hunk 3]
```diff
@@ -65,6 +65,7 @@ public Optional<String> getUpsertStatementByTableSchema(
                 Arrays.stream(fieldNames)
                         .filter(fieldName -> !Arrays.asList(uniqueKeyFields).contains(fieldName))
                         .collect(Collectors.toList());
+        // vertica jdbc currently needs to display the specified type to execute
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/vertica/VerticaDialect.java]:
```suggestion
        // Vertica JDBC currently requires explicitly specifying the data type
```

**Review by Hisoka-X — APPROVED** [review]
LGTM if ci passes. Thanks @chestnut-c

**Review by corgy-w — APPROVED** [review]
TKS
