### PR TITLE
[Fix][Connectors-v2] Fix transaction cancellation failure after broker recovery

### LINKED ISSUE #10005: [Bug] [Connector-v2]It can't work when resuming the task for Kafka which chooses EXACTLY_ONCE.
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

It can't do checkpoint when resume the task through `./seatunnel.sh -r 1036289141794406401 -c ../config/mysqlcdc_to_kafka_exactly_once.conf`, and it can't read new cdc data from mysql  

### SeaTunnel Version

2.3.12

### SeaTunnel Config

```conf
env {
  "job.name"="mysqlcdc_to_kafka_exactly_once"
  "job.mode"=STREAMING
  checkpoint.interval = 60000
  checkpoint.timeout = 300000
}
source {
  MySQL-CDC {
    "split.enable-hash-split-for-string-column"="false"
    "format"="COMPATIBLE_DEBEZIUM_JSON"
    "schema-changes.enabled"="true"
    "startup.mode"=INITIAL
    "snapshot.split.size"=100000
    "snapshot.fetch.size"=1024
    debezium {
      "value.converter.schemas.enable"=true
      "key.converter.schemas.enable"=true
    }
    "connect.timeout.ms"=30000
    "connect.max-retries"=3
    "connection.pool.size"=6
    "chunk-key.even-distribution.factor.lower-bound"=0.05
    "chunk-key.even-distribution.factor.upper-bound"=100
    "sample-sharding.threshold"=1000
    "inverse-sampling.rate"=1000
    "exactly_once"="true"
    "stop.mode"=NEVER
    parallelism=1
    updateFieldType=null
    sceneMode="MULTIPLE_TABLE"
    "result_table_name"=Table18966143936576
    database-names=[
      "lyc_test"
    ]
    table-names=[
      "lyc_test.kfkdata"
    ]
    base-url="jdbc:mysql://xxx:3306/WHRTest?useSSL=false&serverTimezone=UTC&characterEncoding=utf8"
    password="QWerxxx"
    displayName=MySQL-CDC
    username="root"
    server-time-zone=UTC
  }
}
transform {

}
sink {
  Kafka {
    "schema_save_mode"="CREATE_SCHEMA_WHEN_NOT_EXIST"
    "topic_partitions_num"=1
    "topic_replication_num"=1
    "data_save_mode"="APPEND_DATA"
    semantics="EXACTLY_ONCE"
    updateFieldType=null
    "source_table_name"=Table18966143936576
    topic="dailidong_exactly_once_kafka"
    format="COMPATIBLE_DEBEZIUM_JSON"
    "bootstrap.servers"="datasource01:9092"
    kafka.config = {
      "transaction.timeout.ms"="900000"
      "request.timeout.ms"="930000"
      "delivery.timeout.ms"="960000"
      "acks"="all"
      "retries"="3"
      "retry.backoff.ms"="200"
    }
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config config/mysqlcdc_to_kafka_exactly_once.conf
```

### Error Exception
There is no exception info. 

[seatunnel-engine-server.log](https://github.com/user-attachments/files/23238533/seatunnel-engine-server.log)

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

JDK 8

### Screenshots

Image

Image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Carl-Zhou-CN**
close #10005 

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

**Comment by zhangshenghang** [comment]
You can merge dev to handle this exception

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java [hunk 1]
```diff
@@ -1410,26 +1410,85 @@ public void testKafkaProtobufToAssert(TestContainer container)
...
+                        throw new RuntimeException(e);
+                    }
+                });
+
+        given().pollDelay(60, SECONDS)
+                .pollInterval(5, SECONDS)
+                .await()
+                .atMost(10, MINUTES)
+                .untilAsserted(
+                        () -> Assertions.assertTrue(checkData(consumerTopic, 10, sourceData)));
```
Comment (zhangshenghang) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java]: Data will be verified in checkData. Please change the value of the data sent after pausing and resuming before sending it. Currently, both before and after pausing, the data sent is sourceData.getBytes()

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java [hunk 2]
```diff
@@ -1826,88 +1883,98 @@ private void generateNativeTestData(String topic, int start, int end) {
...
+            for (ConsumerRecord<String, String> record : records) {
+                if (lastProcessedOffset < record.offset()) {
+                    data.put(record.key(), record.value());
                 }
-            } while (lastProcessedOffset < endOffset - 1);
-        }
+                lastProcessedOffset = record.offset();
+            }
+        } while (lastProcessedOffset < endOffset - 1);
+        closeKafkaConsumer(consumer);
```
Comment (zhangshenghang) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java]: It is recommended to close it in finally

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java [hunk 3]
```diff
@@ -1466,12 +1522,12 @@ public void testKafkaToKafkaExactlyOnceOnBatch(TestContainer container)
...
-            Map<TopicPartition, Long> offsets =
-                    consumer.endOffsets(Arrays.asList(new TopicPartition(producerTopic, 0)));
-            endOffset = offsets.entrySet().iterator().next().getValue();
-        }
+        KafkaConsumer<String, String> consumer = new KafkaConsumer<>(kafkaConsumerConfig());
+        consumer.subscribe(Arrays.asList(producerTopic));
+        Map<TopicPartition, Long> offsets =
+                consumer.endOffsets(Arrays.asList(new TopicPartition(producerTopic, 0)));
+        endOffset = offsets.entrySet().iterator().next().getValue();
+        closeKafkaConsumer(consumer);
```
Comment (zhangshenghang) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java]: ditto

**Review by davidzollo — DISMISSED** [review]
+1

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java (hunk 1 above)
Comment (Carl-Zhou-CN) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java]: done

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java (hunk 2 above)
Comment (Carl-Zhou-CN) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java]: done

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java (hunk 3 above)
Comment (Carl-Zhou-CN) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/java/org/apache/seatunnel/e2e/connector/kafka/KafkaIT.java]: done

**Comment by Carl-Zhou-CN** [comment]
@zhangshenghang @davidzollo CC

**Review by zhangshenghang — APPROVED** [review]
+1

**Review by corgy-w — APPROVED** [review]
