### PR TITLE
[Fix][Connector-V2] assign size for KafkaSource reader cache queue

### LINKED ISSUE #8956: [Bug] [seatunnel-connectors-v2] [connector-kafka] In the KafkaSource code, the elementsQueue is not assigned a size, resulting in an OutOfMemory (OOM) exception.
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Deploy a SeaTunnel Engine separated mode cluster with one master and one worker. Configure it with 8 cores and 12GB of memory. Submit a stream job where data flows from Kafka to HDFS. There are 10 million pieces of data in the Kafka topic.

```
env {
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 10000
  read_limit.rows_per_second=1
}
```
After the task is started, the worker's memory usage will continue to rise. It will increase from 200M to 5G within 5 minutes. If the job is stopped through the api, the memory usage will not be released. If the task is restored to the RUNNING state again, the memory will continue to rise until an OutOfMemory (OOM) occurs. The worker node is restarted. read_limit.rows_per_second=1 does not actually limit the data reading from kafka. Looking at the createReader method of the KafkaSource class of org.apache.seatunnel.connectors.seatunnel.kafka.source.KafkaSource, elementsQueue = new LinkedBlockingQueue<>(); the size is not specified. It is guessed that this is the cause of the memory overflow. Data reading is not truly associated with the read_limit.rows_per_second limit.

----------------

部署 SeaTunnel Engine 分离模式集群, 一个master,一个worker. 配置为8核,12G内存.  提交一个stream job, 数据从kafka 到 hdfs.   kafka 的topic中有1000w条数据. 
```
env {
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 10000
  read_limit.rows_per_second=1
}
```
任务启动后worker内存使用会内持续上升, 5分钟内从200M到5G.  如果通过api stop job, 内存使用不会释放. 
如果再次恢复任务到RUNNING状态,内存会持续上升,直到OOM.  worker节点重启.
read_limit.rows_per_second=1 实际并未限制住从kafka的数据读取.
翻看org.apache.seatunnel.connectors.seatunnel.kafka.source.KafkaSource 类的 createReader方法中  elementsQueue = new LinkedBlockingQueue<>(); 未指定大小,猜测是此处导致的内存溢出. 
 数据读取未真正与  read_limit.rows_per_second 限制关联.

### SeaTunnel Version

2.3.9

### SeaTunnel Config

```conf
null
```

### Running Command

```shell
null
```

### Error Exception

```log
OOM
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by JesseAtSZ**
### Purpose of this pull request
Assign size for KafkaSource reader cache queue to solve issue 8965.
close https://github.com/apache/seatunnel/issues/8956

### Does this PR introduce _any_ user-facing change?
Yes, this PR adds the reader_cache_queue_size parameter,  which can be adjusted to avoid memory overflow.

### Check list

* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [x] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/config/KafkaSourceOptions.java [hunk 1]
```diff
@@ -41,6 +41,12 @@ public class KafkaSourceOptions extends KafkaBaseOptions {
                     .withDescription(
                             "Kafka consumer group id, used to distinguish different consumer groups.");
 
+    public static final Option<Long> QUEUE_SIZE =
+            Options.key("queue_size")
+                    .longType()
+                    .defaultValue(1000L)
```
Comment (hailin0) [inline seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/config/KafkaSourceOptions.java]:
```suggestion
                    .defaultValue(128L)
```

File: seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSource.java [hunk 2]
```diff
@@ -78,9 +78,10 @@ public List<CatalogTable> getProducedCatalogTables() {
     @Override
     public SourceReader<SeaTunnelRow, KafkaSourceSplit> createReader(
             SourceReader.Context readerContext) {
+        int queueSize = kafkaSourceConfig.getQueueSize();
 
         BlockingQueue<RecordsWithSplitIds<ConsumerRecord<byte[], byte[]>>> elementsQueue =
-                new LinkedBlockingQueue<>();
+                new ArrayBlockingQueue<>(queueSize);
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSource.java]: why change to `ArrayBlockingQueue`?

File: docs/zh/connector-v2/source/Kafka.md [hunk 3]
```diff
@@ -56,6 +56,7 @@ import ChangeLog from '../changelog/connector-kafka.md';
...
 | protobuf_schema                     | String                              | 否    | -                        | 当格式设置为 protobuf 时有效，指定 Schema 定义。                                                                                                                                                                                                                                                                                              |
+| queue_size                          | Long                              | 否    | 1000                     | 用于指定读取队列的长度，可以通过调整该参数避免内存溢出。                                                                                                                                                                                                                                                                                                   |
```
Comment (Hisoka-X) [inline docs/zh/connector-v2/source/Kafka.md]:
```suggestion
| reader_cache_queue_size                          | Long                              | 否    | 1024                     | 用于指定读取队列的长度，可以通过调整该参数避免内存溢出。                                                                                                                                                                                                                                                                                                   |
```

**Comment by davidzollo** [comment]
Please fix it, https://github.com/JesseAtSZ/incubator-seatunnel/actions/runs/14055485086/job/39353925108

image

File: seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSource.java (hunk 2 above)
Comment (JesseAtSZ) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSource.java]: changed back to LinkedBlockingQueue.

File: seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/config/KafkaSourceOptions.java (hunk 1 above)
Comment (JesseAtSZ) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/config/KafkaSourceOptions.java]: changed default value to 1024L

File: docs/zh/connector-v2/source/Kafka.md (hunk 3 above)
Comment (JesseAtSZ) [reply docs/zh/connector-v2/source/Kafka.md]: changed default value to 1024L

**Review by davidzollo — DISMISSED** [review]
+1 if CI passed

**Review by davidzollo — DISMISSED** [review]
+1
LGTM

File: seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSource.java [hunk 4]
```diff
@@ -78,9 +78,9 @@ public List<CatalogTable> getProducedCatalogTables() {
     @Override
     public SourceReader<SeaTunnelRow, KafkaSourceSplit> createReader(
             SourceReader.Context readerContext) {
-
         BlockingQueue<RecordsWithSplitIds<ConsumerRecord<byte[], byte[]>>> elementsQueue =
-                new LinkedBlockingQueue<>();
+                new LinkedBlockingQueue<RecordsWithSplitIds<ConsumerRecord<byte[], byte[]>>>(
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSource.java]:
```suggestion
                new LinkedBlockingQueue<>(
```

Comment (JesseAtSZ) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSource.java]: This is written because there was an error in CI before:  "cannot infer type arguments for LinkedBlockingQueue<>"

Comment (Hisoka-X) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSource.java]: Could you share the ci error link?

Comment (JesseAtSZ) [reply seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSource.java]: I resubmitted the code again, and now it's okay.

**Review by Hisoka-X — COMMENTED** [review]
Please update https://github.com/apache/seatunnel/blob/d1c0e055a835522ca410dcfe11382286bb5a57fa/seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceFactory.java#L44

**Comment by JesseAtSZ** [comment]
> Please update
> Completed
> https://github.com/apache/seatunnel/blob/d1c0e055a835522ca410dcfe11382286bb5a57fa/seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceFactory.java#L44

File: docs/en/connector-v2/source/Kafka.md [hunk 5]
```diff
@@ -56,6 +56,8 @@ They can be downloaded via install-plugin.sh or from the Maven central repositor
...
+| reader_cache_queue_size             | Integer                                                                     | No       | 1024                     | Specify the length of the read queue, which can be adjusted to avoid memory overflow.                                                                                                                                                                                                                                                                                               |
```
Comment (Hisoka-X) [inline docs/en/connector-v2/source/Kafka.md]:
```suggestion
| reader_cache_queue_size             | Integer                                                                     | No       | 1024                     | The reader shard cache queue is used to cache the data corresponding to the shards. The size of the shard cache depends on the number of shards obtained by each reader, rather than the amount of data in each shard.                                                                                                                                                                                                                                                                                            |
```

File: docs/zh/connector-v2/source/Kafka.md [hunk 6]
```diff
@@ -56,7 +56,8 @@ import ChangeLog from '../changelog/connector-kafka.md';
...
-| is_native                           | Boolean                                                                    | No       | false                    | 支持保留record的源信息。                                                                                                                                                                                                                                                                                                                |
+| reader_cache_queue_size             | Integer                             | 否    | 1024                     | 用于指定读取队列的长度，可以通过调整该参数避免内存溢出。                                                                                                                                                                                                                                                                                                   |
```
Comment (Hisoka-X) [inline docs/zh/connector-v2/source/Kafka.md]:
```suggestion
| reader_cache_queue_size             | Integer                             | 否    | 1024                     | Reader分片缓存队列，用于缓存分片对应的数据。占用大小取决于每个reader得到的分片量，而不是每个分片的数据量。                                                                                                                                                                                                                                               |
```

**Review by Hisoka-X — APPROVED** [review]
Thanks @JesseAtSZ . cc @hailin0

**Review by hailin0 — APPROVED** [review]
