### PR TITLE
[Fix][Rest-API] fix submit job api

### LINKED ISSUE #5699: [Bug] [Rest-API] submit job api has some issue
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when use rest api to submit job, failed.

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
https://seatunnel.apache.org/docs/2.3.3/seatunnel-engine/rest-api/
```

### Running Command

```shell
use postman call api `locahost:5801/hazelcast/rest/maps/submit-job`
```

### Error Exception

```log
{
    "status": "fail",
    "message": "null"
}
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liunaijie**
### Purpose of this pull request
close #5699 

### How was this patch tested?

use postman

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Could you add a test case for this? Seem like this is a very important feature we shouldn't missed. It's weird we don't have a test case to cover it. cc @liugddx

**Comment by liunaijie** [comment]
> Could you add a test case for this? Seem like this is a very important feature we shouldn't missed. It's weird we don't have a test case to cover it. cc @liugddx

reuse the `RestApiIT`, but change something.
1. remove `Common.setDeployMode` before startup
when start the st cluster with `./bin/seatunnel-cluster.sh -d` command, the deployMode will be null, so delete this setup to keep consistency

2. remove parameter as they are optional when submit job.
when submit job i think they all should be null. when re-store job they need have value.

File: seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/RestApiIT.java [hunk 1]
```diff
@@ -294,7 +289,7 @@ private Response submitJob(String jobMode) {
                                         + "?"
                                         + parameters);
 
-        response.then().statusCode(200).body("jobName", equalTo("test"));
+        response.then().statusCode(200).body("jobId", equalTo("test"));
```
Comment (liugddx) [inline seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/RestApiIT.java]: Why modify this?

Comment (liunaijie) [reply seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/RestApiIT.java]: reverted. a misstake change.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/RestHttpPostCommandProcessor.java [hunk 2]
```diff
@@ -96,14 +98,20 @@ private void handleSubmitJob(HttpPostCommand httpPostCommand, String uri)
...
                         jobConfig,
                         config,
                         textCommandService.getNode(),
-                        Boolean.parseBoolean(
-                                requestParams.get(RestConstant.IS_START_WITH_SAVE_POINT)),
-                        Long.parseLong(requestParams.get(RestConstant.JOB_ID)));
+                        startWithSavePoint,
+                        startWithSavePoint
+                                ? Long.parseLong(requestParams.get(RestConstant.JOB_ID))
+                                : null);
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/RestHttpPostCommandProcessor.java:114]: Can we report error more clear if we start with savepoint but without put jobId in params. Seem like it will report NPE at now. I think the error message should more clear.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/utils/RestUtil.java [hunk 3]
```diff
@@ -57,6 +57,10 @@ public static void buildRequestParams(Map<String, String> requestParams, String
         } catch (IndexOutOfBoundsException e) {
             throw new IllegalArgumentException("Invalid Params format in Params.");
         }
+        if (Boolean.parseBoolean(requestParams.get(RestConstant.IS_START_WITH_SAVE_POINT))
+                && requestParams.get(RestConstant.JOB_ID) == null) {
+            throw new IllegalArgumentException("Please provide jobId when start with save point.");
+        }
```
Comment (Hisoka-X) [inline seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/utils/RestUtil.java:63]: Thanks @liunaijie for add this, could you add a test case for this too? Please.

File: seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/RestHttpPostCommandProcessor.java (hunk 2 above)
Comment (liunaijie) [reply seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/rest/RestHttpPostCommandProcessor.java:114]: added parameter check

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by Hisoka-X — APPROVED** [review]
Thanks @liunaijie for fix! BTW, the test case you added are very important!
