### PR TITLE
[fix] fix get seatunnel row size npe issue

### LINKED ISSUE #6455: [Bug] [SinkMetrics] the sink metrics collect will get NPE when data type is String[]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

[SinkFlowLifeCycle#250 ](https://github.com/apache/seatunnel/blob/dev/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/task/flow/SinkFlowLifeCycle.java#L251)
https://github.com/apache/seatunnel/blob/dev/seatunnel-api/src/main/java/org/apache/seatunnel/api/table/type/SeaTunnelRow.java#L240

in sink life cycle, will summary the sink bytes. but if the data type is string array, doesn't have null check, will get NPE when value is null.

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
na
```

### Running Command

```shell
na
```

### Error Exception

```log
NPE
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liunaijie**
### Purpose of this pull request
close #6455

### How was this patch tested?
update the current ut

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-api/src/test/java/org/apache/seatunnel/api/table/type/SeaTunnelRowTest.java [hunk 1]
```diff
@@ -51,12 +51,31 @@ void testForRowSize() {
                             1L,
                             map,
                             new BigDecimal("3333.333"),
-                            new String[] {"test2", "test", "3333.333"}
+                            new String[] {"test2", "test", "3333.333"},
+                            new Integer[] {1, 2, 3},
+                            new Long[] {1L, 2L, 3L},
+                            new Double[] {1D, 2D},
+                            new Float[] {1F, 2F}
```
Comment (Hisoka-X) [inline seatunnel-api/src/test/java/org/apache/seatunnel/api/table/type/SeaTunnelRowTest.java]: You missed `Boolean[]`, `Byte[]`, `Short[]`,

**Review by Hisoka-X — COMMENTED** [review]
LGTM except one minior problem.

**Review by Hisoka-X — APPROVED** [review]
LGTM. Thanks @liunaijie !

**Review by hailin0 — APPROVED** [review]
