### PR TITLE
[Bug] [connectors-v2] The Hadoop Source/Sink fails with Unable to find valid Kerberos Ticket.

### LINKED ISSUE #7805: [Bug] [connectors-v2] The Hadoop Source/Sink fails with Unable to find valid Kerberos Ticket.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The Hadoop Source/Sink fails with Unable to find valid Kerberos Ticket. In HadoopFileSystemProxy, the UserGroupInformation Object is tightly bound to the security context of the initiating thread. If we try to run the privileged actions that require the subject's security context, it fails with the error, 

```
Caused by: org.apache.hadoop.security.authentication.client.AuthenticationException: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
```

We can attach Security Context of the Specified Subject to the thread Performing Action by using UserGroupInformation#doAs, it attaches the subject's security context for time being till the action is running. 

This issue can be reproduced,
- Set System property **javax.security.auth.useSubjectCredsOnly** to _true_.
- Run the HdfsFile source/sync job

### SeaTunnel Version

2.3.7

### SeaTunnel Config

```conf
env {
"job.mode"=BATCH
"job.name"="SeaTunnel_Job"
"savemode.execute.location"=CLUSTER
}
source {
HdfsFile {
    path="/data/daily/aggregation/tblAssocProfileData_daily_180710.txt"
    "file_format_type"=CSV
    "field_delimiter"="|"
    parallelism=1,
    "use_kerberos"="true"
    "kerberos_principal"="service_user@REALM.COM"
    "fs.defaultFS"="hdfs://clusterA"
    "hdfs_site_path"="/etc/hadoop/conf/hdfs-site.xml"
    "kerberos_keytab_path"="/home/user/service_user.keytab"
    "krb5_path"="/etc/krb5.conf"
    "core_site_path"="/etc/hadoop/conf/core-site.xml"
}
}
sink {
HdfsFile {
    path="/Projects/test/reports/sea_tunnel/single/"
    tmp_path="/Projects/test/reports/"
    "file_format_type"=CSV
    "row_delimiter"="\n"
    "field_delimiter"="|"
    "enable_header_write"="false"
    "use_kerberos"="true"
    "kerberos_principal"="service_user@REALM.COM"
    "fs.defaultFS"="hdfs://clusterA"
    "hdfs_site_path"="/etc/hadoop/conf/hdfs-site.xml"
    "kerberos_keytab_path"="/home/root/service_user.keytab"
    "krb5_path"="/etc/krb5.conf"
    "core_site_path"="/etc/hadoop/conf/core-site.xml"
}
}
```

### Running Command

```shell
sh /opt/seatunnel-workspace/seatunnel/bin/seatunnel.sh --config /opt/seatunnel-workspace/apache-seatunnel-web-1.0.1/profile/manual.conf
```

### Error Exception

```log
Caused by: org.apache.hadoop.security.authentication.client.AuthenticationException: Error while authenticating with endpoint: http://<kms-host>:9292/kms/v1/keyversion/hdp_analytics_dev_data%400/_eek?eek_op=decrypt
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
	at org.apache.hadoop.security.authentication.client.KerberosAuthenticator.wrapExceptionWithMessage(KerberosAuthenticator.java:237) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.security.authentication.client.KerberosAuthenticator.authenticate(KerberosAuthenticator.java:220) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.security.token.delegation.web.DelegationTokenAuthenticator.authenticate(DelegationTokenAuthenticator.java:143) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.security.authentication.client.AuthenticatedURL.openConnection(AuthenticatedURL.java:350) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.security.token.delegation.web.DelegationTokenAuthenticatedURL.openConnection(DelegationTokenAuthenticatedURL.java:327) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.crypto.key.kms.KMSClientProvider$1.run(KMSClientProvider.java:512) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.crypto.key.kms.KMSClientProvider$1.run(KMSClientProvider.java:507) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	at javax.security.auth.Subject.doAs(Subject.java:439) ~[?:?]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.crypto.key.kms.KMSClientProvider.createConnection(KMSClientProvider.java:506) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.crypto.key.kms.KMSClientProvider.decryptEncryptedKey(KMSClientProvider.java:826) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.crypto.key.kms.LoadBalancingKMSClientProvider$5.call(LoadBalancingKMSClientProvider.java:354) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.crypto.key.kms.LoadBalancingKMSClientProvider$5.call(LoadBalancingKMSClientProvider.java:350) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.crypto.key.kms.LoadBalancingKMSClientProvider.doOp(LoadBalancingKMSClientProvider.java:175) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.crypto.key.kms.LoadBalancingKMSClientProvider.decryptEncryptedKey(LoadBalancingKMSClientProvider.java:350) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.crypto.key.KeyProviderCryptoExtension.decryptEncryptedKey(KeyProviderCryptoExtension.java:535) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.hdfs.HdfsKMSUtil.decryptEncryptedDataEncryptionKey(HdfsKMSUtil.java:216) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.hdfs.HdfsKMSUtil.createWrappedInputStream(HdfsKMSUtil.java:196) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.hdfs.DFSClient.createWrappedInputStream(DFSClient.java:967) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:345) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:339) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:356) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:997) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.seatunnel.connectors.seatunnel.file.hadoop.HadoopFileSystemProxy.getInputStream(HadoopFileSystemProxy.java:166) ~[?:?]
	at org.apache.seatunnel.connectors.seatunnel.file.source.reader.TextReadStrategy.read(TextReadStrategy.java:77) ~[?:?]
	at org.apache.seatunnel.connectors.seatunnel.file.source.BaseFileSourceReader.pollNext(BaseFileSourceReader.java:63) ~[?:?]
	... 11 more
Caused by: org.apache.hadoop.security.authentication.client.AuthenticationException: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
	at org.apache.hadoop.security.authentication.client.KerberosAuthenticator.doSpnegoSequence(KerberosAuthenticator.java:365) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.security.authentication.client.KerberosAuthenticator.authenticate(KerberosAuthenticator.java:205) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.security.token.delegation.web.DelegationTokenAuthenticator.authenticate(DelegationTokenAuthenticator.java:143) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.security.authentication.client.AuthenticatedURL.openConnection(AuthenticatedURL.java:350) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.security.token.delegation.web.DelegationTokenAuthenticatedURL.openConnection(DelegationTokenAuthenticatedURL.java:327) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.crypto.key.kms.KMSClientProvider$1.run(KMSClientProvider.java:512) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at org.apache.hadoop.crypto.key.kms.KMSClientProvider$1.run(KMSClientProvider.java:507) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.7]
	at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	at javax.security.auth.Subject.doAs(Subject.java:439) ~[?:?]
```

### Zeta or Flink or Spark Version

2.3.7

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by shashwatsai**
### Purpose of this pull request
The Hadoop Source/Sink fails with Unable to find valid Kerberos Ticket. In HadoopFileSystemProxy, the UserGroupInformation Object is tightly bound to the security context of the initiating thread. If we try to run the privileged actions that require the subject's security context, it fails with the error, 

```
Caused by: org.apache.hadoop.security.authentication.client.AuthenticationException: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
```

We can attach Security Context of the Specified Subject to the thread Performing Action by using UserGroupInformation#doAs, it attaches the subject's security context for time being till the action is running. 

This issue can be reproduced,
- Set System property **javax.security.auth.useSubjectCredsOnly** to _false_.
- Run the HdfsFile source/sync job

Example: 
```
env {
"job.mode"=BATCH
"job.name"="SeaTunnel_Job"
"savemode.execute.location"=CLUSTER
}
source {
HdfsFile {
    path="/data/daily/aggregation/tblAssocProfileData_daily_180710.txt"
    "file_format_type"=CSV
    "field_delimiter"="|"
    parallelism=1,
    "use_kerberos"="true"
    "kerberos_principal"="service_user@REALM.COM"
    "fs.defaultFS"="hdfs://clusterA"
    "hdfs_site_path"="/etc/hadoop/conf/hdfs-site.xml"
    "kerberos_keytab_path"="/home/user/service_user.keytab"
    "krb5_path"="/etc/krb5.conf"
    "core_site_path"="/etc/hadoop/conf/core-site.xml"
}
}
sink {
HdfsFile {
    path="/Projects/test/reports/sea_tunnel/single/"
    tmp_path="/Projects/test/reports/"
    "file_format_type"=CSV
    "row_delimiter"="\n"
    "field_delimiter"="|"
    "enable_header_write"="false"
    "use_kerberos"="true"
    "kerberos_principal"="service_user@REALM.COM"
    "fs.defaultFS"="hdfs://clusterA"
    "hdfs_site_path"="/etc/hadoop/conf/hdfs-site.xml"
    "kerberos_keytab_path"="/home/root/service_user.keytab"
    "krb5_path"="/etc/krb5.conf"
    "core_site_path"="/etc/hadoop/conf/core-site.xml"
}
}
```

### Does this PR introduce _any_ user-facing change?
No

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by shashwatsai** [comment]
Issue: https://github.com/apache/seatunnel/issues/7805

**Comment by Hisoka-X** [comment]
Thanks @shashwatsai !
Since we lack kerberos-related test cases, could you provide a screenshot of a successful run?

**Review by arshadmohammad — APPROVED** [review]
LGTM +1

**Comment by shashwatsai** [comment]
@Hisoka-X , please review.

Seatunnel Engine Screen grab:
image

Seatunnel Client Screen grab:
image

source/sink paths:
image

File: seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/hadoop/HadoopFileSystemProxy.java [hunk 1]
```diff
@@ -273,12 +300,42 @@ private void initializeWithRemoteUserLogin() throws Exception {
...
+    private <T> T execute(PrivilegedExceptionAction<T> action) throws IOException {
+        if (isAuthTypeKerberos) {
+            return doAsPrivileged(action);
+        } else {
+            try {
+                return action.run();
+            } catch (IOException e) {
+                throw e;
+            } catch (SeaTunnelRuntimeException e) {
+                throw new SeaTunnelRuntimeException(e.getSeaTunnelErrorCode(), e.getParams());
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/hadoop/HadoopFileSystemProxy.java]:
```suggestion
            } catch (IOException | SeaTunnelRuntimeException e) {
                throw e;
```

File: seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/hadoop/HadoopFileSystemProxy.java [hunk 2]
```diff
@@ -273,12 +300,42 @@ private void initializeWithRemoteUserLogin() throws Exception {
...
+
+    private <T> T doAsPrivileged(PrivilegedExceptionAction<T> action) throws IOException {
+        if (fileSystem == null || userGroupInformation == null) {
+            initialize();
+        }
+
+        try {
+            return userGroupInformation.doAs(action);
+        } catch (InterruptedException e) {
+            Thread.currentThread().interrupt();
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/hadoop/HadoopFileSystemProxy.java:340]: does this necessary?

File: seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/hadoop/HadoopFileSystemProxy.java [hunk 3]
```diff
@@ -273,12 +300,42 @@ private void initializeWithRemoteUserLogin() throws Exception {
...
         log.info("Create FileSystem success with RemoteUser: {}.", hadoopConf.getRemoteUser());
-        this.userGroupInformation = pair.getKey();
-        this.fileSystem = pair.getValue();
-        this.fileSystem.setWriteChecksum(false);
+        userGroupInformation = pair.getKey();
+        fileSystem = pair.getValue();
+        fileSystem.setWriteChecksum(false);
+    }
+
+    private <T> T execute(PrivilegedExceptionAction<T> action) throws IOException {
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/hadoop/HadoopFileSystemProxy.java:313]: Please add some comments about why we need execute method to run action?

File: seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/hadoop/HadoopFileSystemProxy.java (hunk 2 above)
Comment (shashwatsai) [reply seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/hadoop/HadoopFileSystemProxy.java:340]: After catching the InterruptedException, thread's interrupt status is cleared, so we need to re-interrupt the thread, for the task threads to continue. CC: @Hisoka-X

File: seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/hadoop/HadoopFileSystemProxy.java (hunk 1 above)
Comment (shashwatsai) [reply seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/hadoop/HadoopFileSystemProxy.java]: incorporated.

File: seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/hadoop/HadoopFileSystemProxy.java (hunk 3 above)
Comment (shashwatsai) [reply seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/hadoop/HadoopFileSystemProxy.java:313]: Thanks, added the necessary comments.

**Comment by shashwatsai** [comment]
Results on Non Keberoised Cluster:
Logs:
```
/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=51679:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Users/shatiwar/repos/seatunnel/seatunnel-connectors-v2/connector-file/connector-file-hadoop/target/connector-file-hadoop-2.3.7-2.12.15.jar:/Users/shatiwar/repos/global-libs/hive-jdbc-standalone.jar:/Users/shatiwar/repos/seatunnel/seatunnel-connectors-v2/connector-jdbc/target/connector-jdbc-2.3.7-2.12.15.jar:/Users/shatiwar/repos/seatunnel/seatunnel-examples/seatunnel-engine-examples/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-core/seatunnel-starter/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-api/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-common/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-config/seatunnel-config-shade/target/seatunnel-config-shade-2.3.7.jar:/Users/shatiwar/repos/seatunnel/seatunnel-config/seatunnel-config-shade/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-config/seatunnel-config-base/target/seatunnel-config-base-2.3.7.jar:/Users/shatiwar/repos/seatunnel/seatunnel-config/seatunnel-config-base/target/classes:/Users/shatiwar/.m2/repository/com/typesafe/config/1.3.3/config-1.3.3.jar:/Users/shatiwar/.m2/repository/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15.jar:/Users/shatiwar/.m2/repository/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.jar:/Users/shatiwar/.m2/repository/org/apache/commons/commons-csv/1.10.0/commons-csv-1.10.0.jar:/Users/shatiwar/repos/seatunnel/seatunnel-shade/seatunnel-guava/target/seatunnel-guava.jar:/Users/shatiwar/repos/seatunnel/seatunnel-shade/seatunnel-guava/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-shade/seatunnel-jackson/target/seatunnel-jackson.jar:/Users/shatiwar/repos/seatunnel/seatunnel-shade/seatunnel-jackson/target/classes:/Users/shatiwar/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-properties/2.13.3/jackson-dataformat-properties-2.13.3.jar:/Users/shatiwar/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.13.3/jackson-datatype-jsr310-2.13.3.jar:/Users/shatiwar/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.13.3/jackson-core-2.13.3.jar:/Users/shatiwar/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.13.3/jackson-databind-2.13.3.jar:/Users/shatiwar/repos/seatunnel/seatunnel-core/seatunnel-core-starter/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-config/seatunnel-config-sql/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-plugin-discovery/target/classes:/Users/shatiwar/.m2/repository/org/apache/commons/commons-compress/1.20/commons-compress-1.20.jar:/Users/shatiwar/.m2/repository/com/beust/jcommander/1.81/jcommander-1.81.jar:/Users/shatiwar/repos/seatunnel/seatunnel-engine/seatunnel-engine-client/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-shade/seatunnel-hazelcast/seatunnel-hazelcast-shade/target/seatunnel-hazelcast-shade-2.3.7.jar:/Users/shatiwar/repos/seatunnel/seatunnel-shade/seatunnel-hazelcast/seatunnel-hazelcast-shade/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-shade/seatunnel-hazelcast/seatunnel-hazelcast-base/target/seatunnel-hazelcast-base-2.3.7.jar:/Users/shatiwar/repos/seatunnel/seatunnel-shade/seatunnel-hazelcast/seatunnel-hazelcast-base/target/classes:/Users/shatiwar/.m2/repository/com/hazelcast/hazelcast/5.1/hazelcast-5.1.jar:/Users/shatiwar/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/Users/shatiwar/repos/seatunnel/seatunnel-engine/seatunnel-engine-core/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-engine/seatunnel-engine-common/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-engine/seatunnel-engine-storage/checkpoint-storage-plugins/checkpoint-storage-local-file/target/classes:/Users/shatiwar/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/Users/shatiwar/repos/seatunnel/seatunnel-engine/seatunnel-engine-storage/checkpoint-storage-api/target/classes:/Users/shatiwar/.m2/repository/com/squareup/okhttp/okhttp/2.7.5/okhttp-2.7.5.jar:/Users/shatiwar/.m2/repository/com/squareup/okio/okio/1.6.0/okio-1.6.0.jar:/Users/shatiwar/repos/seatunnel/seatunnel-engine/seatunnel-engine-server/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-engine/seatunnel-engine-storage/checkpoint-storage-plugins/checkpoint-storage-hdfs/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-engine/seatunnel-engine-storage/imap-storage-plugins/imap-storage-file/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-engine/seatunnel-engine-serializer/serializer-protobuf/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-engine/seatunnel-engine-serializer/serializer-api/target/classes:/Users/shatiwar/.m2/repository/io/protostuff/protostuff-core/1.8.0/protostuff-core-1.8.0.jar:/Users/shatiwar/.m2/repository/io/protostuff/protostuff-api/1.8.0/protostuff-api-1.8.0.jar:/Users/shatiwar/.m2/repository/io/protostuff/protostuff-runtime/1.8.0/protostuff-runtime-1.8.0.jar:/Users/shatiwar/.m2/repository/io/protostuff/protostuff-collectionschema/1.8.0/protostuff-collectionschema-1.8.0.jar:/Users/shatiwar/repos/seatunnel/seatunnel-engine/seatunnel-engine-storage/imap-storage-api/target/classes:/Users/shatiwar/.m2/repository/com/lmax/disruptor/3.4.4/disruptor-3.4.4.jar:/Users/shatiwar/repos/seatunnel/seatunnel-transforms-v2/target/classes:/Users/shatiwar/.m2/repository/com/github/jsqlparser/jsqlparser/4.5/jsqlparser-4.5.jar:/Users/shatiwar/.m2/repository/com/jayway/jsonpath/json-path/2.7.0/json-path-2.7.0.jar:/Users/shatiwar/.m2/repository/net/minidev/json-smart/2.4.7/json-smart-2.4.7.jar:/Users/shatiwar/.m2/repository/net/minidev/accessors-smart/2.4.7/accessors-smart-2.4.7.jar:/Users/shatiwar/.m2/repository/org/ow2/asm/asm/9.1/asm-9.1.jar:/Users/shatiwar/repos/seatunnel/seatunnel-formats/seatunnel-format-json/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-connectors-v2/connector-common/target/classes:/Users/shatiwar/.m2/repository/org/apache/groovy/groovy/4.0.16/groovy-4.0.16.jar:/Users/shatiwar/repos/seatunnel/seatunnel-shade/seatunnel-janino/target/seatunnel-janino.jar:/Users/shatiwar/repos/seatunnel/seatunnel-shade/seatunnel-janino/target/classes:/Users/shatiwar/.m2/repository/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/Users/shatiwar/.m2/repository/commons-codec/commons-codec/1.13/commons-codec-1.13.jar:/Users/shatiwar/.m2/repository/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar:/Users/shatiwar/repos/seatunnel/seatunnel-shade/seatunnel-hadoop3-3.1.4-uber/target/seatunnel-hadoop3-3.1.4-uber.jar:/Users/shatiwar/repos/seatunnel/seatunnel-shade/seatunnel-hadoop3-3.1.4-uber/target/classes:/Users/shatiwar/.m2/repository/org/apache/hadoop/hadoop-client/3.3.6.3.3.6.4-2/hadoop-client-3.3.6.3.3.6.4-2.jar:/Users/shatiwar/.m2/repository/org/apache/hadoop/hadoop-common/3.3.6.3.3.6.4-2/hadoop-common-3.3.6.3.3.6.4-2.jar:/Users/shatiwar/.m2/repository/org/apache/hadoop/thirdparty/hadoop-shaded-protobuf_3_7/1.1.1/hadoop-shaded-protobuf_3_7-1.1.1.jar:/Users/shatiwar/.m2/repository/org/apache/hadoop/thirdparty/hadoop-shaded-guava/1.1.1/hadoop-shaded-guava-1.1.1.jar:/Users/shatiwar/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar:/Users/shatiwar/.m2/repository/org/apache/commons/commons-math3/3.1.1/commons-math3-3.1.1.jar:/Users/shatiwar/.m2/repository/commons-net/commons-net/3.9.0/commons-net-3.9.0.jar:/Users/shatiwar/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/Users/shatiwar/.m2/repository/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.jar:/Users/shatiwar/.m2/repository/org/eclipse/jetty/jetty-servlet/9.4.53.v20231009/jetty-servlet-9.4.53.v20231009.jar:/Users/shatiwar/.m2/repository/org/eclipse/jetty/jetty-security/9.4.53.v20231009/jetty-security-9.4.53.v20231009.jar:/Users/shatiwar/.m2/repository/org/eclipse/jetty/jetty-util-ajax/9.4.53.v20231009/jetty-util-ajax-9.4.53.v20231009.jar:/Users/shatiwar/.m2/repository/org/eclipse/jetty/jetty-webapp/9.4.53.v20231009/jetty-webapp-9.4.53.v20231009.jar:/Users/shatiwar/.m2/repository/org/eclipse/jetty/jetty-xml/9.4.53.v20231009/jetty-xml-9.4.53.v20231009.jar:/Users/shatiwar/.m2/repository/javax/servlet/jsp/jsp-api/2.1/jsp-api-2.1.jar:/Users/shatiwar/.m2/repository/com/sun/jersey/jersey-servlet/1.19.4/jersey-servlet-1.19.4.jar:/Users/shatiwar/.m2/repository/ch/qos/reload4j/reload4j/1.2.22/reload4j-1.2.22.jar:/Users/shatiwar/.m2/repository/commons-beanutils/commons-beanutils/1.9.4/commons-beanutils-1.9.4.jar:/Users/shatiwar/.m2/repository/org/apache/commons/commons-configuration2/2.8.0/commons-configuration2-2.8.0.jar:/Users/shatiwar/.m2/repository/org/apache/commons/commons-text/1.10.0/commons-text-1.10.0.jar:/Users/shatiwar/.m2/repository/org/apache/avro/avro/1.7.7/avro-1.7.7.jar:/Users/shatiwar/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar:/Users/shatiwar/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar:/Users/shatiwar/.m2/repository/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.jar:/Users/shatiwar/.m2/repository/com/google/re2j/re2j/1.1/re2j-1.1.jar:/Users/shatiwar/.m2/repository/com/google/protobuf/protobuf-java/3.24.4/protobuf-java-3.24.4.jar:/Users/shatiwar/.m2/repository/com/google/code/gson/gson/2.9.0/gson-2.9.0.jar:/Users/shatiwar/.m2/repository/org/apache/hadoop/hadoop-auth/3.3.6.3.3.6.4-2/hadoop-auth-3.3.6.3.3.6.4-2.jar:/Users/shatiwar/.m2/repository/com/nimbusds/nimbus-jose-jwt/9.37.2/nimbus-jose-jwt-9.37.2.jar:/Users/shatiwar/.m2/repository/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar:/Users/shatiwar/.m2/repository/org/apache/curator/curator-framework/5.2.0/curator-framework-5.2.0.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/kerb-simplekdc/1.0.1/kerb-simplekdc-1.0.1.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/kerb-client/1.0.1/kerb-client-1.0.1.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/kerby-config/1.0.1/kerby-config-1.0.1.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/kerb-common/1.0.1/kerb-common-1.0.1.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/kerb-crypto/1.0.1/kerb-crypto-1.0.1.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/kerb-util/1.0.1/kerb-util-1.0.1.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/token-provider/1.0.1/token-provider-1.0.1.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/kerb-admin/1.0.1/kerb-admin-1.0.1.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/kerb-server/1.0.1/kerb-server-1.0.1.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/kerb-identity/1.0.1/kerb-identity-1.0.1.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/kerby-xdr/1.0.1/kerby-xdr-1.0.1.jar:/Users/shatiwar/.m2/repository/org/apache/curator/curator-client/5.2.0/curator-client-5.2.0.jar:/Users/shatiwar/.m2/repository/org/apache/curator/curator-recipes/5.2.0/curator-recipes-5.2.0.jar:/Users/shatiwar/.m2/repository/io/dropwizard/metrics/metrics-core/3.2.4/metrics-core-3.2.4.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/kerb-core/1.0.1/kerb-core-1.0.1.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/kerby-pkix/1.0.1/kerby-pkix-1.0.1.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/kerby-asn1/1.0.1/kerby-asn1-1.0.1.jar:/Users/shatiwar/.m2/repository/org/apache/kerby/kerby-util/1.0.1/kerby-util-1.0.1.jar:/Users/shatiwar/.m2/repository/org/codehaus/woodstox/stax2-api/4.2.1/stax2-api-4.2.1.jar:/Users/shatiwar/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.4.0/woodstox-core-5.4.0.jar:/Users/shatiwar/.m2/repository/dnsjava/dnsjava/2.1.7/dnsjava-2.1.7.jar:/Users/shatiwar/.m2/repository/org/apache/hadoop/hadoop-hdfs-client/3.3.6.3.3.6.4-2/hadoop-hdfs-client-3.3.6.3.3.6.4-2.jar:/Users/shatiwar/.m2/repository/com/squareup/okio/okio-jvm/3.4.0/okio-jvm-3.4.0.jar:/Users/shatiwar/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.8.0/kotlin-stdlib-jdk8-1.8.0.jar:/Users/shatiwar/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.8.0/kotlin-stdlib-jdk7-1.8.0.jar:/Users/shatiwar/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.13.3/jackson-annotations-2.13.3.jar:/Users/shatiwar/.m2/repository/org/apache/hadoop/hadoop-yarn-api/3.3.6.3.3.6.4-2/hadoop-yarn-api-3.3.6.3.3.6.4-2.jar:/Users/shatiwar/.m2/repository/javax/xml/bind/jaxb-api/2.2.11/jaxb-api-2.2.11.jar:/Users/shatiwar/.m2/repository/org/apache/hadoop/hadoop-yarn-client/3.3.6.3.3.6.4-2/hadoop-yarn-client-3.3.6.3.3.6.4-2.jar:/Users/shatiwar/.m2/repository/org/eclipse/jetty/websocket/websocket-client/9.4.53.v20231009/websocket-client-9.4.53.v20231009.jar:/Users/shatiwar/.m2/repository/org/eclipse/jetty/jetty-client/9.4.53.v20231009/jetty-client-9.4.53.v20231009.jar:/Users/shatiwar/.m2/repository/org/eclipse/jetty/jetty-http/9.4.53.v20231009/jetty-http-9.4.53.v20231009.jar:/Users/shatiwar/.m2/repository/org/eclipse/jetty/jetty-util/9.4.53.v20231009/jetty-util-9.4.53.v20231009.jar:/Users/shatiwar/.m2/repository/org/eclipse/jetty/jetty-io/9.4.53.v20231009/jetty-io-9.4.53.v20231009.jar:/Users/shatiwar/.m2/repository/org/eclipse/jetty/websocket/websocket-common/9.4.53.v20231009/websocket-common-9.4.53.v20231009.jar:/Users/shatiwar/.m2/repository/org/eclipse/jetty/websocket/websocket-api/9.4.53.v20231009/websocket-api-9.4.53.v20231009.jar:/Users/shatiwar/.m2/repository/org/jline/jline/3.9.0/jline-3.9.0.jar:/Users/shatiwar/.m2/repository/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.6.3.3.6.4-2/hadoop-mapreduce-client-core-3.3.6.3.3.6.4-2.jar:/Users/shatiwar/.m2/repository/org/apache/hadoop/hadoop-yarn-common/3.3.6.3.3.6.4-2/hadoop-yarn-common-3.3.6.3.3.6.4-2.jar:/Users/shatiwar/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/Users/shatiwar/.m2/repository/com/sun/jersey/jersey-core/1.19.4/jersey-core-1.19.4.jar:/Users/shatiwar/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar:/Users/shatiwar/.m2/repository/com/sun/jersey/jersey-client/1.19.4/jersey-client-1.19.4.jar:/Users/shatiwar/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.12.7/jackson-module-jaxb-annotations-2.12.7.jar:/Users/shatiwar/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.jar:/Users/shatiwar/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.12.7/jackson-jaxrs-json-provider-2.12.7.jar:/Users/shatiwar/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.12.7/jackson-jaxrs-base-2.12.7.jar:/Users/shatiwar/.m2/repository/org/apache/hadoop/hadoop-mapreduce-client-jobclient/3.3.6.3.3.6.4-2/hadoop-mapreduce-client-jobclient-3.3.6.3.3.6.4-2.jar:/Users/shatiwar/.m2/repository/org/apache/hadoop/hadoop-mapreduce-client-common/3.3.6.3.3.6.4-2/hadoop-mapreduce-client-common-3.3.6.3.3.6.4-2.jar:/Users/shatiwar/.m2/repository/org/apache/hadoop/hadoop-annotations/3.3.6.3.3.6.4-2/hadoop-annotations-3.3.6.3.3.6.4-2.jar:/Users/shatiwar/.m2/repository/org/xerial/snappy/snappy-java/1.1.10.4/snappy-java-1.1.10.4.jar:/Users/shatiwar/repos/seatunnel/seatunnel-connectors-v2/connector-fake/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-connectors-v2/connector-console/target/classes:/Users/shatiwar/repos/seatunnel/seatunnel-connectors-v2/connector-assert/target/classes:/Users/shatiwar/.m2/repository/com/google/guava/guava/27.0-jre/guava-27.0-jre.jar:/Users/shatiwar/.m2/repository/com/google/guava/failureaccess/1.0/failureaccess-1.0.jar:/Users/shatiwar/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Users/shatiwar/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/shatiwar/.m2/repository/org/checkerframework/checker-qual/3.10.0/checker-qual-3.10.0.jar:/Users/shatiwar/.m2/repository/com/google/errorprone/error_prone_annotations/2.2.0/error_prone_annotations-2.2.0.jar:/Users/shatiwar/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/Users/shatiwar/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar:/Users/shatiwar/.m2/repository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar:/Users/shatiwar/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.17.1/log4j-slf4j-impl-2.17.1.jar:/Users/shatiwar/.m2/repository/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar:/Users/shatiwar/.m2/repository/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar:/Users/shatiwar/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.36/jcl-over-slf4j-1.7.36.jar:/Users/shatiwar/.m2/repository/org/apache/logging/log4j/log4j-1.2-api/2.17.1/log4j-1.2-api-2.17.1.jar org.apache.seatunnel.example.engine.SeaTunnelEngineExample
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/shatiwar/repos/global-libs/hive-jdbc-standalone.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/shatiwar/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.17.1/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Reload4jLoggerFactory]
Oct 10, 2024 7:55:16 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading 'seatunnel.yaml' from the classpath.
Oct 10, 2024 7:55:16 PM org.apache.seatunnel.engine.common.config.SeaTunnelConfig
INFO: seatunnel.home is /Users/shatiwar/repos/seatunnel
Oct 10, 2024 7:55:16 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading 'hazelcast.yaml' from the classpath.
Oct 10, 2024 7:55:17 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading 'hazelcast-client.yaml' from the classpath.
Oct 10, 2024 7:55:17 PM com.hazelcast.instance.impl.HazelcastInstanceFactory
WARNING: Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
Oct 10, 2024 7:55:17 PM com.hazelcast.instance.impl.HazelcastInstanceFactory
WARNING: WARNING: Classpath misconfiguration: found multiple META-INF/services/com.hazelcast.instance.impl.NodeExtension resources: jar:file:/Users/shatiwar/repos/seatunnel/seatunnel-shade/seatunnel-hazelcast/seatunnel-hazelcast-shade/target/seatunnel-hazelcast-shade-2.3.7.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension, jar:file:/Users/shatiwar/repos/seatunnel/seatunnel-shade/seatunnel-hazelcast/seatunnel-hazelcast-base/target/seatunnel-hazelcast-base-2.3.7.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension, jar:file:/Users/shatiwar/.m2/repository/com/hazelcast/hazelcast/5.1/hazelcast-5.1.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension
2024-10-10 19:55:17,427 WARN  com.hazelcast.instance.AddressPicker - [LOCAL] [seatunnel-516897] [5.1] You configured your member address as host name. Please be aware of that your dns can be spoofed. Make sure that your dns configurations are correct.
2024-10-10 19:55:17,430 INFO  com.hazelcast.instance.AddressPicker - [LOCAL] [seatunnel-516897] [5.1] Resolving domain name 'localhost' to address(es): [127.0.0.1, 0:0:0:0:0:0:0:1]
2024-10-10 19:55:17,430 INFO  com.hazelcast.instance.AddressPicker - [LOCAL] [seatunnel-516897] [5.1] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1]
2024-10-10 19:55:17,434 DEBUG com.hazelcast.instance.AddressPicker - [LOCAL] [seatunnel-516897] [5.1] Trying to bind inet socket address: 0.0.0.0/0.0.0.0:5801
2024-10-10 19:55:17,435 DEBUG com.hazelcast.instance.AddressPicker - [LOCAL] [seatunnel-516897] [5.1] Bind successful to inet socket address: /[0:0:0:0:0:0:0:0]:5801
2024-10-10 19:55:17,436 DEBUG com.hazelcast.instance.AddressPicker - [LOCAL] [seatunnel-516897] [5.1] Picked [localhost]:5801, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5801], bind any local is true
2024-10-10 19:55:17,450 INFO  org.apache.seatunnel.engine.server.SeaTunnelServer - SeaTunnel server start...
2024-10-10 19:55:17,451 INFO  com.hazelcast.system - [localhost]:5801 [seatunnel-516897] [5.1] Based on Hazelcast IMDG version: 5.1.0 (20220228 - 21f20e7)
2024-10-10 19:55:17,451 INFO  com.hazelcast.system - [localhost]:5801 [seatunnel-516897] [5.1] Cluster name: seatunnel-516897
2024-10-10 19:55:17,451 DEBUG com.hazelcast.system - [localhost]:5801 [seatunnel-516897] [5.1] Configured Hazelcast Serialization version: 1
2024-10-10 19:55:17,451 INFO  com.hazelcast.system - [localhost]:5801 [seatunnel-516897] [5.1] 
                                                         
 _____               _____                             _ 
/  ___|             |_   _|                           | |
\ `--.   ___   __ _   | |   _   _  _ __   _ __    ___ | |
 `--. \ / _ \ / _` |  | |  | | | || '_ \ | '_ \  / _ \| |
/\__/ /|  __/| (_| |  | |  | |_| || | | || | | ||  __/| |
\____/  \___| \__,_|  \_/   \__,_||_| |_||_| |_| \___||_|
                                                         

2024-10-10 19:55:17,451 INFO  com.hazelcast.system - [localhost]:5801 [seatunnel-516897] [5.1] Copyright © 2021-2022 The Apache Software Foundation. Apache SeaTunnel, SeaTunnel, and its feather logo are trademarks of The Apache Software Foundation.
2024-10-10 19:55:17,451 INFO  com.hazelcast.system - [localhost]:5801 [seatunnel-516897] [5.1] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following: 
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2024-10-10 19:55:17,452 INFO  com.hazelcast.system - [localhost]:5801 [seatunnel-516897] [5.1] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2024-10-10 19:55:17,543 DEBUG com.hazelcast.internal.util.ServiceLoader - The class com.hazelcast.jet.impl.observer.JetObserverDataSerializerHook does not implement the expected interface com.hazelcast.nio.serialization.SerializerHook
2024-10-10 19:55:17,549 DEBUG com.hazelcast.internal.util.ServiceLoader - The class com.hazelcast.jet.impl.metrics.JetMetricsDataSerializerHook does not implement the expected interface com.hazelcast.nio.serialization.SerializerHook
2024-10-10 19:55:17,557 DEBUG com.hazelcast.internal.util.ServiceLoader - The class com.hazelcast.jet.impl.observer.JetObserverDataSerializerHook does not implement the expected interface com.hazelcast.nio.serialization.SerializerHook
2024-10-10 19:55:17,557 DEBUG com.hazelcast.internal.util.ServiceLoader - The class com.hazelcast.jet.impl.metrics.JetMetricsDataSerializerHook does not implement the expected interface com.hazelcast.nio.serialization.SerializerHook
2024-10-10 19:55:17,560 DEBUG com.hazelcast.internal.metrics.impl.MetricsConfigHelper - [localhost]:5801 [seatunnel-516897] [5.1] Collecting debug metrics and sending to diagnostics is disabled
2024-10-10 19:55:17,569 DEBUG com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator - [localhost]:5801 [seatunnel-516897] [5.1] Backpressure is disabled
2024-10-10 19:55:17,575 DEBUG com.hazelcast.spi.impl.operationservice.impl.InboundResponseHandlerSupplier - [localhost]:5801 [seatunnel-516897] [5.1] Running with 2 response threads
2024-10-10 19:55:17,642 DEBUG com.hazelcast.internal.server.tcp.LocalAddressRegistry - [localhost]:5801 [seatunnel-516897] [5.1] LinkedAddresses{primaryAddress=[localhost]:5801, allLinkedAddresses=[[fe80:0:0:0:ce81:b1c:bd2c:69e%utun3]:5801, [fe80:0:0:0:d44b:4ab0:6f7e:6bed%utun4]:5801, [fe80:0:0:0:a98d:c4e0:d60e:1621]:5801, [fe80:0:0:0:e7be:8463:9357:7b8c]:5801, [fe80:0:0:0:d44b:4ab0:6f7e:6bed]:5801, [0:0:0:0:0:0:0:1%lo0]:5801, [fe80:0:0:0:d432:83ff:fe25:728a%llw0]:5801, [fe80:0:0:0:a98d:c4e0:d60e:1621%utun0]:5801, [192.168.1.3]:5801, [10.195.95.29]:5801, [fe80:0:0:0:0:0:0:1%lo0]:5801, [0:0:0:0:0:0:0:1]:5801, [fe80:0:0:0:bed0:74ff:fe4f:6875]:5801, [fe80:0:0:0:e7be:8463:9357:7b8c%utun1]:5801, [fe80:0:0:0:bcd0:74ff:fe4f:6875]:5801, [fe80:0:0:0:bcd0:74ff:fe4f:6875%ap1]:5801, [fe80:0:0:0:ce81:b1c:bd2c:69e]:5801, [fe80:0:0:0:9cb:96da:19a8:b92d%utun2]:5801, [fe80:0:0:0:0:0:0:1]:5801, [fe80:0:0:0:bed0:74ff:fe4f:6875%utun4]:5801, [127.0.0.1]:5801, [fe80:0:0:0:d432:83ff:fe25:728a]:5801, [fe80:0:0:0:9cb:96da:19a8:b92d]:5801, [fe80:0:0:0:d432:83ff:fe25:728a%awdl0]:5801, [localhost]:5801]} are registered for the local member with local uuid=1e45bcb8-c93e-4a36-895b-6528261f2ddd
2024-10-10 19:55:17,716 DEBUG com.hazelcast.system.security - [localhost]:5801 [seatunnel-516897] [5.1] 
🔒 Security recommendations and their status:
  ✅ Use a custom cluster name
  ✅ Disable member multicast discovery/join method
  ⚠️ Use advanced networking, separate client and member sockets
  ⚠️ Bind Server sockets to a single network interface (disable hazelcast.socket.server.bind.any)
  ✅ Disable scripting in the Management Center
  ✅ Disable console in the Management Center
  ⚠️ Enable Security (Enterprise)
  ⚠️ Use TLS communication protection (Enterprise)
  ⚠️ Enable auditlog (Enterprise)
Check the hazelcast-security-hardened.xml/yaml example config file to find why and how to configure these security related settings.

log4j:WARN No appenders could be found for logger (org.apache.seatunnel.engine.server.SeaTunnelNodeContext).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2024-10-10 19:55:17,770 WARN  com.hazelcast.cp.CPSubsystem - [localhost]:5801 [seatunnel-516897] [5.1] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
Oct 10, 2024 7:55:17 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading 'seatunnel.yaml' from the classpath.
Oct 10, 2024 7:55:17 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading 'hazelcast.yaml' from the classpath.
2024-10-10 19:55:17,894 WARN  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] The Node is not ready yet, Node state STARTING,looking forward to the next scheduling
2024-10-10 19:55:17,896 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] Created new BusWork : 294505405
2024-10-10 19:55:17,912 DEBUG org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - start send heartbeat to resource manager, this address: [localhost]:5801
2024-10-10 19:55:17,918 INFO  org.apache.seatunnel.engine.server.CoordinatorService - [localhost]:5801 [seatunnel-516897] [5.1] 
***********************************************
     CoordinatorService Thread Pool Status
***********************************************
activeCount               :                   0
corePoolSize              :                   0
maximumPoolSize           :          2147483647
poolSize                  :                   0
completedTaskCount        :                   0
taskCount                 :                   0
***********************************************

2024-10-10 19:55:17,923 DEBUG com.hazelcast.internal.metrics.impl.MetricsService - [localhost]:5801 [seatunnel-516897] [5.1] Configuring metrics collection, collection interval=5 seconds, retention=5 seconds, publishers=[Management Center Publisher, JMX Publisher]
2024-10-10 19:55:17,915 WARN  org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - failed send heartbeat to resource manager, will retry later. this address: [localhost]:5801
2024-10-10 19:55:17,934 DEBUG com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl - [localhost]:5801 [seatunnel-516897] [5.1] Starting 10 partition threads and 51 generic threads (1 dedicated for priority tasks)
2024-10-10 19:55:17,938 DEBUG com.hazelcast.sql.impl.SqlServiceImpl - [localhost]:5801 [seatunnel-516897] [5.1] Optimizer class "com.hazelcast.jet.sql.impl.CalciteSqlOptimizer" not found, falling back to com.hazelcast.sql.impl.optimizer.DisabledSqlOptimizer
2024-10-10 19:55:17,940 INFO  com.hazelcast.internal.diagnostics.Diagnostics - [localhost]:5801 [seatunnel-516897] [5.1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2024-10-10 19:55:17,944 INFO  com.hazelcast.core.LifecycleService - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5801 is STARTING
2024-10-10 19:55:17,944 DEBUG com.hazelcast.internal.partition.InternalPartitionService - [localhost]:5801 [seatunnel-516897] [5.1] Adding Member [localhost]:5801 - 1e45bcb8-c93e-4a36-895b-6528261f2ddd this
2024-10-10 19:55:17,951 DEBUG com.hazelcast.internal.networking.nio.NioNetworking - [localhost]:5801 [seatunnel-516897] [5.1] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads
2024-10-10 19:55:17,951 DEBUG com.hazelcast.internal.networking.nio.NioNetworking - [localhost]:5801 [seatunnel-516897] [5.1] write through enabled:true
2024-10-10 19:55:17,951 DEBUG com.hazelcast.internal.networking.nio.NioNetworking - [localhost]:5801 [seatunnel-516897] [5.1] IO threads selector mode is SELECT
2024-10-10 19:55:17,959 DEBUG com.hazelcast.internal.cluster.ClusterService - [localhost]:5801 [seatunnel-516897] [5.1] Setting master address to null
2024-10-10 19:55:17,959 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5801 is local? true
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5802 is local? false
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5803 is local? false
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5804 is local? false
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5805 is local? false
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5806 is local? false
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5807 is local? false
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5808 is local? false
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5809 is local? false
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5810 is local? false
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5811 is local? false
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5812 is local? false
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5813 is local? false
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5814 is local? false
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5815 is local? false
2024-10-10 19:55:17,960 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5816 is local? false
2024-10-10 19:55:17,961 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5817 is local? false
2024-10-10 19:55:17,961 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5818 is local? false
2024-10-10 19:55:17,961 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5819 is local? false
2024-10-10 19:55:17,961 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5820 is local? false
2024-10-10 19:55:17,961 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5821 is local? false
2024-10-10 19:55:17,961 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5822 is local? false
2024-10-10 19:55:17,961 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5823 is local? false
2024-10-10 19:55:17,961 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5824 is local? false
2024-10-10 19:55:17,961 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5825 is local? false
2024-10-10 19:55:17,961 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5826 is local? false
2024-10-10 19:55:17,961 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5827 is local? false
2024-10-10 19:55:17,961 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5828 is local? false
2024-10-10 19:55:17,961 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5829 is local? false
2024-10-10 19:55:17,961 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5830 is local? false
2024-10-10 19:55:17,962 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] NOT sending master question to blacklisted endpoints: {}
2024-10-10 19:55:17,962 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5823
2024-10-10 19:55:17,965 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5823 streamId:-1 is not yet in progress
2024-10-10 19:55:17,965 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5821
2024-10-10 19:55:17,966 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5821 streamId:-1 is not yet in progress
2024-10-10 19:55:17,966 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5827
2024-10-10 19:55:17,966 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5827 streamId:-1 is not yet in progress
2024-10-10 19:55:17,966 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5825
2024-10-10 19:55:17,966 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5825 streamId:-1 is not yet in progress
2024-10-10 19:55:17,966 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5815
2024-10-10 19:55:17,966 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5815 streamId:-1 is not yet in progress
2024-10-10 19:55:17,967 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5813
2024-10-10 19:55:17,967 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5813 streamId:-1 is not yet in progress
2024-10-10 19:55:17,967 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5819
2024-10-10 19:55:17,967 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5819 streamId:-1 is not yet in progress
2024-10-10 19:55:17,967 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5817
2024-10-10 19:55:17,967 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5817 streamId:-1 is not yet in progress
2024-10-10 19:55:17,971 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5806
2024-10-10 19:55:17,971 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5806 streamId:-1 is not yet in progress
2024-10-10 19:55:17,971 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5804
2024-10-10 19:55:17,972 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5804 streamId:-1 is not yet in progress
2024-10-10 19:55:17,972 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5810
2024-10-10 19:55:17,972 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5810 streamId:-1 is not yet in progress
2024-10-10 19:55:17,972 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5808
2024-10-10 19:55:17,972 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5808 streamId:-1 is not yet in progress
2024-10-10 19:55:17,972 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5829
2024-10-10 19:55:17,972 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5829 streamId:-1 is not yet in progress
2024-10-10 19:55:17,972 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5802
2024-10-10 19:55:17,973 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5802 streamId:-1 is not yet in progress
2024-10-10 19:55:17,973 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5822
2024-10-10 19:55:17,973 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5822 streamId:-1 is not yet in progress
2024-10-10 19:55:17,973 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5820
2024-10-10 19:55:17,973 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5820 streamId:-1 is not yet in progress
2024-10-10 19:55:17,974 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5826
2024-10-10 19:55:17,974 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5826 streamId:-1 is not yet in progress
2024-10-10 19:55:17,974 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5824
2024-10-10 19:55:17,974 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5824 streamId:-1 is not yet in progress
2024-10-10 19:55:17,974 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5814
2024-10-10 19:55:17,974 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5814 streamId:-1 is not yet in progress
2024-10-10 19:55:17,974 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5812
2024-10-10 19:55:17,974 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5812 streamId:-1 is not yet in progress
2024-10-10 19:55:17,974 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5818
2024-10-10 19:55:17,974 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5818 streamId:-1 is not yet in progress
2024-10-10 19:55:17,974 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5816
2024-10-10 19:55:17,974 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5816 streamId:-1 is not yet in progress
2024-10-10 19:55:17,974 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5807
2024-10-10 19:55:17,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5807 streamId:-1 is not yet in progress
2024-10-10 19:55:17,975 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5805
2024-10-10 19:55:17,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5805 streamId:-1 is not yet in progress
2024-10-10 19:55:17,975 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5811
2024-10-10 19:55:17,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5811 streamId:-1 is not yet in progress
2024-10-10 19:55:17,975 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5809
2024-10-10 19:55:17,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5809 streamId:-1 is not yet in progress
2024-10-10 19:55:17,975 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5830
2024-10-10 19:55:17,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5830 streamId:-1 is not yet in progress
2024-10-10 19:55:17,975 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5828
2024-10-10 19:55:17,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5828 streamId:-1 is not yet in progress
2024-10-10 19:55:17,975 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] Sending master question to [localhost]:5803
2024-10-10 19:55:17,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5803 streamId:-1 is not yet in progress
2024-10-10 19:55:17,985 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5819 is added to the blacklist.
2024-10-10 19:55:17,985 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5815 is added to the blacklist.
2024-10-10 19:55:17,985 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5817 is added to the blacklist.
2024-10-10 19:55:17,985 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5825 is added to the blacklist.
2024-10-10 19:55:17,985 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5823 is added to the blacklist.
2024-10-10 19:55:17,985 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5821 is added to the blacklist.
2024-10-10 19:55:17,985 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5806 is added to the blacklist.
2024-10-10 19:55:17,985 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5827 is added to the blacklist.
2024-10-10 19:55:17,987 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5820 is added to the blacklist.
2024-10-10 19:55:17,987 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5813 is added to the blacklist.
2024-10-10 19:55:17,987 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5810 is added to the blacklist.
2024-10-10 19:55:17,987 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5808 is added to the blacklist.
2024-10-10 19:55:17,987 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5802 is added to the blacklist.
2024-10-10 19:55:17,988 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5822 is added to the blacklist.
2024-10-10 19:55:17,990 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5829 is added to the blacklist.
2024-10-10 19:55:17,991 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5804 is added to the blacklist.
2024-10-10 19:55:17,993 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5814 is added to the blacklist.
2024-10-10 19:55:17,994 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5824 is added to the blacklist.
2024-10-10 19:55:17,994 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5809 is added to the blacklist.
2024-10-10 19:55:17,994 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5805 is added to the blacklist.
2024-10-10 19:55:17,994 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5818 is added to the blacklist.
2024-10-10 19:55:17,995 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5811 is added to the blacklist.
2024-10-10 19:55:17,995 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5807 is added to the blacklist.
2024-10-10 19:55:17,995 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5812 is added to the blacklist.
2024-10-10 19:55:17,995 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5803 is added to the blacklist.
2024-10-10 19:55:17,996 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5828 is added to the blacklist.
2024-10-10 19:55:17,996 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5816 is added to the blacklist.
2024-10-10 19:55:17,996 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5826 is added to the blacklist.
2024-10-10 19:55:17,996 INFO  org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5830 is added to the blacklist.
2024-10-10 19:55:18,068 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5827 streamId:-1 is not yet in progress
2024-10-10 19:55:18,068 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5823 streamId:-1 is not yet in progress
2024-10-10 19:55:18,068 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5825 streamId:-1 is not yet in progress
2024-10-10 19:55:18,068 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5821 streamId:-1 is not yet in progress
2024-10-10 19:55:18,069 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5815 streamId:-1 is not yet in progress
2024-10-10 19:55:18,069 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5813 streamId:-1 is not yet in progress
2024-10-10 19:55:18,069 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5819 streamId:-1 is not yet in progress
2024-10-10 19:55:18,072 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5806 streamId:-1 is not yet in progress
2024-10-10 19:55:18,072 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5817 streamId:-1 is not yet in progress
2024-10-10 19:55:18,072 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5804 streamId:-1 is not yet in progress
2024-10-10 19:55:18,072 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5810 streamId:-1 is not yet in progress
2024-10-10 19:55:18,072 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5808 streamId:-1 is not yet in progress
2024-10-10 19:55:18,072 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5829 streamId:-1 is not yet in progress
2024-10-10 19:55:18,073 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5802 streamId:-1 is not yet in progress
2024-10-10 19:55:18,073 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5822 streamId:-1 is not yet in progress
2024-10-10 19:55:18,074 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5820 streamId:-1 is not yet in progress
2024-10-10 19:55:18,074 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5826 streamId:-1 is not yet in progress
2024-10-10 19:55:18,074 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5824 streamId:-1 is not yet in progress
2024-10-10 19:55:18,074 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5814 streamId:-1 is not yet in progress
2024-10-10 19:55:18,074 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5812 streamId:-1 is not yet in progress
2024-10-10 19:55:18,074 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5818 streamId:-1 is not yet in progress
2024-10-10 19:55:18,075 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5816 streamId:-1 is not yet in progress
2024-10-10 19:55:18,075 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5807 streamId:-1 is not yet in progress
2024-10-10 19:55:18,075 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5805 streamId:-1 is not yet in progress
2024-10-10 19:55:18,075 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5811 streamId:-1 is not yet in progress
2024-10-10 19:55:18,075 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5809 streamId:-1 is not yet in progress
2024-10-10 19:55:18,075 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5830 streamId:-1 is not yet in progress
2024-10-10 19:55:18,075 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5828 streamId:-1 is not yet in progress
2024-10-10 19:55:18,075 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5803 streamId:-1 is not yet in progress
2024-10-10 19:55:18,270 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5823 streamId:-1 is not yet in progress
2024-10-10 19:55:18,270 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5825 streamId:-1 is not yet in progress
2024-10-10 19:55:18,270 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5827 streamId:-1 is not yet in progress
2024-10-10 19:55:18,271 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5815 streamId:-1 is not yet in progress
2024-10-10 19:55:18,270 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5821 streamId:-1 is not yet in progress
2024-10-10 19:55:18,271 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5813 streamId:-1 is not yet in progress
2024-10-10 19:55:18,271 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5819 streamId:-1 is not yet in progress
2024-10-10 19:55:18,272 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5804 streamId:-1 is not yet in progress
2024-10-10 19:55:18,272 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5810 streamId:-1 is not yet in progress
2024-10-10 19:55:18,272 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5817 streamId:-1 is not yet in progress
2024-10-10 19:55:18,272 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5806 streamId:-1 is not yet in progress
2024-10-10 19:55:18,272 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5808 streamId:-1 is not yet in progress
2024-10-10 19:55:18,273 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5829 streamId:-1 is not yet in progress
2024-10-10 19:55:18,273 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5802 streamId:-1 is not yet in progress
2024-10-10 19:55:18,274 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5822 streamId:-1 is not yet in progress
2024-10-10 19:55:18,274 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5820 streamId:-1 is not yet in progress
2024-10-10 19:55:18,274 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5826 streamId:-1 is not yet in progress
2024-10-10 19:55:18,274 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5824 streamId:-1 is not yet in progress
2024-10-10 19:55:18,274 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5814 streamId:-1 is not yet in progress
2024-10-10 19:55:18,274 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5812 streamId:-1 is not yet in progress
2024-10-10 19:55:18,274 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5818 streamId:-1 is not yet in progress
2024-10-10 19:55:18,275 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5816 streamId:-1 is not yet in progress
2024-10-10 19:55:18,275 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5807 streamId:-1 is not yet in progress
2024-10-10 19:55:18,275 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5805 streamId:-1 is not yet in progress
2024-10-10 19:55:18,275 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5811 streamId:-1 is not yet in progress
2024-10-10 19:55:18,275 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5809 streamId:-1 is not yet in progress
2024-10-10 19:55:18,275 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5830 streamId:-1 is not yet in progress
2024-10-10 19:55:18,275 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5828 streamId:-1 is not yet in progress
2024-10-10 19:55:18,276 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5803 streamId:-1 is not yet in progress
2024-10-10 19:55:18,573 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5823 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5815 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5825 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5827 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5821 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5819 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5813 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5804 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5817 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5806 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5810 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5829 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5808 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5802 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5822 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5820 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5824 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5826 streamId:-1 is not yet in progress
2024-10-10 19:55:18,574 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5814 streamId:-1 is not yet in progress
2024-10-10 19:55:18,575 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5812 streamId:-1 is not yet in progress
2024-10-10 19:55:18,575 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5818 streamId:-1 is not yet in progress
2024-10-10 19:55:18,575 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5816 streamId:-1 is not yet in progress
2024-10-10 19:55:18,575 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5807 streamId:-1 is not yet in progress
2024-10-10 19:55:18,575 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5805 streamId:-1 is not yet in progress
2024-10-10 19:55:18,575 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5811 streamId:-1 is not yet in progress
2024-10-10 19:55:18,575 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5809 streamId:-1 is not yet in progress
2024-10-10 19:55:18,575 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5830 streamId:-1 is not yet in progress
2024-10-10 19:55:18,576 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5828 streamId:-1 is not yet in progress
2024-10-10 19:55:18,576 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5803 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5823 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5825 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5815 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5827 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5821 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5819 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5813 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5817 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5804 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5806 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5810 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5829 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5808 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5802 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5820 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5824 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5822 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5812 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5826 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5818 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5814 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5816 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5807 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5805 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5811 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5809 streamId:-1 is not yet in progress
2024-10-10 19:55:18,975 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5830 streamId:-1 is not yet in progress
2024-10-10 19:55:18,976 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5803 streamId:-1 is not yet in progress
2024-10-10 19:55:18,976 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Connection to: [localhost]:5828 streamId:-1 is not yet in progress
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5823 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5821 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5827 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5825 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5815 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5813 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5819 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5817 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5806 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5804 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5810 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5808 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5829 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5802 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5822 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5820 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5826 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5824 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5814 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5812 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5818 is local? false
2024-10-10 19:55:18,977 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5816 is local? false
2024-10-10 19:55:18,978 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5807 is local? false
2024-10-10 19:55:18,978 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5805 is local? false
2024-10-10 19:55:18,978 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5811 is local? false
2024-10-10 19:55:18,978 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5809 is local? false
2024-10-10 19:55:18,978 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5830 is local? false
2024-10-10 19:55:18,978 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5828 is local? false
2024-10-10 19:55:18,978 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5803 is local? false
2024-10-10 19:55:18,978 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] This node will assume master role since none of the possible members accepted join request.
2024-10-10 19:55:18,978 DEBUG com.hazelcast.internal.cluster.ClusterService - [localhost]:5801 [seatunnel-516897] [5.1] Setting master address to [localhost]:5801
2024-10-10 19:55:18,978 DEBUG com.hazelcast.internal.cluster.impl.MembershipManager - [localhost]:5801 [seatunnel-516897] [5.1] Local member list join version is set to 1
2024-10-10 19:55:18,978 DEBUG org.apache.seatunnel.engine.server.LiteNodeDropOutTcpIpJoiner - [localhost]:5801 [seatunnel-516897] [5.1] PostJoin master: [localhost]:5801, isMaster: true
2024-10-10 19:55:18,978 INFO  com.hazelcast.internal.cluster.ClusterService - [localhost]:5801 [seatunnel-516897] [5.1] 

Members {size:1, ver:1} [
	Member [localhost]:5801 - 1e45bcb8-c93e-4a36-895b-6528261f2ddd this master
]

2024-10-10 19:55:18,987 INFO  com.hazelcast.core.LifecycleService - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5801 is STARTED
2024-10-10 19:55:19,002 DEBUG com.hazelcast.internal.metrics.impl.MetricsConfigHelper - hz.client_1 [seatunnel-516897] [5.1] Collecting debug metrics and sending to diagnostics is disabled
2024-10-10 19:55:19,007 DEBUG com.hazelcast.internal.util.ServiceLoader - The class com.hazelcast.jet.impl.observer.JetObserverDataSerializerHook does not implement the expected interface com.hazelcast.nio.serialization.SerializerHook
2024-10-10 19:55:19,007 DEBUG com.hazelcast.internal.util.ServiceLoader - The class com.hazelcast.jet.impl.metrics.JetMetricsDataSerializerHook does not implement the expected interface com.hazelcast.nio.serialization.SerializerHook
2024-10-10 19:55:19,015 INFO  com.hazelcast.client.impl.spi.ClientInvocationService - hz.client_1 [seatunnel-516897] [5.1] Running with 2 response threads, dynamic=true
2024-10-10 19:55:19,021 INFO  org.apache.seatunnel.engine.server.CoordinatorService - [localhost]:5801 [seatunnel-516897] [5.1] This node become a new active master node, begin init coordinator service
2024-10-10 19:55:19,021 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-516897] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is STARTING
2024-10-10 19:55:19,021 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-516897] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is STARTED
2024-10-10 19:55:19,023 DEBUG com.hazelcast.internal.networking.nio.NioNetworking - hz.client_1 [seatunnel-516897] [5.1] TcpIpConnectionManager configured with Non Blocking IO-threading model: 1 input threads and 1 output threads
2024-10-10 19:55:19,023 DEBUG com.hazelcast.internal.networking.nio.NioNetworking - hz.client_1 [seatunnel-516897] [5.1] write through enabled:true
2024-10-10 19:55:19,023 DEBUG com.hazelcast.internal.networking.nio.NioNetworking - hz.client_1 [seatunnel-516897] [5.1] IO threads selector mode is SELECT
2024-10-10 19:55:19,024 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-516897] [5.1] Trying to connect to cluster: seatunnel-516897
2024-10-10 19:55:19,025 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-516897] [5.1] Trying to connect to [localhost]:5801
2024-10-10 19:55:19,034 DEBUG com.hazelcast.internal.server.tcp.TcpServerAcceptor - [localhost]:5801 [seatunnel-516897] [5.1] Accepting socket connection from /127.0.0.1:51836
2024-10-10 19:55:19,034 DEBUG com.hazelcast.internal.server.tcp.TcpServerConnectionManager - [localhost]:5801 [seatunnel-516897] [5.1] Established socket connection between /127.0.0.1:5801 and /127.0.0.1:51836
2024-10-10 19:55:19,042 DEBUG com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask - [localhost]:5801 [seatunnel-516897] [5.1] Processing authentication with clientUuid 7222c435-584a-4656-a9bb-1a3ae4c0c645 and clientName hz.client_1
2024-10-10 19:55:19,043 INFO  com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask - [localhost]:5801 [seatunnel-516897] [5.1] Received auth from Connection[id=1, /127.0.0.1:5801->/127.0.0.1:51836, qualifier=null, endpoint=[127.0.0.1]:51836, remoteUuid=7222c435-584a-4656-a9bb-1a3ae4c0c645, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: 7222c435-584a-4656-a9bb-1a3ae4c0c645, client name: hz.client_1, client version: 5.1
2024-10-10 19:55:19,045 DEBUG com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-516897] [5.1] Checking the cluster: 1efc8f3f-4b3f-4adb-a77c-541562dcbcf3, current cluster: null
2024-10-10 19:55:19,045 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-516897] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_CONNECTED
2024-10-10 19:55:19,045 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-516897] [5.1] Authenticated with server [localhost]:5801:1e45bcb8-c93e-4a36-895b-6528261f2ddd, server version: 5.1, local address: /127.0.0.1:51836
2024-10-10 19:55:19,046 INFO  com.hazelcast.internal.diagnostics.Diagnostics - hz.client_1 [seatunnel-516897] [5.1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2024-10-10 19:55:19,047 DEBUG com.hazelcast.client.impl.spi.ClientClusterService - hz.client_1 [seatunnel-516897] [5.1] Resetting the member list version 
2024-10-10 19:55:19,053 DEBUG com.hazelcast.client.impl.spi.ClientClusterService - hz.client_1 [seatunnel-516897] [5.1] There are internal addresses of members used in the config. The client will use internal addresses
2024-10-10 19:55:19,053 INFO  com.hazelcast.client.impl.spi.ClientClusterService - hz.client_1 [seatunnel-516897] [5.1] 

Members [1] {
	Member [localhost]:5801 - 1e45bcb8-c93e-4a36-895b-6528261f2ddd
}

2024-10-10 19:55:19,066 INFO  com.hazelcast.client.impl.statistics.ClientStatisticsService - Client statistics is enabled with period 5 seconds.
2024-10-10 19:55:19,102 INFO  org.apache.seatunnel.engine.server.CoordinatorService - [localhost]:5801 [seatunnel-516897] [5.1] Loaded event handlers: [org.apache.seatunnel.api.event.LoggingEventHandler@4b95c80d]
2024-10-10 19:55:19,111 INFO  com.hazelcast.internal.partition.impl.PartitionStateManager - [localhost]:5801 [seatunnel-516897] [5.1] Initializing cluster partition table arrangement...
2024-10-10 19:55:19,116 DEBUG com.hazelcast.flakeidgen.impl.FlakeIdGeneratorProxy - [localhost]:5801 [seatunnel-516897] [5.1] Node ID assigned to 'SeaTunnelIdGenerator': 1
2024-10-10 19:55:19,118 DEBUG com.hazelcast.internal.partition.InternalPartitionService - [localhost]:5801 [seatunnel-516897] [5.1] Publishing partition state, stamp: -8661523421455686299
2024-10-10 19:55:19,223 DEBUG com.hazelcast.client.impl.spi.ClientPartitionService - hz.client_1 [seatunnel-516897] [5.1] Applied partition table with partitionStateVersion : 1
2024-10-10 19:55:19,897 INFO  org.apache.seatunnel.engine.client.job.ClientJobProxy - Start submit job, job id: 896765344050315265, with plugin jar []
2024-10-10 19:55:19,938 DEBUG com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor - [localhost]:5801 [seatunnel-516897] [5.1] Invocations:1 timeouts:0 backup-timeouts:0
2024-10-10 19:55:19,983 INFO  org.apache.seatunnel.engine.server.master.JobMaster - in batch mode, the 'checkpoint.interval' configuration of env is missing, so checkpoint will be disabled
2024-10-10 19:55:19,984 INFO  org.apache.seatunnel.engine.server.master.JobMaster - Init JobMaster for Job hdfs_to_hdfs_local.conf (896765344050315265) 
2024-10-10 19:55:19,984 INFO  org.apache.seatunnel.engine.server.master.JobMaster - Job hdfs_to_hdfs_local.conf (896765344050315265) needed jar urls []
2024-10-10 19:55:20,436 INFO  org.apache.seatunnel.engine.client.job.ClientJobProxy - Submit job finished, job id: 896765344050315265, job name: hdfs_to_hdfs_local.conf
2024-10-10 19:55:20,462 DEBUG org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - received slot request, jobID: 896765344050315265, resource profile: ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=0}}, return: SlotProfile{worker=[localhost]:5801, slotID=1, ownerJobID=896765344050315265, assigned=true, resourceProfile=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=0}}, sequence='dd8d498b-fcad-4140-b84b-a5e0b66428cf'}
2024-10-10 19:55:20,462 DEBUG org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - received slot request, jobID: 896765344050315265, resource profile: ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=0}}, return: SlotProfile{worker=[localhost]:5801, slotID=2, ownerJobID=896765344050315265, assigned=true, resourceProfile=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=0}}, sequence='dd8d498b-fcad-4140-b84b-a5e0b66428cf'}
2024-10-10 19:55:20,462 DEBUG org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - received slot request, jobID: 896765344050315265, resource profile: ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=0}}, return: SlotProfile{worker=[localhost]:5801, slotID=3, ownerJobID=896765344050315265, assigned=true, resourceProfile=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=0}}, sequence='dd8d498b-fcad-4140-b84b-a5e0b66428cf'}
2024-10-10 19:55:20,493 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] received deploying task executionId [896765349725208577]
2024-10-10 19:55:20,495 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] deploying task TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=1}, executionId [896765349725208577]
2024-10-10 19:55:20,495 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] deploying TaskGroup TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=1} init success
2024-10-10 19:55:20,497 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] deploying TaskGroup TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=1} success
2024-10-10 19:55:20,504 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] received deploying task executionId [896765349725274113]
2024-10-10 19:55:20,506 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] deploying task TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=3}, executionId [896765349725274113]
2024-10-10 19:55:20,506 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] deploying TaskGroup TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=3} init success
2024-10-10 19:55:20,506 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] deploying TaskGroup TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=3} success
2024-10-10 19:55:20,530 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] accept async execute function from TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=1} with id 01ad8e54-aa18-481e-b3df-f106a6f340ee
2024-10-10 19:55:20,530 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] accept async execute function from TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=3} with id 6f597f28-3d44-420b-a175-96b686533e3d
2024-10-10 19:55:20,533 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] received deploying task executionId [896765349725339649]
2024-10-10 19:55:20,535 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] remove async execute function from TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=3} with id 6f597f28-3d44-420b-a175-96b686533e3d
2024-10-10 19:55:20,535 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] remove async execute function from TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=1} with id 01ad8e54-aa18-481e-b3df-f106a6f340ee
2024-10-10 19:55:20,535 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] deploying task TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000}, executionId [896765349725339649]
2024-10-10 19:55:20,535 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] deploying TaskGroup TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000} init success
2024-10-10 19:55:20,536 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] deploying TaskGroup TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000} success
2024-10-10 19:55:20,560 INFO  org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask - starting seatunnel transform task, index 0
2024-10-10 19:55:20,567 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] accept async execute function from TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000} with id 9a04f6bd-d979-4a29-a7c4-90da4e375697
2024-10-10 19:55:20,570 INFO  org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask - starting seatunnel source task, index 0
2024-10-10 19:55:20,593 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] remove async execute function from TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000} with id 9a04f6bd-d979-4a29-a7c4-90da4e375697
2024-10-10 19:55:20,630 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] accept async execute function from TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000} with id 741adbb0-be05-431d-a0c5-9c8b11608bd5
2024-10-10 19:55:20,630 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] remove async execute function from TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000} with id 741adbb0-be05-431d-a0c5-9c8b11608bd5
2024-10-10 19:55:20,731 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] accept async execute function from TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=1} with id 281d1f09-8d53-4598-8bb7-3f071e4f2c85
2024-10-10 19:55:20,731 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] remove async execute function from TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=1} with id 281d1f09-8d53-4598-8bb7-3f071e4f2c85
2024-10-10 19:55:20,938 DEBUG com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor - [localhost]:5801 [seatunnel-516897] [5.1] Invocations:1 timeouts:0 backup-timeouts:0
2024-10-10 19:55:21,938 DEBUG com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor - [localhost]:5801 [seatunnel-516897] [5.1] Invocations:1 timeouts:0 backup-timeouts:0
2024-10-10 19:55:22,127 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] accept async execute function from TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=1} with id 9716ade2-70c5-450f-a363-b7c6deefbad5
2024-10-10 19:55:22,129 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] accept async execute function from TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000} with id 10fa7497-ebbd-4c02-a627-9d644051b6af
2024-10-10 19:55:22,132 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] remove async execute function from TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=1} with id 9716ade2-70c5-450f-a363-b7c6deefbad5
2024-10-10 19:55:22,132 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] remove async execute function from TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000} with id 10fa7497-ebbd-4c02-a627-9d644051b6af
2024-10-10 19:55:22,705 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] taskDone, taskId = 20000, taskGroup = TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=1}
2024-10-10 19:55:22,717 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] 
***********************************************
    TaskExecutionServer Thread Pool Status
***********************************************
activeCount               :                   5
threadShareTaskQueueSize  :                   0
completedTaskCount        :                   7
taskCount                 :                  12
***********************************************

2024-10-10 19:55:22,717 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] taskGroup TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=1} complete with FINISHED
2024-10-10 19:55:22,717 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] Task TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=1} complete with state FINISHED
2024-10-10 19:55:22,717 INFO  org.apache.seatunnel.engine.server.CoordinatorService - [localhost]:5801 [seatunnel-516897] [5.1] Received task end from execution TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=1}, state FINISHED
2024-10-10 19:55:22,727 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] taskDone, taskId = 60000, taskGroup = TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000}
2024-10-10 19:55:22,775 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] taskDone, taskId = 70000, taskGroup = TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000}
2024-10-10 19:55:22,778 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] 
***********************************************
    TaskExecutionServer Thread Pool Status
***********************************************
activeCount               :                   3
threadShareTaskQueueSize  :                   0
completedTaskCount        :                  10
taskCount                 :                  13
***********************************************

2024-10-10 19:55:22,778 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] taskGroup TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000} complete with FINISHED
2024-10-10 19:55:22,778 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] Task TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000} complete with state FINISHED
2024-10-10 19:55:22,778 INFO  org.apache.seatunnel.engine.server.CoordinatorService - [localhost]:5801 [seatunnel-516897] [5.1] Received task end from execution TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000}, state FINISHED
2024-10-10 19:55:22,779 INFO  org.apache.seatunnel.engine.server.master.JobMaster - release the task group resource TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=50000}
2024-10-10 19:55:22,779 INFO  org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - received slot release request, jobID: 896765344050315265, slot: SlotProfile{worker=[localhost]:5801, slotID=2, ownerJobID=896765344050315265, assigned=true, resourceProfile=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=0}}, sequence='dd8d498b-fcad-4140-b84b-a5e0b66428cf'}
2024-10-10 19:55:22,792 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] taskDone, taskId = 40000, taskGroup = TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=3}
2024-10-10 19:55:22,794 DEBUG org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] 
***********************************************
    TaskExecutionServer Thread Pool Status
***********************************************
activeCount               :                   2
threadShareTaskQueueSize  :                   0
completedTaskCount        :                  12
taskCount                 :                  14
***********************************************

2024-10-10 19:55:22,794 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] taskGroup TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=3} complete with FINISHED
2024-10-10 19:55:22,794 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] Task TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=3} complete with state FINISHED
2024-10-10 19:55:22,794 INFO  org.apache.seatunnel.engine.server.CoordinatorService - [localhost]:5801 [seatunnel-516897] [5.1] Received task end from execution TaskGroupLocation{jobId=896765344050315265, pipelineId=1, taskGroupId=3}, state FINISHED
2024-10-10 19:55:22,819 INFO  org.apache.seatunnel.engine.server.master.JobMaster - release the pipeline Job hdfs_to_hdfs_local.conf (896765344050315265), Pipeline: [(1/1)] resource
2024-10-10 19:55:22,819 INFO  org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - received slot release request, jobID: 896765344050315265, slot: SlotProfile{worker=[localhost]:5801, slotID=3, ownerJobID=896765344050315265, assigned=true, resourceProfile=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=0}}, sequence='dd8d498b-fcad-4140-b84b-a5e0b66428cf'}
2024-10-10 19:55:22,820 INFO  org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - received slot release request, jobID: 896765344050315265, slot: SlotProfile{worker=[localhost]:5801, slotID=1, ownerJobID=896765344050315265, assigned=true, resourceProfile=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=0}}, sequence='dd8d498b-fcad-4140-b84b-a5e0b66428cf'}
2024-10-10 19:55:22,858 INFO  org.apache.seatunnel.engine.client.job.ClientJobProxy - Job (896765344050315265) end with state FINISHED
2024-10-10 19:55:22,880 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-516897] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTTING_DOWN
2024-10-10 19:55:22,882 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-516897] [5.1] Removed connection to endpoint: [localhost]:5801:1e45bcb8-c93e-4a36-895b-6528261f2ddd, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:51836->localhost/127.0.0.1:5801}, remoteAddress=[localhost]:5801, lastReadTime=2024-10-10 19:55:22.875, lastWriteTime=2024-10-10 19:55:22.858, closedTime=2024-10-10 19:55:22.881, connected server version=5.1}
2024-10-10 19:55:22,882 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-516897] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_DISCONNECTED
2024-10-10 19:55:22,883 INFO  com.hazelcast.internal.server.tcp.TcpServerConnection - [localhost]:5801 [seatunnel-516897] [5.1] Connection[id=1, /127.0.0.1:5801->/127.0.0.1:51836, qualifier=null, endpoint=[127.0.0.1]:51836, remoteUuid=7222c435-584a-4656-a9bb-1a3ae4c0c645, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: Connection closed by the other side
2024-10-10 19:55:22,883 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-516897] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTDOWN
2024-10-10 19:55:22,883 INFO  com.hazelcast.core.LifecycleService - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5801 is SHUTTING_DOWN
2024-10-10 19:55:22,884 DEBUG com.hazelcast.internal.cluster.ClusterService - [localhost]:5801 [seatunnel-516897] [5.1] Removed connection to [127.0.0.1]:51836
2024-10-10 19:55:22,885 DEBUG com.hazelcast.internal.server.tcp.LocalAddressRegistry - [localhost]:5801 [seatunnel-516897] [5.1] LinkedAddresses{primaryAddress=[127.0.0.1]:51836, allLinkedAddresses=[[127.0.0.1]:51836]} previously registered for the instance uuid=7222c435-584a-4656-a9bb-1a3ae4c0c645 are removed from the registry
2024-10-10 19:55:22,885 INFO  com.hazelcast.client.impl.ClientEndpointManager - [localhost]:5801 [seatunnel-516897] [5.1] Destroying ClientEndpoint{connection=Connection[id=1, /127.0.0.1:5801->/127.0.0.1:51836, qualifier=null, endpoint=[127.0.0.1]:51836, remoteUuid=7222c435-584a-4656-a9bb-1a3ae4c0c645, alive=false, connectionType=JVM, planeIndex=-1], clientUuid=7222c435-584a-4656-a9bb-1a3ae4c0c645, clientName=hz.client_1, authenticated=true, clientVersion=5.1, creationTime=1728570319041, latest clientAttributes=lastStatisticsCollectionTime=1728570319066,enterprise=false,clientType=JVM,clientVersion=5.1,clusterConnectionTimestamp=1728570319033,clientAddress=127.0.0.1,clientName=hz.client_1,credentials.principal=null,os.committedVirtualMemorySize=0,os.freePhysicalMemorySize=79331328,os.freeSwapSpaceSize=0,os.maxFileDescriptorCount=0,os.openFileDescriptorCount=0,os.processCpuTime=0,os.systemLoadAverage=7.28125,os.totalPhysicalMemorySize=34359738368,os.totalSwapSpaceSize=0,runtime.availableProcessors=10,runtime.freeMemory=121543800,runtime.maxMemory=8589934592,runtime.totalMemory=201326592,runtime.uptime=2463,runtime.usedMemory=79847504, labels=[]}
2024-10-10 19:55:22,885 INFO  com.hazelcast.internal.partition.impl.MigrationManager - [localhost]:5801 [seatunnel-516897] [5.1] Shutdown request of Member [localhost]:5801 - 1e45bcb8-c93e-4a36-895b-6528261f2ddd this master is handled
2024-10-10 19:55:22,885 DEBUG com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-516897] [5.1] Graceful shutdown completed for com.hazelcast.cp.internal.RaftService@6bccd036
2024-10-10 19:55:22,885 DEBUG com.hazelcast.internal.crdt.CRDTReplicationMigrationService - [localhost]:5801 [seatunnel-516897] [5.1] Skipping replication since all CRDTs are replicated
2024-10-10 19:55:22,885 DEBUG com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-516897] [5.1] Graceful shutdown completed for com.hazelcast.cp.internal.session.ProxySessionManagerService@797ada16
2024-10-10 19:55:22,885 DEBUG com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-516897] [5.1] Graceful shutdown completed for CRDTReplicationMigrationService{}
2024-10-10 19:55:22,890 DEBUG com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-516897] [5.1] Graceful shutdown completed for InternalPartitionService {stamp: -8661523421455686299, migrationQ: 0}
2024-10-10 19:55:22,890 DEBUG com.hazelcast.internal.cluster.ClusterService - [localhost]:5801 [seatunnel-516897] [5.1] Setting master address to null
2024-10-10 19:55:22,890 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-516897] [5.1] Shutting down connection manager...
2024-10-10 19:55:22,891 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-516897] [5.1] Shutting down node engine...
2024-10-10 19:55:22,895 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-516897] [5.1] Event forward thread interrupted
2024-10-10 19:55:22,895 DEBUG com.hazelcast.internal.cluster.ClusterService - [localhost]:5801 [seatunnel-516897] [5.1] Setting master address to null
2024-10-10 19:55:23,142 INFO  com.hazelcast.instance.impl.NodeExtension - [localhost]:5801 [seatunnel-516897] [5.1] Destroying node NodeExtension.
2024-10-10 19:55:23,142 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-516897] [5.1] Hazelcast Shutdown is completed in 257 ms.
2024-10-10 19:55:23,142 INFO  com.hazelcast.core.LifecycleService - [localhost]:5801 [seatunnel-516897] [5.1] [localhost]:5801 is SHUTDOWN

Process finished with exit code 0
```

image

**Review by Hisoka-X — APPROVED** [review]
LGTM. Thanks @shashwatsai!

**Review by liugddx — APPROVED** [review]
LGTM
