### PR TITLE
[Hotfix][E2E] Update Test Container Version of SeaTunnel engine

### LINKED ISSUE #5321: [Hotfix] [E2E] The version of SeatTunnel Engine in TestContainerId is too old
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

https://github.com/apache/seatunnel/blob/ed5eadcf73b81af7e08461eeeef80ae09d807635/seatunnel-e2e/seatunnel-e2e-common/src/test/java/org/apache/seatunnel/e2e/common/container/TestContainerId.java#L28-L35

The Version of SeaTunnel is too old.

### SeaTunnel Version

null

### SeaTunnel Config

```conf
null
```

### Running Command

```shell
null
```

### Error Exception

```log
null
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by CheneyYin**
## Purpose of this pull request
- FIX #5321 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [x] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

File: seatunnel-e2e/seatunnel-e2e-common/src/test/java/org/apache/seatunnel/e2e/common/container/TestContainerId.java [hunk 1]
```diff
@@ -32,7 +32,7 @@ public enum TestContainerId {
     FLINK_1_16(FLINK, "1.16.0"),
     SPARK_2_4(SPARK, "2.4.6"),
     SPARK_3_3(SPARK, "3.3.0"),
-    SEATUNNEL(EngineType.SEATUNNEL, "2.3.1");
+    SEATUNNEL(EngineType.SEATUNNEL, "latest");
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-e2e-common/src/test/java/org/apache/seatunnel/e2e/common/container/TestContainerId.java]: how about `dev`?

Comment (CheneyYin) [reply seatunnel-e2e/seatunnel-e2e-common/src/test/java/org/apache/seatunnel/e2e/common/container/TestContainerId.java]: 👍 `dev` is appropriate.

**Review by Hisoka-X — APPROVED** [review]
LGTM, thanks @CheneyYin

**Review by liugddx — APPROVED** [review]
