### PR TITLE
[Fix][Connector-V2][Hbase] Fix source reader only scanning first split

### LINKED ISSUE #10286: [Bug][Connector-V2][Hbase] HBase source only scans the first split/region, read count << HBase count
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When running an HBase -> HBase pipeline with the SeaTunnel connector-v2 HBase source, the job finishes successfully but the `Total Read Count` is much smaller than the real row count in HBase.

- HBase shell `count 'assign_cf_table', {COLUMNS=>'cf1', CACHE=>10000}` returns **10,000,000** rows
- SeaTunnel job summary shows `Total Read Count` / `Total Write Count` around **2460778** 
- Logs show multiple splits were assigned, e.g. `Assigning 4 splits to subtask: 0`, but the source finishes quickly.

Image

Image

### SeaTunnel Version

2.3.12

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  Hbase {
    zookeeper_quorum = "<zk1:2181,zk2:2181,zk3:2181>"
    table = "assign_cf_table"
    caching = 100000
    batch = 100
    cache_blocks = false

    # kerberos configs (masked)
    hbase.client.kerberos.principal = "<principal>"
    hbase.client.keytab.file = "<keytab>"
    krb5_path = "<krb5.conf>"

    hbase_extra_config = {
      "hbase.security.authentication" = "kerberos"
      "hadoop.security.authentication" = "kerberos"
      "hbase.master.kerberos.principal" = "hbase/_HOST@REALM"
      "hbase.regionserver.kerberos.principal" = "hbase/_HOST@REALM"
      "hbase.rpc.protection" = "authentication"
      "hbase.zookeeper.useSasl" = "false"
    }

    schema = {
      columns = [
        { name = "rowkey" type = string },
        { name = "cf1:id" type = string },
        { name = "cf1:name" type = string }
      ]
    }
  }
}

sink {
  Hbase {
    zookeeper_quorum = "<zk1:2181,zk2:2181,zk3:2181>"
    table = "assign_cf_table3"
    rowkey_column = ["rowkey"]
    family_name { all_columns = "cf1" }

    hbase_extra_config = {
      "hbase.security.authentication" = "kerberos"
      "hadoop.security.authentication" = "kerberos"
      "hbase.master.kerberos.principal" = "hbase/_HOST@REALM"
      "hbase.regionserver.kerberos.principal" = "hbase/_HOST@REALM"
      "hbase.rpc.protection" = "authentication"
      "hbase.zookeeper.useSasl" = "false"
    }
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh -e flink -c /path/to/hbase2hbase.conf
```

### Error Exception

```log
N/A (job finishes successfully; only read/write count mismatch)
```

### Zeta or Flink or Spark Version

flink 1.20.1

### Java or Scala Version

java8

### Screenshots

Image

Image

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yzeng1618**
Fixes https://github.com/apache/seatunnel/issues/10286

### Purpose of this pull request
Fix a correctness issue in `connector-hbase` source: when multiple splits (regions) are assigned, `HbaseSourceReader` could effectively scan only the first split because an exhausted `ResultScanner` was reused for subsequent splits.  
This PR creates a new `ResultScanner` per split, closes it after scanning, and adds a unit test to prevent regression.  
A `@VisibleForTesting` constructor is added only to allow injecting a mocked `HbaseClient` in tests; the production behavior is unchanged.

### Does this PR introduce _any_ user-facing change?
Yes. For HBase source, the read count can now correctly include all assigned splits/regions. Previously, the job could finish successfully but read only a fraction of rows.

### How was this patch tested?
Added unit test: `HbaseSourceReaderTest`

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If necessary, please update `incompatible-changes.md` to describe the incompatibility caused by this PR.
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

**Comment by yzeng1618** [comment]
After-repair Test Results
企业微信截图_17676849392798

File: seatunnel-connectors-v2/connector-hbase/src/main/java/org/apache/seatunnel/connectors/seatunnel/hbase/source/HbaseSourceReader.java [hunk 1]
```diff
@@ -115,14 +129,17 @@ public void pollNext(Collector<SeaTunnelRow> output) throws Exception {
...
+                    currentScanner = scanner;
+                    for (Result result : scanner) {
+                        SeaTunnelRow seaTunnelRow =
+                                hbaseDeserializationFormat.deserialize(
+                                        convertRawRow(result), seaTunnelRowType);
+                        output.collect(seaTunnelRow);
+                    }
+                } finally {
+                    currentScanner = null;
                 }
```
Comment (zhangshenghang) [inline seatunnel-connectors-v2/connector-hbase/src/main/java/org/apache/seatunnel/connectors/seatunnel/hbase/source/HbaseSourceReader.java:132]: After modification, the currentScanner field is no longer necessary and can be deleted.

Comment (yzeng1618) [reply seatunnel-connectors-v2/connector-hbase/src/main/java/org/apache/seatunnel/connectors/seatunnel/hbase/source/HbaseSourceReader.java:132]: Good catch, the currentScanner field is no longer needed, I removed it

**Review by zhangshenghang — APPROVED** [review]

**Review by chl-wxp — APPROVED** [review]
LGTM

**Review by corgy-w — APPROVED** [review]
+1
