### PR TITLE
[Improve][connector-iceberg] fix schema change event

### LINKED ISSUE #9208: [Bug] [Connector] Schema Evolution issue in Apache Iceberg
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I am running a MySQL CDC to Apache Iceberg sink. All operations like insert, delete, and update are reflecting correctly. However, schema evolution is not being handled. There are no errors, but when I delete or alter columns in the source MySQL table, the metadata changes are not reflected in Apache Iceberg in S3.

### SeaTunnel Version

2.3.9

### SeaTunnel Config

```conf
env {
  # You can set engine configuration here
  execution.parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 5000
  read_limit.bytes_per_second=7000000
  read_limit.rows_per_second=400
}

source {
  MySQL-CDC {
    server-id = 5652
    base-url = "REMOVING FOR PRIVACY CONCERN"
    username = "admin"
    password = "REMOVING FOR PRIVACY CONCERN"
    table-names = ["hep_test_db.employee_cdc"]
    startup.mode = "initial"
    schema-changes.enabled = true
  }
}

sink {
  Iceberg {
    catalog_name="hadoop_Iceberg"
    iceberg.catalog.config={
      type = "hadoop"
      fs.s3a.endpoint = "REMOVING FOR PRIVACY CONCERN"
      warehouse = "s3a://data-platform-hfn//Raw/"   
    }
    namespace="hep_test_db"
    table="employee_cdc"
    iceberg.table.write-props={
      write.format.default="parquet"
      write.target-file-size-bytes=536870912
    }
    iceberg.table.primary-keys="id"
    #iceberg.table.partition-keys="state"
    iceberg.table.upsert-mode-enabled=true
    iceberg.table.schema-evolution-enabled=true
  }
}
```

### Running Command

```shell
cd to apache_seatunnel path
./bin/seatunnel.sh --config ./config/Final_Config/final_mysql_cdc -m local
```

### Error Exception

```log
No error but my concern is that when updating records, the table name in the logs appears as `hadoop_iceberg.hep_test_db.employee_cdc`, which is expected. However, when running schema evolution, the table name in the logs is prefixed with `MySQL` or starts with `.database.tablename`, as highlighted in the screenshot.
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

Image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by CosmosNi**
fix Schema Change event 

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — DISMISSED** [review]

**Review by Hisoka-X — COMMENTED** [review]
https://github.com/apache/seatunnel/pull/9217/files#diff-8b3c3719aeadee16e250af04a64a2c363a71deadb44adce0850b1cf3bd993c8aR240
I am a little confused as to why the previous test case passed

File: seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/sink/writer/IcebergRecordWriter.java [hunk 1]
```diff
@@ -92,7 +93,7 @@ record = recordConverter.convert(seaTunnelRow, rowType);
 
     @Override
     public void applySchemaChange(SeaTunnelRowType afterRowType, SchemaChangeEvent event) {
-        log.info("Apply schema change start.");
```
Comment (hailin0) [inline seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/sink/writer/IcebergRecordWriter.java:95]: Please handle AlterTableColumnsEvent

https://github.com/apache/seatunnel/blob/dev/seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/JdbcDialect.java#L460

**Review by hailin0 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]

**Comment by Nethaje** [comment]
The issue still persists. Schema evolution is not happening as expected.

Additionally, after altering the source table, when I try to run the update query, the SeaTunnel job itself fails, which was not the case previously.
