### PR TITLE
[Fix][Connector-V2]  Fix NullPointerException when column or tag contains null value in TDengine sink

### LINKED ISSUE #9104: [Bug] [TDengineSinkWriter] get java.lang.NullPointerException if there are empty value in some column or tag in tdengine source tables
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

 if there are empty value in some column or tag in tdengine source tables, the tdengine sink job got failure and get null exception.
below is exception stack:

java.lang.RuntimeException: java.lang.NullPointerException at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:302) at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:70) at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39) at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27) at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:75) at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:50) at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:51) at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:72) at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:169) at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:77) at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:694) at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1019) at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:43) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750) Caused by: java.lang.NullPointerException at org.apache.seatunnel.connectors.seatunnel.tdengine.sink.TDengineSinkWriter.lambda$convertDataType$0(TDengineSinkWriter.java:136) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546) at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505) at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:511) at org.apache.seatunnel.connectors.seatunnel.tdengine.sink.TDengineSinkWriter.convertDataType(TDengineSinkWriter.java:150) at org.apache.seatunnel.connectors.seatunnel.tdengine.sink.TDengineSinkWriter.write(TDengineSinkWriter.java:94) at org.apache.seatunnel.connectors.seatunnel.tdengine.sink.TDengineSinkWriter.write(TDengineSinkWriter.java:51) at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:268) ... 17 more

### SeaTunnel Version

2.3.9

### SeaTunnel Config

```conf
env {
  # You can set engine configuration here
  parallelism = 1
  job.mode = "BATCH"
  checkpoint.interval = 5000
  read_limit.bytes_per_second=7000000
  read_limit.rows_per_second=500  
}

# source config
source {
  TDengine {
    url : "jdbc:TAOS-RS://tdengine-cluster:6041/"
    username : "root"
    password : "taosdata"
    database : "mmbybuduflmz_devices"
    stable : "iotpro_3b523e67fc7e3dd1"
    lower_bound : "2025-04-01 10:30:56.0"
    upper_bound : "2025-04-02 03:00:00.025"
    plugin_output = "mmbybuduflmz_iotpro_3b523e67fc7e3dd1"
}


}

# sink config
sink {
  TDengine {
    plugin_input = ["mmbybuduflmz_iotpro_3b523e67fc7e3dd1"]
    url : "jdbc:TAOS-RS://10.207.11.1:6041/"
    username : "root"
    password : "taosdata"
    database : "mmbybuduflmz_devices"
    stable : "iotpro_3b523e67fc7e3dd1"
    timezone: UTC
}


}
```

### Running Command

```shell
use rest api to submit a job
```

### Error Exception

```log
java.lang.RuntimeException: java.lang.NullPointerException at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:302) at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:70) at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39) at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27) at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:75) at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:50) at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:51) at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:72) at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:169) at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:77) at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:694) at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1019) at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:43) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750) Caused by: java.lang.NullPointerException at org.apache.seatunnel.connectors.seatunnel.tdengine.sink.TDengineSinkWriter.lambda$convertDataType$0(TDengineSinkWriter.java:136) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546) at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505) at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:511) at org.apache.seatunnel.connectors.seatunnel.tdengine.sink.TDengineSinkWriter.convertDataType(TDengineSinkWriter.java:150) at org.apache.seatunnel.connectors.seatunnel.tdengine.sink.TDengineSinkWriter.write(TDengineSinkWriter.java:94) at org.apache.seatunnel.connectors.seatunnel.tdengine.sink.TDengineSinkWriter.write(TDengineSinkWriter.java:51) at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:268) ... 17 more
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jia17**
### Purpose of this pull request
Fix #9104

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
test in local

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Could you add a unit test for this?

**Comment by jia17** [comment]
@Hisoka-X I have added a unit test for the function I changed. Could you please review this PR?

File: seatunnel-connectors-v2/connector-tdengine/src/test/java/org/apache/seatunnel/connectors/seatunnel/tdengine/sink/TDengineSinkWriterTest.java [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+
+        // Mock DriverManager behavior
+        try (MockedStatic<DriverManager> mockedStatic = mockStatic(DriverManager.class)) {
+            mockedStatic.when(() -> DriverManager.getConnection(anyString())).thenReturn(mockConnection);
+            writer = new TDengineSinkWriter(config, rowType);
+        }
+    }
+
+    @Test
+    void testConvertDataType_withNull() throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-tdengine/src/test/java/org/apache/seatunnel/connectors/seatunnel/tdengine/sink/TDengineSinkWriterTest.java]:
```suggestion
    void testConvertDataTypeWithNull() throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
```

File: seatunnel-connectors-v2/connector-tdengine/src/test/java/org/apache/seatunnel/connectors/seatunnel/tdengine/sink/TDengineSinkWriterTest.java [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+        // Use reflection to access the private method
+        Method method = TDengineSinkWriter.class.getDeclaredMethod("convertDataType", Object[].class);
+        method.setAccessible(true);
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-tdengine/src/test/java/org/apache/seatunnel/connectors/seatunnel/tdengine/sink/TDengineSinkWriterTest.java]: It's better to not use reflect. Let's change `convertDataType` scope to default. Then add a annotation `@VisibleForTesting`.

**Comment by Hisoka-X** [comment]
Also please follow the guide to open github action on your fork repository. Thanks! https://github.com/apache/seatunnel/pull/9158/checks?check_run_id=40516607099

**Comment by jia17** [comment]
I have re-optimized the relevant functions based on your suggestions. Thank you!

**Comment by Hisoka-X** [comment]
Please fix test case. 
image

**Comment by jia17** [comment]
I have fix the test case.

**Review by Hisoka-X — APPROVED** [review]

**Comment by Hisoka-X** [comment]
Thanks @jia17

**Review by hailin0 — APPROVED** [review]
