### PR TITLE
[Fix][Core] Fix the placeholders cannot pass parameters when using complex config

### LINKED ISSUE #9797: Source使用多表读取时，占位符无法传递参数
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Source单表使用query时，sql里可以使用占位符传递参数，但是 table_list = [{},{}]时，query的sql占位符无法传递参数

### SeaTunnel Version

Version：2.3.11

### SeaTunnel Config

```conf
env {
  job.name = "oa2doris"  # 任务名称
  job.mode = "BATCH"                 # 任务模式：批
  job.retry.times = 3                # 任务失败重试次数：3次
  job.retry.interval.seconds = 5     # 任务失败重试间隔：3s
  parallelism = 8                # 任务并行度：3
  # read_limit.bytes_per_second=10240000    # 每个并行度每秒读取的最大bytes：10240000 bytes = 10M
  # read_limit.rows_per_second=10000        # 每个并行度每秒读取的最大行数：400行
}

source {
  Jdbc {
    plugin_output = "source_result"
    url = ${DB_OA_ORACLE_URL}
    driver = ${DB_OA_ORACLE_DRIVER}
    connection_check_timeout_sec = 100
    user = ${DB_OA_ORACLE_USER}
    password = ${DB_OA_ORACLE_PASSWORD}
    table_list = [
      {
        table_path = "myoa.km_review_main",
        query = """
        select fd_id,sysdate as etl_time
        from myoa.km_review_main t
        WHERE GREATEST(fd_last_modified_time, doc_create_time)>=TRUNC(sysdate-${inc_offset_days})
        """
      },
      {
        table_path = "myoa.lbpm_audit_note",
        query = """
        select fd_id,fd_notify_type,sysdate as etl_time from myoa.lbpm_audit_note t WHERE FD_CREATE_TIME>=TRUNC(sysdate-${inc_offset_days})
        """
      }
    ]

    partition_num = 8
  }
}

sink {
  Doris {

  }
}
```

### Running Command

```shell
${SEATUNNEL_HOME}/bin/seatunnel.sh --config go/oa2doris_inc.conf --deploy-mode local -i inc_offset_days=1
```

### Error Exception

```log
无法传递参数，导致oracle sql查询时 ORA-00911: 无效字符
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

java1.8

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by LeonYoah**
Close #9797  where placeholders cannot pass parameters when using multiple tables for reading in JDBC Source

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

File: seatunnel-core/seatunnel-core-starter/src/main/java/org/apache/seatunnel/core/starter/utils/ConfigBuilder.java [hunk 1]
```diff
@@ -266,6 +266,9 @@ private static List<?> processVariablesList(List<?> list) {
                                                             System.getProperty(placeholder),
                                                             null);
                                                 });
+                            } else if (variable instanceof Map) {
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-core-starter/src/main/java/org/apache/seatunnel/core/starter/utils/ConfigBuilder.java:269]: what if `variable` is list?

Comment (LeonYoah) [reply seatunnel-core/seatunnel-core-starter/src/main/java/org/apache/seatunnel/core/starter/utils/ConfigBuilder.java:269]: I indeed never expected a scenario where a list is nested within another list. If such a case exists, I think I could add another `if (variable instanceof List)` to recursively call itself

File: seatunnel-core/seatunnel-core-starter/src/test/resources/config_complex_nested_variables.conf [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+  job.mode = "BATCH"
+  job.name = "seatunnel complex nested variable test job"
+  parallelism = 1
+}
+
+source {
+  FakeSource {
+    plugin_output = "fake"
+    row.num = 10
+    # 测试复杂嵌套结构：List 中包含 Map 和嵌套 List
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-core-starter/src/test/resources/config_complex_nested_variables.conf]: Please remove chinese

Comment (LeonYoah) [reply seatunnel-core/seatunnel-core-starter/src/test/resources/config_complex_nested_variables.conf]: > Please remove chinese

sorry

File: seatunnel-core/seatunnel-core-starter/src/test/java/org/apache/seatunnel/core/starter/utils/ConfigShadeTest.java [hunk 3]
```diff
@@ -283,6 +283,74 @@ public void testVariableReplacementWithReservedPlaceholder() {
                 configCheckException.getMessage());
     }
 
+    @Test
+    public void testTableListPlaceholderReplacement() throws URISyntaxException {
```
Comment (Hisoka-X) [inline seatunnel-core/seatunnel-core-starter/src/test/java/org/apache/seatunnel/core/starter/utils/ConfigShadeTest.java:287]: Could you merge the two case into one? With one config file.

Comment (LeonYoah) [reply seatunnel-core/seatunnel-core-starter/src/test/java/org/apache/seatunnel/core/starter/utils/ConfigShadeTest.java:287]: Yes, I can

**Review by Hisoka-X — APPROVED** [review]
Thanks @LeonYoah

**Review by Carl-Zhou-CN — APPROVED** [review]
+1
