### PR TITLE
[Fix][Connector-V2] Fix http source can not read streaming

### LINKED ISSUE #7698: [Bug] [HTTP SOURCE] STREAMING模式下，http只get了一次数据，从外部post新数据后，并不能流式更新或插入
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

测试seatunnel的同步功能时，使用http作为source，mysql作为sink。不论配不配置poll_interval_millis，都只在任务启动时同步一次数据到mysql里面，然后在任务保持任务运行状态下，post新数据后，并没有更新或插入操作，日志也显示数据条数持续不变，怀疑未进行轮询
微信截图_20240920113345

### SeaTunnel Version

2.3.7

### SeaTunnel Config

```conf
env {
  job.mode = "STREAMING"
  job.name="http_mysql"
  execution.parallelism = 1
  checkpoint.interval = 10000
}

source {
  Http {
    
    url = "http://******.******：*****/api/sync/user"
    method = "GET"
    format = "json"
    
    headers = {
      Cookie: "token=*****"
    }
    
    poll_interval_millis = 5000
    
    result_table_name = "sync_user_1"
    
    json_field = {
      userId = "$.result[*].userId"
      email = "$.result[*].email"
    }
        
    schema = {
      fields {
        userId = "string"
        email = "string"
      }
    }
    
    
  }
}


transform {
  Sql {
    source_table_name = "sync_user_1"
    result_table_name = "sync_user_2"
    query = "SELECT userId AS username, email, 1 AS active FROM sync_user_1 where email != ''"
  }
}


sink {
    jdbc{
        source_table_name = "sync_user_2"
        url = "jdbc:mysql://*****:3306/***"
        driver = "com.mysql.cj.jdbc.Driver"
        user = "root"
        password = "admin"
        query = "INSERT INTO ab_user_bak (username, email, active) VALUES (?,?,?) ON DUPLICATE KEY UPDATE email = VALUES(email), active = VALUES(active)" 
    }
}
```

### Running Command

```shell
no
```

### Error Exception

```log
no
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by CosmosNi**
#7698 

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Any test case?

**Comment by CosmosNi** [comment]
@Hisoka-X PTAL

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-http-e2e/src/test/java/org/apache/seatunnel/e2e/connector/http/HttpIT.java [hunk 1]
```diff
@@ -151,6 +203,73 @@ public void tearDown() {
...
+    @TestTemplate
+    public void testStreamingSourceToAssertSink(TestContainer container)
+            throws InterruptedException, IOException {
+        try {
+            CompletableFuture.supplyAsync(
+                    () -> {
+                        try {
+                            Container.ExecResult execResult1 =
+                                    container.executeJob("/http_streaming_json_to_assert.conf");
+                            Assertions.assertEquals(0, execResult1.getExitCode());
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-http-e2e/src/test/java/org/apache/seatunnel/e2e/connector/http/HttpIT.java]: Streaming job should never return.

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-http-e2e/src/test/resources/http_streaming_json_to_assert.conf [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+transform {
+  Sql {
+    source_table_name = "fake"
+    result_table_name = "fake1"
+    query = "select  CONCAT(c_string, CAST(RAND() AS STRING)) as c_string, c_int from fake"
+  }
+}
+
+sink {
+  Jdbc {
```
Comment (Hisoka-X) [inline seatunnel-e2e/seatunnel-connector-v2-e2e/connector-http-e2e/src/test/resources/http_streaming_json_to_assert.conf]: why not just use `Assert` sink to check data?

**Review by Hisoka-X — COMMENTED** [review]
Thanks @CosmosNi  for update!

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-http-e2e/src/test/resources/http_streaming_json_to_assert.conf (hunk 2 above)
Comment (CosmosNi) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-http-e2e/src/test/resources/http_streaming_json_to_assert.conf]: Because I need to verify streaming data writing, but No way to interrupt Assert .So use  awaitility to interrupt.

File: seatunnel-e2e/seatunnel-connector-v2-e2e/connector-http-e2e/src/test/java/org/apache/seatunnel/e2e/connector/http/HttpIT.java (hunk 1 above)
Comment (CosmosNi) [reply seatunnel-e2e/seatunnel-connector-v2-e2e/connector-http-e2e/src/test/java/org/apache/seatunnel/e2e/connector/http/HttpIT.java]: get

**Comment by Hisoka-X** [comment]
waiting ci passes

File: seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java [hunk 3]
```diff
@@ -180,6 +180,7 @@ public void internalPollNext(Collector<SeaTunnelRow> output) throws Exception {
             } else {
                 if (httpParameter.getPollIntervalMillis() > 0) {
                     Thread.sleep(httpParameter.getPollIntervalMillis());
+                    internalPollNext(output);
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java]: I recheck it and this code might cause a stack overflow.
I think we should override https://github.com/apache/seatunnel/blob/71b8b943903ec8ff3868f104e5dc979fccf34bd5/seatunnel-connectors-v2/connector-common/src/main/java/org/apache/seatunnel/connectors/seatunnel/common/source/AbstractSingleSplitReader.java#L34
in `HttpSourceReader`.
Then let engine to invoke `pollNext` in the loop, so that the job would be streaming.

Comment (CosmosNi) [reply seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java]: get.PTAL

File: seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java [hunk 4]
```diff
@@ -153,6 +153,15 @@ private void updateRequestParam(PageInfo pageInfo) {
                 .put(pageInfo.getPageField(), pageInfo.getPageIndex().toString());
     }
 
+    @Override
+    public void pollNext(Collector<SeaTunnelRow> output) throws Exception {
+        super.pollNext(output);
+        if (Boundedness.UNBOUNDED.equals(context.getBoundedness())) {
+            this.noMoreSplits = false;
+            pollNext(output);
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java]:
```suggestion
Thread.sleep() ???
```

Comment (CosmosNi) [reply seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java]: method:internalPollNext() already Thread.sleep().  suggest move up?

**Review by Hisoka-X — APPROVED** [review]
LGTM. Thanks @CosmosNi

File: seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java [hunk 5]
```diff
@@ -153,6 +153,11 @@ private void updateRequestParam(PageInfo pageInfo) {
                 .put(pageInfo.getPageField(), pageInfo.getPageIndex().toString());
     }
 
+    @Override
+    public void pollNext(Collector<SeaTunnelRow> output) throws Exception {
+        internalPollNext(output);
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java]:
```suggestion
        synchronized (lock) {
            internalPollNext(output);
        }
```

**Review by Hisoka-X — CHANGES_REQUESTED** [review]

File: seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java (hunk 5 above)
Comment (Hisoka-X) [reply seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java]: we should lock it to make sure checkpoint not trigger before split read finished.

**Review by Hisoka-X — DISMISSED** [review]

**Review by Hisoka-X — DISMISSED** [review]

**Comment by TyrantLucifer** [comment]
It seems that some ci tasks have some errors. Could you please check it? @CosmosNi

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]
