### PR TITLE
[Fix][Connectors-Jdbc] Postgres supports streaming and batch reading and writing of the `interval` data type

### LINKED ISSUE #9582: [Bug] [seatunnel-connectors-v2] Not support the pg "interval" data type
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

How to handle the pg INVERTAL data type?

### SeaTunnel Version

2.3.11

### SeaTunnel Config

```conf
env {
  # You can set SeaTunnel environment configuration here
  execution.parallelism = 2
  job.mode = "STREAMING"
  checkpoint.interval = 30000
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

source {
  Postgres-CDC {
    username = "username"
    password = "password"
    database-names = ["database"]
    schema-names = ["schema"]
    table-names = ["database.schema.interval_table"]
    base-url = "jdbc:postgresql://{ip}:5432/postgres?loggerLevel=OFF"
    startup.mode = "INITIAL"
    # debezium.interval.handling.mode = "STRING"
    debezium.interval.handling.mode = "string"
    server-id = "88888888"
  }
}

sink {
  jdbc {
    url = "jdbc:postgresql://{ip}:5432/postgres?stringtype=unspecified"
    driver = "org.postgresql.Driver"
    user = "user"
    password = "password"
    
    generate_sink_sql = true
    database = "database"
    table = "schema.interval_table"
    schema_save_mode = CREATE_SCHEMA_WHEN_NOT_EXIST
    data_save_mode = APPEND_DATA
    support_upsert_by_query_primary_key_exist = true
    primary_keys = ["id"]
  }

}
```

### Running Command

```shell
nohup ./bin/seatunnel.sh --config ./config/test.config 2>&1 &
```

### Error Exception

```log
不对啊，还是报错

2025-07-17 09:20:30,018 INFO  [o.a.s.e.c.j.ClientJobProxy    ] [main] - Job (998035888464199681) end with state FAILED
2025-07-17 09:20:30,018 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTTING_DOWN
2025-07-17 09:20:30,024 INFO  [.c.i.c.ClientConnectionManager] [main] - hz.client_1 [seatunnel] [5.1] Removed connection to endpoint: [localhost]:5801:3425387c-6644-4483-9336-dc8738aa06d9, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:35395->localhost/127.0.0.1:5801}, remoteAddress=[localhost]:5801, lastReadTime=2025-07-17 09:20:30.004, lastWriteTime=2025-07-17 09:20:28.297, closedTime=2025-07-17 09:20:30.022, connected server version=5.1}
2025-07-17 09:20:30,024 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_DISCONNECTED
2025-07-17 09:20:30,027 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTDOWN
2025-07-17 09:20:30,028 INFO  [s.c.s.s.c.ClientExecuteCommand] [main] - Closed SeaTunnel client......
2025-07-17 09:20:30,028 INFO  [s.c.s.s.c.ClientExecuteCommand] [main] - Closed metrics executor service ......
2025-07-17 09:20:30,028 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 

===============================================================================


2025-07-17 09:20:30,028 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Fatal Error, 

2025-07-17 09:20:30,028 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Please submit bug report in https://github.com/apache/seatunnel/issues

2025-07-17 09:20:30,029 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Reason:SeaTunnel job executed failed 

2025-07-17 09:20:30,029 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:228)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:40)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:302)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:70)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:70)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:50)
	at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:51)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:72)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:165)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:77)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:694)
	at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1023)
	at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:43)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableSinkWriter.prepareCommit(MultiTableSinkWriter.java:276)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:201)
	... 17 more
Caused by: java.util.concurrent.ExecutionException: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableSinkWriter.prepareCommit(MultiTableSinkWriter.java:274)
	... 18 more
Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.flush(JdbcOutputFormat.java:142)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSinkWriter.prepareCommit(JdbcSinkWriter.java:143)
	at org.apache.seatunnel.api.sink.SinkWriter.prepareCommit(SinkWriter.java:75)
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableSinkWriter.lambda$prepareCommit$4(MultiTableSinkWriter.java:259)
	... 6 more
Caused by: java.sql.BatchUpdateException: Batch entry 5 INSERT INTO "postgres"."wjx_cdc"."wjx_interval_table" ("id", "value") VALUES (6, '11815200000000') ON CONFLICT ("id") DO UPDATE SET "value"=EXCLUDED."value" was aborted: ERROR: interval field value out of range: "11815200000000"
  Where: unnamed portal parameter $2 = '...'  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:186)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:571)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
	at org.apache.seatunnel.shade.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
	at org.apache.seatunnel.shade.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.FieldNamedPreparedStatement.executeBatch(FieldNamedPreparedStatement.java:540)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.SimpleBatchStatementExecutor.executeBatch(SimpleBatchStatementExecutor.java:54)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.BufferReducedBatchStatementExecutor.executeBatch(BufferReducedBatchStatementExecutor.java:89)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.attemptFlush(JdbcOutputFormat.java:172)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.flush(JdbcOutputFormat.java:136)
	... 9 more
Caused by: org.postgresql.util.PSQLException: ERROR: interval field value out of range: "11815200000000"
  Where: unnamed portal parameter $2 = '...'
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
	... 19 more

	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:220)
	... 2 more
 
2025-07-17 09:20:30,030 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:228)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:40)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:302)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:70)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:70)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:50)
	at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:51)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:72)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:165)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:77)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:694)
	at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1023)
	at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:43)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableSinkWriter.prepareCommit(MultiTableSinkWriter.java:276)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:201)
	... 17 more
Caused by: java.util.concurrent.ExecutionException: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableSinkWriter.prepareCommit(MultiTableSinkWriter.java:274)
	... 18 more
Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.flush(JdbcOutputFormat.java:142)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSinkWriter.prepareCommit(JdbcSinkWriter.java:143)
	at org.apache.seatunnel.api.sink.SinkWriter.prepareCommit(SinkWriter.java:75)
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableSinkWriter.lambda$prepareCommit$4(MultiTableSinkWriter.java:259)
	... 6 more
Caused by: java.sql.BatchUpdateException: Batch entry 5 INSERT INTO "postgres"."schema"."interval_table" ("id", "value") VALUES (6, '11815200000000') ON CONFLICT ("id") DO UPDATE SET "value"=EXCLUDED."value" was aborted: ERROR: interval field value out of range: "11815200000000"
  Where: unnamed portal parameter $2 = '...'  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:186)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:571)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
	at org.apache.seatunnel.shade.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
	at org.apache.seatunnel.shade.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.FieldNamedPreparedStatement.executeBatch(FieldNamedPreparedStatement.java:540)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.SimpleBatchStatementExecutor.executeBatch(SimpleBatchStatementExecutor.java:54)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.BufferReducedBatchStatementExecutor.executeBatch(BufferReducedBatchStatementExecutor.java:89)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.attemptFlush(JdbcOutputFormat.java:172)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.flush(JdbcOutputFormat.java:136)
	... 9 more
Caused by: org.postgresql.util.PSQLException: ERROR: interval field value out of range: "11815200000000"
  Where: unnamed portal parameter $2 = '...'
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
	... 19 more

	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:220)
	... 2 more
2025-07-17 09:20:30,034 INFO  [s.c.s.s.c.ClientExecuteCommand] [SeaTunnel-CompletableFuture-Thread-0] - run shutdown hook because get close signal
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by chestnut-c**
### Purpose of this pull request

 Postgres supports `interval` data type for reading and writing. close https://github.com/apache/seatunnel/issues/9582

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

for batch task:
The interval data type is not supported before modification
企业微信截图_f3441053-f801-4fbf-9209-fea2a7483c3e

After modification, the interval data type can be read and written normally.

Clipboard_Screenshot_1752762697
Clipboard_Screenshot_1752762722
Clipboard_Screenshot_1752762678

for streaming task:
And it is compatible with cdc scenarios. The Postgres interval type is converted to microseconds (long type) in Debezium such as io.debezium.time.MicroDuration , so if it is an number, it is given in microseconds by default.
Clipboard_Screenshot_1753002878
Clipboard_Screenshot_1753003301

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

File: seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/psql/PostgresJdbcRowConverter.java [hunk 1]
```diff
@@ -49,6 +49,7 @@
 import java.util.Locale;
 import java.util.Optional;
 
+import static com.teradata.jdbc.jdbc_4.ifsupport.EscapeConstants.INTERVAL;
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/psql/PostgresJdbcRowConverter.java]: The import class seems not right?

File: seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/psql/PostgresJdbcRowConverter.java [hunk 2]
```diff
@@ -189,6 +190,11 @@ public PreparedStatement toExternal(
                             inetObject.setType(PG_INET);
                             inetObject.setValue(String.valueOf(row.getField(fieldIndex)));
                             statement.setObject(statementIndex, inetObject);
+                        } else if (INTERVAL.equalsIgnoreCase(sourceType)) {
+                            PGobject inetObject = new PGobject();
+                            inetObject.setType(INTERVAL);
+                            inetObject.setValue(String.valueOf(row.getField(fieldIndex)));
+                            statement.setObject(statementIndex, inetObject);
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/psql/PostgresJdbcRowConverter.java]: This part didn't cover by test case. Please update postgres e2e test case.

File: seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/psql/PostgresJdbcRowConverter.java (hunk 1 above)
Comment (chestnut-c) [reply seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/psql/PostgresJdbcRowConverter.java]: yeah, i will fix it

File: seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/psql/PostgresJdbcRowConverter.java (hunk 2 above)
Comment (chestnut-c) [reply seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/psql/PostgresJdbcRowConverter.java]: ok i will cover it

**Comment by WJX20** [comment]
Your way of writing is not quite correct. You directly converted the read-out microsecond numbers into "strings". Debezium's configuration provides an 'interval.handling.mode' attribute. Seatunnel should retain this attribute. When reading the Debezium configuration, the user can choose whether to select 'string' or 'number'.
interval

**Comment by WJX20** [comment]
Moreover, your approach only covers the "day" type. The "interval" type should also include "month" and "year".
The processing method for the interval data type is that the default value is 365.25 days for a year, and 365.25/12 = 30.4375 days for a month.

**Comment by chestnut-c** [comment]
> Debezium

@WJX20 Yes, I am dealing with the default number type when the `'interval.handling.mode` parameter is not used. Since Debezium does not retain the format when reading, in order to make the data calculation more accurate, it is only formatted to the day. Even if it is calculated to the year and month, it is still impossible to guarantee the same format. As long as the interval data is consistent, the format does not have to be the same. other ,If you need the same format, you can try using the `interval.handling.mode` parameter to get the interval data in string format containing year, month, and day.

**Comment by chestnut-c** [comment]
> interval.handling.mode

Clipboard_Screenshot_1753091513

The default type currently processed is `io.debezium.time.MicroDuration`
The default type is to keep the accuracy as much as possible and convert it to day format by default.u can use this way `debezium={"interval.handling.mode":"string"}` to support setting the `interval.handling.mode` parameter to keep the original format `io.debezium.time.Interval` 
Clipboard_Screenshot_1753091623

**Comment by WJX20** [comment]
got off work

**Comment by chestnut-c** [comment]
> got off work

@WJX20 now you can use this configuration parameter `interval.handling.mode`，I think it is supported, the test is OK, the format has been preserved, u can use this way `debezium={"interval.handling.mode":"string"}` to support setting the interval.handling.mode parameter 
Clipboard_Screenshot_1753093008
企业微信截图_49f439c6-e018-4a30-aa67-c9ed7dcfbc85

企业微信截图_bfbccb7a-545c-4a47-aa49-2dc666de5083

**Review by Hisoka-X — DISMISSED** [review]
LGTM. Thanks @chestnut-c

**Comment by WJX20** [comment]
ok，Let me test it. The naming of 'inetObject' is not standard. This is of the 'INET' data type.
intervalObject

**Comment by chestnut-c** [comment]
> ok，Let me test it. The naming of 'inetObject' is not standard. This is of the 'INET' data type. intervalObject

ok i will fix it next time

**Comment by corgy-w** [comment]
@chestnut-c I changed the variable name and it's OK. If I wait a moment and merge it

**Review by corgy-w — APPROVED** [review]
wait ci

**Comment by chestnut-c** [comment]
> @chestnut-c I changed the variable name and it's OK. If I wait a moment and merge it

ok thx @corgy-w

**Review by Hisoka-X — APPROVED** [review]
