### PR TITLE
[Fix][Connector-V2] Fix Doris sink retry backoff and scheduler leak

### LINKED ISSUE #10627: [Bug] [Doris Connector] DorisSinkWriter lacks circuit breaker, causing cascading OOM when Doris BE is unavailable
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues) and found no similar issues.

### SeaTunnel Version

2.3.x / dev branch

### SeaTunnel Component

Doris Connector (Sink)

### What happened

When all Doris BE nodes become unavailable (returning `Connection refused`), the `DorisSinkWriter` enters an unbounded error loop that can eventually contribute to engine-level OOM and cascading cluster failure.

**Root Cause Analysis:**

1. **`DorisSinkWriter.checkDone()` has no circuit breaker or failure counter.** The `scheduledExecutorService.scheduleWithFixedDelay(this::checkDone, ...)` runs every `intervalTime` ms (default 10s). When `dorisStreamLoad.getLoadFailedMsg()` returns non-null (due to Connection refused), it logs `stream load finished unexpectedly` and sets `loadException`, but the scheduler keeps running indefinitely. There is no mechanism to:
   - Count consecutive failures and fail fast after a threshold
   - Apply exponential backoff on repeated failures
   - Stop the scheduler after persistent downstream unavailability

2. **`DorisCommitter.commitTransaction()` retries without backoff.** The retry loop catches `IOException` (including `HttpHostConnectException: Connection refused`) and immediately retries by switching to a different frontend. There is no delay between retries, which amplifies load on the remaining infrastructure.

3. **`DorisCommitter.abortTransaction()` maxRetry is never initialized.** The field `int maxRetry` defaults to `0` and is never set from `DorisSinkConfig.getMaxRetries()`. The loop `while (retry++ <= maxRetry)` effectively runs only once (when retry=0), making abort retry non-functional.

4. **Engine-level job retry amplifies the problem.** When the sink fails, the Zeta engine retries the job, creating new `DorisSinkWriter` instances. Each new writer starts its own `checkDone()` scheduler, which also fails immediately. Over hours of Doris unavailability, this creates a large number of error log entries and failed stream load attempts that contribute to heap pressure.

**In a production incident, this pattern produced:**
- ~77,000 `Connection refused` errors over 6h39m
- ~269,000 `stream load finished unexpectedly` log entries
- Eventually contributed to JVM OOM and Hazelcast node shutdown

### Relevant Code

**DorisSinkWriter.java - checkDone() (no circuit breaker):**
```java
private void checkDone() {
    String errorMsg;
    log.debug("start timer checker, interval {} ms", intervalTime);
    if ((errorMsg = dorisStreamLoad.getLoadFailedMsg()) != null) {
        log.error("stream load finished unexpectedly: {}", errorMsg);
        loadException =
                new DorisConnectorException(
                        DorisConnectorErrorCode.STREAM_LOAD_FAILED, errorMsg);
    }
    // No failure counting, no backoff, no circuit breaker
    // Scheduler continues running indefinitely even after persistent failures
}
```

**DorisCommitter.java - commitTransaction() (no backoff):**
```java
while (retry++ <= dorisSinkConfig.getMaxRetries()) {
    // ...
    try {
        response = httpClient.execute(putBuilder.build());
    } catch (IOException e) {
        log.error("commit transaction failed: ", e);
        hostPort = dorisSinkConfig.getFrontends();
        continue; // Immediate retry, no backoff
    }
    // ...
}
```

**DorisCommitter.java - abortTransaction() (maxRetry bug):**
```java
int maxRetry; // Never initialized from config, defaults to 0

private void abortTransaction(DorisCommitInfo committable) throws IOException {
    int retry = 0;
    while (retry++ <= maxRetry) { // maxRetry=0, so loop body runs once
        // ...
    }
}
```

### Key Logs (sanitized)

**Connection refused errors flooding the log:**
```
2026-03-17 00:00:01,346 ERROR [o.a.s.c.d.s.w.DorisSinkWriter] [stream-load-check] - stream load finished unexpectedly: org.apache.http.conn.HttpHostConnectException: Connect to 10.x.x.x:8040 [/10.x.x.x] failed: Connection refused (Connection refused)
2026-03-17 00:00:01,346 ERROR [o.a.s.c.d.s.w.DorisSinkWriter] [stream-load-check] - stream load finished unexpectedly: org.apache.http.conn.HttpHostConnectException: Connect to 10.x.x.x:8040 [/10.x.x.x] failed: Connection refused (Connection refused)
... (repeated ~77,000 times over 6h39m across 3 BE nodes)
```

**Eventual OOM causing checkpoint failure:**
```
2026-03-17 05:31:14,445 ERROR [.s.e.s.c.CheckpointCoordinator] - store checkpoint states failed.
java.lang.OutOfMemoryError: Java heap space
```

**Final Hazelcast node shutdown due to OOM:**
```
2026-03-17 06:39:56,618 INFO  [c.h.i.i.Node] - [10.x.x.x]:5801 [seatunnel] [5.1] Hazelcast Shutdown is completed in 54061 ms.
2026-03-17 06:39:56,618 ERROR [c.h.s.i.o.i.InvocationMonitor] - [10.x.x.x]:5801 [seatunnel] [5.1] Java heap space
java.lang.OutOfMemoryError: Java heap space
```

### Suggested Improvements

1. **Add circuit breaker to DorisSinkWriter**: Track consecutive failure count in `checkDone()`. After N consecutive failures (configurable, e.g., `doris.sink.max-consecutive-failures=100`), stop the scheduler and fail the task immediately instead of continuing to retry indefinitely.

2. **Add exponential backoff to DorisCommitter retry**: Add `Thread.sleep()` with exponential backoff between retries in `commitTransaction()` (e.g., 1s, 2s, 4s...).

3. **Fix maxRetry initialization in abortTransaction()**: Initialize `maxRetry` from `dorisSinkConfig.getMaxRetries()` in the constructor, or use `dorisSinkConfig.getMaxRetries()` directly in the loop condition.

4. **Add rate limiting to error logging**: When the same error repeats thousands of times, consider logging at reduced frequency (e.g., log every Nth occurrence or use a time-based throttle) to reduce log volume and I/O pressure.

### How to reproduce

1. Set up a SeaTunnel Zeta cluster with a streaming job writing to Doris
2. Stop all Doris BE nodes (kill the BE processes or block port 8040 with iptables)
3. Observe that `DorisSinkWriter` continuously logs `stream load finished unexpectedly` errors at `intervalTime` frequency
4. With engine job retry enabled, observe that each retry creates new writer instances that also fail immediately
5. Over extended periods (hours), this contributes to heap pressure and can lead to OOM

### Anything else?

This issue is specifically about the Doris connector's lack of resilience mechanisms. The OOM in the production incident had multiple contributing factors (including control-plane request accumulation), but the Doris connector's unbounded retry behavior was a significant amplifier.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by JAEKWANG97**
### Purpose of this pull request

Fixes three resilience issues in the Doris sink connector that cause cascading OOM when Doris BE nodes are unavailable. Closes #10627.

1. **`DorisSinkWriter.checkDone()`**: Stop the scheduled executor after a stream load failure is detected. Previously the scheduler ran indefinitely, flooding logs with repeated errors.

2. **`DorisCommitter.commitTransaction()`**: Add exponential backoff between retries (1s, 2s, 4s… up to 16s) to reduce load on remaining infrastructure during BE unavailability.

3. **`DorisCommitter.abortTransaction()`**: Fix `maxRetry` field never initialized from config, causing abort retry to run only once (defaulted to 0).

### Does this PR introduce _any_ user-facing change?

No. Internal retry and scheduling behavior is improved. No config options or public APIs changed.

### How was this patch tested?

Manual code-path review only. No dedicated tests were added for this change.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If necessary, please update `incompatible-changes.md` to describe the incompatibility caused by this PR.
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

**Review by davidzollo — DISMISSED** [review]
@DanielLeens Can you review this PR?

File: seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/sink/committer/DorisCommitter.java [hunk 1]
```diff
@@ -132,13 +133,22 @@ private void commitTransaction(DorisCommitInfo committable)
         }
     }
 
+    private void sleepBeforeRetry(int retry) throws IOException {
+        try {
+            Thread.sleep(1000L * (1L << Math.min(retry - 1, 4)));
```
Comment (yzeng1618) [inline seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/sink/committer/DorisCommitter.java]: if retry <= 0 ever slips in, 1L << -1 becomes Long.MIN_VALUE and Thread.sleep throws. 
```suggestion
            int shift = Math.min(Math.max(retry - 1, 0), 4);
            Thread.sleep(1000L * (1L << shift));
```

**Review by yzeng1618 — COMMENTED** [review]
I’d suggest adding a small set of unit tests to lock in the new retry behavior:

​sleepBeforeRetry​: verify retry = 1 sleeps ~1s, retry = 5 caps at ~16s, and InterruptedException restores the interrupt flag and rethrows as IOException.
​commitTransaction​: mock the HttpClient to throw IOException N times before succeeding, and assert total elapsed time is at least the cumulative backoff.
​abortTransaction​: mock the FE to always fail and assert the number of requests equals maxRetries + 1.

**Comment by JAEKWANG97** [comment]
> I’d suggest adding a small set of unit tests to lock in the new retry behavior:

I think checking the real backoff timing also makes sense, but I’m not sure how stable that would be in CI. It might be a bit flaky.

Would it be okay to use simpler tests for this, like verifying the retry path and retry count instead?

File: seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/sink/committer/DorisCommitter.java (hunk 1 above)
Comment (JAEKWANG97) [reply seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/sink/committer/DorisCommitter.java]: Thanks! I applied this in a new commit.

**Comment by JAEKWANG97** [comment]
While working on this issue, I also found two more points in the same retry path:

1. response cleanup is not handled in commitTransaction and abortTransaction
2. sleepBeforeRetry is still called even after the last failed attempt

Since this is my first PR here, I tried to keep the scope small and focused on the retry/backoff behavior from the issue, so I did not include those changes in this PR.

**Review by DanielLeens — CHANGES_REQUESTED** [review]
Hi @JAEKWANG97, thank you for the careful follow-up here, and welcome to the SeaTunnel community. I pulled the PR locally and reviewed the Doris sink retry path end to end.

Local branch: `seatunnel-review-10772`  
Head reviewed: `9ed6a7a0f`

Runtime path checked:

```text
Doris sink writes records
  -> DorisSinkWriter.write()
      -> DorisStreamLoad.writeRecord()
  -> scheduled checker
      -> DorisSinkWriter.checkDone()
          -> getLoadFailedMsg() is not null
          -> set loadException
          -> shutdownNow() the scheduler
          -> the next write() fails through checkLoadException()

checkpoint / abort path
  -> DorisSinkWriter.prepareCommit()
      -> flush()
      -> returns DorisCommitInfo(txnId)
  -> DorisCommitter.commit()
      -> commitTransaction()
          -> httpClient.execute()
          -> retry with backoff on IOException or non-200 response
  -> DorisCommitter.abort()
      -> abortTransaction()
          -> retry abort with the same backoff path
```

The normal Doris 2PC commit/abort path and the streaming failure-check path both hit this PR.

## Findings

Issue 1: failed HTTP responses are not closed before retrying

- Location: `seatunnel-connectors-v2/connector-doris/src/main/java/org/apache/seatunnel/connectors/doris/sink/committer/DorisCommitter.java:100`
- Why it matters: when Doris returns a non-200 response or an abort response without an entity, the code moves to the next retry without consuming/closing the `CloseableHttpResponse`. Since this PR makes `abortTransaction()` retry instead of failing immediately, that resource leak can now be amplified in the abort path.
- Suggested fix: close/consume each failed response before retrying, and make sure the success path also closes the response after reading the entity.
- Severity: medium

Issue 2: the code sleeps even after the last failed attempt

- Location: `DorisCommitter.java:97`
- Why it matters: `while (retry++ <= maxRetries)` increments `retry` before the sleep call. On the final failed attempt there is no next retry, but the code still waits. This slows checkpoint commit/abort failure convergence when Doris is unavailable.
- Suggested fix: only sleep when another attempt remains, or rewrite the loop as an explicit `for (int attempt = 0; attempt <= maxRetries; attempt++)`.
- Severity: low

Issue 3: the new retry behavior has no small unit test yet

- Location: `DorisCommitter.java:136`
- Why it matters: this PR changes retry timing and interrupt handling. A small test can lock in retry count, interrupt flag restoration, and the "do not sleep after final failure" behavior.
- Suggested fix: it is fine to avoid flaky wall-clock assertions. Mocking `CloseableHttpClient` and using an injectable/package-private sleeper would keep the test stable.
- Severity: low

Local checks performed:

- `git fetch upstream pull/10772/head:seatunnel-review-10772 --force`: passed.
- `git diff --stat upstream/dev...seatunnel-review-10772`: 2 files, `+41/-10`.
- Code inspection covered `DorisCommitter` and `DorisSinkWriter`.
- GitHub checks observed: `Build`, `labeler`, and `Notify test workflow` are passing.
- Local build/tests were not run in this review.

## Merge conclusion

### Conclusion: can merge after fixes

Blocking items:

1. Issue 1: please close/consume failed HTTP responses before retrying. This is the one resource-safety point I think should be fixed in this PR.

Non-blocking suggestions:

- Issue 2: skip the final unnecessary sleep.
- Issue 3: add a small non-flaky retry behavior test.

Overall evaluation:

This is a good first contribution, and the direction is absolutely reasonable. The scheduler shutdown part is helpful, and the retry backoff is the right idea. Once the failed-response cleanup is handled, the patch will be much safer for real Doris failure scenarios. Thanks again for keeping the scope thoughtful.

**Comment by JAEKWANG97** [comment]
Thanks for review! I resolved the merge conflicts and rebased this branch onto the latest `dev`.

Since there were already recent Doris changes in the committer/writer paths, I kept the current upstream flow there and only reapplied the remaining fixes from this PR:
- close failed/success HTTP responses before retry/return in both commit and abort paths
- add bounded backoff between retries
- skip the final unnecessary sleep after the last failed attempt
- stop the writer-side scheduler once load failure is detected
- add small non-flaky tests for retry sleep behavior and response cleanup

**Comment by DanielLeens** [comment]
Hi @JAEKWANG97, thank you for the careful update, and again welcome to the SeaTunnel community. I rechecked the latest head locally after your rebase and follow-up changes.

# What This PR Fixes
- User pain point: when Doris commit/abort or stream-load checking fails, the old retry path could leave failed HTTP responses open, sleep even after the final failed attempt, and keep the writer-side scheduler running after a load failure had already been detected.
- Fix approach: the PR now closes HTTP responses with try-with-resources, adds bounded retry backoff that skips the final unnecessary sleep, stops the scheduler after setting `loadException`, and adds small non-flaky unit tests for response cleanup and retry sleep behavior.
- One-line summary: Doris sink failure handling is now cleaner, safer, and easier to test.

# Runtime Path Checked

```text
Doris sink write path
  -> DorisSinkWriter.write()
      -> DorisStreamLoad.writeRecord()
  -> scheduled checker
      -> DorisSinkWriter.checkDone()
          -> getLoadFailedMsg() returns an error
          -> set loadException
          -> shutdownNow() the scheduler
          -> the next write() fails through checkLoadException()

Checkpoint / 2PC commit path
  -> DorisSinkWriter.prepareCommit()
      -> flush()
      -> returns DorisCommitInfo(txnId)
  -> DorisCommitter.commit()
      -> commitTransaction()
          -> httpClient.execute()
          -> IOException or redirect follow-up failure: record error, sleep only if another retry remains
          -> non-200 response: close response, sleep only if another retry remains
          -> 200 response: handle success, then close response

Abort path
  -> DorisCommitter.abort()
      -> abortTransaction()
          -> same retry, backoff, and response cleanup behavior as commit
```

# Key Findings
- The normal Doris 2PC commit/abort path hits this PR.
- The streaming load failure-check path also hits the scheduler shutdown change.
- The previous response-cleanup concern is fixed: failed and successful responses are now closed.
- The previous final-sleep concern is fixed: `sleepBeforeNextAttempt(...)` only sleeps when another attempt remains.
- The added tests cover commit/abort backoff and response cleanup without relying on wall-clock timing.

# Findings

Issue 1: the current GitHub Build check is cancelled
- Location: GitHub check `Build` / run `72369836026`
- Why it matters: the current head still needs a valid CI signal before merge. The code-side concerns I had are addressed, but the PR is still blocked while Build is CANCELLED.
- Suggested fix: please rerun the PR checks; if anything fails, start with the Doris committer/writer unit tests and connector build logs.
- Severity: Medium

# Compatibility / Side Effects
Compatibility: fully compatible.

No API, option, default value, protocol, serialization format, or historical upgrade behavior is changed. The success path remains the same. Failure paths now release HTTP responses more reliably and avoid an unnecessary final wait.

# Merge Decision
### Conclusion: can merge after fixes

1. Blocking items
- Issue 1: rerun the current head CI and make sure the checks are green.

2. Recommended non-blocking improvements
- None from my side. For a first contribution, this is nicely focused and the important safety points are covered now.

Overall, the code changes look good to me. Once the cancelled Build check is rerun successfully, I think this PR is ready to merge.

**Comment by JAEKWANG97** [comment]
Thanks for the review. : )

I followed up on the CI failure by changing the DorisCommitter resource handling to a Java 8-compatible try-with-resources form. The latest Build rerun is now green.

**Comment by DanielLeens** [comment]
# What This PR Fixes
- User pain point: The Doris sink could sleep unnecessarily on the last retry and keep its background checker alive after load failure, which made the failure path noisy and leaky.
- Fix approach: `DorisCommitter` now skips the final useless sleep and closes both failed and successful responses; `DorisSinkWriter` shuts the checker down immediately after load failure.
- One-line summary: This PR tightens Doris sink retry behavior and resource cleanup.

# 1. Code Review

## 1.1 Core Logic Analysis
- Exact change: The key changes are in `DorisCommitter.java:92-160`, `DorisSinkWriter.java:268-282`, and `DorisCommitterTest.java:183-257`.
- Before / After snippets:
```java
// retry path slept even on the last attempt
// failed responses were not always closed
```
```java
sleepBeforeNextAttempt(attempt);
try (CloseableHttpResponse closeableResponse = response) { ... }
// scheduler shutdown on load failure
```
- Key findings:
- The commit/abort retry path now skips the final meaningless sleep.
- HTTP responses are closed in both retry-failure and success cases.
- `DorisSinkWriter.checkDone()` now shuts the scheduler down as soon as stream load has failed.
- Correctness analysis: These changes all hit real runtime paths: commit/abort are part of the 2PC main flow, and `checkDone()` is the background load-health checker. The earlier Java 8 resource-handling concern is also addressed on the current head.
- Runtime path reviewed:
```text
Doris 2PC
  -> DorisCommitter.commitTransaction() / abortTransaction() [DorisCommitter.java:92-160,163-170+]
  -> retry over FE hosts
  -> close every HTTP response under try-with-resources

Background load checker
  -> DorisSinkWriter.checkDone() [DorisSinkWriter.java:268-282]
  -> detect loadFailedMsg
  -> set loadException and shutdown scheduler
```

## 1.2 Compatibility Impact
- Fully compatible. No API, config, or protocol change is introduced.

## 1.3 Performance / Side Effects
- Removing the final useless sleep actually improves failure-path latency; the rest of the changes are positive cleanup.

## 1.4 Error Handling and Logs
No formal issue found. The remaining attention point is only CI / merge gating.

# 2. Code Quality Assessment

## 2.1 Code Style
- The failure path is cleaner and more consistent than before.

## 2.2 Test Coverage
- The new tests cover “skip final sleep” and response closing, which are the right regression points.

## 2.3 Documentation
- No user-facing documentation update is needed.

# 3. Architecture

## 3.1 Elegance of the Solution
- This is a precise fix.

## 3.2 Maintainability
- Retry and resource-release behavior is easier to follow now.

## 3.3 Extensibility
- Other HTTP-based committers can reuse the same “no final sleep + always close responses” pattern.

## 3.4 Backward Compatibility
- Backward compatible; it only fixes error-path behavior.

# 4. Issue Summary
| No. | Issue | Location | Severity |
|---|---|---|---|
| - | No formal issue found | - | - |

# 5. Merge Conclusion
### Conclusion: can merge

1. Blocking items
   - None.

2. Recommended non-blocking items
   - None.

- Overall assessment: The current head looks ready from both code review and CI signals. I do not see a remaining blocker.
- Better alternative: The current implementation is already the most direct correct fix.
- Local branch info: `seatunnel-review-10772` at HEAD `5775405ecab22fd0e7ee43ab1f2921b1c3b4c690`, compared with `upstream/dev`
- Local source-level analysis: I rechecked the full diff and the commit / abort / checkDone call chain locally at source level. I did not run Maven in this batch.
- CI status: `Build`, `Notify test workflow`, and `labeler` are all green.

**Review by davidzollo — APPROVED** [review]
+1
Good job. Thanks for your contribution.
I'm looking forward to your more paritcipation^_^

**Comment by DanielLeens** [comment]
I re-reviewed the latest head locally and the current version looks good to me.

This PR fixes a real sink failure-path problem, not just cosmetic logging. The normal runtime chain is:
```text
DorisSinkWriter.checkDone() [DorisSinkWriter.java:268-282]
  -> stream load failure detected
      -> loadException is set
      -> scheduler is shut down immediately, so the writer stops spamming repeated errors

DorisCommitter.commitTransaction(...) [DorisCommitter.java:92-160]
  -> FE/BE commit request
  -> response is closed with try-with-resources
  -> retry backoff only happens when another retry will actually occur

DorisCommitter.abortTransaction(...) [163-238]
  -> same cleanup and retry discipline for abort
```

I checked the updated retry/cleanup logic and the related tests. The fix is targeted, compatibility is preserved, and the resource behavior is clearly better in failure scenarios. The current Build is green on this head as well.

I did not find any blocking issue in the latest version. From my side, this is ready to merge.

**Review by yzeng1618 — APPROVED** [review]
LGTM +1

**Comment by DanielLeens** [comment]
Hi @JAEKWANG97, thanks for the careful follow-up. I pulled the latest head locally again and rechecked the full diff against `upstream/dev`.

What this PR solves
- User pain: Doris sink could retry too aggressively on commit/abort failures, leak HTTP responses on failed attempts, and keep the writer-side checker logging after load failure was already known.
- Fix approach: `DorisCommitter` now closes each HTTP response with `try-with-resources`, uses bounded backoff that skips the final unnecessary sleep, and `DorisSinkWriter.checkDone()` stops the scheduler after setting `loadException`.
- One-line summary: this is a focused stability fix for the real Doris failure path, and the current head looks merge-ready from my side.

Runtime path I checked
```text
DorisSinkWriter.write()
  -> DorisStreamLoad.writeRecord()
  -> scheduled checker
      -> checkDone()
          -> getLoadFailedMsg() != null
          -> set loadException
          -> stop scheduler

Checkpoint / 2PC path
  -> prepareCommit()
      -> flush()
      -> DorisCommitInfo
  -> DorisCommitter.commit()/abort()
      -> HttpUtil.executeWithRedirectTracking(...)
      -> try-with-resources closes response
      -> sleepBeforeNextAttempt(attempt)
```

Merge conclusion
### Conclusion: can merge

1. Blocking items
- None from my current code review.

2. Suggested follow-ups
- Please keep the final merge gated on green GitHub checks, but the current `Build` is already green on this head.

I also checked the new activity after my previous review: there was no new code change, only reviewer activity. With the current head and current CI status, I do not see a remaining blocker from Daniel’s side.

**Comment by JAEKWANG97** [comment]
Thanks everyone for the reviews and approvals!

**Comment by DanielLeens** [comment]
Hi @JAEKWANG97, I rechecked the current head again after the latest PR activity.

There is no new code change after Daniel’s latest review on this head. The only newer activity is your follow-up thank-you comment, and the current `Build` is green.

The runtime conclusion is unchanged:
```text
DorisSinkWriter.checkDone()
  -> load failure detected
  -> set loadException
  -> shutdown scheduler immediately

DorisCommitter.commit()/abort()
  -> retry over FE hosts
  -> close every HTTP response
  -> sleep only when another retry remains
```

### Conclusion: can merge

1. Blocking items
- None from my current follow-up review.

2. Suggested follow-up
- None from my side.

From Daniel’s side, the current head still looks ready to merge.

**Review by corgy-w — APPROVED** [review]
+1
