### PR TITLE
[Connector-V2] [Kafka] Fix Kafka Streaming problem

### LINKED ISSUE #2583: [Bug] [kafka-source] Multiple KafkaSource failed with Only one StreamingContext may be started in this JVM.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I add seatunnel as maven dependencies to start my service, when I create two kafka-source task, I found only one task works, another one failed.

### SeaTunnel Version

V1.2.2

### SeaTunnel Config

```conf
env {
  spark.app.name = "SeaTunnel"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  spark.master = "local"
  spark.serializer = "org.apache.spark.serializer.KryoSerializer"
  spark.yarn.archive = "hdfs:///app-logs/spark-2.4.4-1.0.2.zip"
  spark.proxy-user = "spark"
  spark.driver.allowMultipleContexts = true
}

source {
  KafkaStream {
    topics = "test1"
    consumer.bootstrap.servers = "xxx.xxx.xxx.xxx:9092"
    consumer.group.id = "consumer0001"
    result_table_name = "test"
  }
}

transform {
  Sql {
    sql = "SELECT * FROM test"
  }
}

sink {
   Console {
   }
}
```

### Running Command

```shell
import org.apache.seatunnel.common.config.DeployMode;
import org.apache.seatunnel.core.base.Seatunnel;
import org.apache.seatunnel.core.base.command.Command;
import org.apache.seatunnel.core.spark.args.SparkCommandArgs;
import org.apache.seatunnel.core.spark.command.SparkCommandBuilder;

import java.io.FileNotFoundException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class SparkEngineExample {

    static class SparkTask implements Runnable {

        private String confFile;

        public SparkTask(String confFile) {
            this.confFile = confFile;
        }

        public String getTestConfigFile(String configFile) throws URISyntaxException, FileNotFoundException {
            URL resource = SparkEngineExample.class.getResource(configFile);
            if (resource == null) {
                throw new FileNotFoundException("Could not find config file: " + configFile);
            }
            return Paths.get(resource.toURI()).toString();
        }

        @Override
        public void run() {
            String configFile = null;
            try {
                configFile = getTestConfigFile(this.confFile);
            } catch (URISyntaxException e) {
                e.printStackTrace();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
            SparkCommandArgs sparkArgs = new SparkCommandArgs();
            sparkArgs.setConfigFile(configFile);
            sparkArgs.setCheckConfig(false);
            sparkArgs.setVariables(null);
            sparkArgs.setDeployMode(DeployMode.CLIENT);
            Command<SparkCommandArgs> sparkCommand = new SparkCommandBuilder().buildCommand(sparkArgs);
            Seatunnel.run(sparkCommand);
        }
    }

    public static void main(String[] args) {
        ExecutorService service = Executors.newCachedThreadPool();
        service.execute(new SparkTask("/examples/test1.conf"));
        service.execute(new SparkTask("/examples/test2.conf"));
        service.shutdown();
    }
}
```

### Error Exception

```log
22/08/31 18:53:41 ERROR Seatunnel: 

===============================================================================


22/08/31 18:53:41 ERROR Seatunnel: Fatal Error, 

22/08/31 18:53:41 ERROR Seatunnel: Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

22/08/31 18:53:41 ERROR Seatunnel: Reason:Execute Spark task error 

22/08/31 18:53:41 ERROR Seatunnel: Exception StackTrace:java.lang.RuntimeException: Execute Spark task error
	at org.apache.seatunnel.core.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:79)
	at org.apache.seatunnel.core.base.Seatunnel.run(Seatunnel.java:39)
	at com.somnus.SparkEngineExample$SparkTask.run(SparkEngineExample.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Only one StreamingContext may be started in this JVM. Currently running StreamingContext was started atorg.apache.spark.streaming.StreamingContext.start(StreamingContext.scala:569)
org.apache.seatunnel.spark.stream.SparkStreamingExecution.start(SparkStreamingExecution.scala:68)
org.apache.seatunnel.core.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:76)
org.apache.seatunnel.core.base.Seatunnel.run(Seatunnel.java:39)
com.somnus.SparkEngineExample$SparkTask.run(SparkEngineExample.java:67)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
	at org.apache.spark.streaming.StreamingContext$.org$apache$spark$streaming$StreamingContext$$assertNoOtherContextIsActive(StreamingContext.scala:738)
	at org.apache.spark.streaming.StreamingContext.start(StreamingContext.scala:571)
	at org.apache.seatunnel.spark.stream.SparkStreamingExecution.start(SparkStreamingExecution.scala:68)
	at org.apache.seatunnel.core.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:76)
	... 5 more
 
22/08/31 18:53:41 INFO ContextHandler: Started o.s.j.s.ServletContextHandler@16c74877{/streaming,null,AVAILABLE,@Spark}
```

### Flink or Spark Version

Spark2.4.4

### Java or Scala Version

Scala2.11.12

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #2754: [Bug] [Connector-v2-kafka] Failed to running in streaming mode
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

issues:
- java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
- Duplicate consume message when commit_on_checkpoint enable

### SeaTunnel Version

dev branch

### SeaTunnel Config

```conf
env {
  execution.parallelism = 2
  job.mode = "STREAMING"
}
```

### Running Command

```shell
run as example module
```

### Error Exception

```log
22/09/15 17:49:04 WARN Task: Source: SeaTunnel KafkaSource -> Sink Writer: Unnamed (1/1)#0 (2e1f52d0a07ae1993e29025337346e81) switched from RUNNING to FAILED with failure cause: java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2490)
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquireAndEnsureOpen(KafkaConsumer.java:2474)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1496)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1400)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1357)
	at org.apache.seatunnel.connectors.seatunnel.kafka.source.KafkaSourceReader.notifyCheckpointComplete(KafkaSourceReader.java:144)
	at org.apache.seatunnel.translation.source.ParallelSource.notifyCheckpointComplete(ParallelSource.java:202)
	at org.apache.seatunnel.translation.flink.source.BaseSeaTunnelSourceFunction.notifyCheckpointComplete(BaseSeaTunnelSourceFunction.java:116)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.notifyCheckpointComplete(AbstractUdfStreamOperator.java:130)
	at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.notifyCheckpointComplete(StreamOperatorWrapper.java:99)
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.notifyCheckpointComplete(SubtaskCheckpointCoordinatorImpl.java:334)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.notifyCheckpointComplete(StreamTask.java:1171)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$notifyCheckpointCompleteAsync$10(StreamTask.java:1136)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$notifyCheckpointOperation$12(StreamTask.java:1159)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:93)
	at org.apache.flink.streaming.runtime.tasks.mailbox.Mail.run(Mail.java:90)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMailsWhenDefaultActionUnavailable(MailboxProcessor.java:344)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMail(MailboxProcessor.java:330)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:202)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:684)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.executeInvoke(StreamTask.java:639)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:650)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:623)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.RuntimeException: java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
		at org.apache.seatunnel.translation.flink.source.BaseSeaTunnelSourceFunction.cancel(BaseSeaTunnelSourceFunction.java:110)
		at org.apache.flink.streaming.api.operators.StreamSource.cancel(StreamSource.java:154)
		at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:210)
		at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:191)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:656)
		... 4 more
	Caused by: java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
		at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2490)
		at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2373)
		at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2351)
		at org.apache.seatunnel.connectors.seatunnel.kafka.source.KafkaSourceReader.close(KafkaSourceReader.java:85)
		at org.apache.seatunnel.translation.source.ParallelSource.close(ParallelSource.java:149)
		at org.apache.seatunnel.translation.flink.source.BaseSeaTunnelSourceFunction.cancel(BaseSeaTunnelSourceFunction.java:107)
		... 8 more
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
@hailin0 @ashulin Hi, PTAL

File: seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceReader.java [hunk 1]
```diff
@@ -140,32 +170,17 @@ public void handleNoMoreSplits() {
...
-        return new KafkaConsumer<>(props);
-    }
-
-    private Set<TopicPartition> convertToPartition(Collection<KafkaSourceSplit> sourceSplits) {
-        return sourceSplits.stream().map(KafkaSourceSplit::getTopicPartition).collect(Collectors.toSet());
+        consumerThreadMap.forEach((split, consumerThread) -> {
+            try {
+                consumerThread.getTasks().put(consumer -> {
+                    if (this.metadata.isCommitOnCheckpoint()) {
+                        consumer.commitSync();
```
Comment (ashulin) [inline seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceReader.java]: This is wrong, it will also commit the offset between `snapshot -> notifyCheckpointComplete` to kafka broker

File: seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceReader.java [hunk 2]
```diff
@@ -140,32 +172,19 @@ public void handleNoMoreSplits() {
...
-    }
-
-    private Set<TopicPartition> convertToPartition(Collection<KafkaSourceSplit> sourceSplits) {
-        return sourceSplits.stream().map(KafkaSourceSplit::getTopicPartition).collect(Collectors.toSet());
+        consumerThreadMap.forEach((split, consumerThread) -> {
+            try {
+                consumerThread.getTasks().put(consumer -> {
+                    if (this.metadata.isCommitOnCheckpoint()) {
+                        Map<TopicPartition, OffsetAndMetadata> offsets = new HashMap<>();
+                        offsets.put(split.getTopicPartition(), new OffsetAndMetadata(split.getEndOffset()));
```
Comment (ashulin) [inline seatunnel-connectors-v2/connector-kafka/src/main/java/org/apache/seatunnel/connectors/seatunnel/kafka/source/KafkaSourceReader.java]: This has the same problem, because `pollNext#135` keeps calling `split#setEndOffset`;
You can backup the offset info when the checkpoint is triggered in the `#snapshotState`.

**Review by ashulin — COMMENTED** [review]
LGTM

**Review by ashulin — APPROVED** [review]

**Review by EricJoy2048 — APPROVED** [review]
+1
