### PR TITLE
[Fix][Connector-HTTP] Add default content-type when user not set

### LINKED ISSUE #9476: [Bug] [seatunnel-connector-http-base] should check whether it already exists Content-Type in header,  to avoid duplicate additions
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

In some scenarios, I need to set the Content-Type header to "application/json;utf-8". Therefore, I manually added it in the configuration file's headers. Consequently, the code logic should first check whether it already exists to avoid duplicate additions. 

bug code snippet:
we should  check if  already exists  HTTP.CONTENT_TYPE to avoid duplicate additions.
```
....
 } else {
            // we should  check if  already exists  HTTP.CONTENT_TYPE to avoid duplicate additions.
            request.addHeader(HTTP.CONTENT_TYPE, APPLICATION_JSON);
            StringEntity entity =
                    new StringEntity(JsonUtils.toJsonString(body), ContentType.APPLICATION_JSON);
            entity.setContentEncoding(new BasicHeader(HTTP.CONTENT_TYPE, APPLICATION_JSON));
            request.setEntity(entity);
        }
.....
```

complete code snippet：
```
  private void addBody(HttpEntityEnclosingRequestBase request, Map<String, Object> body)
            throws UnsupportedEncodingException {
        if (MapUtils.isEmpty(body)) {
            body = new HashMap<>();
        }
        boolean isFormSubmit =
                request.getHeaders(HTTP.CONTENT_TYPE) != null
                        && request.getHeaders(HTTP.CONTENT_TYPE).length > 0
                        && APPLICATION_FORM.equalsIgnoreCase(
                                request.getHeaders(HTTP.CONTENT_TYPE)[0].getValue());
        if (isFormSubmit) {
            if (MapUtils.isNotEmpty(body)) {
                List<NameValuePair> parameters = new ArrayList<>();
                Set<Map.Entry<String, Object>> entrySet = body.entrySet();
                for (Map.Entry<String, Object> e : entrySet) {
                    String name = e.getKey();
                    String value = e.getValue().toString();
                    NameValuePair pair = new BasicNameValuePair(name, value);
                    parameters.add(pair);
                }
                // Set to the request's http object
                request.setEntity(new UrlEncodedFormEntity(parameters, ENCODING));
            }
        } else {
            request.addHeader(HTTP.CONTENT_TYPE, APPLICATION_JSON);
            StringEntity entity =
                    new StringEntity(JsonUtils.toJsonString(body), ContentType.APPLICATION_JSON);
            entity.setContentEncoding(new BasicHeader(HTTP.CONTENT_TYPE, APPLICATION_JSON));
            request.setEntity(entity);
        }
    }
```

the code detail:
https://github.com/apache/seatunnel/blob/a7675d1782d82db5424c4f0db362663cbc1e3ff3/seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/client/HttpClientProvider.java#L492C13-L492C68

### SeaTunnel Version

2.3.11

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  Http {
    plugin_output = "http"
    url = "http://127.0.0.1:5000/api/cursor_data"
    method = "GET"

    format = "json"
 	content_field = "$.data.*"
     keep_page_param_as_http_param = true
     pageing = {
                page_type="Cursor"
                 cursor_field ="cursor"
                cursor_response_field="$.paging.cursors.next"
     }

header ={
Content-Type=application/json;utf-8

}
      schema = {
	    fields {
		    content=string
            id=int
            name=string


		}
      }

        json_field = {
            content = "$.data[*].content"
            id = "$.data[*].id"
            name = "$.data[*].name"

          }
    }
  }


# Console printing of the read Http data
sink {
  Console {
    parallelism = 1
  }
}
```

### Running Command

```shell
Assuming config file is `http_paging.config`

${SEATUNNEL_HOME}/bin/seatunnel.sh --deploy-mode local -c http_paging.config
```

### Error Exception

```log
Although no explicit errors occur, certain APIs require the exact Content-Type: application/json;charset=utf-8 header. Since the HTTP signature validation also depends on this specific value, I must configure it directly in the settings file.
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Alberne**
### Purpose of this pull request

should check whether it already exists Content-Type in header, to avoid duplicate additions
close issue #9476

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
not added, this code is very simple and clear. only  check whether it already exists Content-Type in header, to avoid duplicate additions. 

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)

### CODE REVIEW

File: seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/client/HttpClientProvider.java [hunk 1]
```diff
@@ -489,6 +489,9 @@ static void addBody(HttpEntityEnclosingRequestBase request, Map<String, Object>
                 request.setEntity(new UrlEncodedFormEntity(parameters, ENCODING));
             }
         } else {
+            if (!request.containsHeader(HTTP.CONTENT_TYPE)) {
+                request.addHeader(HTTP.CONTENT_TYPE, APPLICATION_JSON);
+            }
```
[the remark this answers is not in the document]
Comment (Alberne) [reply seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/client/HttpClientProvider.java:495]: LMGT~

**Comment by Alberne** [comment]
@Hisoka-X please review code

**Comment by Hisoka-X** [comment]
Hi @Alberne . I found this issue already fixed by https://github.com/apache/seatunnel/pull/9363. Could you verify it again? We should set request header by user themself now.

**Comment by Alberne** [comment]
> Hi @Alberne . I found this issue already fixed by #9363. Could you verify it again? We should set request header by user themself now.

@Hisoka-X  Yes, I suggest making adjustments to the original logic for compatibility. The initial logic was that the system automatically adds the Content-Type header, so it should first check whether the user has already set the Content-Type header. If the user hasn't customized it, the system should then set it.

Additionally, because the original logic automatically adds the Content-Type header, the tasks currently running in production have not custom-set this header. If we do not perform compatibility checks, it would affect the online tasks.

File: seatunnel-connectors-v2/connector-http/connector-http-base/src/test/java/org/apache/seatunnel/connectors/seatunnel/http/client/HttpClientProviderTest.java [hunk 2]
```diff
@@ -18,20 +18,70 @@
...
+        //        verify(mockRequest).setEntity(any(HttpEntity.class));
+
+        Header[] currentHeaders =
+                new Header[] {new BasicHeader(HTTP.CONTENT_TYPE, "application/json;utf-8")};
+        when(mockRequest.getAllHeaders()).thenReturn(currentHeaders);
+
+        Header[] resultHeaders = mockRequest.getAllHeaders();
+        Assertions.assertEquals(1, resultHeaders.length);
+        Assertions.assertEquals(HTTP.CONTENT_TYPE, resultHeaders[0].getName());
+        Assertions.assertEquals("application/json;utf-8", resultHeaders[0].getValue());
```
Comment (Hisoka-X) [inline seatunnel-connectors-v2/connector-http/connector-http-base/src/test/java/org/apache/seatunnel/connectors/seatunnel/http/client/HttpClientProviderTest.java]: What is the purpose of this test?

**Review by Hisoka-X — COMMENTED** [review]
I found the test case you added not right. We should check the default content-type worked or not when we add custom content-type.

File: seatunnel-connectors-v2/connector-http/connector-http-base/src/test/java/org/apache/seatunnel/connectors/seatunnel/http/client/HttpClientProviderTest.java (hunk 2 above)
Comment (Alberne) [reply seatunnel-connectors-v2/connector-http/connector-http-base/src/test/java/org/apache/seatunnel/connectors/seatunnel/http/client/HttpClientProviderTest.java]: thanks,  already fixed.

**Comment by Alberne** [comment]
@Hisoka-X  hi,  please review code.

**Comment by Alberne** [comment]
> I found the test case you added not right. We should check the default content-type worked or not when we add custom content-type.

@Hisoka-X fixed.

**Review by Hisoka-X — APPROVED** [review]
LGTM. cc @CosmosNi

**Review by corgy-w — APPROVED** [review]
