### PR TITLE
[Bug] [JDBC Source] fix split exception when source table is empty

### LINKED ISSUE #4569: [Bug] [JDBC Source] Exception when table have no data and partition_column is not null
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Exception when table have no data and partition_column is not null

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
*
```

### Running Command

```shell
*
```

### Error Exception

```log
[INFO] 2023-04-13 19:05:27.408 - task execute result:2023-04-13 19:05:27,408 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 

[INFO] 2023-04-13 19:05:27.408 - task execute result:

[INFO] 2023-04-13 19:05:27.408 - task execute result:===============================================================================

[INFO] 2023-04-13 19:05:27.408 - task execute result:

[INFO] 2023-04-13 19:05:27.408 - task execute result:

[INFO] 2023-04-13 19:05:27.409 - task execute result:2023-04-13 19:05:27,408 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error, 

[INFO] 2023-04-13 19:05:27.409 - task execute result:

[INFO] 2023-04-13 19:05:27.409 - task execute result:2023-04-13 19:05:27,408 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

[INFO] 2023-04-13 19:05:27.409 - task execute result:

[INFO] 2023-04-13 19:05:27.410 - task execute result:2023-04-13 19:05:27,408 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed 

[INFO] 2023-04-13 19:05:27.410 - task execute result:

[INFO] 2023-04-13 19:05:27.410 - task execute result:2023-04-13 19:05:27,409 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed

[INFO] 2023-04-13 19:05:27.410 - task execute result:	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:170)

[INFO] 2023-04-13 19:05:27.410 - task execute result:	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)

[INFO] 2023-04-13 19:05:27.410 - task execute result:	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)

[INFO] 2023-04-13 19:05:27.410 - task execute result:Caused by: org.apache.seatunnel.api.common.PrepareFailException: ErrorCode:[API-01], ErrorDescription:[Configuration item validate failed] - PluginName: jdbc, PluginType: source, Message: java.lang.NumberFormatException: null

[INFO] 2023-04-13 19:05:27.410 - task execute result:	at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.prepare(JdbcSource.java:96)

[INFO] 2023-04-13 19:05:27.410 - task execute result:	at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:64)

[INFO] 2023-04-13 19:05:27.410 - task execute result:	at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:371)

[INFO] 2023-04-13 19:05:27.410 - task execute result:	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:132)

[INFO] 2023-04-13 19:05:27.410 - task execute result:	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:114)

[INFO] 2023-04-13 19:05:27.410 - task execute result:	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)

[INFO] 2023-04-13 19:05:27.410 - task execute result:	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)

[INFO] 2023-04-13 19:05:27.410 - task execute result:	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:129)

[INFO] 2023-04-13 19:05:27.410 - task execute result:	... 2 more

[INFO] 2023-04-13 19:05:27.410 - task execute result: 

[INFO] 2023-04-13 19:05:27.410 - task execute result:2023-04-13 19:05:27,409 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 

[INFO] 2023-04-13 19:05:27.410 - task execute
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by laglangyue**
…olumn is not null

## Purpose of this pull request

close #4569

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by laglangyue** [comment]
now we just support numeric, getLong() will be implemented by jdbc driver, it's safe.

File: seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/source/JdbcSourceFactory.java [hunk 1]
```diff
@@ -155,11 +155,11 @@ static PartitionParameter createPartitionParameter(
                 max =
                         config.getPartitionUpperBound().isPresent()
                                 ? config.getPartitionUpperBound().get()
-                                : Long.parseLong(rs.getString(1));
+                                : rs.getLong(1);
```
Comment (hailin0) [inline seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/source/JdbcSourceFactory.java:158]: If the table is empty, then rs.next() return false

Comment (hailin0) [reply seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/source/JdbcSourceFactory.java:158]: PartitionParameter#minValue also throws a NPE if it is value null

Comment (laglangyue) [reply seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/source/JdbcSourceFactory.java:158]: > If the table is empty, then rs.next() return false

no, if the table is empty, rs.next() return ture, may because of subquery

Comment (laglangyue) [reply seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/source/JdbcSourceFactory.java:158]: I have test some empty table (c1 int , c2 bigint ,c3 tinyint)
if query is corretly, PartitionParameter#minValue will not throw NPE, because the getLong() return long ,it has default value 0

Comment (laglangyue) [reply seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/source/JdbcSourceFactory.java:158]: image

image

Comment (hailin0) [reply seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/source/JdbcSourceFactory.java:158]: > PartitionParameter#minValue also throws a NPE if it is value null

here

https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/source/JdbcSourceSplitEnumerator.java#L110

Comment (laglangyue) [reply seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/source/JdbcSourceFactory.java:158]: done, I refactor Long to long, it has default value if not set.
Besides, the property of PartitionParameter has no private added

**Comment by laglangyue** [comment]
@TyrantLucifer @ic4y @ashulin PTAL

**Review by hailin0 — APPROVED** [review]

**Review by TaoZex — APPROVED** [review]
+1

**Review by lightzhao — APPROVED** [review]

**Review by EricJoy2048 — APPROVED** [review]
