### PR TITLE
[Hotfix][connector-clickhouse] fix get clickhouse local table name with closing bracket from distributed table engineFull

### LINKED ISSUE #4482: [Bug] [connector-clickhouse] “Distributed（'clusterw_7shard','default','user_info'）”Character segmentation problem about the local table named user_info
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I use connector-clickhouse to write data to clickhouse,find error below
image
I checked the source code and found a string segmentation problem
4b07390c5aae29966fa14794d87df76
The replace method in the source code does not remove the brackets from the table name
Causes a problem with the subsequent spliced SQL statements
0c5d73943db855361e898ba8466356f

### SeaTunnel Version

Seatunnel 2.3.1

### SeaTunnel Config

```conf
env {
  execution.parallelism = 4
  job.mode = "STREAMING"
  job.name = "test.kafka.2.clickhouse"
}

source {
  Kafka {
    result_table_name = "user_info_kafka"
    schema = {
      fields {
        name = "string"
        age = "int"
        salary = "double"
      }
    }
    format = json
    topic = "kafka-test"
    bootstrap.servers = "XXXX:9092"
    consumer.group = "kafka-clickhouse-test01"
    commit_on_checkpoint = false
    kafka.config = {
      auto.offset.reset = "latest"
      enable.auto.commit = "true"
    }
  }
}

transform {
  Sql {
    source_table_name = "user_info_kafka"
    result_table_name = "clus_user_info"
    query = "select name, age, salary from user_info_kafka"
  }
}

sink {
  Clickhouse {
    host = "XXXX:8123"
    database = "default"
    table = "clus_user_info"
    username = "default"
    password = "XXX"
    split_mode = true
    sharding_key = "name"
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/kafka-to-clickhouse-test01.conf -e local
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.connectors.seatunnel.clickhouse.exception.ClickhouseConnectorException: ErrorCode:[API-05], ErrorDescription:[Table not existed] - Cannot get table from clickhouse, resultSet is empty
        at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.ClickhouseProxy.getClickhouseDistributedTable(ClickhouseProxy.java:102)
        at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.ClickhouseProxy.getClickhouseTable(ClickhouseProxy.java:230)
        at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.ClickhouseSink.prepare(ClickhouseSink.java:145)
        at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSinkInstance(ConnectorInstanceLoader.java:90)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:414)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:132)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:112)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xifeng**
## Purpose of this pull request
close #4482 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by xifeng** [comment]
@hailin0 @TyrantLucifer thanks

**Review by yabola — APPROVED** [review]

**Comment by yabola** [comment]
Do you know why it used '//)' before and will it introduce regression bug?

File: seatunnel-connectors-v2/connector-clickhouse/src/main/java/org/apache/seatunnel/connectors/seatunnel/clickhouse/sink/client/ClickhouseProxy.java [hunk 1]
```diff
@@ -86,7 +86,7 @@ public DistributedEngine getClickhouseDistributedTable(
 
                 String clusterName = infos.get(0);
                 String localDatabase = infos.get(1);
-                String localTable = infos.get(2).replace("\\)", "").trim();
+                String localTable = infos.get(2).replace(")", "").trim();
```
Comment (EricJoy2048) [inline seatunnel-connectors-v2/connector-clickhouse/src/main/java/org/apache/seatunnel/connectors/seatunnel/clickhouse/sink/client/ClickhouseProxy.java:89]: @Hisoka-X  PTAL

**Review by Hisoka-X — APPROVED** [review]

**Review by EricJoy2048 — APPROVED** [review]
