### PR TITLE
[Core] [Fix] add plugin mapping ignore case

### LINKED ISSUE #1884: [Feature][Core] Plugin-Mapping load ignore case
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At dev now, we use `plugin-mapping.properties` to find plugin we should load. The logic is: Parse config, then get source/sink plugin name. use this name to find plugin-mapping key in `plugin-mapping.properties`. The value will be plugin jar prefix name. Finally the jar load success.
The problem is plugin name in config not support ignore case (older version supported). We should support any case plugin name can map to plugin-mapping key. 

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request
add plugin mapping ignore case
This close #1884 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

File: seatunnel-core/seatunnel-core-base/src/test/java/org/apache/seatunnel/core/base/config/PluginFactoryTest.java [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+
+        Config pluginMapping = ConfigFactory
+                .parseFile(new File(Objects.requireNonNull(PluginFactoryTest.class.getResource("/plugin-mapping.properties")).getPath()))
+                .resolve(ConfigResolveOptions.defaults().setAllowUnresolved(true))
+                .resolveWith(ConfigFactory.systemProperties(),
+                        ConfigResolveOptions.defaults().setAllowUnresolved(true));
+
+        PluginFactory<SparkEnvironment> factory = new PluginFactory<>(config, EngineType.SPARK);
+
+        Method method = factory.getClass().getDeclaredMethod("getPluginMappingValue", Config.class,
```
Comment (ruanwenjun) [inline seatunnel-core/seatunnel-core-base/src/test/java/org/apache/seatunnel/core/base/config/PluginFactoryTest.java]: You can remove the private of `getPluginMappingValue`, then you don't need to use reflect in UT.

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/core/base/config/PluginFactory.java [hunk 2]
```diff
@@ -156,7 +156,11 @@ private String getPluginMappingKey(PluginType type, String pluginName) {
     }
 
     private String getPluginMappingValue(Config pluginMapping, PluginType type, String pluginName) {
-        return pluginMapping.getConfig(this.engineType.getEngine()).getConfig(type.getType()).getString(pluginName);
+
+        return pluginMapping.getConfig(this.engineType.getEngine()).getConfig(type.getType()).entrySet()
+                .stream().filter(entry -> entry.getKey().equalsIgnoreCase(pluginName))
+                .collect(Collectors.toList()).get(0).getValue().unwrapped().toString();
+
```
Comment (ruanwenjun) [inline seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/core/base/config/PluginFactory.java]: `.get(0)` there might cause NullPointException. It's better change to 
```java
.stream()
.filter()
.findAny()
```

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: seatunnel-core/seatunnel-core-base/src/test/java/org/apache/seatunnel/core/base/config/PluginFactoryTest.java (hunk 1 above)
Comment (Hisoka-X) [reply seatunnel-core/seatunnel-core-base/src/test/java/org/apache/seatunnel/core/base/config/PluginFactoryTest.java]: In fact, `getPluginMappingValue` should be private, so I think we should use reflect in here

Comment (ruanwenjun) [reply seatunnel-core/seatunnel-core-base/src/test/java/org/apache/seatunnel/core/base/config/PluginFactoryTest.java]: You can change the scope to default or protect, this can help to test. Using reflect in UT is not a good practice, when we change the method name, we cannot get the error in compile time.

Comment (Hisoka-X) [reply seatunnel-core/seatunnel-core-base/src/test/java/org/apache/seatunnel/core/base/config/PluginFactoryTest.java]: Ok, I will change this.

**Review by ruanwenjun — APPROVED** [review]
LGTM
